Feature/Deposit state flow - DAO-543
aragon/app-legacy pull request #100
Opened 2021-12-20 18:41 UTC by Fabricevladimir

- installed react-hook-forms
- setup deposit stepper
- stubs to show usage

2021-12-21 12:43 UTC, sepehr2github requested changes
Thank you! Unfortunately, App crashes on /finance/new-transfer 
![image](https://user-images.githubusercontent.com/46657145/146931668-43f4d11b-c10d-4dca-944c-addaa0f75cdf.png)

Can you check it? Thanks

2021-12-21 13:01 UTC, Fabricevladimir commented
> Thank you! Unfortunately, App crashes on /finance/new-transfer ![image](https://user-images.githubusercontent.com/46657145/146931668-43f4d11b-c10d-4dca-944c-addaa0f75cdf.png)
> 
> Can you check it? Thanks

The transfer type is being read from the state, so navigating directly will crash (for now). I left a few comments about this in the code.

2021-12-22 15:57 UTC, WissenIstNacht approved these changes
Thanks, looks good to me!

Left some comments about incosequential stuff. Feel free to make changes or merge the PR 👍🏻

2021-12-22 15:57 UTC, WissenIstNacht commented on packages/web-app/src/utils/constants.ts
> +export enum TransferTypes {
Ah yes, our dear ol' friends, enums. 😋

I don't this will ever become a bottleneck for performance, but: be aware that enums generate _really_ ugly JS code.

There's a cool sort of middle-ground that mitigates this but still allows to have enums: using the `const` enums. I.e.:

```
const enum TransferTypes {
  Deposit = 'Deposit',
  Withdraw = 'Withdraw',
}
```

Obviously this only works for examples like this one, where the enums are completely defined at compile time (and wont be changed later).

Don't worry about it though :)

2021-12-22 15:57 UTC, WissenIstNacht commented on packages/web-app/src/containers/transferMenu/index.tsx
> +    if (isConnected()) {
Nice one, didn't think about this while reviewing Rakesh's PR.

2021-12-22 15:57 UTC, WissenIstNacht commented on packages/web-app/src/pages/newDeposit.tsx
> +  const [currentStep, setStep] = useState<Steps>(Steps['Configure Deposit']);
opportunity for a cool little hook: 

```
const [prev, curr, next] = useStepper(TOTAL_STEP_COUNT); 
```

where `prev` and `next` are essentially the callbacks from below, and curr is the `currentStep` (and all is managed by the same `useEffect` that you already defined).

Totally optional, though 👍🏻

2021-12-22 15:57 UTC, WissenIstNacht commented on packages/web-app/src/pages/newDeposit.tsx
> +          {currentStep === Steps['Configure Deposit'] ? (
Out of curiosity: Have you ever used `react-if`?

Cool little package that allows to write conditional statements in JSX. Some people don't like it, though...

2021-12-23 06:58 UTC, sepehr2github approved these changes
Thank you, Fabrice. awesome as always.

2021-12-23 10:10 UTC, Fabricevladimir commented on packages/web-app/src/pages/newDeposit.tsx
> +          {currentStep === Steps['Configure Deposit'] ? (
I haven't, but I have always wanted to use if in JSX! I think that will be available with the new version of React.

2021-12-23 10:11 UTC, Fabricevladimir commented on packages/web-app/src/pages/newDeposit.tsx
> +  const [currentStep, setStep] = useState<Steps>(Steps['Configure Deposit']);
This is a good idea, especially since the Withdraw and Deposit are fully separated right now. We'll need a stepper for Withdraw as well.

2021-12-23 10:15 UTC, Fabricevladimir commented on packages/web-app/src/containers/transferMenu/index.tsx
> +    if (isConnected()) {
See this takes care of the modal, but not all the situations which begs the question, should we be gatekeeping here at all or move that logic to the Deposit page itself since a user can technically navigate to the new-deposit page without connecting their wallet...

2021-12-23 10:56 UTC, Fabricevladimir commented on packages/web-app/src/utils/constants.ts
> +export enum TransferTypes {
Thanks for pointing that out. I wasn't aware!

2021-12-23 11:05 UTC, merged

2021-12-23 11:21 UTC, WissenIstNacht commented on packages/web-app/src/containers/transferMenu/index.tsx
> +    if (isConnected()) {
Another good point... Another thing for Selim to figure out haha