Feature/TransferCard - DAO-539
aragon/app-legacy pull request #101
Opened 2021-12-21 11:52 UTC by Fabricevladimir

- TransferCard (to/from) web-app component
- Fixed transfers test issue

Note: Component shown on web-app homepage

2021-12-21 19:50 UTC, WissenIstNacht requested changes
That was refreshingly easy to review :D

Thanks for the PR. I left a comment on a minor issue with the shortening of addresses. The rest look great!

2021-12-21 19:50 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +  "TransferCard": {
Could go to the labels category :D

The only reaosn I'm pointing this out is because I just reviewed Rakesh's PR where he put a "to" into that the `labels` object. Both are fine and/or can be changed later though :)

2021-12-21 19:50 UTC, WissenIstNacht commented on packages/web-app/src/components/transferCard/index.tsx
> +    'overflow-hidden font-bold text-ui-800 overflow-ellipsis whitespace-nowrap',
I think Sepehr introduced an address shortening function a while back that puts the ellipsis in the middle. I think this would be more aligned with other parts of the design (like the address on the wallet button).

2021-12-22 09:15 UTC, RakeshUP commented on packages/web-app/src/locales/en/common.json
> +  "TransferCard": {
Fine for now. We could later move it to labels object(create a label inside finance object if it makes sense)

2021-12-22 09:18 UTC, RakeshUP commented on packages/web-app/src/utils/strings.ts
> +export function capitalize(
We could use css for this `text-transform: capitalize`

https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform

2021-12-22 09:19 UTC, RakeshUP commented on packages/web-app/src/components/transferCard/index.tsx
> +    'overflow-hidden font-bold text-ui-800 overflow-ellipsis whitespace-nowrap',
The function mentioned is being used in the ButtonWallet I guess

2021-12-22 09:21 UTC, RakeshUP approved these changes
Looks good! 
Can be merged after capitalize and wallet address ellipsis functions are taken care of

2021-12-22 09:22 UTC, RakeshUP commented
Woah too many merge conflicts!!

2021-12-22 09:34 UTC, Fabricevladimir commented on packages/web-app/src/utils/strings.ts
> +export function capitalize(
I wasn't aware this would be language specific. Awesome suggestion!

2021-12-22 10:13 UTC, Fabricevladimir commented on packages/web-app/src/components/transferCard/index.tsx
> +    'overflow-hidden font-bold text-ui-800 overflow-ellipsis whitespace-nowrap',
That function returns a shortened address. When the screen size gets smaller, it won't shrink accordingly. I'll add it here with a todo because the overflow-ellipsis is still needed for like a long ens or DAO name

2021-12-22 10:57 UTC, WissenIstNacht approved these changes

2021-12-22 14:14 UTC, merged