Offchain plugin base
aragon/app-legacy pull request #1031
Opened 2023-09-21 16:01 UTC by emmdim

## Description

This is the base for the offchain plugin implementation

2023-09-21 16:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aragon/app?pullRequest=1031) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aragon/app?pullRequest=1031) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aragon/app?pullRequest=1031) it.</sub>

2023-09-22 08:09 UTC, elboletaire requested changes
First review, waiting for your `todo(kon)` changes.

2023-09-22 08:09 UTC, elboletaire commented on src/hooks/usePluginClient.tsx
> +export type OFFCHAIN_PLUGIN_TYPE = typeof OFFCHAIN_PLUGIN_NAME;
Use PascalCase for types.

2023-09-22 08:09 UTC, elboletaire commented on src/hooks/useVocdoniSdk.tsx
> +export const UseVocdoniClientProvider: React.FC = ({children}) => {
This is confusing. Methods starting with `use` are hooks, but here you're defining a provider. Better call it `VocdoniClientProvider`.

2023-09-22 08:09 UTC, elboletaire commented on yarn.lock
> +  version "20.4.9"
You're using multiple `@types/node` definitions, which could cause linting issues. Best thing to do is have only one, and always equaling your node version (i.e. if you're using node 18, @types/node should be also a version 18). Not a huge deal, but as I said, can cause issues.

2023-09-22 08:11 UTC, elboletaire commented on yarn.lock
> +  version "20.4.9"
But, checking again the package.json changes, this is obviously caused by a dependency, so it can safely be ignored if hasn't failed yet.

2023-09-22 08:36 UTC, selankon commented on src/hooks/usePluginClient.tsx
> +export type OFFCHAIN_PLUGIN_TYPE = typeof OFFCHAIN_PLUGIN_NAME;
65d07a37 fixes it

2023-09-22 08:36 UTC, selankon commented on src/hooks/useVocdoniSdk.tsx
> +export const UseVocdoniClientProvider: React.FC = ({children}) => {
65d07a37 fixes it

2023-09-22 08:37 UTC, selankon commented
> First review, waiting for your `todo(kon)` changes.

I checked and the remaining todos are going to be fixed on other branches so they can remain

2023-10-30 11:53 UTC, closed without merging

2023-10-30 11:53 UTC, selankon commented
Closed in favour to https://github.com/aragon/app/pull/1074