Feature/Input Value component DAO-546
aragon/app-legacy pull request #104
Opened 2021-12-22 13:56 UTC by RakeshUP

2021-12-22 14:53 UTC, Fabricevladimir requested changes
Good work!

2021-12-22 14:53 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/valueInput.tsx
> +const StyledButton = styled.button.attrs({
This should be ButtonText secondary, size small, bgWhite.

2021-12-22 14:53 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/valueInput.tsx
> +  onButtonClick: () => void;
I saw that the text input named the element adornment, can we agree on one name for the sake of consistency?

2021-12-22 14:53 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/valueInput.tsx
> +    if (mode === 'default') {
Not requesting a change for this. It seems we're going to use the same border styles for all the inputs, might be worth having that in one place.

2021-12-22 14:53 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/valueInput.tsx
> +  padding: 6px 6px 6px 16px;
Can we switch this over to TW instead of straight CSS?  Documentation for the focus within can be found [here](https://v2.tailwindcss.com/docs/hover-focus-and-other-states#focus-within).

2021-12-23 06:25 UTC, sepehr2github commented on packages/ui-components/src/components/input/valueInput.tsx
> +  mode?: 'default' | 'success' | 'warning' | 'critical';
'mode' prop is optional here but you never defined a default value!

2021-12-23 06:44 UTC, sepehr2github commented on packages/ui-components/src/components/input/valueInput.tsx
> +  padding-top: 6px;
Also for padding please use tailwind classes. If needed you can define 0.75 in spacing.

2021-12-23 06:44 UTC, sepehr2github reviewed
Thank you Rakash. Looks nice 👍

2021-12-23 08:51 UTC, RakeshUP commented on packages/ui-components/src/components/input/valueInput.tsx
> +  padding: 6px 6px 6px 16px;
Apparently, TW's focus-within is not working when used along with the hover variant. When both are specified, the hover is taking precedence over focus-within. 

I used focus-within in plain CSS and it seems to be working as expected!

2021-12-23 09:14 UTC, RakeshUP commented on packages/ui-components/src/components/input/valueInput.tsx
> +    if (mode === 'default') {
The design seems to use both focus and active variants for input, and I guess active should apply when value is being entered. I'll confirm with Selim and update the border styles for all inputs and also extract to a single place then

2021-12-23 11:07 UTC, Fabricevladimir approved these changes
Ready to roll!

2021-12-23 11:07 UTC, Fabricevladimir commented on packages/ui-components/tailwind.config.js
> +        0.75: '6px',
If you get a chance, mirror that change over to the web-app as well!

2022-01-03 08:59 UTC, sepehr2github approved these changes
Good to go 👍

2022-01-03 09:11 UTC, merged