Feature/CardText component DAO-541
aragon/app-legacy pull request #106
Opened 2021-12-23 11:56 UTC by RakeshUP

CardText added to web-app components

2021-12-23 12:11 UTC, RakeshUP commented on packages/web-app/src/components/cardText/index.tsx
> +}
lineClamp could be added as an optional prop. If none is provided, no clamping. Otherwise the number of lines of clamping is taken as prop

2021-12-23 14:52 UTC, Fabricevladimir requested changes, later dismissed
Good work! I wasn't aware of the line clamping. Interesting.

2021-12-23 14:52 UTC, Fabricevladimir commented on packages/web-app/src/components/cardText/index.tsx
> +import React from 'react';
Should this be in ui-components? This is tiny, not sure why it would be, but it's in the component library...

2021-12-23 14:52 UTC, Fabricevladimir commented on packages/web-app/src/components/cardText/index.tsx
> +  className: 'p-2 font-normal rounded-xl bg-ui-0 space-y-0.25 text-ui-600',
Please include the tablet breakpoint styling as well.

2021-12-23 14:52 UTC, Fabricevladimir commented on packages/web-app/src/components/cardText/index.tsx
> +  title: string;
There is also a `type` property that takes in 'title' or 'label'. And our ever-present `bgWhite`.

2021-12-23 15:01 UTC, WissenIstNacht reviewed
Thanks! 🙂 

Wasn't aware of the line-clamp plugin either. Two comments from my side:

1. Regarding line clamping. Apparently, Selim does not intend the text to be cropped. (See Sepehr's comment on the ticket). So I guess variable sized cards are not too much of an issue.
2. As Fabrice mentioned, there's an actual component for this in the Component page on FIgma. Therefore, I think this should be moved to `ui-components`.

 Otherwise, I think Fabrices comments cover everything. As always, let me know if I missed something 👍🏼

2021-12-23 15:55 UTC, RakeshUP commented
I did not seem to notice the Card component in the Aragon Components. I have changed everything and removed line-clamp from dependencies too.

2021-12-24 11:32 UTC, WissenIstNacht approved these changes
Thanks a ton for the changes, looks good to me 👍🏼

2022-01-03 08:57 UTC, sepehr2github commented on packages/ui-components/src/components/cards/cardText.tsx
> +const Container = styled.div.attrs(({bgWhite}:ContainerProps) => {
It's better to have a space separator here.
`{bgWhite}: ContainerProps`

2022-01-03 08:57 UTC, sepehr2github commented on packages/ui-components/src/components/cards/cardText.tsx
> +const Title = styled.p.attrs(({type}:TitleProps) => {
Also here!

2022-01-03 08:58 UTC, sepehr2github approved these changes
Thank you a lot! just a few minor suggestions

2022-01-03 09:48 UTC, merged