Feature/Edit tokenCard - DAO-540
aragon/app-legacy pull request #107
Opened 2021-12-23 13:16 UTC by Fabricevladimir

- Modified `tokenCard` to take `bgWhite` prop as well as type of `vault` or `transfer`
- Renamed card components to be more consistent with design system
- Restructured storybook to place all card components in one folder
- Updated web-app to match component name change
- Slight modification to token sort to keep undefined value at the end of list
- Added more MANA because I can

2021-12-24 14:30 UTC, WissenIstNacht requested changes
Thanks Fabrice!

LIttle detail to handle on the token card :)

2021-12-24 14:30 UTC, WissenIstNacht commented on packages/ui-components/src/components/card/cardToken.tsx
> +                <span> {props.tokenUSDValue}</span>
If `tokenUsdValue` is not there for some reason (like, say, you forget to pass it to the corresponding story :D), this will only show the dot from line 55.

2022-01-03 08:41 UTC, sepehr2github approved these changes
Sounds Great! Thank you.

2022-01-03 15:55 UTC, WissenIstNacht approved these changes
Good to go!

2022-01-03 16:13 UTC, merged