WIP: offchain voting process
aragon/app-legacy pull request #1074
Opened 2023-10-16 14:36 UTC by selankon

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task: [APP-0000](https://aragonassociation.atlassian.net/browse/APP-0000)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have tested my code on the test network.

2023-10-17 09:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/aragon/app?pullRequest=1074) <br/>All committers have signed the CLA.

2023-10-17 14:55 UTC, elboletaire commented on src/containers/configureCommunity/proposalCreation.tsx
> +      )}
Considering the entire component is not rendered with the condition, it would be better to clearly return null after such condition, i.e.

```js
// you could leave the const declaration for better readability, but since it's only
// used once, and for the sake of a shorter example, I've ommited it here
if (!(isCustomToken || tokenType === 'ERC-20' || tokenType === 'governance-ERC20')) {
  return null
}

// normal render of the compnent
return (
  <>
    {/* [...] */}
  </>
)
```

2023-10-17 14:55 UTC, elboletaire commented on src/containers/configureCommunity/proposalCreation.tsx
> +    </div>
I know these two components did exist already, but I'm wondering if the condition could have been added there instead. Checking them I see they both also access the form context so, unless they're used in different form contexts, with different fields (i.e. `membership` exists in one form, but not in another one already using these two components; or the logic of these two components is just different in another form), this condition could be there.

PS. Remember I'm reviewing by just looking at the code... if you consider this logic makes sense here, just ignore my comment :_)

2023-10-17 14:55 UTC, elboletaire commented on src/containers/goLive/index.tsx
> +      {votingType === 'offChain' && <Committee />}
Maybe this condition could also be in its own component directly (?)

2023-10-17 14:55 UTC, elboletaire commented on src/context/stepperModal.tsx
> +                label={t('TransactionModal.gasEstimationErrorLabel') as string}
`t` also has a `toString()` method, but it's virtually the same you did here (since the only problem of not using `toString()` is typescript complaining about it not being of type string). Just so you know the method exists 😉

2023-10-18 15:07 UTC, elboletaire requested changes

2023-10-18 15:07 UTC, elboletaire commented on src/context/useOffchainVoting.tsx
> +  }, [proposal]);
This is one of those cases where you **could** avoid using `useMemo`. If you still want the function-alike syntax, remember you can use a self-executing function:

```js
const isApprovalPeriod = ((proposal) => {
  if (!proposal) return false;
  return (
    proposal.endDate.valueOf() < new Date().valueOf() &&
    proposal.expirationDate.valueOf() > new Date().valueOf()
  );
})(proposal)
```

Most `useMemo` used below of the aforementioned one could be changed to not be `useMemo`, except for the `approved` one, since there you're traversing an array using `some`, and it's always a good idea to use `useMemo` when working with array functions (specially when those arrays can be gigantic; if you know it'll be short, could be safe to not use it there too).

Also, not one of those crytical changes you should prioritize tbh.. just a heads up about the proper usage of `useMemo`.

2023-10-18 15:07 UTC, elboletaire commented on src/context/useOffchainVoting.tsx
> +    }
This ternary here is quite confusing. I'd suggest:

```js
if (!(address && client)) {
  return
}

if (approved || !isApprovalPeriod || !proposalCanBeApproved) {
  setCanApprove(false)
  return
}
checkCanVote()
```

Edit: reviewing my own review ~20h later... tbh the entire logic in this effect is quite confusing.

2023-10-18 15:07 UTC, elboletaire commented on src/hooks/useCensus3.tsx
> +  }, [census3, chainId]);
I'd suggest not using ternaries unless you really need to (i.e. a react component rendering part, or assigning values to an object), since they tend to difficult readability.

Actually, I now do realize you can entirely remove the condition:

```js
useEffect(() => {
  ;(async () => {
    if (chainId && census3) {
      setIsSupported((await census3.getSupportedChains()).includes(chainId))
    }
  })()
}, [census3, chainId]);
```

2023-10-18 15:07 UTC, elboletaire commented on src/hooks/useCensus3.tsx
> +        // todo(kon): handle chain is not supported
Friendly reminder to check all comments and, either change what's required, or remove them.

2023-10-18 15:07 UTC, elboletaire commented on src/hooks/useDaoOffchainProposal.tsx
> +  }, [intervalInMills]);
No need to use state for an interval id you're not using afterwards:

```js
useEffect(() => {
  let id: number
  if ((intervalInMills || 0) > 0) {
    setNumberOfRuns(value => value + 1);

    id = window.setInterval(() => {
      setNumberOfRuns(value => value + 1);
    }, intervalInMills);

    return
  }
  window.clearInterval(id)

  return () => window.clearInterval(id);
}, [intervalInMills]);
  ```

2023-10-18 15:07 UTC, elboletaire commented on src/hooks/useDaoOffchainProposal.tsx
> +  useEffect(() => {
It's always a good idea to add a comment at the top of the effect describing its usage, specially in huge ones like this, and considering the condition to run it is ~60lines below.

2023-10-18 15:07 UTC, elboletaire commented on src/hooks/useDaoOffchainProposal.tsx
> +      getDaoProposal(proposalGuid);
Use brackets for better readability (and consistency with all the code).

Personally, I preffer having these conditions in effects at the very begin, so you clearly see **when** the effect is gonna run. And since I usually use self-calling functions in async effects, the creation of the named method `getDaoProposal` (which is used only once) would not be required, making everything look quite different. But personal preferences, I guess :)

Edit: now I see this is probably a modified copy-paste coming from `useProposals`, so I understand you just changed an already existing flow 😅. There are actually more files very similar... `useProposals`, `useDaoOffchainProposal` and `useDaoProposal` are all quite similar.

2023-10-18 15:07 UTC, elboletaire commented on src/hooks/useWalletCanVote.tsx
> +          : await fetchOnchainVoting();
These ternaries...

```suggestion
        if (isOffchainVoting) {
          return await fetchCanVoteOffchain();
        }
        await fetchOnchainVoting();
```

2023-10-18 15:07 UTC, elboletaire commented on src/hooks/useWalletCanVote.tsx
> +        }
Could be a one-liner

```suggestion
        canVote = await vocdoniClient.isInCensus(offchainProposalId) &&
          !(await vocdoniClient.hasAlreadyVoted(offchainProposalId));
```

2023-10-18 15:07 UTC, elboletaire commented on src/pages/proposal.tsx
> +
friendly reminder to remove unwanted comments

2023-10-18 15:07 UTC, elboletaire commented on src/pages/proposal.tsx
>          : (proposal as MultisigProposal)?.approvals?.length >=
Ouch 😅. And I was complaining about ternaries 😂

2023-10-18 15:07 UTC, elboletaire commented on src/utils/committeeVoting.ts
> +  }
Maybe use switch here

```suggestion
  switch (true) {
    case executed:
      return t('offchainVotingTerminal.btnLabel.executed');
    case approved:
      return t('offchainVotingTerminal.btnLabel.approved');
    case notBegan:
      return t('offchainVotingTerminal.btnLabel.approve');
    case voted:
      return t('offchainVotingTerminal.btnLabel.voted');
    case canApprove:
      return t('offchainVotingTerminal.btnLabel.approve');
  }
```

I say "maybe" since using typescript may require adding a `default` option with a `throw Error`, and would end up being more code (and that error could bring more issues, considering this seems to be a view helper/render method).

Another option is to not use the `else`, since it's not required in this case (because you're always returning after a condition is met):


```suggestion
  if (executed) {
    return t('offchainVotingTerminal.btnLabel.executed');
  }
  if (approved) {
    return t('offchainVotingTerminal.btnLabel.approved');
  }
  if (notBegan) {
    return t('offchainVotingTerminal.btnLabel.approve');
  }
  if (voted) {
    return t('offchainVotingTerminal.btnLabel.voted');
  }
  if (canApprove) {
    return t('offchainVotingTerminal.btnLabel.approve');
  }
```

2023-10-18 15:07 UTC, elboletaire commented on src/components/addCommitteeMembers/row.tsx
> +        )
Considering the amount of logic required by the `some` param, would be more clear if you define it as a `const` the line before (outside of the `if` condition).

2023-10-18 15:07 UTC, elboletaire commented on src/containers/defineCommittee/index.tsx
> +                      })}
`count` in `i18next` is usually for plurals: https://www.i18next.com/translation-function/plurals

Doesn't mean it won't work this way, just another heads-up. Using an extractor would generate 2 or 3 strings when finding `count` as an interpolation value in a translation.

2023-10-23 15:00 UTC, selankon commented on src/hooks/useDaoOffchainProposal.tsx
> +  }, [intervalInMills]);
This hook doesn't exists anymore

2023-10-24 08:26 UTC, selankon commented on src/pages/proposal.tsx
>          : (proposal as MultisigProposal)?.approvals?.length >=
After rebase this ternary was moved into a if else statements

2023-11-03 11:39 UTC, RuggeroCino reviewed
I reviewed roughly half of the changed files and left some initial comments. I saw that you're still actively pushing changes to the branch, probably it makes sense for me to continue the review when you're at least done with all the type and eslint issues, what do you think?

2023-11-03 11:39 UTC, cgero-eth commented on .env.development
> +
Let's remove this new space here so that all the `.env` files have the same format

2023-11-03 11:39 UTC, cgero-eth commented on .env.staging
> +VITE_FEATURE_FLAG_GASLESS_PLUGIN=false
I'd suggest to enable the plugin on staging, QA can start testing it there
```suggestion
VITE_FEATURE_FLAG_GASLESS_PLUGIN=true
```

2023-11-03 11:39 UTC, cgero-eth commented on .gitignore
> +
The `.idea` entry is duplicated

2023-11-03 11:39 UTC, cgero-eth commented on package.json
> +    "@aragon/sdk-client": "1.14.0",
Let's restore this version
```suggestion
    "@aragon/sdk-client": "^1.14.0",
```

2023-11-03 11:39 UTC, cgero-eth commented on src/components/StepperProgress/index.tsx
> +export default StepperModalProgress;
We should avoid default exports and have one component per file, but I know this is not currently enforced across the app. Feel free to just resolve the comment if you won't have time to do so, I'll create a Jira ticket to fix this anyway

2023-11-03 11:39 UTC, cgero-eth commented on src/hooks/usePluginClient.tsx
> +  client: TokenVotingClient | MultisigClient | GaslessVotingClient
I would suggest to introduce a new type like:
```
type PluginClient = TokenVotingClient | MultisigClient | GaslessVotingClient
```
And use this when needed

2023-11-03 11:39 UTC, cgero-eth commented on src/hooks/useVocdoniSdk.tsx
> +export const VocdoniEnv: EnvOptions = EnvOptions.STG;
We can easily add a new environment variable on the `.env` files like:
```
VITE_VOCDONI_ENV=dev|stg|prod
```
And use it here as:
```
export const CovdoniEnv: EnvOptions = import.meta.env.VITE_VOCDONI_ENV;
```

2023-11-03 11:39 UTC, cgero-eth commented on src/components/addCommitteeMembers/footer.tsx
> +const AddWalletsFooter: React.FC<WalletsFooterProps> = ({totalAddresses}) => {
It would be nice if we could improve the file name <=> component name matching. The folder is called `/addCommitteeMembers` but the component is `AddWalletsFooter`, I would probably rename these components to `AddCommittee*` like `AddCommitteeFooter` (and the folder to `/addCommittee` ?)

2023-11-03 11:39 UTC, cgero-eth commented on src/components/addCommitteeMembers/footer.tsx
> +export const FooterItem2 = styled.div.attrs({
Let's not export components if they're not used. You can find a list of unused exports/files/dependencies by running the [knip](https://github.com/webpro/knip) tool: `npx knip`
```suggestion
const FooterItem1 = styled.div.attrs({
  className: 'flex-1',
})``;

const FooterItem2 = styled.div.attrs({
```

2023-11-03 11:39 UTC, cgero-eth commented on src/components/addCommitteeMembers/index.tsx
> +  });
Is the `controlledFields` variable needed here? As far as I can see we're only using the fields id and total length and we might remove the `useWatch` call to the `committee` field as well

2023-11-03 11:39 UTC, cgero-eth commented on src/components/addCommitteeMembers/index.tsx
> +      // insert(1, {address: address, amount: '0'});
I would remove the commented out code

2023-11-03 11:39 UTC, cgero-eth commented on src/components/addCommitteeMembers/row.tsx
> +      const isDuplicateAddress = committee?.some(
Can we use the `walletInWalletList` utility here? Looks like it has been introduced but it is not used

2023-11-03 11:39 UTC, cgero-eth commented on src/components/StepperProgress/index.tsx
> +import React from 'react';
Folder name should be `stepperProgress` and not `StepperProgress`

2023-11-03 11:39 UTC, cgero-eth commented on src/components/executionExpirationtime/index.tsx
> +import React, {useCallback} from 'react';
Folder name should be `executionExpirationTime` and not `executionEpirationtime`

2023-11-03 11:39 UTC, RuggeroCino commented on src/components/executionExpirationtime/index.tsx
> +          label={t('alert.maxDurationAlert') as string}
The cast to string is redundant here and below as well, does it throws some type error for you?
```suggestion
          label={t('alert.maxDurationAlert')}
```

2023-11-03 11:39 UTC, RuggeroCino commented on src/components/filteredAddressList/index.tsx
> +      {/*<ModalHeader>*/}
This commented out code can be removed, right?

2023-11-03 11:39 UTC, RuggeroCino commented on src/components/filteredAddressList/index.tsx
> +  // tokenMembership: boolean;
Let's remove this if not needed
```suggestion
```

2023-11-03 11:39 UTC, RuggeroCino commented on src/containers/communityAddressesModal/index.tsx
> -      <ModalHeader>
The `<ModalHeader />` and `<Container />` components below can now be removed

2023-11-06 10:43 UTC, selankon commented on src/containers/configureCommunity/proposalCreation.tsx
> +    </div>
Well, it seems that the `MultisigEligibility` component appears also on the settings edition, which i am not sure if use a pretty different form contexts. 

As we have not yet implemented the editSettings page, I will let this open until is implemented to check if this component can be refactored.

2023-11-06 10:46 UTC, selankon commented on src/containers/goLive/index.tsx
> +      {votingType === 'offChain' && <Committee />}
Mmm I'm not sure: the committee is a conditional step, so on this way, you can see that is a "condtional step". Could be done also on the component itself, but on the way its implemented, you avoid to execute some of the hooks that are on top of the component. 

Imo this can be let like this

2023-11-06 11:56 UTC, selankon commented on src/components/executionExpirationtime/index.tsx
> +import React, {useCallback} from 'react';
I cannot see `executionEpirationtime` string anywhere on the whole app, where did you find it?

2023-11-06 12:04 UTC, cgero-eth commented on src/containers/configureCommunity/proposalCreation.tsx
> +      )}
Using the React fragment is redundant here, right?
```suggestion
      {membership === 'multisig' && <MultisigEligibility />}
```

2023-11-06 12:04 UTC, cgero-eth commented on src/containers/configureCommunity/proposalCreation.tsx
> +          <TokenProposalCreation />
I would suggest to merge the logic of the `ProposalCreation` and `TokenProposalCreation` components in one component instead of creating two small components:
```
{membership === 'token' && isAllowedToConfigureVotingEligibility && <SelectEligibility />}
```

2023-11-06 12:04 UTC, cgero-eth commented on src/containers/delegationGatingMenu/delegationGatingMenu.tsx
> +  }
Do we accidentally open this dialog for the gaseless plugin? We should fix this by not opening the dialog instead of not rendering it

2023-11-06 12:04 UTC, cgero-eth commented on src/containers/editSettings/majorityVoting.tsx
> +    : (pluginSettings as VotingSettings | undefined);
During the initial render, the `pluginSettings` variable will be `undefined`
```suggestion
  const votingSettings = pluginSettings as GaslessPluginVotingSettings | VotingSettings | undefined;
```

2023-11-06 12:04 UTC, cgero-eth commented on src/containers/editSettings/majorityVoting.tsx
> +              {/*  type="action-builder"*/}
We usually avoid pushing commented-out code as it is a bad practice, can we get rid of all the commented code before merging this PR to develop?

2023-11-06 12:04 UTC, cgero-eth commented on src/hooks/useDaoProposal.tsx
File is empty and can be removed

2023-11-06 12:04 UTC, cgero-eth commented on src/utils/committeeVoting.ts
> +    // const locale = (Locales as Record<string, Locale>)[i18n.language];
Does this still happen?

2023-11-06 12:04 UTC, cgero-eth commented on src/services/aragon-sdk/queries/use-voting-settings.ts
> +  return 'onlyMultisigProposalCreation' in settings;
We should not be passing an empty object to this function:
```suggestion
  return settings ? 'onlyMultisigProposalCreation' in settings : false;
```

2023-11-06 12:04 UTC, cgero-eth commented on src/containers/proposalStepper/index.tsx
> +        // {...(type === 'os-update' && {skipStep: true, hideWizard: true})}
Why is this commented out?

2023-11-06 12:04 UTC, cgero-eth commented on src/hooks/useFunctionStepper.tsx
> +export type StepsMap<X extends GenericKeyEnum> = Record<X, StepData>;
If we're not actually using `number | symbol` types, I would avoid using this `GenericKeyEnum` type everywhere and write it as `extends string`. It would also be better if, instead of just `X`, we give a better name to the generic type so that it's easier to understand what it represents, like:
```suggestion
export type StepsMap<TStepKey extends string> = Record<TStepKey, StepData>;
```

2023-11-06 12:06 UTC, selankon commented on .env.staging
> +VITE_FEATURE_FLAG_GASLESS_PLUGIN=false
a8227c7f829332c2105b782a48f4b11fbcef430a

2023-11-06 12:06 UTC, selankon commented on .gitignore
> +
a8227c7f829332c2105b782a48f4b11fbcef430a

2023-11-06 12:06 UTC, selankon commented on src/components/executionExpirationtime/index.tsx
> +          label={t('alert.maxDurationAlert') as string}
a8227c7f829332c2105b782a48f4b11fbcef430a

2023-11-06 12:06 UTC, selankon commented on src/components/filteredAddressList/index.tsx
> +  // tokenMembership: boolean;
a8227c7f829332c2105b782a48f4b11fbcef430a

2023-11-06 12:06 UTC, selankon commented on src/containers/communityAddressesModal/index.tsx
> -      <ModalHeader>
a8227c7f829332c2105b782a48f4b11fbcef430a

2023-11-06 12:06 UTC, RuggeroCino commented on src/components/executionExpirationtime/index.tsx
> +import React, {useCallback} from 'react';
@selankon It's on the folder and component name, the `t` on the `time` word should be uppercased

2023-11-06 12:09 UTC, selankon commented on src/components/filteredAddressList/index.tsx
> +      {/*<ModalHeader>*/}
a8227c7f829332c2105b782a48f4b11fbcef430a

2023-11-06 12:23 UTC, selankon commented on src/components/executionExpirationtime/index.tsx
> +import React, {useCallback} from 'react';
@elboletaire just show me that you are referring to the camel case, I will fix it :P

2023-11-06 16:21 UTC, RuggeroCino reviewed
That's the last round of feedbacks regarding the code and the changed files, I will now be doing some local tests to double check that current functionalities are not affected

2023-11-06 16:21 UTC, cgero-eth commented on src/utils/proposals.ts
> +    console.log(voters);
```suggestion
```

2023-11-06 16:21 UTC, cgero-eth commented on src/hooks/useDaoToken.tsx
> +    daoDetails?.plugins[0] || ({} as InstalledPluginListItem);
Looks like the cast to `InstalledPluginListItem` is not needed
```suggestion
  const {id: pluginType} = daoDetails?.plugins[0] ?? {};
```

2023-11-06 16:21 UTC, cgero-eth commented on src/context/createGaslessProposal.tsx
> +      console.log('DEBUG', 'Estimated cost', cost, 'balance', account!.balance);
Are these debug console logs still needed?

2023-11-06 16:21 UTC, cgero-eth commented on src/containers/settings/gaslessVoting/index.tsx
> +  // const navigate = useNavigate();
Let's remove all the commented out code on this file as well 🙏🏻

2023-11-06 16:21 UTC, cgero-eth commented on src/containers/transactionModals/gaslessVotingModal.tsx
> +  ) => Promise<void>;
Let's move the props definition to a separate type and update the return type of the function to `React.FC`:
```
type GaslessVotingModalProps = { ... }

export const GasslessVotingModal: React.FC<GaslessVotingModalProps> = (...) => { ... }
```

2023-11-06 16:21 UTC, cgero-eth commented on src/containers/transactionModals/gaslessVotingModal.tsx
> +  setVoteSubmitted: React.Dispatch<React.SetStateAction<boolean>>;
The two callbacks can be probably simplified as:
```suggestion
  setShowVoteModal: (showModal: boolean) => void;
  setVoteSubmitted: (voteSubmitted: boolean) => void;
```

2023-11-06 16:21 UTC, cgero-eth commented on src/containers/votingTerminal/committeeVotingTerminal.tsx
> +  pluginType: PluginTypes;
Let's move these props type definition to a `CommitteeVotingTerminalProps` type

2023-11-06 16:21 UTC, cgero-eth commented on src/services/aragon-sdk/queries/use-proposal.ts
> +  data = await client?.methods.getProposal(params.id);
Looks like the `daoName` and `daoAddress` params of the `GaslessVotingClient.getProposal` function are optional. Also this function is not called if `params.id` is not set:
```suggestion
  const data = await client?.methods.getProposal(params.id);
```

2023-11-06 16:21 UTC, cgero-eth commented on src/pages/proposeSettings.tsx
>      return pluginClient?.estimation.createProposal(proposalCreationData);
Instead of adding a `@ts-ignore` directive and disable the eslint rule, I would just return in case the client is a gasless voting client and write a comment:
```suggestion
    // The propose settings flow is not currently handled by the gasless voting client
    if (!proposalCreationData || isGaslessVotingClient(pluginClient)) return;

    return pluginClient?.estimation.createProposal(proposalCreationData);
```

2023-11-06 16:21 UTC, cgero-eth commented on src/pages/proposeSettings.tsx
> +    );
Same here:
```suggestion
    // The propose settings flow is not currently handled by the gasless voting client
    if (isGaslessVotingClient(pluginClient)) {
      return;
    }

    const proposalIterator =
      pluginClient.methods.createProposal(proposalCreationData);
```

2023-11-06 16:21 UTC, cgero-eth commented on src/context/prepareUpdate.tsx
> +      // @ts-ignore
I wouldn't add a `@ts-ignore` here but instead just return void if the client is a `GaslessVotingClient`, same for the `preparePluginIterator` handling below

2023-11-06 16:21 UTC, cgero-eth commented on src/pages/createDAO.tsx
> +  // }, [eligibilityType, errors.eligibilityTokenAmount, membership]);
This can be removed, right?
```suggestion
```

2023-11-06 16:21 UTC, RuggeroCino commented on src/pages/proposal.tsx
> +        sanitizeHtml(proposal.metadata.description!, {
We're already checking that `proposal.metadata.description` is not null, right?
```suggestion
        sanitizeHtml(proposal.metadata.description, {
```

2023-11-06 16:21 UTC, RuggeroCino commented on src/pages/proposal.tsx
> +              votingTerminal={<VTerminal />}
Instead of passing the `VotingTerminal` as prop, I would suggest to pass it as a child component:
```
<CommitteeVotingTerminal
  proposal={proposal}
  {...}
>
  <VotingTerminal />
</CommitteeVotingTerminal>
```

2023-11-06 16:21 UTC, RuggeroCino commented on src/context/useGaslessVoting.tsx
> +      console.log('DEBUG', 'ElectionId and vote', electionId, vocVote);
Let's remove the `console.log` if they're not needed anymore

2023-11-06 16:21 UTC, RuggeroCino commented on src/context/createProposal.tsx
> +          // expirationDate: Date;
We probably need this to display the proposal even when not yet indexed by subgraph

2023-11-06 16:21 UTC, RuggeroCino commented on src/context/createProposal.tsx
> +          // disabledCallback={disableActionButton}
Let's remove these if not currently needed:
```suggestion
```

2023-11-07 08:13 UTC, selankon commented on src/components/StepperProgress/index.tsx
> +export default StepperModalProgress;
https://github.com/aragon/app/commit/a8227c7f829332c2105b782a48f4b11fbcef430a

2023-11-07 08:14 UTC, selankon commented on src/components/executionExpirationtime/index.tsx
> +import React, {useCallback} from 'react';
(on your first comment you wrote `executionEpirationtime` which has a typo, and i was looking for this :P )

2023-11-07 08:20 UTC, selankon commented on src/containers/configureCommunity/proposalCreation.tsx
> +          <TokenProposalCreation />
Absolutely yes, maybe i split this for some purpose during the coding and I forget to merge it again. I will fix it

2023-11-07 08:28 UTC, selankon commented on src/containers/delegationGatingMenu/delegationGatingMenu.tsx
> +  }
True, this is done here https://github.com/aragon/app/blob/19d3c319778fb51ae02125459e7382b02fbf4532/src/pages/proposal.tsx#L573-L577 and shouldn't be open.

I'll delete this lines

2023-11-07 08:33 UTC, selankon commented on src/containers/editSettings/majorityVoting.tsx
> +              {/*  type="action-builder"*/}
Ok, but we are awaiting a the GraphQl implementation to have a feature that we need to implement the commented code. Hopefully before merge. I will let this comment open as reminder

2023-11-07 08:43 UTC, selankon commented on src/utils/committeeVoting.ts
> +    // const locale = (Locales as Record<string, Locale>)[i18n.language];
Not anymore.  fixing

2023-11-07 08:47 UTC, selankon commented on src/containers/proposalStepper/index.tsx
> +        // {...(type === 'os-update' && {skipStep: true, hideWizard: true})}
Commented by development purposes by @emmdim . 

This is because if there are a pending os-update, you cannot add actions, and we disabled it for development purposes. I'll let this comment open as a reminder

2023-11-07 09:02 UTC, selankon commented on src/hooks/useFunctionStepper.tsx
> +export type StepsMap<X extends GenericKeyEnum> = Record<X, StepData>;
Mmm not sure why I add `number | symbol` as key types... Maybe at the beginning i was thinking on other behavior. Thanks for point to it!

I implement your solution, but i have a question: could not be even better to still use a type alias to store the `StepsMap` key type?

```ts
export type GenericKeyEnum = string;
```

On this way, you will ensure readability or scalability for future refactors, imho

2023-11-07 09:18 UTC, selankon commented on src/hooks/useFunctionStepper.tsx
> +export type StepsMap<X extends GenericKeyEnum> = Record<X, StepData>;
f947d5a8

2023-11-07 09:18 UTC, selankon commented on src/utils/proposals.ts
> +    console.log(voters);
f947d5a8

2023-11-07 09:18 UTC, selankon commented on src/services/aragon-sdk/queries/use-voting-settings.ts
> +  return 'onlyMultisigProposalCreation' in settings;
f947d5a8

2023-11-07 09:18 UTC, selankon commented on src/utils/committeeVoting.ts
> +    // const locale = (Locales as Record<string, Locale>)[i18n.language];
f947d5a8

2023-11-07 09:18 UTC, selankon commented on src/hooks/useDaoProposal.tsx
f947d5a8

2023-11-07 09:19 UTC, selankon commented on src/containers/editSettings/majorityVoting.tsx
> +    : (pluginSettings as VotingSettings | undefined);
f947d5a8

2023-11-07 09:19 UTC, selankon commented on src/containers/delegationGatingMenu/delegationGatingMenu.tsx
> +  }
f947d5a8

2023-11-07 09:19 UTC, selankon commented on src/containers/configureCommunity/proposalCreation.tsx
> +          <TokenProposalCreation />
f947d5a8

2023-11-07 09:19 UTC, selankon commented on src/containers/configureCommunity/proposalCreation.tsx
> +      )}
f947d5a8

2023-11-07 09:19 UTC, selankon commented on src/components/executionExpirationtime/index.tsx
> +import React, {useCallback} from 'react';
f947d5a8

2023-11-07 09:25 UTC, RuggeroCino commented on src/containers/editSettings/majorityVoting.tsx
> +              {/*  type="action-builder"*/}
@selankon Sounds good, we can also keep it and merge the PR if this is going to be fixed soon 👍🏻

2023-11-07 09:25 UTC, selankon commented on .env.development
> +
Lol, something on my OS is adding a new line at the end of the file. I tried with different editors without success, and for some editors the line is not there, so strange i have to research deeper 😵

2023-11-07 09:28 UTC, RuggeroCino commented on src/components/executionExpirationtime/index.tsx
> +import React, {useCallback} from 'react';
Oops 🙈

2023-11-07 09:29 UTC, selankon commented on src/hooks/useDaoToken.tsx
> +    daoDetails?.plugins[0] || ({} as InstalledPluginListItem);
I took this line from here

https://github.com/aragon/app/blob/develop/src/context/govTokensWrapping.tsx#L53C1-L54

Should i modify also there? Is Aragon app already existing code

2023-11-07 09:35 UTC, selankon commented on src/context/createGaslessProposal.tsx
> +      console.log('DEBUG', 'Estimated cost', cost, 'balance', account!.balance);
I guess not!

2023-11-07 09:36 UTC, cgero-eth commented on src/hooks/useFunctionStepper.tsx
> +export type StepsMap<X extends GenericKeyEnum> = Record<X, StepData>;
@selankon You're right, having a type alias would make the functionality/component easier to extend if we plan to use other types as step keys

2023-11-07 09:39 UTC, selankon commented on src/containers/settings/gaslessVoting/index.tsx
> +  // const navigate = useNavigate();
This is for the same as the commented here: https://github.com/aragon/app/pull/1074#discussion_r1384549315

I'll let this open as a reminder

2023-11-07 09:40 UTC, RuggeroCino commented on src/hooks/useDaoToken.tsx
> +    daoDetails?.plugins[0] || ({} as InstalledPluginListItem);
@selankon If we don't get type issues there as well yes please 🙏🏻

2023-11-07 10:03 UTC, selankon commented on src/hooks/useDaoToken.tsx
> +    daoDetails?.plugins[0] || ({} as InstalledPluginListItem);
7abb8407

2023-11-07 10:03 UTC, selankon commented on src/context/createGaslessProposal.tsx
> +      console.log('DEBUG', 'Estimated cost', cost, 'balance', account!.balance);
7abb8407

2023-11-07 10:03 UTC, selankon commented on src/containers/transactionModals/gaslessVotingModal.tsx
> +  ) => Promise<void>;
7abb8407

2023-11-07 10:03 UTC, selankon commented on src/pages/proposal.tsx
> +        sanitizeHtml(proposal.metadata.description!, {
7abb8407

2023-11-07 10:04 UTC, selankon commented on src/pages/proposal.tsx
> +              votingTerminal={<VTerminal />}
7abb8407

2023-11-07 10:04 UTC, selankon commented on src/context/useGaslessVoting.tsx
> +      console.log('DEBUG', 'ElectionId and vote', electionId, vocVote);
7abb8407

2023-11-07 10:04 UTC, selankon commented on src/context/createProposal.tsx
> +          // disabledCallback={disableActionButton}
7abb8407

2023-11-07 10:18 UTC, RuggeroCino commented on .env.development
> +
A new line at the end of the file is fine, but here the new line is on the first line

2023-11-07 10:19 UTC, selankon commented on src/context/createProposal.tsx
> +          // expirationDate: Date;
d691c862

2023-11-07 10:31 UTC, elboletaire commented on .env.development
> +
Not your os @selankon, but the editorconfig defined in the project: https://github.com/aragon/app/blob/develop/.editorconfig#L9

2023-11-07 10:41 UTC, elboletaire commented on .env.development
> +
Correction on my previous comment (now removed): indeed the new line at the beginning of the file is really weird. FYI the new line at the end is there [due to `.editorconfig` defined that way in the project](https://github.com/aragon/app/blob/develop/.editorconfig#L9) (btw kinda curious that it has the new line at the end defined, but the `.editorconfig` file itself does not have that new line at the end 😅).

2023-11-08 20:42 UTC, emmdim commented on src/context/createGaslessProposal.tsx
> +    endDate: data?.endDate ?? new Date(),
@selankon as we have repeated various times, there was even an issue about it that you closed, the endDate cannot be the current date

2023-11-08 20:45 UTC, emmdim commented on src/context/createGaslessProposal.tsx
> +    endDate: data?.endDate ?? new Date(),
You either need to add minDuration or ensure that the value is going to be there

2023-11-09 12:20 UTC, RuggeroCino commented
@emmdim @selankon I run some smoke tests locally and didn't find any issue. I only saw this new error on the console for some DAO page (e.g. http://localhost:3000/#/daos/ethereum/safari.dao.eth/dashboard):
<img width="815" alt="Screenshot 2023-11-09 at 13 17 29" src="https://github.com/aragon/app/assets/19923822/15440e13-fe76-4d63-afc6-b11f972b6c04">

2023-11-10 10:49 UTC, RuggeroCino commented on .env.example
> +VITE_VOCDONI_ENV='stg'
This should probably be on the `.env.staging` file and not here

2023-11-10 10:50 UTC, RuggeroCino commented on package.json
> +    "build": "tsc && cross-env NODE_ENV=development node --max_old_space_size=16384 ./node_modules/vite/bin/vite.js build --sourcemap true > build.txt",
Just a reminder to switch it back before merging the PR
```suggestion
    "build": "tsc && cross-env NODE_ENV=production node --max_old_space_size=16384 ./node_modules/vite/bin/vite.js build --sourcemap true > build.txt",
```

2023-11-13 09:43 UTC, RuggeroCino approved these changes

2023-11-13 16:15 UTC, merged