Fix: APP-2551 - Crowdin Issues
aragon/app-legacy pull request #1085
Opened 2023-10-23 08:13 UTC by sepehr2github

## Description

- Fix crowdin labels on indicated places

Task: [APP-2551](https://aragonassociation.atlassian.net/browse/APP-2551)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [x] I have tested my code on the test network.

2023-10-23 14:56 UTC, Fabricevladimir commented on src/containers/proposalStepper/index.tsx
> +        <SetupVotingForm
Why not get the members inside SetupVotingForm instead and enable the query based on the votingSettings type? There's a typeguard called isMultisigVotingSettings so you won't even need to pass in additional props

2023-10-24 10:59 UTC, Fabricevladimir requested changes
Thanks! Left a few comments.

2023-10-24 10:59 UTC, Fabricevladimir commented on src/containers/setupVotingForm/index.tsx
> +  daoMembers?: DaoMembersData;
See previous comment.

2023-10-24 10:59 UTC, Fabricevladimir commented on src/containers/setupVotingForm/multisig.tsx
> +  pluginSettings,
If you opt to pass the `pluginSettings` in here, can you type it accordingly so you don't have to cast it later on?

2023-10-24 10:59 UTC, Fabricevladimir commented on src/containers/smartContractComposer/emptyStateModal/emptyState.tsx
> +          description={htmlIn(t)('scc.emptyState.description')}
Something is off about this:

2023-10-24 11:01 UTC, Fabricevladimir commented
There's an issue with the gating as well for token voting: 
<img width="403" alt="Screenshot 2023-10-24 065428" src="https://github.com/aragon/app/assets/16927999/540b9497-ccbb-4c01-a805-384d98967775">

2023-10-25 10:01 UTC, Fabricevladimir requested changes

2023-10-25 10:01 UTC, Fabricevladimir commented on src/containers/setupVotingForm/index.tsx
> +  pluginSettings: VotingSettings;
This type should be SupportedVotingSettings

2023-10-25 10:01 UTC, Fabricevladimir commented on src/locales/en/common.json
> +      "tokenDescription": "You don’t have the required voting power or token balance. Creating proposals in {{daoName}} requires at least {{amount}} ‘{{tokenSymbol}}’ in either voting power or token
This is being used to gate the tokenVoting proposal creation. You don't seem to be passing the actual values in.

2023-10-26 09:38 UTC, Fabricevladimir commented on src/containers/setupVotingForm/tokenVoting.tsx
> +  pluginSettings: SupportedVotingSettings;
This should be `VotingSettings/MajorityVotingSettings`, that's why there's a lint issue.

2023-10-26 09:41 UTC, Fabricevladimir commented on src/locales/en/common.json
> +      "descLinkURL": "https://",
This is weird. Are we sure wwe want this gone?

2023-10-26 09:56 UTC, sepehr2github commented on src/locales/en/common.json
> +      "descLinkURL": "https://",
It's not the only empty description list, which I don't know why

2023-10-26 10:08 UTC, sepehr2github commented on src/locales/en/common.json
> +      "descLinkURL": "https://",
Just checked the link, It's invalid! 404 indeed.

2023-10-26 10:14 UTC, Fabricevladimir approved these changes

2023-10-27 07:28 UTC, merged