Fix: APP-2514 - Change default Proposal Threshold for DAO with Newly Minted token to ≥1 token
aragon/app-legacy pull request #1128
Opened 2023-11-13 15:23 UTC by Barukimang

## Description

Found the following in `createDAO.tsx`: `eligibilityTokenAmount: 1, minimumTokenAmount: 1,` meaning that the default value for the Proposal Threshold is already `1`. So I did the following:

- Removed setting on DAO creation with new token which sets Proposal Threshold to the lowest entered token amount at the wallet rows (see image 1)

- Then removed the logic which is setting the Proposal Threshold to the lowest entered token amount at the wallet rows on deletion of a wallet row

Image 1

<img width="1572" alt="image" src="https://github.com/aragon/app/assets/16764792/c1777f92-ac19-497d-bdac-882b6e533b9a">

Task: [APP-2514](https://aragonassociation.atlassian.net/browse/APP-2514)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [x] I have tested my code on the test network.

2023-11-14 10:17 UTC, Fabricevladimir requested changes
Thanks, @Barukimang !

2023-11-14 10:17 UTC, Fabricevladimir commented on src/components/addWallets/row.tsx
This `minimumTokenAmount` is being used to set the `eligibilityyTokenAmount`; you'll have to remove that assignment as well because right now, when you enter a custom number, navigating back to the page has it overwritten to 1. This is happening both in the Dao Creation flow and Edit Settings one. With the Edit settings, if you close the Accordion after updating the min proposal eligibility, it reverts back to 1 as well.

2023-11-14 18:45 UTC, Barukimang commented on src/components/addWallets/row.tsx
Am not sure whether I am able to comprehend your comment. My brain has turned to holiday mode already I think haha.

The behavior of closing the accordion in the Edit Settings after updating the min proposal eligibility and it reverting to the 'current eligibility' when opening it again is there at Production as well.

Which assignment exactly are you referring to?

I do see that I should remove redundant references to 

`'eligibilityType',
                    'eligibilityTokenAmount',`

in the `callback` below. Is that what you mean?

2023-11-16 11:27 UTC, Fabricevladimir commented on src/components/addWallets/row.tsx
>The behavior of closing the accordion in the Edit Settings after updating the min proposal eligibility and it reverting to the 'current eligibility' when opening it again is there at Production as well.

That my dear friend is a bug lol. If you prefer to create a ticket for it, let me know, and I'll approve this PR

2023-11-16 12:25 UTC, Barukimang commented on src/components/addWallets/row.tsx
Hahah and me assuming everything on Production was bug free 😛 

No worries, will create the ticket for it as bug-ticket-meastro.

Pushed one more commit btw 👇 removing `'eligibilityType', 'eligibilityTokenAmount',` in the calback.

2023-11-21 09:11 UTC, Fabricevladimir approved these changes

2023-11-22 12:26 UTC, merged