F/update card
aragon/app-legacy pull request #1143
Opened 2023-11-24 09:28 UTC by sepehr2github

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task: [APP-0000](https://aragonassociation.atlassian.net/browse/APP-0000)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have tested my code on the test network.

2023-11-24 12:14 UTC, Fabricevladimir requested changes

2023-11-24 12:14 UTC, Fabricevladimir commented on src/utils/proposals.ts
> +export async function isVerifiedAragonUpdateProposal(
Considering this is now an async function, I would highly recommend having a react-query hook in the services for it.

2023-11-24 12:14 UTC, Fabricevladimir commented on src/containers/defineProposal/update.tsx
> +      : 'Multisig';
Do we not have translation keys for this?

2023-11-24 12:14 UTC, Fabricevladimir commented on src/context/createProposal.tsx
> +                pluginAddress: pluginAddress,
These two should be coming from the action inputs

2023-11-24 12:14 UTC, Fabricevladimir commented on src/context/createProposal.tsx
> +                initData: new Uint8Array([]),
`initData` as well.

2023-11-24 12:14 UTC, Fabricevladimir commented on src/context/createProposal.tsx
> +          const daoActionsArray =
This should be renamed to `pluginUpdateActions` or something since it's the plugin update and not the Dao update

2023-11-24 12:14 UTC, Fabricevladimir commented on src/hooks/useUpdateVerification.tsx
> +export function useUpdateVerification(daoAddress: string, proposalId?: string) {
Please update the comments since this is no longer a mock and now takes in a different parameter(s). 

I haven't wrapped the whole concept around my head just yet, but doesn't this force you to run both validations even if the propsal is only one type of update proposal?

Also, in general, I recommend using the services structure for these hooks as we're able to manage them easier and have fine grained control concerning when to enable/disable a hook.

2023-11-24 12:14 UTC, Fabricevladimir commented on src/hooks/useUpdateVerification.tsx
> +        client?.methods.isPluginUpdateProposal(proposalId as string),
Shouldn't this be `isPluginUpdateProposalValid`?

2023-11-24 12:14 UTC, Fabricevladimir commented on src/hooks/useUpdateVerification.tsx
> +      enabled: Boolean(daoAddress) && Boolean(proposalId),
The query seemingly no longer needs `daoAddress`, I'm not sure it should be part of what is enabling and disabling it.

2023-11-24 12:14 UTC, Fabricevladimir commented on src/containers/proposalSnapshot/index.tsx
> +  }, [client, proposalId]);
That is potentially a whole lot of calls trying to find if the proposal is an update proposal. My proposal (hehehe) is that at the very least convert this to a react-query query so we can make use of caching.

2023-11-24 12:14 UTC, Fabricevladimir commented on src/components/proposalList/index.tsx
> +  }, [client, proposalId]);
See my comment on the proposal snapshot

2023-11-24 12:30 UTC, sepehr2github commented on src/containers/defineProposal/update.tsx
> +      : 'Multisig';
No, we don't

2023-11-24 12:30 UTC, Fabricevladimir commented
Two other things:
Seems like the `isMember` function isn't working and returning false when that's not the case.
The banner on top of the Proposal Card doesn't show up for the update proposals

A final very nice to have would be after proposal execution, if we know that it is an update proposal, invalidate the queries that fetch the plugin and os versions because right now once we've executed the proposal, the version card on the settings page doesn't get updated until we manually refresh the page or wait the allotted 5 mins for the query to become stale

2023-11-27 12:49 UTC, Fabricevladimir commented on src/locales/en/common.json
> +      "etherscanStatusCritical": "Not verified on {{blockExplorerName}}",
This ticket hasn't been picked up yet so there is no variable being passed for these strings.

Also, for whatever reason the title for the update Proposal has `p` tags surrounding it

2023-11-27 12:49 UTC, Fabricevladimir commented on src/pages/proposal.tsx
> +import {featureFlags} from 'utils/featureFlags';
We have a duplicate (thoughh commented out) import on line 59

2023-11-27 12:49 UTC, Fabricevladimir commented on src/pages/proposal.tsx
>            {/* @todo: Add isUpdateProposal check once it's developed */}
Can you remove the comment, please

2023-11-27 12:49 UTC, Fabricevladimir commented on src/context/proposalTransaction.tsx
> +  const queryNetwork = useMemo(
Why have this outside and not calculated inside the funciton that needs it?

2023-11-27 12:49 UTC, Fabricevladimir commented on src/containers/updateVerificationCard/index.tsx
> +
Not a huge deal, but ths is going to run for every proposal regardless of whether it's a os-update or default proposal because we don't have access to the options object to enable this only after the `useIsUpdateProposal` hook returns true.

2023-11-27 12:49 UTC, Fabricevladimir commented on src/containers/updateVerificationCard/Status.tsx
> +export const Status: React.FC<StatusProps> = ({
Can you lowercase the file name?

2023-11-27 12:49 UTC, Fabricevladimir commented on src/pages/proposal.tsx
> +          {proposal &&
Don't forget to hide the verification card when the proposal is neither pending nor active.

2023-11-28 11:24 UTC, sepehr2github commented on src/locales/en/common.json
> +      "etherscanStatusCritical": "Not verified on {{blockExplorerName}}",
could you point me to the update Proposal title file?

2023-11-28 18:00 UTC, Fabricevladimir approved these changes

2023-11-28 18:00 UTC, merged