Chore: Button ODS APP implementation
aragon/app-legacy pull request #1222
Opened 2024-02-08 12:00 UTC by RakeshUP

## Description

Task: [APP-2753](https://aragonassociation.atlassian.net/browse/APP-2753)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [x] I have tested my code on the test network.

2024-02-08 19:31 UTC, jamesej requested changes
Hi Rakesh, thanks for grinding through this, pretty much all looks good except for the styling fix I have in a comment. Also it seems that the `bgWhite` and `active` props are just ignored on the new button, can you confirm that's intended?

2024-02-08 19:31 UTC, jamesej commented on src/containers/selectChainForm/index.tsx
> -            isActive={networkType === 'main'}
Doesn't look like the isActive prop is mapped onto the new ODS Button

2024-02-08 19:31 UTC, jamesej commented on src/containers/selectChainForm/index.tsx
> -            isActive={networkType === 'test'}
Same issue with isActive

2024-02-08 19:31 UTC, jamesej commented on src/containers/daoFilterModal/index.tsx
>          className="hidden lg:block"
should be lg:flex - lg;block removes flex style and breaks layout of icon in button

2024-02-09 10:06 UTC, jamesej commented
Another thing, there are buttons in SearchHeader.tsx, stateEmpty/index.tsx and pageEmptyState/index.tsx not yet converted and I think you may have missed converting ButtonWallet.tsx - was that intentional?

2024-02-09 11:04 UTC, RakeshUP commented
Hi @jamesej, thanks for the quick review!

- The new ODS button does not have both `isActive` or `bgWhite` prop. Also the `secondary` and `ghost` variant's styles have changed. So the prop changes were intended.
- The new ODS library does not include ButtonGroup and ButtonWallet yet and there are no plans to build these components on the ODS for now. So these changes have to wait.
- Apart from that I've skipped 6 files because they are ODS module components like WYISWYG editor/EmptyState which will anyways be changed soon.

I'll give the whole changes a quick QA and ensure that none of the buttons are breaking the app layout now

2024-02-13 11:33 UTC, jamesej approved these changes
All good, what a giant PR!

2024-02-13 11:52 UTC, merged