Replace linearprogress with Progress from ODS
aragon/app-legacy pull request #1228
Opened 2024-02-13 11:30 UTC by sepehr2github

## Description

- Replace linearprogress with Progress from ODS
- Fix empty link breaking the proposal creation

Task1: [APP-2775](https://aragonassociation.atlassian.net/browse/APP-2775)
Task2: [APP-2800](https://aragonassociation.atlassian.net/browse/APP-2800)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [x] I have tested my code on the test network.

2024-02-13 18:27 UTC, jamesej requested changes
The issue around the new `Progress` component not having `w-full` class probably affects all instances except in Voting Terminal.

2024-02-13 18:27 UTC, jamesej commented on src/containers/configureCommunity/minParticipation.tsx
> +                            100
`((govTokenTotalSuppy * (value / 100)) / govTokenTotalSupply) * 100` is actually equal to just `value`

2024-02-13 18:27 UTC, jamesej commented on src/components/multisigMinimumApproval/minimumApproval.tsx
> +            <Progress value={((value <= max ? value : max) / max) * 100} />
Original `LinearProgress` has a container div with the style `w-full` set on it. `Progress` doesn't have this and so does not extend to the full width of `LinearProgressContainer`, which looks wrong. This is likely a problem with the component itself.

2024-02-13 18:29 UTC, sepehr2github commented on src/containers/configureCommunity/minParticipation.tsx
> +                            100
> `((govTokenTotalSuppy * (value / 100)) / govTokenTotalSupply) * 100` is actually equal to just `value`

hahaha, nice catch

2024-02-14 14:17 UTC, RuggeroCino reviewed
Something's off on the min-participation progress:
<img width="828" alt="Screenshot 2024-02-14 at 15 16 04" src="https://github.com/aragon/app/assets/19923822/8bfc7f04-4bf6-405b-8fb8-26084ca8a6a9">

2024-02-15 08:41 UTC, RuggeroCino approved these changes
All good for me, thanks @sepehr2github!

2024-02-15 08:42 UTC, merged