Feature/Link - DAO-608
aragon/app-legacy pull request #125
Opened 2022-01-11 16:34 UTC by Fabricevladimir

- added `Link` component 
- removed stray log in test

2022-01-11 17:06 UTC, sepehr2github commented on packages/ui-components/src/components/link/link.tsx
> +      {...(external ? {target: '_blank'} : {})}
Thank you for adding this option.

2022-01-11 17:09 UTC, sepehr2github approved these changes
Looks Great! Awsome. Fabrice

2022-01-12 11:25 UTC, WissenIstNacht requested changes
Thanks, looks great!

There's a tiny change needed, then we should be good to go.

2022-01-12 11:25 UTC, WissenIstNacht commented on packages/ui-components/src/components/link/link.tsx
> +      focus:bg-ui-0 rounded focus:ring-2 focus:ring-primary-500 focus:outline-none`;
So apparently, the focus state is not meant to change the background. I t should always be transparent. The reason this was done on figma is because apparently you need to set a background to show the border or something. Not your fault, but it needs changing :)

2022-01-12 11:25 UTC, WissenIstNacht commented on packages/ui-components/stories/link.stories.tsx
> +  href: 'https://abc.com',
Exotic choice :D

2022-01-12 11:25 UTC, WissenIstNacht commented on packages/ui-components/src/components/input/dateInput.tsx
> +
Thanks!

2022-01-12 18:04 UTC, Fabricevladimir commented on packages/ui-components/stories/link.stories.tsx
> +  href: 'https://abc.com',
What can I say? I'm wild!

2022-01-12 18:04 UTC, Fabricevladimir commented on packages/ui-components/stories/link.stories.tsx
> +  href: 'https://abc.com',
What can I say? I'm wild!

2022-01-12 20:13 UTC, WissenIstNacht approved these changes

2022-01-13 10:54 UTC, merged