Feature: DAO 613 - Progress status
aragon/app-legacy pull request #128
Opened 2022-01-13 09:54 UTC by WissenIstNacht

This PR implements:
- Progress->Status component
- Corresponding story
- Corresponding test

2022-01-13 14:35 UTC, Fabricevladimir requested changes
Nice work, thanks! Left a few comments here and there. I'm pleasantly surprised at how complicated the component itself turned out to be with the different props affecting each other.

2022-01-13 14:35 UTC, Fabricevladimir commented on packages/ui-components/src/components/icons/interface/icon_block.tsx
> +          clip-rule="evenodd"
Can you camel case `fill-rule` and `clip-rule`?

2022-01-13 14:35 UTC, Fabricevladimir commented on packages/ui-components/src/components/icons/interface/radio/cancle.tsx
> +      <g clip-path="url(#clip0_430_5)">
Camel casing for `clip-path`

2022-01-13 14:35 UTC, Fabricevladimir commented on packages/ui-components/src/components/icons/interface/radio/cancle.tsx
> +export const IconRadioCancle: IconType = ({
Slight misspelling, should be 'cancel'.

2022-01-13 14:35 UTC, Fabricevladimir commented on packages/ui-components/src/components/progress/status.tsx
> +      <BlockContainer>
If no block is given, the icon shouldn't be rendered.

2022-01-13 14:35 UTC, Fabricevladimir commented on packages/ui-components/src/components/progress/status.tsx
> +/* Lord knows it hurts. */
Yes, this is just sad, really.

2022-01-13 14:35 UTC, Fabricevladimir commented on packages/ui-components/src/components/progress/status.tsx
> +   */
I appreciate this comment. Is this something that can or even should be implemented in the code itself? Like if the mode is one of that shouldn't show the block, hide the block even if the property is provided? While it does limit the user, it also doesn't ever make sense to have the block shown. Thoughts?

2022-01-13 14:35 UTC, Fabricevladimir commented on packages/ui-components/src/components/progress/status.tsx
> +   * If no date is passed when one is required, a fallback text will be displayed.
I think you either forgot to add the fallback text or update the comment!

Also, would hiding the date even if it is given when the mode is `upcoming` a better approach? Related to the block prop comment.

2022-01-13 14:35 UTC, Fabricevladimir commented on packages/ui-components/src/components/progress/status.tsx
> +export type ProgressStatusProps = {
Very thorough documentation; I like! 👍🏾

2022-01-13 14:35 UTC, Fabricevladimir commented on packages/ui-components/src/components/progress/status.tsx
> +const TopContainer = styled.div.attrs({className: 'flex justify-between'})``;
This seems to be a fixed width on the designs. Currently, the content is squished together on mobile.

2022-01-17 10:42 UTC, RakeshUP approved these changes
Nice. The whole BlockContainer should be conditionally rendered. The other comments are very minor too.

2022-01-17 10:48 UTC, WissenIstNacht commented on packages/ui-components/src/components/progress/status.tsx
> +const TopContainer = styled.div.attrs({className: 'flex justify-between'})``;
Hmm. You're right. But does that make sense...?

FYI: The reason for the cropping on mobile is not in the component itself but in the way I set up the story. I wrapped it into a div that takes 1/3 of the screen. On mobile, that's obviously way too small and squishes the content. I've modified the story to only do the 1/3 width on tablet or larger.

Should I still fix the width or do you think it makes sense after the correction?

2022-01-17 11:01 UTC, WissenIstNacht commented on packages/ui-components/src/components/progress/status.tsx
> +   * If no date is passed when one is required, a fallback text will be displayed.
Turns out I pretty much forgot to do all of that stuff. Thanks for catching it!

2022-01-17 11:55 UTC, Fabricevladimir commented on packages/ui-components/src/components/progress/status.tsx
> +const TopContainer = styled.div.attrs({className: 'flex justify-between'})``;
Ah, that makes sense. I'm not sure why it's fixed width (maybe Figma thing?). To me it makes more sense having it take up the size of the parent.

2022-01-17 11:55 UTC, Fabricevladimir approved these changes

2022-01-17 13:23 UTC, merged