feature/Table->Voters component DAO-610
aragon/app-legacy pull request #130
Opened 2022-01-13 11:38 UTC by RakeshUP

2022-01-13 13:29 UTC, WissenIstNacht commented on packages/ui-components/src/components/table/tableCell.tsx
> +    | React.FunctionComponentElement<ButtonTextProps>;
Oops, missed that dependency. Could try to use the link component that Fabrice finished? Don't sweat it if it takes too much time. It looks just as good with the button.

2022-01-13 14:13 UTC, WissenIstNacht requested changes
Looks good, thanks! :)

Could you add the a test with the basic test scaffolding?

2022-01-13 14:13 UTC, WissenIstNacht commented on packages/ui-components/src/components/table/tableCell.tsx
> +    | React.FunctionComponentElement<ButtonTextProps>;
Oops, missed that dependency. Could try to use the link component that Fabrice finished? Don't sweat it if it takes too much time. It looks just as good with the button.

2022-01-13 15:44 UTC, Fabricevladimir requested changes
Great work! Thanks

2022-01-13 15:44 UTC, Fabricevladimir commented on packages/ui-components/src/components/table/tableCell.tsx
> +      <td
In the designs, the cell types, except for `head` and `foot`, have an inset boxshadow.

2022-01-13 15:44 UTC, Fabricevladimir commented on packages/ui-components/src/components/table/tableCell.tsx
> +  return null;
Would it be a better approach to return the most often used type (`text` maybe?) by default instead of null?

2022-01-13 15:44 UTC, Fabricevladimir commented on packages/ui-components/src/components/table/votersTable.tsx
> +          <TableCell type="head" text="Token Amount" rightAligned />
I want to cry while writing this, but the table head text should be translatable strings.

2022-01-13 15:44 UTC, Fabricevladimir commented on packages/ui-components/src/components/table/votersTable.tsx
> +                colorScheme={voter.option === 'Yes' ? 'success' : 'critical'}
This is something to think about for future maybe, but are 'yes' and 'no' the only options we have? If so, perhaps the type of the `option` prop should reflect so.

2022-01-13 15:44 UTC, Fabricevladimir commented on packages/ui-components/src/components/table/votersTable.tsx
> +  tr td {
If we could do any of this with TW it would be great for stuff like themes.

2022-01-17 13:13 UTC, RakeshUP commented on packages/ui-components/src/components/table/tableCell.tsx
> +      <td
<img width="1162" alt="Screenshot 2022-01-17 at 6 41 54 PM" src="https://user-images.githubusercontent.com/20946466/149775239-2e3d3c60-5bb0-4705-8e3a-511eae1cfa1a.png">

It's causing a double border effect in link cell in the footer. The required border style for the whole table is in the table component

2022-01-17 13:15 UTC, RakeshUP commented on packages/ui-components/src/components/table/votersTable.tsx
> +          <TableCell type="head" text="Token Amount" rightAligned />
Yeah, I thought of it too. Maybe we add i18n to the ui-components library too. @sepehr2github had faced a problem in this PR https://github.com/aragon/zaragoza/pull/139

2022-01-17 13:15 UTC, RakeshUP commented on packages/ui-components/src/components/table/votersTable.tsx
> +                colorScheme={voter.option === 'Yes' ? 'success' : 'critical'}
It seems to be only 2 options for now. The designs look that way

2022-01-17 13:23 UTC, Fabricevladimir commented on packages/ui-components/src/components/table/votersTable.tsx
> +          <TableCell type="head" text="Token Amount" rightAligned />
Yes! I very much much like the idea of the translation in ui-components

2022-01-17 14:04 UTC, RakeshUP commented on packages/ui-components/src/components/table/votersTable.tsx
> +  tr td {
Adding TW classes using className prop to TableCell component introduces a lot of classes in that component and the code might become difficult to understand. About [TW first and last modifiers](https://v2.tailwindcss.com/docs/hover-focus-and-other-states#:~:text=It%E2%80%99s%20important%20to%20note%20that%20you%20should%20add%20any%20first%3A%20utilities%20to%20the%20child%20element%2C%20not%20the%20parent%20element.)

2022-01-17 16:32 UTC, Fabricevladimir approved these changes
Looks good!

2022-01-18 09:12 UTC, WissenIstNacht approved these changes
Thanks for the

2022-01-18 09:16 UTC, merged