Feature/subgraph-init
aragon/app-legacy pull request #146
Opened 2022-01-17 13:19 UTC by Rekard0

-draft ERD
-draft mapping
-draft template

2022-01-18 12:11 UTC, nivida requested changes
Added a few comments.. but definitely have to think about the data model closer asap.

2022-01-18 12:11 UTC, nivida commented on .gitignore
> +subgraph.yaml
EOF

2022-01-18 12:11 UTC, nivida commented on .prettierrc
> +  "bracketSpacing": false,
Yeah, I was meaning in the chat that you better keep this change and the code style changes in general out of this PR. But we can keep it for now and discuss the prettier configuration later on together.

2022-01-18 12:11 UTC, nivida commented on packages/subgraph/manifest/data/rinkeby.json
> +  "network": "rinkeby",
Rinkeby is not the correct network :))

2022-01-18 12:11 UTC, nivida commented on packages/subgraph/manifest/subgraph.placeholder.yaml
> +repository: https://github.com/zaragoza
```aragon/zaragoza```

2022-01-18 12:11 UTC, nivida commented on packages/subgraph/manifest/subgraph.placeholder.yaml
> +          file: ./../contracts/artifacts/contracts/core/processes/stoppable/StoppableProcess.sol/StoppableProcess.json
Paths in general should use the constants as discussed :)

2022-01-18 12:11 UTC, nivida commented on packages/subgraph/manifest/subgraph.placeholder.yaml
> +          handler: handleStartVote
EOF

2022-01-18 12:11 UTC, nivida commented on packages/subgraph/package.json
> +  "homepage": "https://github.com/aragon/zaragoza#readme",
this could point directly to the subgraph package :)

2022-01-18 12:11 UTC, nivida commented on packages/subgraph/package.json
> +  "scripts": {
The whole graph setup should be in a docker container.

2022-01-18 12:11 UTC, nivida commented on packages/subgraph/package.json
> +    "manifest-rinkeby": "scripts/build-manifest.sh rinkeby"
We better should test directly with Arbitrum.

2022-01-18 12:11 UTC, nivida commented on packages/subgraph/schema.graphql
> +enum VoterState {
Related this we have to discuss of how we handle such things in a more generic way. Especially if we have an out look into the future of this product.

2022-01-18 12:11 UTC, nivida commented on packages/subgraph/schema.graphql
> +  isActive: Boolean!
isActive?

2022-01-18 12:11 UTC, nivida commented on packages/subgraph/schema.graphql
> +  isRemoved: Boolean!
isRemoved?

2022-01-18 12:11 UTC, nivida commented on packages/subgraph/schema.graphql
> +  dao: Dao!
What if a process is used by multiple DAOs in the future? eg a sub-dao?

2022-01-18 12:11 UTC, nivida commented on packages/subgraph/schema.graphql
> +  daoAddress: Bytes!
can't we use the address as ID?

2022-01-18 12:11 UTC, nivida commented on packages/subgraph/scripts/build-manifest.sh
> +  > subgraph.yaml
EOF

2022-01-18 12:11 UTC, nivida commented on packages/subgraph/src/dao.ts
> +  let id =
If we have such IDs concatenated based on event data should we I think create a keccak hash out of it to save some stored bytes.

2022-01-18 12:11 UTC, nivida commented on packages/subgraph/src/process.ts
> +  let proposalEntiry = new Proposal(id);
typo😇

2022-01-19 08:31 UTC, Rekard0 commented on packages/subgraph/manifest/data/rinkeby.json
> +  "network": "rinkeby",
yes, sure, each network,and testnet will have its own JSON down the road

2022-01-19 08:31 UTC, Rekard0 commented on .gitignore
> +subgraph.yaml
done

2022-01-19 08:35 UTC, Rekard0 commented on packages/subgraph/manifest/subgraph.placeholder.yaml
> +repository: https://github.com/zaragoza
done

2022-01-19 08:36 UTC, Rekard0 commented on packages/subgraph/manifest/subgraph.placeholder.yaml
> +          handler: handleStartVote
done

2022-01-19 08:38 UTC, Rekard0 commented on packages/subgraph/package.json
> +  "homepage": "https://github.com/aragon/zaragoza#readme",
done

2022-01-19 08:44 UTC, Rekard0 commented on .prettierrc
> +  "bracketSpacing": false,
opps, ok

2022-01-19 08:58 UTC, Rekard0 commented on packages/subgraph/schema.graphql
> +enum VoterState {
yah, forgot to remove

2022-01-19 09:03 UTC, Rekard0 commented on packages/subgraph/scripts/build-manifest.sh
> +  > subgraph.yaml
done

2022-01-19 09:03 UTC, Rekard0 commented on packages/subgraph/src/process.ts
> +  let proposalEntiry = new Proposal(id);
thanks, done

2022-01-19 10:25 UTC, Rekard0 commented on packages/subgraph/src/dao.ts
> +  let id =
well, yes we can, but i noticed this pattern of concatenating is a common practice, it is easier for reading while debugging...etc
but sure we can think of optimizations like this.

2022-01-19 10:28 UTC, Rekard0 commented on packages/subgraph/schema.graphql
> +  daoAddress: Bytes!
yes, thanks

2022-01-19 10:30 UTC, Rekard0 commented on packages/subgraph/package.json
> +  "scripts": {
i made another task for this,,, should it be include it in this PR?

2022-01-19 10:31 UTC, Rekard0 commented on packages/subgraph/manifest/subgraph.placeholder.yaml
> +          file: ./../contracts/artifacts/contracts/core/processes/stoppable/StoppableProcess.sol/StoppableProcess.json
i made another task for this,,, should it be include it in this PR?

2022-01-19 11:40 UTC, Rekard0 commented on packages/subgraph/schema.graphql
> +  dao: Dao!
thanks, we should use many-to-many relationship
done

2022-01-19 11:41 UTC, Rekard0 commented on packages/subgraph/package.json
> +    "manifest-rinkeby": "scripts/build-manifest.sh rinkeby"
i made another task for this,,, should it be include it in this PR?

2022-01-20 14:23 UTC, nivida commented on packages/subgraph/manifest/subgraph.placeholder.yaml
> +          file: ./../contracts/artifacts/contracts/core/processes/stoppable/StoppableProcess.sol/StoppableProcess.json
Feel free to do it in a separate PR to not blow this one up even more

2022-01-20 14:23 UTC, nivida commented on packages/subgraph/package.json
> +    "manifest-rinkeby": "scripts/build-manifest.sh rinkeby"
👍

2022-01-20 14:25 UTC, nivida commented on packages/subgraph/src/dao.ts
> +  let id =
Hmm good point.. cause I was in this situation once.. and it annoyed me cause I was not able to check things in a few seconds.. 👍

2022-01-20 14:25 UTC, nivida commented on packages/subgraph/package.json
> +  "scripts": {
👍

2022-01-20 14:28 UTC, nivida approved these changes
Approved! :) 

The mentioned improvements required will be done as discussed in other smaller PRs to not blow this one up even more.

2022-01-20 15:30 UTC, merged