Feature/pagination
aragon/app-legacy pull request #159
Opened 2022-01-20 15:07 UTC by sepehr2github

- pagination added
- change storybook background settings

2022-01-20 16:27 UTC, WissenIstNacht commented on packages/ui-components/src/components/pagination/pagination.tsx
> +  defaultStep?: number;
I'm not sure I understand this. When I change it to something else on the story, nothing seems to change.

2022-01-20 16:33 UTC, WissenIstNacht commented on packages/ui-components/src/components/pagination/pagination.tsx
> +    const List = [];
lowercase :p

2022-01-20 16:36 UTC, WissenIstNacht commented on packages/ui-components/src/components/pagination/pagination.tsx
> +      {ButtonList()}
ButtonList is pretty much a React component, no? You coul actually use this in JSX, then. Like `<ButtonList />`

2022-01-20 17:04 UTC, WissenIstNacht commented on packages/ui-components/src/components/pagination/pagination.tsx
> +      return <>{List}</>;
```suggestion
      return List;
```

Maybe a bit less complicatedd :p

2022-01-20 17:07 UTC, WissenIstNacht commented on packages/ui-components/src/components/pagination/pagination.tsx
> +      for (let i = 1; i <= 5; i++) {
careful here: the maximum of the loop is actually related to the `distance` variable. Maybe you should express 5 as in terms of distance

2022-01-20 17:08 UTC, WissenIstNacht commented on packages/ui-components/src/components/pagination/pagination.tsx
> +    const Distance = 3;
Not sure, but it might be worth exposing this as a prop.

Also, lowercase :D

2022-01-20 17:19 UTC, WissenIstNacht commented on packages/ui-components/src/components/pagination/pagination.tsx
> +      for (let i = totalSteps - 5; i <= totalSteps; i++) {
You have a off by one error here. Should be 4 instead of 5.

```suggestion
      for (let i = totalSteps - 4; i <= totalSteps; i++) {
```

But ideally it should be `totalSteps - (tailSize - 1)`, where `tailSize` is the numer of elements you want to show at the beginning/end.

2022-01-20 17:23 UTC, WissenIstNacht requested changes
Thanks a lot, cool component! :)

I found a small error in the logic. Also, I left some comments on the code itself (variable naming, props and such). Let me know if you dis- / agree!

2022-01-20 18:11 UTC, sepehr2github commented on packages/ui-components/src/components/pagination/pagination.tsx
> +      return <>{List}</>;
the return of the arrey is a react element and can not return an array. So I tried to return an array as react element

2022-01-20 18:13 UTC, sepehr2github commented on packages/ui-components/src/components/pagination/pagination.tsx
> +      for (let i = 1; i <= 5; i++) {
That's exactly what you said!

2022-01-20 18:14 UTC, sepehr2github commented on packages/ui-components/src/components/pagination/pagination.tsx
> +      for (let i = totalSteps - 5; i <= totalSteps; i++) {
Thanks, you're right!

2022-01-21 08:02 UTC, RakeshUP approved these changes
Looks good.

2022-01-21 09:57 UTC, WissenIstNacht approved these changes

2022-01-21 09:57 UTC, WissenIstNacht commented on packages/ui-components/src/components/pagination/pagination.tsx
> +  distance?: number;
Thanks a lot the changes and exposing this.

There is still an edge case that is slightly wrong. If you set the distance to one and click the next page button twice you get `1 ... 2 3 4 ... 10`. But it's not a huge deal.

I'll approve the PR.

2022-01-21 12:46 UTC, sepehr2github commented on packages/ui-components/src/components/pagination/pagination.tsx
> +  distance?: number;
Thanks. Selim said the distance will be fixed

2022-01-21 12:46 UTC, merged