Feature/factory tests
aragon/app-legacy pull request #164
Opened 2022-01-23 15:58 UTC by novaknole

2022-01-24 10:45 UTC, nivida requested changes

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/core/processes/Process.sol
> +                    action.to != address(this)
why this check? I think you want to execute also things outside of the DAO?

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/factories/DAOFactory.sol
> +    struct AllowedActions {
Can you elaborate closer on this struct? from my perspective is this not required :))

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/factories/DAOFactory.sol
> +        TokenFactory.MintConfig calldata _mintConfig,
Can't we have token and mint config in the same struct?

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/factories/DAOFactory.sol
> +        DAOConfig calldata _daoConfig,
We have to think here about how we can pass the minimum amount of bytes for the creation of a DAO.. It will have quite some impact on how much a DAO creation costs..🤔

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/factories/DAOFactory.sol
> +    // @param _daoConfig The DAO name and metadata
I think the natspec is missing a few definitions.

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/factories/DAOFactory.sol
> +        dao.grant(address(dao), address(tokenFactory), dao.ROOT_ROLE());
Probably worth to comment here why we grant the TokenFactory permissions on the DAO. Noticed this cause I had to read the TokenFactory contract first to understand why exactly.

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/factories/DAOFactory.sol
> +        ACLData.BulkItem[] memory items = new ACLData.BulkItem[](4);
Can't we do all those permissions within one ACL.Bulk?

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/factories/DAOFactory.sol
> +        emit DAOCreated(_daoConfig.name, address(token), address(voting));
Probably worth to sync about the registry and daofactory events on a quick call.. we could also have just here in the factory one event and no event in the registry..

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/factories/TokenFactory.sol
> +        address[] tos;
I would use a better name as ``tos``

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/factories/TokenFactory.sol
> +    // TODO: Worth considering the decimals ?
yup definitely worth :-)

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/factories/TokenFactory.sol
> +    // @return MerkleMinter Merkle Minter
natspec is misleading

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/factories/TokenFactory.sol
> +            // token to make it governance token.
probably worth in general to check the grammar of the added comments.. sorrey😇

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/factories/TokenFactory.sol
> +        address token = _tokenConfig.addr;
I think this isn't required cause ``token`` as defined here will only be used on line 65 and otherwise overwritten.

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/factories/TokenFactory.sol
> +        // IMPORTANT: If creator already has a token, It's that token's
Probably worth to move this comment to the function natspec.

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/factories/TokenFactory.sol
> +
one break too much🤓

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/permissions/DAOPermissionHandler.sol
> +    function __Initialize_DAO_Permission(IDAO _dao) internal {
Nice you used here the recommended naming of OZ? Should we after this PR apply it to all contracts? WDYT?

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/permissions/DAOPermissionHandler.sol
> +abstract contract DAOPermissionHandler {
Let us ask some other folks as well to come up with a better name.. my eyes somehow burn..

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/permissions/DAOPermissionHandler.sol
> +pragma solidity 0.8.10;
Let us add here the natpec as on all other contracts as well :))

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/tokens/GovernanceERC20.sol
> +    function delegates(address account) public view virtual override returns (address) {
noice! yup this requirement will definitely come up..

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/tokens/GovernanceToken.sol
> +abstract contract GovernanceToken is Initializable, DAOPermissionHandler, ERC20VotesUpgradeable {
what is the reason for this abstract contract? In this PR it isn't used anywhere.. 

Natspec is missing.

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/tokens/MerkleDistributor.sol
> +}
EOF

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/tokens/MerkleDistributor.sol
> + * SPDX-License-Identifier:    GPL-3.0
Just to double check.. you overtook the license from Uniswap right? not that we get into troubles :))

2022-01-24 10:45 UTC, nivida commented on packages/contracts/contracts/tokens/MerkleMinter.sol
> + * SPDX-License-Identifier:    GPL-3.0
Can't we have this licensed as everything else under MIT?

2022-01-24 10:45 UTC, nivida commented on packages/contracts/test/utils/voting.ts
> +}
EOF

2022-01-25 07:21 UTC, novaknole commented on packages/contracts/contracts/factories/DAOFactory.sol
> +        dao.grant(address(dao), address(tokenFactory), dao.ROOT_ROLE());
Our GovernanceERC20 token has a `mint` function that is auth restricted. TokenFactory needs to have permissions so that it can allow itself to mint tokens right away on GovernanceERC20.

2022-01-25 07:22 UTC, novaknole commented on packages/contracts/contracts/factories/DAOFactory.sol
> +        ACLData.BulkItem[] memory items = new ACLData.BulkItem[](4);
no, one of them is bulking on `voting` , and the other one is on the `dao`.

2022-01-25 07:23 UTC, novaknole commented on packages/contracts/contracts/factories/TokenFactory.sol
> +        address token = _tokenConfig.addr;
Not sure exactly what you mean.. elaborate ?

2022-01-25 07:24 UTC, novaknole commented on packages/contracts/contracts/permissions/DAOPermissionHandler.sol
> +    function __Initialize_DAO_Permission(IDAO _dao) internal {
Yes... Much safer.

2022-01-25 07:24 UTC, novaknole commented on packages/contracts/contracts/tokens/GovernanceToken.sol
> +abstract contract GovernanceToken is Initializable, DAOPermissionHandler, ERC20VotesUpgradeable {
No reason. Forgot to remove this.

2022-01-25 14:41 UTC, novaknole commented on packages/contracts/contracts/core/processes/Process.sol
> +                    action.to != address(this)
After talking and discussing, This check shouldn't be here.

2022-01-25 14:41 UTC, novaknole commented on packages/contracts/contracts/core/processes/Process.sol
> +                    action.to != address(this)
After talking and discussing, This check shouldn't be here.

2022-01-25 14:41 UTC, novaknole commented on packages/contracts/contracts/factories/DAOFactory.sol
> +    struct AllowedActions {
`allowedActions` struct removed. It makes sense though, but for MVP, no need.

2022-01-25 14:42 UTC, novaknole commented on packages/contracts/contracts/factories/DAOFactory.sol
> +        TokenFactory.MintConfig calldata _mintConfig,
In the future,  We might decide to right away pass the merkle mint settings as well(like root hash and tree). In this way, I don't want to have everything in single struct.

2022-01-25 14:44 UTC, novaknole commented on packages/contracts/contracts/factories/DAOFactory.sol
> +        DAOConfig calldata _daoConfig,
you mean, `bytes metadata` in the `DAOConfig` ? It can be doable with bytes32(ipfs hash) and we will definatelly look into this and change it later.

2022-01-26 10:17 UTC, nivida commented on packages/contracts/contracts/factories/DAOFactory.sol
> +        dao.grant(address(dao), address(tokenFactory), dao.ROOT_ROLE());
Yeah I just thought it would be worth to add such a comment to the code. But we can also keep it as it is.

2022-01-26 10:18 UTC, nivida commented on packages/contracts/contracts/factories/DAOFactory.sol
> +        ACLData.BulkItem[] memory items = new ACLData.BulkItem[](4);
ohh true.. thanks:)

2022-01-26 10:21 UTC, nivida commented on packages/contracts/contracts/factories/TokenFactory.sol
> +        address token = _tokenConfig.addr;
You can use tokenConfig.addr directly instead of writing it first into a mem var.

2022-02-01 14:34 UTC, merged