Integration/all proposals DAO-596
aragon/app-legacy pull request #165
Opened 2022-01-23 16:09 UTC by sepehr2github

- Implement the governance page skeleton
- change alert message prop on proposal card
- add getDateProposals to convert the proposal's timestamp to a proper format

2022-01-24 07:54 UTC, sepehr2github commented
@WissenIstNacht I think we should discuss about the combination of this one and https://github.com/aragon/zaragoza/pull/160/files

2022-01-24 10:58 UTC, WissenIstNacht requested changes
Very nice PR, thanks a lot!

Left a few suggestions. Let me know what you think!

2022-01-24 10:58 UTC, WissenIstNacht commented on packages/web-app/src/utils/date.ts
> +export function getDateProposals(
Architectural point: Ideally, functions should do as few things as possible (thereby increasing reusability and composability). A good rule of thumb to see whether that is the case is by comparing the function's name and what it returns. 

In your case, the function's name suggest that you want to get a Date's proposal (or a proposal's date). The output, however, is a formatted and translatated string containing the proposal's type AND date. In this case, a more accurate name would be `formatProposalDateAndType` (but even with this, it's not really clear how you format the date). This very long name indicates that the function probably does more than it should. Personally, I'd break it up into two functions: `getRemainingTime` and `translateProposalType`. Now you can get a remainig time even if it's not about a proposal and you can translate the proposal type even if there's not date involved.

2022-01-24 10:58 UTC, WissenIstNacht commented on packages/web-app/src/pages/governance.tsx
> +          <SearchInput placeholder="Type to filter" />
I think we can remove the SearchInput until we actually have a search functionality in place.

2022-01-24 10:58 UTC, WissenIstNacht commented on packages/web-app/src/components/proposalList/index.tsx
> +            key={index}
Probably would be better to use a string containing the publisher and the date here (something like `{publisheraddress + startDate}`) instead of the `index`. This should be enough to uniquely identify each list element.

2022-01-24 11:07 UTC, WissenIstNacht commented
As for the combination with my PR. I suggest you merge yours first, then I will adapt mine.

2022-01-24 13:56 UTC, Fabricevladimir requested changes
Good work! Thanks

2022-01-24 13:56 UTC, Fabricevladimir commented on packages/web-app/src/pages/governance.tsx
> +    displayedProposals.sort(sortProposals);
Filtered proposals should go through whatever algorithm decides how many pages of proposals are to be displayed. Currently, the number of pages isn't being updated to correspond to the actual number of proposals to be displayed (`displayedProposals`).

2022-01-24 13:56 UTC, Fabricevladimir commented on packages/web-app/src/utils/date.ts
> +export function getDateProposals(
^ Solid points

2022-01-24 14:04 UTC, Fabricevladimir requested changes

2022-01-24 14:04 UTC, Fabricevladimir commented on packages/web-app/src/pages/governance.tsx
> +              totalPages={Math.ceil(displayedProposals.length / 6) as number}
The pagination buttons are being rendered as a list, but in the component we forgot to pass each button a key. 
Btw, might be a good idea to extract 6 as symbolic constant.

2022-01-25 10:21 UTC, sepehr2github commented on packages/web-app/src/pages/governance.tsx
> +    displayedProposals.sort(sortProposals);
It will update. May be I couldn't get the point

2022-01-25 11:06 UTC, Fabricevladimir approved these changes
Good to go for me

2022-01-25 11:10 UTC, WissenIstNacht commented
Very nice, thanks!

2022-01-25 11:11 UTC, WissenIstNacht approved these changes

2022-01-25 11:12 UTC, merged