Feature/Card with Image+Label DAO-647
aragon/app-legacy pull request #174
Opened 2022-01-25 13:46 UTC by RakeshUP

2022-01-27 11:05 UTC, WissenIstNacht requested changes
Thanks! :)

2022-01-27 11:05 UTC, WissenIstNacht commented on packages/web-app/src/components/cardWithImage/index.tsx
> +      {/* TODO: Change this url to an imported local image */}
Can you expose the src url as well?

2022-01-27 11:05 UTC, WissenIstNacht commented on packages/web-app/src/components/cardWithImage/index.tsx
> +  }
Was on the phone with Selim earlier and had a quick chat about this. The size of the image should be dictated by the parent and an image ratio, not by the image itself. For now I think most SVGs we'll pass will be more or less square, so I'd just go with full width and let it take the vertical space it needs.

2022-01-27 16:40 UTC, Fabricevladimir approved these changes
Thanks. Good work. Ready to merge once the other comments have been addressed.

2022-01-27 16:40 UTC, Fabricevladimir commented on packages/web-app/src/components/cardWithImage/index.tsx
> +})<React.ImgHTMLAttributes<HTMLImageElement>>`
Should be able to remove the type there, I think.

2022-01-27 16:40 UTC, Fabricevladimir commented on packages/web-app/src/components/cardWithImage/index.tsx
> +})<React.ImgHTMLAttributes<HTMLImageElement>>`
Should be able to remove the type there, I think.

2022-01-27 16:40 UTC, Fabricevladimir commented on packages/web-app/src/components/cardWithImage/index.tsx
> +})<React.ImgHTMLAttributes<HTMLImageElement>>`
Should be able to remove the type there, I think.

2022-01-28 09:53 UTC, WissenIstNacht approved these changes

2022-01-28 10:21 UTC, merged