Feature/Assemble page (Select blockchain) - DAO-634
aragon/app-legacy pull request #187
Opened 2022-01-31 18:11 UTC by Fabricevladimir

- added select blockchain view
- wired to form

2022-02-01 11:10 UTC, RakeshUP approved these changes

2022-02-01 11:13 UTC, RakeshUP commented
Could you make the FullScreenStepper take the total steps of the wizard as a prop and currentStep as the child option prop? The useStepper would still have children.length as the value so that the next, prev, etc work properly. Just the display values in wizard would be coming in as props.

2022-02-02 11:05 UTC, WissenIstNacht requested changes
Hey there, thanks for the PR, looks great.

I left a few minor comments thorughout the code. nothing importnat.

There is one thing however: The stepper is not adapted to mobile. It shouldn't take too much to change the layout for mobile.

2022-02-02 11:05 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +    "mainNet": "Main net",
I would either go with Mainnet \(Testnet, Whatevernet\) or Main Network \(Test Network, Whatever Network\). I'd suggest the first, to stay consistent with our other products and the definitions we have in useWallet.

Just saw that you copied that from the desings. My bad. But then "Main Net" :)

2022-02-02 11:05 UTC, WissenIstNacht commented on packages/web-app/src/utils/library.ts
> +export function isTestNet(chainId: number) {
https://github.com/aragon/use-wallet/blob/master/src/chains.ts

Every chain listed has a boolean field called `testnet` :)

2022-02-02 11:05 UTC, WissenIstNacht commented on packages/web-app/src/containers/selectChainForm/index.tsx
> +// TODO: Find proper place. Configs maybe?
yeah, or constants.

2022-02-02 11:05 UTC, WissenIstNacht commented on packages/web-app/src/containers/selectChainForm/index.tsx
> +              <DropdownContent>
Opening the dropdown always focuses the first item (I would expect it to focus either no item, or the one currently selected)

If it's a hassle to change leave it as is and drop a TODO for later. I'm not even sure what Selim intended here in the first place.

2022-02-02 11:05 UTC, WissenIstNacht commented on packages/web-app/src/containers/selectChainForm/index.tsx
> +      {id: 137, name: 'Polygon', ...chainMetadata.polygon},
You could have saved yourself some typing by adding the id and name to the metadata as well and then simply list the metadata objects :yum:

2022-02-02 11:34 UTC, Fabricevladimir commented on packages/web-app/src/utils/library.ts
> +export function isTestNet(chainId: number) {
Sweet

2022-02-02 11:36 UTC, Fabricevladimir commented on packages/web-app/src/containers/selectChainForm/index.tsx
> +      {id: 137, name: 'Polygon', ...chainMetadata.polygon},
That's true yes. Wasn't sure where and how these guys were going to live

2022-02-02 11:46 UTC, Fabricevladimir commented on packages/web-app/src/containers/selectChainForm/index.tsx
> +              <DropdownContent>
Isn't first item focus default for dropdowns? But, yeah, this is residue from using Popover instead of Dropdown. There is a TODO for it.

2022-02-06 21:37 UTC, sepehr2github approved these changes
Awsome Fabrice. One more step to finish creation flow 👍 . 
Just a minor thing:
<img width="382" alt="Screen Shot 2022-02-07 at 1 01 31 AM" src="https://user-images.githubusercontent.com/46657145/152702376-232dbf18-0cb8-4629-a12b-6d353d80ccb2.png">

What happened to the internal border-radius?

And a simple question: Why do we have a network switch at all? We can direct creation flow based on the active wallet chain? because It's sort of weird that I can create dao in the test net while my active wallet active chain is mainnet!

2022-02-07 09:46 UTC, Fabricevladimir commented
@sepehr2github About the borderRadius, I finally added the proper 10px border radius for the default button in the ui-components, but the key hadn't been added to the web-app TW config. @RakeshUP has added it though in a different PR so I'll disregard it here just to minimize conflicts.

As for the network type, I assume the network type you choose here is takes precedence over the wallet chain. So at the end of the flow, when you want to deploy your DAO, at some point we'll have to point out to the user that the desired network and the one their wallet is currently connected to aren't the same...

2022-02-07 12:24 UTC, WissenIstNacht approved these changes

2022-02-07 13:52 UTC, merged