Feature / DAO-632
aragon/app-legacy pull request #195
Opened 2022-02-02 13:24 UTC by Rekard0

- add module for contracts in templates
- add readme
- setup unit testing env via docker
- refactor mapping and schema to adapt with new contracts

2022-02-03 14:52 UTC, nivida requested changes
I've added a few comments :)

btw. deploy.sh got checked in and is an empty file.

2022-02-03 14:52 UTC, nivida commented on packages/subgraph/Dockerfile
> +FROM ubuntu:20.04
Could you use a docker compose for this. I don't think we have to create a docker image especially for this. Feel free to copy the one from Govern I created over as I mentioned once.

2022-02-03 14:52 UTC, nivida commented on package.json
> +    "manifest:subgraph:arbitrum:rinkeby": "lerna run --scope=@aragon/zaragoza-subgraph --stream manifest-arbitrum-rinkeby",
Most of those commands should be in the subgraph package.

2022-02-03 14:52 UTC, nivida commented on packages/subgraph/README.md
> +cd ../.. && yarn && cd packages/subgraph
it doesn't depend if I'm correct if you run yarn in packages/subgraph or on the root folder cause we have a yarn workspace.

2022-02-03 14:52 UTC, nivida commented on packages/subgraph/README.md
> +cd ../.. && yarn build:contracts && cd packages/subgraph
This could be included directly in the commands of this package.

2022-02-03 14:52 UTC, nivida commented on packages/subgraph/README.md
> +GRAPH_KEY=<GRAPH_KEY> yarn deploy-<DESIRED_NETWORK> <THEGRAPH_USERNAME> <SUBGRAPH_NAME> <DESIRED_NETWORK>
Probably worth to have all this in a .env file and using it in a bash script.

2022-02-03 14:52 UTC, nivida commented on packages/subgraph/README.md
> +yarn test:docker
"yarn test"  should be enough :)

2022-02-03 14:52 UTC, nivida commented on packages/subgraph/README.md
> +### Deploy the subgraph locally
All this would be obsolet if you use the Govern scripts etc. as mentioned once.

2022-02-03 14:52 UTC, nivida commented on packages/subgraph/manifest/subgraph.placeholder.yaml
> +  # # Voting (package process)
Not required to commit such out commented sections.

2022-02-03 14:52 UTC, nivida commented on package.json
> +    "lerna": "^3.22.1"
I'm wondering how lerna found into this repo. If you have the could you investigate if we really need it? Currently, I think we don't.

2022-02-03 14:52 UTC, nivida commented on packages/subgraph/package.json
> +    "@graphprotocol/graph-cli": "^0.25.1",
Is the CLI not a devDependency?

2022-02-03 14:52 UTC, nivida commented on packages/subgraph/schema.graphql
> +  actions: [Action!]! @derivedFrom(field: "dao")
shouldn't this be executions?

2022-02-03 14:52 UTC, nivida commented on packages/subgraph/schema.graphql
>    tokenDeposits: [VaultDeposit!]! @derivedFrom(field: "dao")
can't we merge eth- and tokenDeposits just to deposits?

2022-02-03 14:52 UTC, nivida commented on packages/subgraph/schema.graphql
> +  erc20Balances: [ERC20Balance!] @derivedFrom(field: "dao")
I think this should be balances and include eth and tokens.

2022-02-03 14:52 UTC, nivida commented on packages/subgraph/src/dao.ts
> +// import {SimpleVoting} from '../generated/templates';
Can get removed at all if not used.

2022-02-03 14:52 UTC, nivida commented on packages/subgraph/src/dao.ts
Shouldn't we replace process added with the ACL events as discussed yesterday?

2022-02-03 14:52 UTC, nivida commented on packages/subgraph/src/dao.ts
> +  entity.reason = event.params._reference;
I think we can call it "reference" cause it is a known wording from finance (payment reference).

2022-02-03 14:52 UTC, nivida commented on packages/subgraph/src/dao.ts
> +  entity.amount = event.params.amount;
Wdyt? should we add in the contracts the possibility to add a payment reference as well?

2022-02-03 15:59 UTC, Rekard0 commented on packages/subgraph/schema.graphql
> +  erc20Balances: [ERC20Balance!] @derivedFrom(field: "dao")
yes, it will be in the next PR feature/DAO-677

2022-02-03 16:00 UTC, Rekard0 commented on packages/subgraph/src/dao.ts
> +// import {SimpleVoting} from '../generated/templates';
amended

2022-02-03 16:01 UTC, Rekard0 commented on packages/subgraph/src/dao.ts
yes, it will be in PR feature/DAO-675

2022-02-03 16:03 UTC, Rekard0 commented on packages/subgraph/src/dao.ts
> +  entity.reason = event.params._reference;
yes, aggreed

2022-02-03 16:10 UTC, Rekard0 commented on packages/subgraph/src/dao.ts
> +  entity.amount = event.params.amount;
do u mean creating function receiveEth(reference) in contract so we can pass reference to event, and also in the receive() passing 'no reference' as reference? 
can we override receive() to have a param?

2022-02-03 16:17 UTC, Rekard0 commented on packages/subgraph/README.md
> +cd ../.. && yarn && cd packages/subgraph
yes, amended

2022-02-03 16:28 UTC, Rekard0 commented on packages/subgraph/README.md
> +cd ../.. && yarn build:contracts && cd packages/subgraph
yes, thanks, amended.

2022-02-03 16:29 UTC, Rekard0 commented on package.json
> +    "manifest:subgraph:arbitrum:rinkeby": "lerna run --scope=@aragon/zaragoza-subgraph --stream manifest-arbitrum-rinkeby",
amended

2022-02-03 19:16 UTC, Rekard0 commented on packages/subgraph/README.md
> +GRAPH_KEY=<GRAPH_KEY> yarn deploy-<DESIRED_NETWORK> <THEGRAPH_USERNAME> <SUBGRAPH_NAME> <DESIRED_NETWORK>
yes, we can use .env instead. amended

2022-02-07 10:02 UTC, nivida commented on packages/subgraph/src/dao.ts
> +  entity.amount = event.params.amount;
I was meaning that we can add a "reference" argument to the deposit method we already have. :-) 

We can't override receive() cause it is a std fallback if someone is sending ETH to this contract.

2022-02-07 10:04 UTC, nivida commented on packages/subgraph/src/dao.ts
> +  entity.amount = event.params.amount;
But let us create out of this a task and we can if we want change it later on:))

2022-02-07 12:30 UTC, Rekard0 commented on packages/subgraph/README.md
> +yarn test:docker
yes, done

2022-02-07 12:31 UTC, Rekard0 commented on packages/subgraph/README.md
> +### Deploy the subgraph locally
yes, now all can be done via docker compose

2022-02-07 12:31 UTC, Rekard0 commented on packages/subgraph/manifest/subgraph.placeholder.yaml
> +  # # Voting (package process)
yes removed

2022-02-07 12:41 UTC, Rekard0 commented on packages/subgraph/package.json
> +    "@graphprotocol/graph-cli": "^0.25.1",
i was following the example of subgraph-demo, but yes, it can be devDependency. amended

2022-02-07 12:42 UTC, Rekard0 commented on packages/subgraph/schema.graphql
> +  actions: [Action!]! @derivedFrom(field: "dao")
yes, it will be in PR feature/dao-676

2022-02-07 13:06 UTC, Rekard0 commented on package.json
> +    "lerna": "^3.22.1"
yes it is needed for running npm scripts such as: lerna run ..etc
however it is not needed if lerna is installed globally.

should we remove it? and assume lerna is installed globally?

2022-02-07 13:19 UTC, Rekard0 commented on packages/subgraph/schema.graphql
>    tokenDeposits: [VaultDeposit!]! @derivedFrom(field: "dao")
ok, i will consider that in its PR

2022-02-07 14:22 UTC, Rekard0 commented on packages/subgraph/Dockerfile
> +FROM ubuntu:20.04
done

2022-02-08 17:44 UTC, nivida commented on package.json
> +    "lerna": "^3.22.1"
So let us keep it for now 👍

2022-02-08 17:56 UTC, nivida commented
Thanks for all the changes. As stated by you do further improvements come with other smaller PRs. Merging it now.

2022-02-08 17:56 UTC, merged