Feature/Transfer Modal DAO-660
aragon/app-legacy pull request #196
Opened 2022-02-02 15:53 UTC by RakeshUP

All other modals are refactored in this PR. Things like switching between modal and bottom sheet are handled and a few styling and naming changes too.

2022-02-07 11:20 UTC, Fabricevladimir requested changes
Massive work. Thanks, the modal system needed an overhaul. Left some comments.

2022-02-07 11:20 UTC, Fabricevladimir commented on packages/web-app/src/containers/transactionModal/index.tsx
> +            )} 30 ${t('labels.sec')} ${t('labels.ago')}`}</p>
You can have this as an interpolated string and pass in the seconds like so:  "Synced  {{seconds}} ago"

2022-02-07 11:20 UTC, Fabricevladimir commented on packages/web-app/src/containers/transactionModal/index.tsx
> +const TransactionModal: React.FC<TransactionModalProps> = ({
Should this be in web-app or ui-components?

2022-02-07 11:20 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useMediaQuery.tsx
> +function useMediaQuery(query: string): boolean {
Thanks for this. The initial plan was to use TW instead of explicit media queries, but there are quite a few cases where that's just not possible. For convenience's sake though since we already know which screens we'll support, it would be nice if we could just get the screen from the hook. Something like:
`const {isTablet} = useScreenSizes(); // or: isMobile, isDesktop and so on` 
What do you think?

2022-02-07 11:20 UTC, Fabricevladimir commented on packages/web-app/tailwind.config.js
> +      borderRadius: {
Thanks, I forgot to update this in the PR that added it in ui-components. Perhaps one TW config would be a better approach...

2022-02-07 11:20 UTC, Fabricevladimir commented on packages/web-app/src/containers/transactionModal/index.tsx
> +};
Missing cost and gas fee props I think

2022-02-07 11:20 UTC, Fabricevladimir commented on packages/web-app/src/containers/transactionModal/index.tsx
> +          <StrongText>{'$16.28'}</StrongText>
The total cost should be calculated dynamically.

2022-02-07 11:20 UTC, Fabricevladimir commented on packages/web-app/src/containers/transactionModal/index.tsx
> +            <p className="text-sm text-right text-ui-500">{'127gwei'}</p>
This should probably come as props as well, or at the very least derived from the ETH value. Ethers.js has a utility function for that I believe...

2022-02-07 12:56 UTC, RakeshUP commented on packages/web-app/tailwind.config.js
> +      borderRadius: {
The bigger issue is that styles are not packaged with the ui-components package. The package should contain its own styles and should be able to work independently, but that's not happening now

2022-02-07 12:57 UTC, RakeshUP commented on packages/web-app/src/containers/transactionModal/index.tsx
> +};
Estimating gas fee, transaction cost in native token, and cost in USD are to be done in a separate task. I've hardcoded those values for now. I didn't add the props, because was not sure what props are needed. I think it needs contract address and function name too for estimating the prices

2022-02-07 13:00 UTC, RakeshUP commented on packages/web-app/src/containers/transactionModal/index.tsx
> +            <p className="text-sm text-right text-ui-500">{'127gwei'}</p>
Every value is hardcoded for now, till it's fixed in other tickets DAO-661 and DAO-662

2022-02-07 13:02 UTC, RakeshUP commented on packages/web-app/src/containers/transactionModal/index.tsx
> +const TransactionModal: React.FC<TransactionModalProps> = ({
I am putting components with translated strings in the web-app package for now

2022-02-07 13:10 UTC, RakeshUP commented on packages/web-app/src/containers/transactionModal/index.tsx
> +            )} 30 ${t('labels.sec')} ${t('labels.ago')}`}</p>
Cool, I am taking at that

2022-02-07 13:21 UTC, RakeshUP commented on packages/web-app/src/hooks/useMediaQuery.tsx
> +function useMediaQuery(query: string): boolean {
A much better way to do the way you think is to use have a listener on document.innerWidth and returning issTablet, isMobile, etc values based on that. Because to export the same structure we would need three matchMedia listeners, which would result in more re-renders. 

We can change this in the future to use a listener on document.innerWidth

2022-02-07 14:03 UTC, RakeshUP commented on packages/web-app/src/containers/transactionModal/index.tsx
> +            )} 30 ${t('labels.sec')} ${t('labels.ago')}`}</p>
Changed it

2022-02-08 13:43 UTC, Fabricevladimir commented on packages/web-app/src/containers/transactionModal/index.tsx
> +};
Fair enough

2022-02-08 13:44 UTC, Fabricevladimir commented on packages/web-app/tailwind.config.js
> +      borderRadius: {
Yup, you're right. This is something we definitely need to revisit.

2022-02-08 13:48 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useMediaQuery.tsx
> +function useMediaQuery(query: string): boolean {
Ah, yes. I would like this yes. innerWidth would be compared to our screen sizes and update memoized boolean values. If it takes too much time, we can leave it for later, but it would really be helpful in terms of dev experience.

2022-02-08 21:03 UTC, sepehr2github approved these changes
Massive Work Rakash! Well Done! honestly the reason I had to make bottom sheet to web app is that the storybook couldn't support framer motion and we should find a solution later to move the whole modal to UI components. But anyway Thank you!

2022-02-09 11:29 UTC, RakeshUP commented on packages/web-app/src/hooks/useMediaQuery.tsx
> +function useMediaQuery(query: string): boolean {
Changed the api to the one you suggested

2022-02-09 11:58 UTC, Fabricevladimir approved these changes

2022-02-09 12:47 UTC, merged