chore/ DAO-655
aragon/app-legacy pull request #198
Opened 2022-02-02 21:32 UTC by sepehr2github

- percentage state added to numeric input
- full-width style added to default mode

2022-02-03 09:55 UTC, Fabricevladimir requested changes
Thanks! Left some comments.

2022-02-03 09:55 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/numberInput.tsx
> +          placeholder={'0'}
Are we against a user input as placeholder?

2022-02-03 09:55 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/numberInput.tsx
> +        {percentage && <Percent disabled={disabled}>%</Percent>}
There is a weird state when the value is undefined and the placeholder shows along with the %; the placeholder text color and % text color are different.

2022-02-03 09:55 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/numberInput.tsx
>          onClick={() => inputRef.current?.stepDown()}
It doesn't seem as if stepDown and stepUp trigger an onChange event on the input by default, so if this component is controlled, when the user clicks on either button, the controller value will not be updated.

2022-02-03 09:55 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/numberInput.tsx
> +          {...(percentage && {percentage, min: 0, max: 100})}
When the percentage prop is set to true, the input can only show 2 characters no matter how wide it is. So if you insert 100, you only see 00

2022-02-07 09:41 UTC, Fabricevladimir approved these changes
Thanks! This can be merged once the up and down comments are addressed.

2022-02-07 09:41 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/numberInput.tsx
> +        onClick={() => handleChange('up')}
Small comment, the name is reversed here. Name is down, but handleChange is called with 'up'.

2022-02-07 09:41 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/numberInput.tsx
> +    mode === 'up' ? inputRef.current?.stepDown() : inputRef.current?.stepUp();
The condition is flipped.. we're calling stepDown() when 'up' is passed in.

2022-02-07 09:41 UTC, Fabricevladimir commented on packages/ui-components/src/components/button/buttonIcon.tsx
> +  small: 'h-4 w-4 p-1',
Height is technically unnecessary here because the ButtonBase takes care of that for all the buttons.

2022-02-09 06:56 UTC, RakeshUP approved these changes

2022-02-09 06:56 UTC, merged