TokenFactory tests
aragon/app-legacy pull request #204
Opened 2022-02-07 11:04 UTC by mathewmeconry

## Changes
- adds max node version to the readme
- adds smock as a dependency for contracts and configures hardhat properly
- adds tests for TokenFactory.sol
- removes unused event `DAOCreated` from TokenFactory.sol

2022-02-07 11:30 UTC, novaknole requested changes
Some stuff can be added in the tests as well and distributorBase is not mentioned anywhere.

For example, 

```
MerkleMinter(merkleMinter).initialize(
            _dao,
            GovernanceERC20(token),
            distributorBase
        );
  ```
  
  We can use `toHaveBeenCalledWith` here for the merkle minter and so on.

2022-02-07 11:30 UTC, novaknole commented on packages/contracts/test/core/token-factory.ts
> +      expect(tx[0]).not.to.be.eq(governanceWrappedBase.address);
* This seems that the check doesn't serve any strong purpose.  Whatever I almost do/change in `TokenFactory`'s contract, the test would still succeed.

2022-02-07 11:30 UTC, novaknole commented on packages/contracts/test/core/token-factory.ts
> +      const transferTopic = IERC20Upgradeable.getEventTopic('Transfer');
In this test , can't we use `to.emit` and `withArgs` solution ? Much cleaner and easier.

2022-02-07 11:30 UTC, novaknole commented on packages/contracts/test/core/token-factory.ts
> +        expect(dao.grant).to.have.been.calledWith(
In this test, we should also have the check that `dao.revoke` was called with those arguments. no need to have another test which is below this one.

2022-02-07 11:30 UTC, novaknole commented on packages/contracts/test/core/token-factory.ts
> +        expect(dao.grant).to.have.been.calledWith(
This can also be in the same test above.

2022-02-07 11:30 UTC, novaknole commented on packages/contracts/test/core/token-factory.ts
> +        expect(dao.grant).to.have.been.calledWith(
same goes for this. Idea is that 

```
expect(dao.grant).to.have.been.calledWith
```

all the calls  can be inside one test, since `tokenConfig.addr` is 0x...000 for all of them.

2022-02-07 11:30 UTC, novaknole commented on packages/contracts/test/core/token-factory.ts
> +        expect(dao.grant).to.have.been.calledWith(
same for this as well.

2022-02-07 11:30 UTC, novaknole commented on packages/contracts/test/core/token-factory.ts
> +      expect(tx[0]).not.to.be.eq(governanceBase.address);
This seems that the check doesn't serve any strong purpose. Whatever I almost do/change in TokenFactory's contract, the test would still succeed.

2022-02-07 14:01 UTC, mathewmeconry commented
> Some stuff can be added in the tests as well and distributorBase is not mentioned anywhere.
> 
> For example,
> 
> ```
> MerkleMinter(merkleMinter).initialize(
>             _dao,
>             GovernanceERC20(token),
>             distributorBase
>         );
> ```
> 
> We can use `toHaveBeenCalledWith` here for the merkle minter and so on.

unfortunately not. because of the call to `clone()` we cannot deploy a mocked or faked contract to this address

2022-02-07 14:02 UTC, mathewmeconry commented on packages/contracts/test/core/token-factory.ts
> +      expect(tx[0]).not.to.be.eq(governanceWrappedBase.address);
at least it ensures that we don't use the contract deployed in `setupBases`. So I would like to leave this test in

2022-02-07 14:03 UTC, mathewmeconry commented on packages/contracts/test/core/token-factory.ts
> +      const transferTopic = IERC20Upgradeable.getEventTopic('Transfer');
we can but then we cannot test multiple mints in one call. As far as I know `to.emit` and `withArgs` can only test for one event and not multiple at the same time

2022-02-07 14:04 UTC, mathewmeconry commented on packages/contracts/test/core/token-factory.ts
> +      expect(tx[0]).not.to.be.eq(governanceBase.address);
at least it ensures that we don't use the contract deployed in `setupBases`. So I would like to leave this test in

2022-02-07 14:07 UTC, mathewmeconry commented on packages/contracts/test/core/token-factory.ts
> +        expect(dao.grant).to.have.been.calledWith(
done

2022-02-07 14:54 UTC, novaknole commented on packages/contracts/test/core/token-factory.ts
> +      const transferTopic = IERC20Upgradeable.getEventTopic('Transfer');
```
tx.to.emit('Transfer').withArgs(var1, var2, var3).to.emit('Transfer).withArgs(var4, var5, var6)
```

This should work. Have done it before.

2022-02-07 16:29 UTC, mathewmeconry commented on packages/contracts/test/core/token-factory.ts
> +      const transferTopic = IERC20Upgradeable.getEventTopic('Transfer');
changed to use the erc20 contract address which gets emitted in the new `TokenCreated` event

2022-02-08 17:41 UTC, nivida commented on packages/contracts/test/core/token-factory.ts
> +      expect(tx[0]).not.to.be.eq(governanceWrappedBase.address);
more assertions are always good :)

2022-02-08 17:42 UTC, nivida commented
@novaknole Discussed it with @mathewmeconry and merged this PR after.

2022-02-08 17:42 UTC, nivida approved these changes

2022-02-08 17:43 UTC, merged