Assemble/ DAO-652
aragon/app-legacy pull request #219
Opened 2022-02-09 21:01 UTC by sepehr2github

2022-02-10 17:46 UTC, Fabricevladimir requested changes
Thanks! Good work. Left a couple of comments. The only major issue I saw was that when a validation message is shown (on desktop) it causes the corresponding percentage input to drop down.
![image](https://user-images.githubusercontent.com/16927999/153465903-f1376be5-0b4a-419c-9951-dcc5eff1a359.png)

2022-02-10 17:46 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/textInput.tsx
>        disabled ? 'bg-ui-100 border-ui-200 border-2' : 'bg-ui-0'
This should probably be updated in a separate ticket, but I noticed that on the designs, the adornment button isn't actually disabled when the input itself is disabled...

2022-02-10 17:46 UTC, Fabricevladimir commented on packages/web-app/src/components/addWallets/row.tsx
> +          <ButtonIcon
It seems for the DAO Treasury, this button is not present, well at least not on the desktop view.

2022-02-10 17:46 UTC, Fabricevladimir commented on packages/web-app/src/components/addWallets/row.tsx
> +  const {getValues, setValue} = useFormContext();
If you're using `useFormContext`, you can simplify the props by removing control and getting it from the `useFormContext` hook.

2022-02-10 17:46 UTC, Fabricevladimir commented on packages/web-app/src/locales/en/common.json
> +      "createTokenHelplink": "Token Minting Guide."
Small typo. The period should be removed.

2022-02-11 09:30 UTC, RakeshUP approved these changes

2022-02-11 12:24 UTC, sepehr2github commented on packages/ui-components/src/components/input/textInput.tsx
>        disabled ? 'bg-ui-100 border-ui-200 border-2' : 'bg-ui-0'
actually, there are two versions of the designs. I implement this based on user testing branch and on that branch the button is disabled (actually there is no adornment at all but I left the refactor for later because the functionality is same)

2022-02-11 12:28 UTC, sepehr2github commented on packages/web-app/src/components/addWallets/row.tsx
> +          <ButtonIcon
Yes and no. You. can see the button here but in general, you're right
![Screen Shot 2022-02-11 at 3 55 46 PM](https://user-images.githubusercontent.com/46657145/153591393-4be1ca5b-2862-4325-8e53-9b790c9555ca.png)

2022-02-11 12:31 UTC, sepehr2github commented on packages/web-app/src/locales/en/common.json
> +      "createTokenHelplink": "Token Minting Guide."
Which period?

2022-02-11 14:21 UTC, Fabricevladimir commented on packages/web-app/src/locales/en/common.json
> +      "createTokenHelplink": "Token Minting Guide."
The one for createTokenHelpLink. It's displaying a period with the link

2022-02-11 14:24 UTC, sepehr2github commented on packages/web-app/src/locales/en/common.json
> +      "createTokenHelplink": "Token Minting Guide."
![Screen Shot 2022-02-11 at 5 53 31 PM](https://user-images.githubusercontent.com/46657145/153608722-840561b7-668c-4020-878d-e75184f93563.png)
Can you commit the changes there is no period here? I don't understand :)))

2022-02-11 14:30 UTC, Fabricevladimir approved these changes

2022-02-11 14:42 UTC, merged