Feature: Assemble voting setup page - Dao 621
aragon/app-legacy pull request #226
Opened 2022-02-11 12:17 UTC by WissenIstNacht

This PR implements step 2 of the withdrawal form, voting setup:
- assemble necessary UI components on the page
- perform validation on user input

2022-02-14 11:48 UTC, sepehr2github commented on packages/web-app/src/components/inputTime/inputTime.tsx
> +import styled from 'styled-components';
I'm not sure if It's right place for this comment but. the date format in designs is yyyy/mm/dd but in this pr is mm/dd/yyyy.

2022-02-14 11:49 UTC, sepehr2github commented on packages/web-app/src/containers/setupVotingForm/index.tsx
> +  // ellapse between the creation of the form context and this stage of the form.
I know. implementing this validator wasn't easy at all. Good job! 👍

2022-02-14 11:50 UTC, nivida reviewed
I've seen it does add 18 code smells to the code base. Would be great to at least address the Major and Critical code smells. 

Hint: I think the coverage generation is missing so that SonarQube can analyze it as well.

2022-02-14 11:58 UTC, sepehr2github requested changes
Well Done Vali! you did a great job. I left A few comments.

1) The time picker looks broken on my screen. maybe it needs some width adjustment
![Screen Shot 2022-02-14 at 3 07 18 PM](https://user-images.githubusercontent.com/46657145/153859446-2920e479-3e2b-46c1-8331-cf1bdadcbf9d.png)
Also, we need to fix the alignment issues!

2) I think you mention this before. I don't remember if the issue was this or something else but when I selected my start date and end date the next button was still disabled. (without any alert messages) 
![Screen Shot 2022-02-14 at 3 13 30 PM](https://user-images.githubusercontent.com/46657145/153860160-f86b87b9-adf5-473e-bd5e-f3511060e325.png)

2022-02-14 16:07 UTC, WissenIstNacht commented on packages/web-app/src/components/inputTime/inputTime.tsx
> +import styled from 'styled-components';
The date displayed in the input depends on the browser's locale :)

I already notified Selim about it a while ago 👍🏼

2022-02-14 17:11 UTC, WissenIstNacht commented
Hey @sepehr2github, thanks for the review! About the two points you mentioned:

1. I forgot to check chrome before creating the PR, sorry 🙈 The alignment issues should be resolved now 👍🏼 
2. Yes, that's what I explained on a daily a few days back. The form thinks that something is wrong, which is why it does not let you go on. However, I'm not 100% sure what it thinks is wrong. Interestingly, if you go back a step, the button is still disabled. If you then change the token amount input, though, it will turn back to normal (also in the next step).

2022-02-15 11:03 UTC, sepehr2github commented on packages/web-app/src/components/inputTime/inputTime.tsx
> +import styled from 'styled-components';
Ah. Thanks

2022-02-15 13:13 UTC, RakeshUP approved these changes

2022-02-15 13:16 UTC, RakeshUP commented
Looks good. For me in Chrome browser, the `M` in `PM` seems to be cut off

<img width="358" alt="Screenshot 2022-02-15 at 6 43 57 PM" src="https://user-images.githubusercontent.com/20946466/154069134-9afba667-98bb-4ad9-8d5d-241db136a9f0.png">

2022-02-15 19:50 UTC, sepehr2github approved these changes

2022-02-16 09:38 UTC, merged