Feature/ DAO-694
aragon/app-legacy pull request #236
Opened 2022-02-15 21:55 UTC by Rekard0

- refactor SimpleVoting incontracts
- refactor SimpleVoting in Subgraph
- refactor subgraph constants
- redeploy contracts

2022-02-16 07:29 UTC, nivida requested changes
LGTM! Only the naming of the ERC20Voting entities in the schema could get simplified slightly. Would be great if you could also elaborate closer on why ``ERC20VotingVoter`` and ``ERC20VotingVoterProposal`` is required? :) 

``ERC20VotingVoter`` & ``ERC20VotingVoterProposal`` are as commented a bit strange names. :)

2022-02-16 07:29 UTC, nivida commented on packages/subgraph/schema.graphql
> +type ERC20VotingVoter @entity {
Can't we call this also just voter?

2022-02-16 07:29 UTC, nivida commented on packages/subgraph/schema.graphql
> +type ERC20VotingVoterProposal @entity {
This probably could be called ``ERC20Vote``?

2022-02-16 07:31 UTC, nivida requested changes

2022-02-16 07:31 UTC, nivida commented on packages/subgraph/schema.graphql
> +  erc20VotingPkg: ERC20VotingPackage!
Here the ``erc20VotingPkg`` field probably can just be called ``contract``? Totally open to hear about other suggestions :)

2022-02-17 09:47 UTC, Rekard0 commented on packages/subgraph/schema.graphql
> +type ERC20VotingVoter @entity {
i don't think we can, because later we will have whitelistVoter, but instead it can implements Voter interface.

2022-02-17 09:47 UTC, Rekard0 commented on packages/subgraph/schema.graphql
> +type ERC20VotingVoterProposal @entity {
yes we can, done

2022-02-17 09:50 UTC, Rekard0 commented on packages/subgraph/schema.graphql
> +  erc20VotingPkg: ERC20VotingPackage!
thanks,  i noticed basically pkg and erc20VotingPkg are essentially the same, so now we can only use pkg.
i prefer to keep the field name as pkg, because it is of package interface

2022-02-17 12:53 UTC, nivida commented on packages/subgraph/schema.graphql
> +type ERC20VotingVoter @entity {
Yeah.. I think we can fix this as soon the package registry is existing and those voting types are handled as package with a separate subgraph 👍

2022-02-17 12:54 UTC, nivida commented on packages/subgraph/schema.graphql
> +  erc20VotingPkg: ERC20VotingPackage!
agreed :-)

2022-02-17 12:54 UTC, nivida approved these changes

2022-02-17 12:54 UTC, merged