Assemble page/ DAO-658 DAO-659
aragon/app-legacy pull request #240
Opened 2022-02-16 20:34 UTC by sepehr2github

2022-02-21 09:01 UTC, RakeshUP reviewed
@sepehr2github Did you take a look at the Description List component that exists in the web-app package? It could be used like [this](https://github.com/aragon/zaragoza/blob/cf239cb1dff9f74f611e1967e5a78fc15a0c5401/packages/web-app/src/pages/home.tsx#L32)

2022-02-21 09:56 UTC, sepehr2github commented
> @sepehr2github Did you take a look at the Description List component that exists in the web-app package? It could be used like [this](https://github.com/aragon/zaragoza/blob/cf239cb1dff9f74f611e1967e5a78fc15a0c5401/packages/web-app/src/pages/home.tsx#L32).

No @RakeshUP I wasn't aware of that :/

2022-02-22 12:11 UTC, WissenIstNacht requested changes
Hey Sepehr, thanks  a lot for the PR.

The page assembly on the review ("go live" page) looks good visually :muscle: 

However, there are a lot of important things that do not work in this flow. I don't think I did a review on this since the blockchain selection, so it's hard to judge what's going on. I've noted a few things above, but there's more. For example:
- The wallet list form does not complain when a row is empty. 
- The wallet list form does not complain when a row has an amount but no wallet address.
- Deleting a row from the wallet list form does not update the total in the footer.
- Selecting an existing token on the second step leaves the "continue" button disabled.
- The stepper shows a wrong number of steps (this is because there are more pages that steps, since the "intro" and the "go live" page count as part of the stepper as well)
- The minium approval amount does not change in the inline alert on "configure governance"
- ...

I'm sure it's not all your fault, you just have the bad luck of being the one who finishes the flow :p But since this PR is supposed to include validation (DAO 659) AND it's the last PR for this flow, we need to address these changes somehow. My suggestion would be this: remove the 659 ticket from this PR and send it back to "to do". This way, we can merge the "visual" part (DAO 658). Then, we can and fix everything that is currently broken in the form and validation on 659. Wdyt?

2022-02-22 12:11 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "Supply": "Supply",
two things here:

1) Keep the variable names lower case
2) The string "Supply" is already defined a few lines above. I suggest keeping the other one, but renaming it from `existingTokenSupply` to just `supply`.

2022-02-22 12:11 UTC, WissenIstNacht commented on packages/ui-components/src/components/input/inputImageSingle.tsx
> +  preview?: string | null;
Not super important, but if the preview source is a string, `''` might be better than `null` (you can still treat `''` as not having a preview, but you wont ever get into trouble with null.)

2022-02-22 12:11 UTC, WissenIstNacht commented on packages/web-app/src/components/addWallets/footer.tsx
> +  const TotalSupply = getValues('tokenTotalSupply');
lowercase

2022-02-22 12:11 UTC, WissenIstNacht commented on packages/web-app/src/components/addWallets/row.tsx
>    const walletFieldArray = getValues('wallets');
Not sure where to put this (since it was on an earlier PR). But this component is not a `LinkRow` :p

2022-02-22 12:11 UTC, WissenIstNacht commented on packages/web-app/src/pages/createDAO.tsx
> +  const daoSetupCommunityIsValid = useMemo(() => {
This doesn't work when using an existing token :( (The button is disabled for me, even when the contract address is correct)

2022-02-22 12:11 UTC, WissenIstNacht commented on packages/web-app/src/containers/setupCommunity/addExistingToken.tsx
> +    if (chainId.id) {
Just FYI: The form data type doesn't contain a `chainId` (or `blockchain`) field

2022-02-22 12:11 UTC, WissenIstNacht commented on packages/web-app/src/containers/goLive/index.tsx
> +    <Container>
I'm writing this here because it concerns all the cards in this containers: The cards currently grow in width when the screen gets wider, which they should not. (The header should, but not the summary cards.)

2022-02-22 12:11 UTC, WissenIstNacht commented on packages/web-app/src/containers/goLive/blockchain.tsx
> +            {t('createDAO.review.network', {network: blockchain.network})}
Something is wrong here. The Netowrk is showing "main net", but it should be "Main Net".

2022-02-22 12:11 UTC, WissenIstNacht commented on packages/web-app/src/containers/goLive/daoMetadata.tsx
> +          {daoLogo && (
The logo should be center-aligned with the label "Logo"

2022-02-22 12:11 UTC, WissenIstNacht commented on packages/web-app/src/containers/goLive/community.tsx
> +          <TextContent>{membership}</TextContent>
Should say "Token Holders" instead of "token".

2022-02-22 12:11 UTC, WissenIstNacht commented on packages/web-app/src/containers/goLive/community.tsx
> +              {tokenTotalSupply} {tokenSymbol}
This doesn't update corretly. For example, I entered the ANT token to use an existing token. Then I changed to create a token. I added a name, symbol and distribution. But in the end it shows ANT with a distribution, instead of the nem name and symbol I added :)

2022-02-22 12:11 UTC, WissenIstNacht commented on packages/web-app/src/containers/goLive/governance.tsx
> +            <div>{t('createDAO.review.days', {durationDays})}</div>
Doesn't show any day/hour/minute.

2022-02-24 10:09 UTC, sepehr2github commented on packages/web-app/src/containers/goLive/community.tsx
> +              {tokenTotalSupply} {tokenSymbol}
I will fix it in new PR

2022-02-24 10:09 UTC, sepehr2github commented on packages/web-app/src/containers/goLive/community.tsx
> +          <TextContent>{membership}</TextContent>
I will fix it in new PR

2022-02-24 10:11 UTC, sepehr2github commented on packages/web-app/src/containers/goLive/daoMetadata.tsx
> +          {daoLogo && (
I will fix it in new PR

2022-02-24 10:11 UTC, sepehr2github commented on packages/web-app/src/containers/goLive/blockchain.tsx
> +            {t('createDAO.review.network', {network: blockchain.network})}
I will fix it in new PR

2022-02-24 10:12 UTC, sepehr2github commented on packages/web-app/src/containers/goLive/index.tsx
> +    <Container>
I should fix the wab app grid and I will do it in next PR

2022-02-24 10:12 UTC, sepehr2github commented on packages/web-app/src/containers/setupCommunity/addExistingToken.tsx
> +    if (chainId.id) {
Next PR

2022-02-24 13:28 UTC, sepehr2github commented
This Pr is fine in visual view and I will send another PR to fix all other remaining logic issues. Please review this PR (only visual aspect) @WissenIstNacht @Fabricevladimir

2022-02-24 17:28 UTC, WissenIstNacht commented on packages/web-app/src/containers/goLive/community.tsx
> +          <TextContent>{membership}</TextContent>
Seems like a visual thing to me, though 😅

2022-02-24 17:56 UTC, WissenIstNacht commented on packages/web-app/src/containers/goLive/index.tsx
> +    <Container>
Which next PR? 😅 

No but seriously, 659 is about validation. Introducing a grid system is a bit out of scope there. So you'd have to open a new ticket. But by the time you or someone else finishes it, this will be blocked in QA... Also I feel like this is quite fundamental in this PR. And the fix is literally adding a width class in two places...

But yeah, if all this doesn't convince you add a ticket for later 😉

2022-02-24 17:58 UTC, sepehr2github commented on packages/web-app/src/containers/goLive/community.tsx
> +          <TextContent>{membership}</TextContent>
Sure! No worries. I'm gonna fix it now

2022-02-24 20:34 UTC, sepehr2github commented on packages/web-app/src/containers/goLive/index.tsx
> +    <Container>
I had a discussion with Fabrice and he will create a separate task for grids. but I fixed it using tailwind classes

2022-02-25 09:43 UTC, WissenIstNacht commented
Looking really good, thanks a lot! 💪🏼

2022-02-25 09:43 UTC, WissenIstNacht approved these changes

2022-02-25 10:33 UTC, RakeshUP approved these changes

2022-02-27 14:04 UTC, merged