feat: contract deployment
aragon/app-legacy pull request #247
Opened 2022-02-21 14:02 UTC by mathewmeconry

2022-02-22 09:32 UTC, nivida requested changes
LGTM! But on merge into main should it only update the factory contracts and not the Registry cause there in case we have to update it are some further steps required.

2022-02-22 10:28 UTC, mathewmeconry commented
> LGTM! But on merge into main should it only update the factory contracts and not the Registry cause there in case we have to update it are some further steps required. Also it would be great to have the new addresses of the factories added together with a commit hash to a deployments.md or similar in this repository.

done
it updates the `Releases.md` file in `packages/contracts` and updates the `active_contracts.json` file in the root of this repository.
`active_contracts.json` can then be reused for other deployments

2022-02-22 15:01 UTC, nivida approved these changes
LGTM! thanks! :))

2022-02-23 10:44 UTC, Rekard0 commented on packages/contracts/scripts/deploy.ts
> +import {ethers} from 'hardhat';
i am a bit confused. why we use hardhat script when we have hardhat-deploy plugin installed and used. check package.json and /deploy

or i am missing something?

2022-02-23 10:53 UTC, mathewmeconry commented on packages/contracts/scripts/deploy.ts
> +import {ethers} from 'hardhat';
valid point. haven't noticed this plugin.
I'll restructure it with the refactoring to support multiple networks properly

2022-03-01 13:03 UTC, Rekard0 approved these changes

2022-03-01 13:04 UTC, merged