Feature/ListItemDao & CardDao refactor - DAO-702
aragon/app-legacy pull request #248
Opened 2022-02-21 14:10 UTC by Fabricevladimir

- adds ListItemDao component
- refactors CardDao component and updates existing references in web-app
- refactors AvatarDao component (not explicitly in ticket, but was necessary for CardDao refactor)

2022-02-21 17:58 UTC, WissenIstNacht requested changes
Thanks a lot for the refactoring, Fabrice :)

I found a few minor things that need changing. The rest are mostly questions from my side regarding the designs, etc.

2022-02-21 17:58 UTC, WissenIstNacht commented on packages/ui-components/src/components/avatar/avatarDao.tsx
> +  return error === true || !src ? (
Comparison looks sus :D

2022-02-21 17:58 UTC, WissenIstNacht commented on packages/ui-components/src/components/avatar/avatarDao.tsx
> +    const arr = daoName.trim().split(' ');
Just out of curiosity, why `useCallback` rather than `useMemo`?

2022-02-21 17:58 UTC, WissenIstNacht commented on packages/ui-components/src/components/avatar/avatarDao.tsx
> +  daoName: string;
careful, passing `''` (or a variaton of this) messes up the component.

2022-02-21 17:58 UTC, WissenIstNacht commented on packages/ui-components/stories/cardDao.stories.tsx
> -  wide: true,
I think this can be removed :)

2022-02-21 17:58 UTC, WissenIstNacht commented on packages/ui-components/src/components/cards/cardDao.tsx
> - *
Sorry, don't knwo where else to put this:

I'm confused about the design here. The smaller looking card seems to be for larger breakpoints, while the larger looking one seems to be made for smaller breakpoints. Are we sure this is not an error on Selim's part?

Another thing about the design: The card on the _right_ in figma does not show any text underneath it. On your current implementation it does, though.

2022-02-21 17:58 UTC, WissenIstNacht commented on packages/ui-components/src/components/cards/cardDao.tsx
> +        className="desktop:hidden"
I think Rakesh introduced a cool component that abstracts this kind of stuff (Just FYI, I know it's been a while) :)

2022-02-21 17:58 UTC, WissenIstNacht commented on packages/ui-components/src/components/cards/cardDao.tsx
> +    <Card data-testid="cardDao">
Currently, only the switch button on the right registers (click) interactions. Are you sure this is what Selim intended?

2022-02-21 17:58 UTC, WissenIstNacht commented on packages/ui-components/src/components/listItem/dao.tsx
> +  /** ListItem value; defaults to daoName if not provided */
I don't quite understand what this is for. What does it do if a value _is_ provided...?

2022-02-21 17:58 UTC, WissenIstNacht commented on packages/ui-components/src/components/listItem/dao.tsx
> +export type ListItemDaoProps = {
OK I think I understand where this is headed. Not sure I agree with it, though :joy:

I know you talked with Selim about this, so I don't want to wedge myself into that convo. I'll just say that this, to me, is not a LIstItem, but a radio button. And I would implement it as such. But again, don't let me distract you.

2022-02-21 18:17 UTC, Fabricevladimir commented on packages/ui-components/src/components/avatar/avatarDao.tsx
> +    const arr = daoName.trim().split(' ');
Quick refactor of avatarDao probably. `useMemo` would certainly be the better choice considering daoName changes only when you switch daos. Thanks for catching that

2022-02-21 18:23 UTC, Fabricevladimir commented on packages/ui-components/src/components/avatar/avatarDao.tsx
> +  return error === true || !src ? (
Haha it's a callback to proper programming languages! I'll update it to remove the true

2022-02-21 18:26 UTC, Fabricevladimir commented on packages/ui-components/src/components/avatar/avatarDao.tsx
> +  daoName: string;
I'm unable to reproduce this... 🤔

2022-02-21 18:36 UTC, Fabricevladimir commented on packages/ui-components/src/components/cards/cardDao.tsx
> - *
The smaller one is what is next to the navigation menu in desktop navbar. The larger one is for the bottomSheet and modal header for mobile menu on mobile and tablet respectively.

I'll update the text. Thanks for catching that

2022-02-21 18:39 UTC, Fabricevladimir commented on packages/ui-components/src/components/cards/cardDao.tsx
> +        className="desktop:hidden"
Yes, I remember seeing it, unfortunately I couldn't find it so I did it this way 🙈

2022-02-21 18:40 UTC, Fabricevladimir commented on packages/ui-components/src/components/cards/cardDao.tsx
> +    <Card data-testid="cardDao">
Yeah this one is a headache. You expect the whole card to be clickable, but then why add a button there without a different specified action. I'll ask him about it though

2022-02-21 18:50 UTC, Fabricevladimir commented on packages/ui-components/src/components/listItem/dao.tsx
> +  /** ListItem value; defaults to daoName if not provided */
This is an attempt at a slight improvement to the radio button but not dilemma. Currently these things are about as useless as possible 😆

2022-02-21 18:54 UTC, Fabricevladimir commented on packages/ui-components/src/components/listItem/dao.tsx
> +export type ListItemDaoProps = {
Yeah, I don't want them as simply prettied containers either. They're a not exactly intuitive to work with. Perhaps I should implement these as radio buttons and see where that leads.

2022-02-23 05:54 UTC, RakeshUP commented on packages/web-app/src/components/daoSwitcherMenu/index.tsx
>              <AvatarDao label={name} domain={ens} src={icon} onClick={onClick} />
The app is crashing when I try to switch DAO's in web-app. This line has a compile error

2022-02-23 05:55 UTC, RakeshUP approved these changes

2022-02-23 11:11 UTC, WissenIstNacht commented on packages/web-app/src/components/daoSwitcherMenu/index.tsx
>              <AvatarDao label={name} domain={ens} src={icon} onClick={onClick} />
I think this whole component will be gone with the next PR Fabrice is working one. But yeah, maybe fix it anyway so that we don't merge faulty code to dev.

2022-02-23 11:11 UTC, WissenIstNacht approved these changes

2022-02-23 13:06 UTC, merged