Chore/Merge Navs - DAO-700
aragon/app-legacy pull request #251
Opened 2022-02-21 17:04 UTC by Fabricevladimir

- merges process and default navbars
- updates styling

NOTE: Lots of file changes 😅 mainly because navbar is now split into two files (desktop and mobile), extraction into smaller components, and deletion

Also, the DAO switcher and mobile process breadcrumb will be updated in new task once #248  (new ListItemDao component and CardDao refactors) is merged.

2022-02-22 09:39 UTC, RakeshUP commented on packages/web-app/src/components/navLinks/index.tsx
> +    'active:text-primary-700 disabled:text-ui-300 focus:bg-ui-50 ' +
This focus behaviour doesn't seem to happen in the older navbar. Also when a navlink is focussed, this causes the sticky navbar background to not be translucent

2022-02-22 09:43 UTC, RakeshUP approved these changes
The DAO switcher section in mobile bottom sheet is missing `padding`. And are the icons next to navlinks only displayed in mobile view? The breadcrumbs too have the same `home` icon for both governance and finance

2022-02-22 13:37 UTC, Fabricevladimir commented on packages/web-app/src/components/navLinks/index.tsx
> +    'active:text-primary-700 disabled:text-ui-300 focus:bg-ui-50 ' +
Yeah, we have new NavItems that come like this they have actual background colors for focus, disabled, and selected. They're not ui-component components, but they're defined on the top of the desktop nav in the Components designs.

2022-02-22 13:42 UTC, Fabricevladimir commented
> The DAO switcher section in mobile bottom sheet is missing `padding`. And are the icons next to navlinks only displayed in mobile view? The breadcrumbs too have the same `home` icon for both governance and finance

I added a note about refactoring the DAO switcher (both desktop and mobile) in a separate task. The PR was getting too large.

Selim has opted to remove the icons on the desktop nav because when going from an unselected to selected state, they caused too much space disruption.

The home icon on the breadcrumbs doesn't change based on the 'base' page, (at least not that I'm aware of  👀)

2022-02-22 17:51 UTC, WissenIstNacht requested changes
Phew, another biggie :joy:

But thanks and well done, this was really necessary.

Aside from the rather minor comments above, there's a couple more things I want to point out:
- S'up with the DaoSwitcher component? It got deleted from the `navbar/index.tsx`. I can't find any other use for it rn.
- After selecting Page button stays focused (with transparent BG). When focus is lifted button goes active (white BG). Kind of annoying. Don't worry about this rn, just something to keep in mind. Maybe discuss it with Selim at some point.

2022-02-22 17:51 UTC, WissenIstNacht commented on packages/web-app/tailwind.config.js
> +        15: '120px',
(Don't think you're ever using this...?)

2022-02-22 17:51 UTC, WissenIstNacht commented on packages/web-app/src/components/fullScreenStepper/fullScreenStepper.tsx
>    navbarLabel: string;
These are no longer needed then, right?

2022-02-22 17:51 UTC, WissenIstNacht commented on packages/web-app/src/containers/navbar/desktop.tsx
> +              <BreadcrumbDropdown
You forgot to pass the `onClose` prop here (leading to the dropdown staying open after selecting a page)

2022-02-22 17:51 UTC, WissenIstNacht commented on packages/web-app/src/containers/navbar/breadcrumbDropdown.tsx
> +      <Popover
I thought I saw a proper Dropdown component somewhere, lately :thinking::joy:

2022-02-22 17:51 UTC, WissenIstNacht commented on packages/web-app/src/containers/navbar/desktop.tsx
> +              src=" "
This gives me an error (or rather, a broken picture icon).

2022-02-22 17:51 UTC, WissenIstNacht commented on packages/web-app/src/containers/navbar/desktop.tsx
> +            <ButtonIcon
This still doesn't do anything right? :joy:

2022-02-22 17:51 UTC, WissenIstNacht commented on packages/web-app/src/containers/navbar/desktop.tsx
> +            <CardDao
I _think_ this is not correctly aligned with the navlinks (didn't measure it, might be wrong haha)

2022-02-22 17:51 UTC, WissenIstNacht commented on packages/web-app/src/containers/navbar/desktop.tsx
> +              onClick={(path: string) => navigate(path)}
This currently doesn't work for me. When I'm on `finance/new-deposit` I expect to be brought back to `finance`. Instead I land on `/`

2022-02-23 10:33 UTC, Fabricevladimir commented on packages/web-app/tailwind.config.js
> +        15: '120px',
I was at one point but then didn't need it anymore

2022-02-23 10:47 UTC, Fabricevladimir commented on packages/web-app/src/containers/navbar/desktop.tsx
> +              <BreadcrumbDropdown
Aha. That's weird though. You'd think unmounting the page would take it away considering we don't go from breadcrumb page to breadcrumb page. Good catch

2022-02-23 10:50 UTC, Fabricevladimir commented on packages/web-app/src/containers/navbar/breadcrumbDropdown.tsx
> +      <Popover
No idea what you're talking about lol

2022-02-23 10:52 UTC, Fabricevladimir commented on packages/web-app/src/containers/navbar/desktop.tsx
> +              src=" "
I'll add the image back to it for the sake of this PR, but it has since been refactored in #248.

2022-02-23 10:53 UTC, Fabricevladimir commented on packages/web-app/src/containers/navbar/desktop.tsx
> +            <CardDao
This will be fixed in the PR after #248

2022-02-23 10:54 UTC, Fabricevladimir commented on packages/web-app/src/containers/navbar/desktop.tsx
> +            <ButtonIcon
Oh yeah

2022-02-23 10:59 UTC, Fabricevladimir commented on packages/web-app/src/containers/navbar/desktop.tsx
> +              onClick={(path: string) => navigate(path)}
Ah, correct. I'll update and use the actual paths

2022-02-23 11:20 UTC, Fabricevladimir commented
> * S'up with the DaoSwitcher component? It got deleted from the `navbar/index.tsx`. I can't find any other use for it rn.
Yes, I removed this temporarily because everything in it has been refactored, but I didn't want to do it in this PR. So once the other #248 has been merged, then I'll put it back in new and improved 😄 

> * After selecting Page button stays focused (with transparent BG). When focus is lifted button goes active (white BG). Kind of annoying. Don't worry about this rn, just something to keep in mind. Maybe discuss it with Selim at some point.
The mistake was on my part. The focus should not have had a non transparent background

2022-02-23 12:08 UTC, sepehr2github approved these changes

2022-02-23 13:59 UTC, WissenIstNacht approved these changes

2022-02-23 17:01 UTC, merged