Chore/Disabled options in ButtonGroup, Link url fixes DAO-701 DAO-592
aragon/app-legacy pull request #253
Opened 2022-02-22 10:53 UTC by RakeshUP

- Makes few tabs in VotingTerminal disabled
- Adds protocol(`http://` - this is the default behaviour in almost every app and also tiptap editor) to links to prevent opening them as relative paths

2022-02-23 13:20 UTC, Fabricevladimir approved these changes
Thanks for the fixes!

2022-02-23 13:20 UTC, Fabricevladimir commented on packages/web-app/src/components/addLinks/row.tsx
> +          new RegExp(URL_PATTERN).test(url) &&
I understand why this is being done. Do you think it's perhaps better to limit the user input to only a url that contains the protocol in the first place so that we don't have to do this regex matching multiple times?

2022-02-23 16:07 UTC, WissenIstNacht commented on packages/web-app/src/components/addLinks/row.tsx
> +        new RegExp(URL_PATTERN).test(url) ||
Could you extract the RegExp objects into variables and reuse them? Creating new ones for each test is kind of (unnecessarily) expensive.

2022-02-23 16:12 UTC, WissenIstNacht requested changes
Thanks Rakesh!

2022-02-24 13:30 UTC, RakeshUP commented on packages/web-app/src/components/addLinks/row.tsx
> +          new RegExp(URL_PATTERN).test(url) &&
I did this because all the other apps I checked like Notion, Jira, etc adds http:// to every URL without a protocol. Also this is the default behaviour in our Tiptap editor

2022-02-24 14:30 UTC, RakeshUP commented on packages/web-app/src/components/addLinks/row.tsx
> +        new RegExp(URL_PATTERN).test(url) ||
Fixed it

2022-02-25 09:51 UTC, WissenIstNacht commented on packages/web-app/src/utils/constants.ts
> +  /^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([-.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/i;
Nice catch. Could have been an annoying bug to find later 👍🏼

2022-02-25 09:51 UTC, WissenIstNacht approved these changes

2022-02-25 10:03 UTC, RakeshUP commented on packages/web-app/src/utils/constants.ts
> +  /^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([-.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/i;
It already created issues. When I put regex declaration to a constant and reused it, instead of instantiating the regex multiple times, the /g started giving problems and this StackOverflow post saved me. https://stackoverflow.com/questions/2851308/why-does-my-javascript-regex-test-give-alternating-results

2022-02-25 10:03 UTC, merged