Feature/ DAO-696
aragon/app-legacy pull request #256
Opened 2022-02-23 13:09 UTC by sepehr2github

- add withdrawa actions
- create basic actions context

Note: I've tried to create a simple pipeline state structure with proper methods but regarding the best context structure we need a discussion

2022-02-25 10:47 UTC, RakeshUP approved these changes
IMO the `Reset Action` button should only clear the states in that particular action. When I have 2 withdraw asset actions and click reset on any, both the form's state is reset. If it makes sense to make another copy of `ConfigureWithdrawForm`, please do. 

But otherwise, this PR is very good. ActionContext 👌👏

2022-02-25 11:28 UTC, Fabricevladimir requested changes
Thanks Sepehr! Moving the actions into the context as opposed to leaving them in the New Proposal form context very much simplifies things 👍🏾 
Left a couple of comments about the position of things.

2022-02-25 11:28 UTC, Fabricevladimir commented on packages/web-app/src/containers/actionBuilder/index.tsx
> +  const actionsComponents = (name: ActionsTypes, index: number) => {
Why not make this an actual component with props and such?

2022-02-25 11:28 UTC, Fabricevladimir commented on packages/web-app/src/containers/actionBuilder/withdrawAction.tsx
> +const WithdrawAction: React.FC<Props> = ({index}) => {
Because a global form is being used for multiple withdraw actions, the fields (to, amount, etc.) will all refer to same values, meaning when you have multiple withdraws, a change in one will be produced in the other. A solution might be to make each action its own form, maybe?

2022-02-25 11:28 UTC, Fabricevladimir commented on packages/web-app/src/containers/addActionMenu/index.tsx
> +  ADD_REMOVE_TOKENS = 'add_remove_address',
Small typo? Did you mean `ADD_REMOVE_ADDRESS`?

2022-02-25 11:28 UTC, Fabricevladimir commented on packages/web-app/src/containers/addActionMenu/index.tsx
>  import {ActionListItem, IconChevronRight} from '@aragon/ui-components';
This one is on me. This should be `ListItemAction` and not `ActionListItem`. There probably is no difference in actual styling, but the `ActionListItem` will be removed since it's no longer in the Components designs. This confusion was introduced when we merged `ListItemMenu` and `ListItemText` into `ListItemAction`. I had forgotten to remove the already present `ActionListItem` component.

2022-02-25 11:28 UTC, Fabricevladimir commented on packages/web-app/src/pages/newProposal.tsx
> +  const formMethods = useForm<WithdrawFormData>({
Using WithdrawFormData here leads to believe that a New Proposal has the same values as a Withdraw and we also lose the actual New Proposal data (Author, title, summary and the rest). Perhaps this should be moved to the Withdraw assets option.

2022-02-25 11:28 UTC, Fabricevladimir commented on packages/web-app/src/pages/newProposal.tsx
> +  useEffect(() => {
This is an extension of the previous comment. As it is, once the user hits the New Proposal page, the form is populated with `from` and `type` even if the proposal doesn't include an actual Withdraw action.

2022-02-25 11:28 UTC, Fabricevladimir commented on packages/web-app/src/pages/newProposal.tsx
> +  const handleTokenSelect = (token: BaseTokenInfo) => {
Same here, this is not necessary unless the user actually wants to include a Withdraw action. I understand though that Token Menu requires the handler to be on the same page. If we can move the Token Menu to where the withdraw action is actually taking place, we can remove this from here. Better yet, at some point we need to move this handler into the Token Menu itself. There's a lot of duplication going around with `handleTokenSelect` 😄

2022-02-27 15:35 UTC, sepehr2github commented on packages/web-app/src/containers/actionBuilder/withdrawAction.tsx
> +const WithdrawAction: React.FC<Props> = ({index}) => {
It's just a placeholder somehow. I will pass index for now but for later we can find a better logic

2022-02-28 19:39 UTC, sepehr2github commented on packages/web-app/src/pages/newProposal.tsx
> +  const handleTokenSelect = (token: BaseTokenInfo) => {
We need to fix this based on actions pipeline structure

2022-03-01 10:09 UTC, Fabricevladimir approved these changes

2022-03-01 10:22 UTC, merged