Chore/ DAO-706
aragon/app-legacy pull request #259
Opened 2022-02-28 07:23 UTC by sepehr2github

2022-02-28 16:15 UTC, Fabricevladimir approved these changes
Thanks!

2022-02-28 16:15 UTC, Fabricevladimir commented on packages/web-app/src/pages/createDAO.tsx
>    const daoSetupCommunityIsValid = useMemo(() => {
At some point we should try to extract these validators into a hook or the like

2022-03-01 09:42 UTC, RakeshUP approved these changes

2022-03-01 10:45 UTC, merged

2022-03-01 11:09 UTC, WissenIstNacht requested changes
Hey Sepehr, thanks for the awesome work! Validation really is a pain.

Aside from the issue above with the stepper numbers, there's a few more details I've found. Most of them are really small issues. I've separated them into things that need to be changed, and things that we should keep in mind and maybe address later. 

Necessary changes:

- Wallet list:
  - first wallet address input has “Your Wallet” as value intead of placeholder. This leads to problems like: User can not directly paste. Text doesn't vanish on click. Validation doesn't trigger. Etc.
  - Empty addresses rows are currently allowed (i.e., rows with no address AND no token amount). This is not a problem in the form itself. But on the review page, it will count the empty row as an address. I.e., if you enter one valid address and and empty one, it will say "See 3 addresses" on the review. 
  - There's a typo on the double wallet error. Should be "You can't enter an address twice".  That being said, I would use a different copy: “Address must not be reused” (because in the rest of the app errors never speak to the user directly. Also, it’s not only that the user can’t enter the address twice, but any number of times more than one) 
- Review:
  - Entering super long url in links breaks the layout of DAO Metadata component.
  - Fallback DAO icon not shown in DAO Metadata
- Setup Community
  - Using an existing token, and then switch to new token doesn't fully reset the tokens. For example, if you use ANT and then change to create a new Token, the name and Symbol will be "Aragon Network Token" and "ANT". Also, the wallet list component will show the total supply of ANT.

Optional changes:

- Link List:
    - “Links is mandatory” error appears as soon as user starts typing in title. Maybe should only appear when user leaves the field?
- Wallet list:
    - Rounding percentages (equal distribution among 3 addresses gives 33%, which adds up to 99%)
    - Going back to edit a part of the form does not reset the check (I’m not sure if it should, so take this with a grain of salt)

2022-03-01 11:09 UTC, WissenIstNacht commented on packages/web-app/src/components/fullScreenStepper/fullScreenStepper.tsx
> -  totalFormSteps,
I'm not sure you're doing yourself a favour by removing this. It was added by Rakesh to take care of forms that had more pages than the form (for example, in the case where there was an intro page, like on the creation flow).

If you keep this remove, you'll walk into trouble in existing flows like the deposit flow. For example, with your current changes, the stepper starts counting from 0. I.e., the "Configure Deposit" step is "step 0 of 2", but it should be "step 1 of 2".