Feature/Page headers - DAO-739
aragon/app-legacy pull request #268
Opened 2022-03-03 19:07 UTC by Fabricevladimir

- adds breadcrumbs to page headers
- makes breadcrumbs bold

Note: Per the design system, page headers should technically be a component. I've embedded them directly into the web-app because I disagree 🥊

2022-03-08 07:55 UTC, sepehr2github commented on packages/web-app/src/pages/proposal.tsx
> +    // if (publisherAddress === account) return 'you';
are These comments required?

2022-03-08 08:12 UTC, sepehr2github reviewed
Thanks Fabrice! good job man, Just a small thing.
<img width="326" alt="Screen Shot 2022-03-08 at 11 36 20 AM" src="https://user-images.githubusercontent.com/46657145/157193705-70bc3995-be5c-4099-bde0-aaffbe04d2f7.png">
On the token page when I click on the finance page It won't come back! and Also we should fix this padding issue

2022-03-08 10:34 UTC, WissenIstNacht requested changes
Thanks man, look great!

2022-03-08 10:34 UTC, WissenIstNacht commented on packages/web-app/src/pages/proposal.tsx
> +  className: 'flex flex-col gap-y-2 desktop:p-0 px-2 tablet:px-3 pt-2',
Detail regarding tablet layout: The Header section is narrower than the content section (ecause of the 3 unit padding in the x direction). Would be nice to have their width aligned. Not sure if you want to remove the padding here or add it to the container. I'll let you figure it out :D

2022-03-08 12:24 UTC, Fabricevladimir commented on packages/web-app/src/pages/proposal.tsx
> +    // if (publisherAddress === account) return 'you';
I'll remove them, but they were code to be used once backend is integrated

2022-03-08 12:31 UTC, Fabricevladimir commented on packages/web-app/src/pages/proposal.tsx
> +  className: 'flex flex-col gap-y-2 desktop:p-0 px-2 tablet:px-3 pt-2',
Yup, good catch. For the header component, the padding is correct per ui-components->header->proposal. I didn't modify the page content size because it's an app-wide issue that warrants its own ticket I felt.

2022-03-08 16:49 UTC, WissenIstNacht commented on packages/web-app/src/pages/proposal.tsx
> +  className: 'flex flex-col gap-y-2 desktop:p-0 px-2 tablet:px-3 pt-2',
Right, all good 👍🏼

2022-03-08 16:50 UTC, WissenIstNacht approved these changes

2022-03-09 09:15 UTC, RakeshUP approved these changes

2022-03-09 11:01 UTC, merged