fix withdraw flow validation issues
aragon/app-legacy pull request #273
Opened 2022-03-07 11:50 UTC by josemarinas

2022-03-07 11:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aragon/zaragoza?pullRequest=273) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aragon/zaragoza?pullRequest=273) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aragon/zaragoza?pullRequest=273) it.</sub>

2022-03-08 11:00 UTC, sepehr2github reviewed
Thank you, Jose! Well Done!
Just one minor thing. On Withdraw flow page two I selected Date + Time and I changed the values then I went to next page but I forgot to do sth. when I came back to page two the end tab was on days not Date + Time

2022-03-08 13:41 UTC, Fabricevladimir reviewed
Thank you! This was an annoying bug

2022-03-08 13:41 UTC, Fabricevladimir commented on packages/web-app/src/containers/configureWithdraw/index.tsx
> +      trigger('amount');
While this triggers for the amount properly, we might not want to do that on the very first render. Since the amount field isn't yet dirty, we'll be showing an error the second the user selects a token. Thoughts?

2022-03-08 17:16 UTC, WissenIstNacht requested changes
Hey there, thanks a lot for the PR :)

Unfurtonately I think your code has solved a few things, but broken others 😅

2022-03-08 17:16 UTC, WissenIstNacht commented on packages/web-app/src/containers/setupVotingForm/index.tsx
> -      setError('startTime', {
So there's a couple of issues with letting react hook form assign errors by returning them from the validator function:
- If you change the start date to be after 5 days before the end date (e.g., you land on the page and increase the start date by one day), the error will appear on the start date. This doesn't really make sense.
- Also, the errors are not properly cleared. For example, after the above scenario, increasing the enddate by at least one does not reset the error.

2022-03-10 09:28 UTC, josemarinas commented
> Thank you, Jose! Well Done! Just one minor thing. On Withdraw flow page two I selected Date + Time and I changed the values then I went to next page but I forgot to do sth. when I came back to page two the end tab was on days not Date + Time

Yes, that happens because of the initial state of the field. The first solution that comes to my mind is using a React hook with state for the whole withdrawal process, and start managing the forms in this way, but maybe it is a little overkill, let me know what you think

2022-03-10 09:29 UTC, josemarinas commented on packages/web-app/src/containers/configureWithdraw/index.tsx
> +      trigger('amount');
Yes, you are right, it should be solved by adding a check to know if the field is dirty in the if

2022-03-10 09:31 UTC, josemarinas commented on packages/web-app/src/containers/setupVotingForm/index.tsx
> -      setError('startTime', {
Sure, it makes sense, I'll try it and let you know

2022-03-21 15:17 UTC, WissenIstNacht approved these changes
Thanks, the validation issue seems to work 👍🏼 

Regarding @sepehr2github 's comment: I will open a new ticket on this issue and deal with it on a separate PR.

2022-03-22 15:49 UTC, Fabricevladimir commented
There's a small issue with the amount validation. Validation for amount isn't triggering when the contract address changes. It can be reproduced by following these steps:
1. In token menu, select add custom token
2. Insert incorrect contract address & some value for the amount (just so the field is dirty)
3. Back in token menu, select one of the DAO tokens

I'm not sure if we want to fix this here or merge and resolve the issue in a separate ticket.

2022-03-23 11:22 UTC, WissenIstNacht commented
Closing the PR as it's already been merged. We'll have another ticket(s) to tackle pending issues across the various forms.

2022-03-23 11:22 UTC, closed without merging