Feature/ DAO-443
aragon/app-legacy pull request #28
Opened 2021-11-08 13:21 UTC by sepehr2github

- Bottom sheet added
- Backdrop Component added
- farmer motion added

2021-11-09 09:58 UTC, WissenIstNacht requested changes
Thanks, looks nice!

2021-11-09 09:58 UTC, WissenIstNacht commented on packages/web-app/src/pages/home.tsx
> +      <BottomSheet onOpen={onOpen} isOpen={isOpen} onClose={onToggle} />
Use `onClose` as handler for the `onClose` prop [my recomendation] or use `onToggle` but remove the unused onClose method.

2021-11-09 09:58 UTC, WissenIstNacht commented on packages/web-app/src/components/BottomSheet/index.tsx
> +function usePrevious(value: boolean) {
Maybe I'm missing something, but I feel like this is a bit overkill :)

Either way: It's a nice hook to have and might be reused in the future. Could you a) move it to the hooks folder and b) generalize it to have a variable type?

2021-11-09 09:58 UTC, WissenIstNacht commented on packages/web-app/src/components/BottomSheet/index.tsx
> +  &::before {
one colon is enough I think: `&:before`

2021-11-09 09:58 UTC, WissenIstNacht commented on packages/web-app/src/components/BottomSheet/index.tsx
> +  function onDragEnd(event: MouseEvent | TouchEvent | PointerEvent, info: any) {
`_` for unused arg?

2021-11-09 17:15 UTC, Fabricevladimir reviewed
This is really cool! One thing I did notice is that if you drag the sheet up high enough, it "un-sticks" from the bottom of the screen. Is it a lack of content that's doing that?

2021-11-09 17:15 UTC, Fabricevladimir commented on packages/ui-components/src/components/backdrop/backdrop.tsx
> +export interface BackdropProps {
Can you separate the imports and content?

2021-11-09 17:15 UTC, Fabricevladimir commented on packages/ui-components/src/components/backdrop/backdrop.tsx
> + * Primary UI component for user interaction
This comment should be updated.

2021-11-09 17:15 UTC, Fabricevladimir commented on packages/web-app/src/pages/home.tsx
> +      <Button onClick={onToggle} label="Toggle" />
The toggle handler might be the one to remove because the button doesn't actually toggle the `bottomsheet`. It just opens it, but doesn't close it. That said, I expect  the demo will be scrapped!

2021-11-10 09:38 UTC, WissenIstNacht requested changes

2021-11-10 09:38 UTC, WissenIstNacht commented on packages/web-app/src/Hooks/usePrevious.tsx
> +  const previousValueRef = useRef<boolean>();
```suggestion
export default function usePrevious<T>(value: T) {
  const previousValueRef = useRef<T>();
```

2021-11-10 09:38 UTC, WissenIstNacht commented on packages/web-app/src/Hooks/usePrevious.tsx
> +import {useEffect, useRef} from 'react';
The hooks folder should be a lower case (`.../hooks/...`)

2021-11-10 09:38 UTC, WissenIstNacht commented on packages/web-app/src/components/BottomSheet/index.tsx
> +  function onDragEnd(event: MouseEvent | TouchEvent | PointerEvent, info: any) {
```suggestion
  function onDragEnd(_: MouseEvent | TouchEvent | PointerEvent, info: any) {
```

2021-11-10 09:51 UTC, Fabricevladimir approved these changes
Looks good! This can be merged once @WissenIstNacht's comments have been addressed.

2021-11-10 13:04 UTC, WissenIstNacht approved these changes

2021-11-10 16:41 UTC, merged