Feature/DAO switcher & abstain vote option
aragon/app-legacy pull request #284
Opened 2022-03-14 12:29 UTC by RakeshUP

DAO switcher first pass(DAO-715) & abstain voting option added(DAO-745)

The DAO switcher is very basic and is missing out on functionality. We can work on it further after we have some real data and also decide the parameters in urls

2022-03-21 15:54 UTC, Fabricevladimir reviewed
Thanks! The Apollo client local storage variable mechanism is very handy

2022-03-21 15:54 UTC, Fabricevladimir commented on packages/ui-components/src/components/table/votersTable.tsx
> +                colorScheme={
Might want to extract this into a variable.

2022-03-21 15:54 UTC, Fabricevladimir commented on packages/web-app/src/containers/navbar/daoSelectMenu.tsx
>    const handleDaoSelect = (dao: {daoName: string; daoAddress: string}) => {
If a dao is only the name and address, how do we know which network a dao belongs to?

2022-03-22 10:35 UTC, WissenIstNacht requested changes
Thanks Rakesh. I think Fabrice's comments already cover everything. PIng me when they're resolved.

2022-03-22 14:02 UTC, RakeshUP commented on packages/web-app/src/containers/navbar/daoSelectMenu.tsx
>    const handleDaoSelect = (dao: {daoName: string; daoAddress: string}) => {
I am still not sure of the data structure for the favoriteDAOs array. I just copied it from the existing temp data in Navbar DaoSelector. Things like ENS name for DAO might be added too along with network

2022-03-22 14:26 UTC, Fabricevladimir commented on packages/web-app/src/containers/navbar/daoSelectMenu.tsx
>    const handleDaoSelect = (dao: {daoName: string; daoAddress: string}) => {
I guess that's also going to depend on how we figure out which network a DAO is in as well. Fair enough.

2022-03-22 14:26 UTC, Fabricevladimir approved these changes

2022-03-22 15:10 UTC, WissenIstNacht approved these changes

2022-03-22 15:13 UTC, merged