Feature/ Dao-754
aragon/app-legacy pull request #288
Opened 2022-03-17 10:05 UTC by sepehr2github

- contributors address modal added
- refactored voters table (please review this and let me know if this approach is best or not)

2022-03-21 15:30 UTC, Fabricevladimir requested changes
Thanks, nice work! Left a couple of comments

2022-03-21 15:30 UTC, Fabricevladimir commented on packages/web-app/src/containers/communityAddressesModal/index.tsx
> +    const list = wallets
Would this be best memoized instead of calculated inside useEffect and stored as state?

2022-03-21 15:30 UTC, Fabricevladimir commented on packages/web-app/src/containers/communityAddressesModal/index.tsx
> +        <VotersTable
Can you take care of an empty state for when no address matches the search query?

2022-03-22 15:08 UTC, RakeshUP approved these changes

2022-03-23 11:16 UTC, Fabricevladimir approved these changes

2022-03-23 11:16 UTC, merged