Feature: Wallet based DAO
aragon/app-legacy pull request #306
Opened 2022-04-04 16:23 UTC by josemarinas

## Description

Enabled the wallet based DAO flow and added the required changes for it to work. The list of wallets is stored in the `useForm` with the key `walletList`. A component was added to `ui-components` and the `Label` component was modified to accept HTML

Task: [DAO-572](https://aragonassociation.atlassian.net/browse/DAO-572)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2022-04-05 15:21 UTC, brickpop commented on packages/web-app/src/containers/goLive/community.tsx
> +    alert('not implemented');
Why is that alert and TO DO here?

2022-04-05 17:04 UTC, josemarinas commented on packages/web-app/src/containers/goLive/community.tsx
> +    alert('not implemented');
As far as I know, there is a different ticket to implement the modal with a list of addresses so once this ticket is resolved his function should be updated

2022-04-07 14:15 UTC, Fabricevladimir requested changes
Good work, thanks, very involved task! Left a few comments.

2022-04-07 14:15 UTC, Fabricevladimir commented on packages/ui-components/src/components/label/label.tsx
> +        {!renderHtml && <Heading>{label}</Heading>}
You may be able to simplify (!) this by using the conditional operator.

2022-04-07 14:15 UTC, Fabricevladimir commented on packages/web-app/src/components/walletList/index.tsx
> +  const walletArray: string[] = useWatch({
react-hook-form provides a `useFieldArray` hook to simplify this type of listing of fields. Checkout the `addWallets` or `addLinks` components to take a look

2022-04-07 14:15 UTC, Fabricevladimir commented on packages/web-app/src/components/walletList/index.tsx
> +            <>
Might want to wrap this in a div so you can pass it a key. React will complain about it not having a unique key prop

2022-04-07 14:15 UTC, Fabricevladimir commented on packages/web-app/src/components/walletList/index.tsx
> +            label="Add address"
Can you use the translation strings for the label here?

2022-04-07 14:15 UTC, Fabricevladimir commented on packages/web-app/src/components/walletList/index.tsx
> +        <Popover
There is a pending task to replace the popovers in the application with the dropdown component from ui-components. Could you use that instead here?

2022-04-07 14:15 UTC, Fabricevladimir commented on packages/web-app/src/components/walletList/row.tsx
> +  const handleDeleteWallet = () => {
Blank line between the methods for readability purposes please 😄

2022-04-07 14:15 UTC, Fabricevladimir commented on packages/web-app/src/components/walletList/row.tsx
> +              // <ErrorContainer>
Don't forget to delete if comment is unnecessary

2022-04-07 14:15 UTC, Fabricevladimir commented on packages/web-app/src/components/walletList/row.tsx
> +                    onClick={handleDeleteAllAddresses}
Are you certain this is supposed to delete all addresses and not just the corresponding address? It seems a bit counter-intuitive.

2022-04-07 14:15 UTC, Fabricevladimir commented on packages/web-app/src/components/walletList/row.tsx
> +          <Popover
Would be great if you could use a dropdown here as well instead. If it takes too much time, move on and we'll implement the dropdown in a separate task

2022-04-07 14:15 UTC, Fabricevladimir commented on packages/web-app/src/components/walletList/row.tsx
> +              disabled={walletList.length <= 2}
Can you clarify why this button is disabled?

2022-04-07 14:15 UTC, Fabricevladimir commented on packages/web-app/src/containers/configureCommunity/index.tsx
> +                          Math.round(
Would it be more efficient to memoize this up top?

2022-04-07 14:15 UTC, Fabricevladimir commented on packages/ui-components/src/components/alerts/alertCard.tsx
> +  mode?: 'neutral' | 'success' | 'warning' | 'critical';
Shouldn't neutral be info?

2022-04-07 14:15 UTC, Fabricevladimir commented on packages/ui-components/src/components/alerts/alertCard.tsx
> +  subtitle?: string;
Can you rename this to helptext to align with the designs unless you feel the design should change instead?

2022-04-07 14:15 UTC, Fabricevladimir commented on packages/web-app/src/components/walletList/row.tsx
> +    <Controller
When there's an error it pushes down the menu button.

![image](https://user-images.githubusercontent.com/16927999/162219018-a4c59fed-9487-4453-9edc-4b1765c7a20f.png)

2022-04-07 14:15 UTC, Fabricevladimir commented on packages/ui-components/src/components/alerts/alertCard.tsx
> +      <TextContainer>
The text forces the icon to shrink on mobile

![image](https://user-images.githubusercontent.com/16927999/162219731-3ad0d05b-fc5a-4dfd-aba0-4f54f7b9a47c.png)

2022-04-11 11:10 UTC, josemarinas commented on packages/web-app/src/components/walletList/row.tsx
> +              disabled={walletList.length <= 2}
It does not make much sense to allow the user to delete its own address from this list, but I'm waiting for selim to tell me about how it should be done

2022-04-11 13:35 UTC, josemarinas commented on packages/ui-components/src/components/alerts/alertCard.tsx
> +  mode?: 'neutral' | 'success' | 'warning' | 'critical';
Maybe, I'm not sure, I used the naming convention that is used in the AlertInline component

2022-04-11 13:57 UTC, josemarinas commented on packages/ui-components/src/components/alerts/alertCard.tsx
> +      <TextContainer>
Hmm, I checked this, but it seems like a bigger issue with the icon components in general, if you do the same test with the `AlertInline` component it happens the exact same thing.

2022-04-12 14:58 UTC, josemarinas commented on packages/ui-components/src/components/label/label.tsx
> +        {!renderHtml && <Heading>{label}</Heading>}
Fixed in the last commit

2022-04-12 14:59 UTC, josemarinas commented on packages/web-app/src/components/walletList/index.tsx
> +  const walletArray: string[] = useWatch({
It took me a while to understand how `useFieldArray` worked, but I believe right now is working properly with this hook

2022-04-12 14:59 UTC, josemarinas commented on packages/web-app/src/components/walletList/index.tsx
> +        <Popover
Updated the code with dropdown instead of popovers

2022-04-12 15:01 UTC, josemarinas commented on packages/web-app/src/components/walletList/row.tsx
> +                    onClick={handleDeleteAllAddresses}
I talked with selim, and he updated the design with the new options. I implemented the in them new commit

2022-04-12 15:02 UTC, josemarinas commented on packages/web-app/src/containers/configureCommunity/index.tsx
> +                          Math.round(
Yes, makes sense, is not a super complex operation but makes sense to have it in a different place just for readability, so I updated the code with an `useMemo` :smile:

2022-04-12 15:14 UTC, Fabricevladimir commented on packages/ui-components/src/components/alerts/alertCard.tsx
> +  mode?: 'neutral' | 'success' | 'warning' | 'critical';
Info would be sweet! For the naming convention in general always go with what's on figma (unless you have a reason not, in that case ping one of the designers to discuss it), because sometimes the existing components have been refactored on figma but the changes are not yet reflected in the code itself

2022-04-12 15:16 UTC, Fabricevladimir commented on packages/ui-components/src/components/alerts/alertCard.tsx
> +      <TextContainer>
Ah, good catch. If you wrap a div around the icon like so `<div>{styles[mode].icon}</div>` that should fix it I believe. It would be great if you could do that for the AlertInline as well, that one is on me 🙈

2022-04-13 11:12 UTC, sepehr2github approved these changes

2022-04-14 10:36 UTC, Fabricevladimir approved these changes
Thanks for the changes!

2022-04-18 09:41 UTC, merged