Feature: Transaction detail
aragon/app-legacy pull request #308
Opened 2022-04-05 16:14 UTC by Fabricevladimir

## Description
- Shows modal with transaction detail when transfer is clicked
- Modifies modal max width

Task: [DAO-820](https://aragonassociation.atlassian.net/jira/software/c/projects/DAO/boards/2?modal=detail&selectedIssue=DAO-820&sprint=52)

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2022-04-10 21:01 UTC, sepehr2github commented on packages/web-app/src/utils/types.ts
> +} & (
Looks Cool ;)

2022-04-10 21:01 UTC, sepehr2github commented on packages/web-app/src/utils/types.ts
> +  | {transferType: 'VaultWithdraw'; to: Address; proposalId: string}
Looks Cool ;)

2022-04-10 21:06 UTC, sepehr2github commented on packages/web-app/src/locales/en/common.json
>  }
Usually, all the files have a empty line by end of them, but It's not a big deal

2022-04-10 21:07 UTC, sepehr2github commented on packages/web-app/src/hooks/usePollTransfersPrices.tsx
> +            ...(transfer.__typename === 'VaultDeposit'
If we can merge that enum, We can use it in several places, for example here

2022-04-10 21:10 UTC, sepehr2github approved these changes
Thanks, Fabrice. PR looks good to me but I left a few recommendations! Those are nice to have mostly

2022-04-11 07:24 UTC, josemarinas requested changes
I couldn't find anything besides the lack of some translations, good job :+1:

2022-04-11 07:24 UTC, josemarinas commented on packages/web-app/src/containers/transactionDetail/index.tsx
> +            title="Reference"
I believe this should be a translation function `t('transactionDetail.reference')`

2022-04-11 07:24 UTC, josemarinas commented on packages/web-app/src/pages/transfers.tsx
> +                <Option value="all" label="All" />
Update labels with translations

2022-04-11 10:47 UTC, Fabricevladimir commented on packages/web-app/src/utils/types.ts
> +  | {transferType: 'VaultWithdraw'; to: Address; proposalId: string}
Sure thing!

2022-04-11 10:48 UTC, Fabricevladimir commented on packages/web-app/src/locales/en/common.json
>  }
It automatically removes it for JSON files

2022-04-11 10:52 UTC, Fabricevladimir commented on packages/web-app/src/containers/transactionDetail/index.tsx
> +            title="Reference"
Good catch thanks!

2022-04-12 09:58 UTC, RakeshUP approved these changes

2022-04-12 11:55 UTC, josemarinas approved these changes

2022-04-12 12:09 UTC, merged