Feature: Implement Web3modal
aragon/app-legacy pull request #310
Opened 2022-04-07 07:56 UTC by josemarinas

## Description

- Change `useWallet` for `useSigner` hook
- Add new disconnect modal
- Add configuration in vite to support the web3 modal

Task: [ID]()

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2022-04-10 20:39 UTC, sepehr2github commented on packages/web-app/src/app.tsx
> +      {/* <WalletMenu /> */}
Remove This commented menu please

2022-04-10 20:42 UTC, sepehr2github commented on packages/web-app/vite.config.ts
> +      // ↓ Needed for development mode
please use prettier to fix format issues here

2022-04-10 20:50 UTC, sepehr2github commented on packages/web-app/src/containers/navbar/walletMenu.tsx
> +            {ensName && <Title>{ensName}</Title>}
I couldn't see my ens name on the wallet Modal. It was OK on the wallet button but here Nothing showed for me! if you don't have any ensName it please let me know. I can test for you 👍

2022-04-10 20:52 UTC, sepehr2github commented on packages/web-app/src/containers/navbar/index.tsx
> +      console.log(isWalletOpen);
I'm not sure! but this console is unnecessary, please remove it.

2022-04-10 20:54 UTC, sepehr2github commented on packages/web-app/package.json
> +    "rollup-plugin-polyfill-node": "^0.9.0",
May I ask you to give me some information regarding adding this component?

2022-04-10 20:55 UTC, sepehr2github commented on packages/web-app/package.json
> +    "rollup-plugin-polyfill-node": "^0.9.0",
May I ask you to give me some information regarding adding this component?

2022-04-10 20:57 UTC, sepehr2github reviewed
Thanks a lot, Jose! Nice kick-off 👍 . You did a great job, Just left a few comments for you, my friend!

2022-04-11 13:37 UTC, WissenIstNacht requested changes
Hey Jose, thanks a ton for all the work.

Most of the of comments I left where on minor issues that need to be changed. However, there are two more important comments around already existing hooks (ens and balance). It would be great if we could settle on just one piece of code :)

2022-04-11 13:37 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useWallet.tsx
> +export interface IUseWalletProps {
Could you reference the original interface here instead of copying all the fields into a new type? Something like

```
interface UseWalletProps extends SignerValue {
  //whatever is in IUseWallet but not in SignerValue. 
}
```

Obviously the logic extends to any other fields that may be borrowed from other interfaces/types :)

2022-04-11 13:37 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useWallet.tsx
> +    if (provider && address) {
Were you aware that there already exist a hook for this? If so, why did you chose to re-implement it here? If not, could you try to merge the code?

2022-04-11 13:37 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useWallet.tsx
> +    if (address && provider) {
Were you aware that there already exist a hook for this? If so, why did you chose to re-implement it here? If not, could you try to merge the code?

2022-04-11 13:37 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useWalletTokens.tsx
> +              balance ? balance.toString() : '',
Due to your removing of the type when destructuring `useWallet`, balance can now be a `BigNumber`. Have you made sure this does not break things in the UI (in other words does `toString` of a `BigNumber` result in the same string value as before?)

2022-04-11 13:37 UTC, WissenIstNacht commented on packages/web-app/src/containers/navbar/walletMenu.tsx
> +            {ensName && <Title>{ensName}</Title>}
I think this is because the `useEnsName` is still tied to `useWallet` (I mean the package here, not the new hook :yum:) and wasn't updated to work with the new wallet mechanism. I left a comment in the `useWallet` (the hook, this time) to address this.

2022-04-11 13:37 UTC, WissenIstNacht commented on packages/web-app/src/containers/navbar/walletMenu.tsx
> +export const WalletMenu = () => {
Could you leave a lin of space here and there? :D

(At least around functions would be nice)

2022-04-11 13:37 UTC, WissenIstNacht commented on packages/web-app/src/containers/navbar/desktop.tsx
> +  const isConnected = status === 'connected';
Isn't the `isConnect` value already computed in `useWallet`?

2022-04-11 15:07 UTC, brickpop reviewed
Thank you for your contribution Jose

2022-04-11 15:07 UTC, brickpop commented on packages/web-app/src/app.tsx
> +      {/* <WalletMenu /> */}
+1

2022-04-11 15:07 UTC, brickpop commented on packages/web-app/src/containers/navbar/index.tsx
> +      console.log(isWalletOpen);
+1

2022-04-11 15:07 UTC, brickpop commented on packages/web-app/src/containers/navbar/index.tsx
> +      console.error(err);
Can you please add a Jira task for handling this error on the UI side?

2022-04-11 15:07 UTC, brickpop commented on packages/web-app/src/containers/navbar/walletMenu.tsx
> +export const WalletMenu = () => {
```suggestion

export const WalletMenu = () => {
```

2022-04-11 15:07 UTC, brickpop commented on packages/web-app/src/containers/navbar/walletMenu.tsx
> +            {ensName && <Title>{ensName}</Title>}
Have a look here @josemarinas: 
- `provider.lookupAddress(address) => ensDomain (possibly empty)`
- `provider.resolveName(ensDomain) => address`


https://docs.ethers.io/v5/api/providers/provider/#Provider-ResolveName

2022-04-11 15:07 UTC, brickpop commented on packages/web-app/src/containers/navbar/walletMenu.tsx
> +          onClick={() => alert('not implemented')}
Can we create a task or identity the task that will implement this?

2022-04-11 15:07 UTC, brickpop commented on packages/web-app/src/index.tsx
> +      infuraId: 'mainnet.eth.aragon.network',
Is this out API key? Shouldn't this be fetched from `process.env` or from the settings somehow?

2022-04-11 19:08 UTC, josemarinas commented on packages/web-app/vite.config.ts
> +      // ↓ Needed for development mode
When I run `yarn lint` doesn't seem to have a problem over here

2022-04-11 19:11 UTC, josemarinas commented on packages/web-app/package.json
> +    "rollup-plugin-polyfill-node": "^0.9.0",
The web3modal uses some libraries from nodejs, so this is just a polyfill to make `global` and other variables available. Without this the web3modal won't work

2022-04-11 19:15 UTC, josemarinas commented on packages/web-app/src/hooks/useWallet.tsx
> +export interface IUseWalletProps {
Yes, the thing is that `SignerValue` is not exported in the package, so I can't use it. @brickpop can you update the use signer and export the `SignerValue` type?

2022-04-11 19:49 UTC, josemarinas commented on packages/web-app/src/hooks/useWalletTokens.tsx
> +              balance ? balance.toString() : '',
Yes, I tested with my wallet in the finance page, the only one where `useWalletTokens` is used, and it works

2022-04-11 19:56 UTC, josemarinas commented on packages/web-app/src/hooks/useWallet.tsx
> +    if (provider && address) {
Yes, but since they are not used in other parts of the code, for me, it makes sense having them in the new `useWallet`, but if you prefer to have them separated we can leave them separated, but I'll have to adapt them because they use the `useProviders` hook that uses the old `useWallet`

2022-04-11 20:03 UTC, josemarinas commented on packages/web-app/src/containers/navbar/walletMenu.tsx
> +            {ensName && <Title>{ensName}</Title>}
That's what I'm doing inside the new `useWallet` hook, so the ensName should appear, but I don't have an ENS domain, so I can't test it properly

2022-04-12 07:50 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useWallet.tsx
> +    if (address && provider) {
I think I remembered something wrong here. I don't think there's a hook for the balance. Sorry 😅

2022-04-12 07:51 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useWallet.tsx
> +    if (provider && address) {
No problem. If you think it makes more sense to keep them together, go for it. 😊 

The only thing I would ask, then, is to delete the file with the separated hooks (`useEnsData.tsx`) and make sure nothing in the code base references them anymore.

2022-04-12 09:17 UTC, WissenIstNacht requested changes
Hey, thanks a lot for addressing the issues. The only thing missing is the formatting on the the vite config file pointed out by @sepehr2github.

If you're having issues with this, let me know.

2022-04-12 09:53 UTC, josemarinas commented on packages/web-app/src/hooks/useWallet.tsx
> +    if (provider && address) {
Sure, it is updated in this new commit

2022-04-12 10:01 UTC, josemarinas commented on packages/web-app/src/containers/navbar/index.tsx
> +      console.error(err);
https://aragonassociation.atlassian.net/browse/APP-249

Here it goes, feel free to update it

2022-04-12 10:05 UTC, josemarinas commented on packages/web-app/src/containers/navbar/walletMenu.tsx
> +          onClick={() => alert('not implemented')}
Yes, first we will have to come into an agreement of how these transactions are going to be handled. In the sense of if a transaction is pending and the integration of this with the client and SDK.

2022-04-12 10:10 UTC, josemarinas commented
> Hey, thanks a lot for addressing the issues. The only thing missing is the formatting on the the vite config file pointed out by @sepehr2github.
> 
> If you're having issues with this, let me know.
> 
> // Edit: I just noticed your reply further up. You are right, es-lint does not pick up on this. The issue is that the respective linting command is scoped to `src`, which doesn't include config files.

Ok, that makes sense, I made a new commit fixing the linting of the `vite.config.js`

2022-04-12 12:49 UTC, josemarinas commented on packages/web-app/src/hooks/useWallet.tsx
> +export interface IUseWalletProps {
Jordi updated the `use-signer` paackage so now we can inport `SignerValue`

2022-04-12 13:49 UTC, WissenIstNacht approved these changes
Thanks a lot for all the changes. LGTM!

2022-04-12 16:36 UTC, brickpop approved these changes

2022-04-12 16:36 UTC, brickpop commented on packages/web-app/src/hooks/useWallet.tsx
> +  }, [status]);
Couldn't this be as simple as having `const isConnected = status === 'connected';` ?
We're creating a state that is 100% computed, but this is very minor to be any stopper.

2022-04-13 08:20 UTC, merged