Feature/Governance Page Subgraph Integration
aragon/app-legacy pull request #312
Opened 2022-04-07 10:40 UTC by RakeshUP

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task: [76](https://aragonassociation.atlassian.net/jira/software/c/projects/APP/boards/41/backlog?view=detail&selectedIssue=APP-76&issueLimit=100) [77](https://aragonassociation.atlassian.net/jira/software/c/projects/APP/boards/41/backlog?view=detail&selectedIssue=APP-77&issueLimit=100)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2022-04-12 10:36 UTC, WissenIstNacht requested changes
Thanks a lot, Rakesh. Really nice to see live data coming in for the daos.

There's a couple of things that are bugging me, though. One is rather minor that I already pointed out in the comments above. But it appears in several places and I thought I'd summarize it here. It's about all the loading and error states in the app that are just "swallowed". I admit it's kind of annoying to add stuff that will be deleted later. But I think it's imporant to point out where things aren't done yet. I.e., at least have a message that say "Loading" or "Some error happened". It will help the QA team a lot to understand what's going on and hopefully incentivise them to create tasks to cover these kinds of issues.

The other thing that's bugging me is the type generation. Don't get me wrong, it's a super cool feature, but at the moment it seems a bit... lacking. A lot of types default to `any` (or worse, `any | null`). Why is that? Can this be improved in the future? (Also, a lot of types are lower case. Is there no way to configure this differently?)

2022-04-12 10:36 UTC, WissenIstNacht commented on packages/web-app/src/index.tsx
> +                <ApolloProvider client={client['rinkeby']}>
So basically "it doesn't matter" which network is passed at this point because it will be specified again when calling the `useQuery` hook?

2022-04-12 10:36 UTC, WissenIstNacht commented on packages/web-app/src/utils/types.ts
> +  creator: string;
Is this the same one as `publisher` on line 110? If so, are both needed? If not, could you delete one of them?

2022-04-12 10:36 UTC, WissenIstNacht commented on packages/web-app/src/services/prices.ts
> +  client: ApolloClient<object>,
What was wrong with the old type?

Anyway, if you're not using it anymore pls removing it from the imports at the top. :)

2022-04-12 10:36 UTC, WissenIstNacht commented on packages/web-app/src/pages/proposal.tsx
> +    return null;
Could you display a paragraph here that says "Loading" so that whoever does QA doesn't think there's something wrong?

Same goes for the other if statements below.

2022-04-12 10:36 UTC, WissenIstNacht commented on packages/web-app/src/components/proposalList/index.tsx
> +              // {...(categorizedProposal.type === 'active' && {
Why is this commented out?

2022-04-12 10:36 UTC, WissenIstNacht commented on packages/web-app/src/components/proposalList/index.tsx
> +              title={metadata.title}
The title and subtitle do not show for the two proposals you deployed.

2022-04-13 10:56 UTC, RakeshUP commented
@WissenIstNacht I forgot to put it in the description here, we discussed this during the standup call on Monday. This PR has many hacky bits to make things on the Governance page work. The types generated are from the subgraph schema, so we need to start refining from there and I've created a separate subtask to do that. I've marked this ready for review because some things in the apollo client setup have changes in this PR that might be useful for other tasks(like network switching, types generation, etc). But regarding the integration in the Governance pages, a lot of things might change due to the refactoring.

2022-04-13 10:57 UTC, RakeshUP commented on packages/web-app/src/components/proposalList/index.tsx
> +              title={metadata.title}
The title and proposal summary are not available in the rinkeby subgraph. Once we have proper data from the subgraph, it should work

2022-04-13 11:05 UTC, RakeshUP commented on packages/web-app/src/index.tsx
> +                <ApolloProvider client={client['rinkeby']}>
Yes, for REST API queries, it doesn't matter which client is used as the Coingecko URL is the same, but for subgraph queries, we need to pass the intended network's client to useQuery. 
This rinkeby client is there so we don't need to pass a client for REST queries

2022-04-20 15:05 UTC, RakeshUP commented on packages/web-app/src/services/prices.ts
> +  client: ApolloClient<object>,
Apollo client is imported directly from the @apollo package and not as a hook for which we defined types

2022-04-20 15:05 UTC, RakeshUP commented
Git auto-merging is not working correctly and I'm closing this PR and creating a new one

2022-04-20 15:05 UTC, closed without merging