Feature: wallet base Dao - addresses modal - APP-4
aragon/app-legacy pull request #318
Opened 2022-04-18 10:02 UTC by sepehr2github

## Description

- addresses modal added to go live page for wallet base dao
- edit the voting table in component UI to fix single column view issue

Task: [ID]()

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [x] I have tested my code on the test network.

2022-04-20 09:30 UTC, josemarinas commented on packages/web-app/src/components/whitelistWallets/index.tsx
> +    replace([{address: account}]);
In the designs, when this table is displayed for the first time has 1 empty field, If you delete this empty address It won't match de design anymore

2022-04-20 09:35 UTC, josemarinas commented on packages/web-app/src/pages/createDAO.tsx
> +  whitelistWallets: [{address: 'My Wallet'}],
Same, that in the previous comment, this is necessary to match the figma design

2022-04-20 09:38 UTC, Fabricevladimir requested changes
Thanks for this one! Left a few comments

2022-04-20 09:38 UTC, Fabricevladimir commented on packages/web-app/src/containers/configureCommunity/index.tsx
> +              required: t('errors.emptyDistributionDays') as string,
Sonarcloud complains about the as string cast 😢

2022-04-20 09:38 UTC, Fabricevladimir commented on packages/web-app/src/containers/communityAddressesModal/index.tsx
>            <VotersTable
Can you add a width to this one if possible? When there is only my wallet on the list the table shrinks

2022-04-20 09:38 UTC, Fabricevladimir commented on packages/web-app/src/components/whitelistWallets/row.tsx
>            <Dropdown
I noticed that even with the disabled my wallet row, the dropdown can be triggered and the options are still available. With that we can remove the my wallet option all together. I'm not sure why the button isn't taking the disabled state.

Because of that, we can reset or delete my wallet and still fool the form into thinking it's valid. There is also an issue of the error state staying even when we switch from wallet based to token based dao, but if this dropdown or the options in there can be disabled that issue can't be reproduced.

2022-04-20 09:39 UTC, Fabricevladimir commented
One last thing, could you remove the coming soon text from the Authorized Wallets listItem?

2022-04-20 09:42 UTC, josemarinas reviewed
Thank you, these bugs were pretty annoying, I left you a couple of comments

2022-04-20 09:45 UTC, josemarinas commented on packages/web-app/src/containers/configureCommunity/index.tsx
> +              required: t('errors.emptyDistributionDays') as string,
Yes, but if you don't do this cast then typescript will complain about not doing the cast :smiling_face_with_tear:

2022-04-21 09:21 UTC, WissenIstNacht reviewed
Thanks a lot for the fixes!

I don't have much to add. It would be cool if you could get back to me on the math though :)

2022-04-21 09:21 UTC, WissenIstNacht commented on packages/web-app/src/containers/configureCommunity/index.tsx
> +  const minimumParticipationPercent = useMemo(() => {
Wait, what...? 😅

A few things look very suspicious here. Why is the code doing `100*100`? Why is it rounding something and then dividing again? Why is it ceiling something inside a round?

Is there a formula written down for this somewhere?

2022-04-21 09:21 UTC, WissenIstNacht commented on packages/web-app/src/containers/configureCommunity/index.tsx
> +              required: t('errors.emptyDistributionDays') as string,
Sonarcloud is right. The type cast ist not necessary (search for "required: t(" in this project and you'll find examples without string cast).

I'm pretty sure I've had this problem as well. I can't remember how I solved it, though. :/

2022-04-21 10:02 UTC, sepehr2github commented on packages/web-app/src/containers/configureCommunity/index.tsx
> +  const minimumParticipationPercent = useMemo(() => {
@josemarinas You are the best guy to explain this

2022-04-21 10:51 UTC, josemarinas commented on packages/web-app/src/containers/configureCommunity/index.tsx
> +  const minimumParticipationPercent = useMemo(() => {
Yeah, I'm sure there is a more elegant way of doing this but basically what you want is the rounded  percentage of votes that you will need for example, if the wallet length is 3 and the minimum participation the expected result of this is `66.66%`

So first you compute the number of wallets that are needed to approve the proposals. Using the previous example, the expected result will be `2`, and the code that gives this result is:

```js
          Math.ceil(
            ((minimumParticipation || defaultMinimumParticipation) *
              whitelistWallets.length) /
              100
          )) /
```

Now with this result you want to obtain the `66.67%` previously mentioned. If we call the result obtained in the previous formula `minWalletsApproval` the percentage represented should be computed like this

```js
minWalletsApproval*100/whitelistWallets.length
```
This will give you 66.66666666666... but you are only interested in 2 decimals, so you multiply do this to obtain an integer with the precision you want:
```js
Math.ceil((minWalletsApproval*100/whitelistWallets)*100)
```
And you will obtain `6667` if you divide this by 100 you will obtain `66.67`

As I said, I'm sure there is a simpler and more elegant way of doing this

2022-04-21 13:53 UTC, Fabricevladimir approved these changes
Ready to go!

2022-04-22 06:51 UTC, josemarinas approved these changes
Seems nice to me, I'll have to review the code on the validation and default value in the tables before the create DAO branch is merged. Because it will expect the value to be the actual wallet address and not `My Wallet`

2022-04-22 10:36 UTC, merged