Feature/basic-buttons-DAO-439
aragon/app-legacy pull request #32
Opened 2021-11-09 15:11 UTC by WissenIstNacht

Added buttons according to design system.

2021-11-09 17:33 UTC, Fabricevladimir commented on packages/ui-components/src/components/button/button.tsx
> +  mode: 'primary' | 'secondary' | 'tertiary' | 'ghost';
Can we get some comments on some of these guys? Functionality for example I'd like to know a bit more about at a glance.

2021-11-09 18:23 UTC, Fabricevladimir requested changes

2021-11-09 18:23 UTC, Fabricevladimir commented on packages/ui-components/src/components/button/button.tsx
> +  functionality: 'add' | 'open' | 'normal';
Is it possible to generalize this? I'd like to be able to add whatever icon I want and maybe have the prop determine where to put it. Something like `<Button icon={abc} right/>` or `<Button iconRight={abc}/>`. What do you think?

2021-11-09 18:23 UTC, Fabricevladimir commented on packages/ui-components/src/components/button/button.tsx
> +  disable,
Typo? I think it was expecting `disabled` 😄

2021-11-09 18:23 UTC, Fabricevladimir commented on packages/ui-components/src/components/button/button.tsx
> +  functionality: ButtonProps['functionality'];
Ha! I like this. This is us making TS do the work for a change!

2021-11-09 18:23 UTC, Fabricevladimir commented on packages/ui-components/src/components/button/button.tsx
> +const Content: React.FC<ContentProps> = ({label, functionality}) => {
Hmm this seems like it could have been achieved with TW + SC, especially if we generalize the button to take any icon. Like change the `order` of the flex box items based on whether we want the icon on the right or left.. Thoughts?

2021-11-09 18:23 UTC, Fabricevladimir commented on packages/ui-components/src/components/button/button.tsx
> +  if (functionality === 'add') {
I think this could be simplified to 2 if statements since we're actually returning the JSX.

2021-11-09 18:23 UTC, Fabricevladimir commented on packages/ui-components/src/components/button/button.tsx
> +      <FlexDiv className="flex">
We can remove the `className=flex` since FlexDiv already has `display: flex;` applied

2021-11-09 18:23 UTC, Fabricevladimir commented on packages/ui-components/src/components/button/button.tsx
> +const StyledButton = styled(SizedButton).attrs(({mode}: StyledButtonProps) => {
I like the composition! For whatever reason I keep forgetting you can extend an already defined styled component 😅

2021-11-09 18:23 UTC, Fabricevladimir commented on packages/ui-components/src/components/button/button.tsx
> +  if (mode === 'primary') {
Might consider adding a default so that if the user passes in something random the button is still styled properly. That said, I don't know if the typings will allow them to 🤔

2021-11-09 18:23 UTC, Fabricevladimir commented on packages/ui-components/stories/Button.stories.tsx
> +export const AllProps = Template.bind({});
Do you think we should have the different states of the button as stories or is that too much? I feel like right now, it's a bit of a hassle to go through all the props in Storybooks canvas layout. That said, the controls are laid out well so...

2021-11-10 09:13 UTC, sepehr2github commented on packages/ui-components/stories/Button.stories.tsx
> +    console.log('hi');
Maybe you can use Alert('hi') instead of the console.log

2021-11-10 09:16 UTC, sepehr2github reviewed
Thank you. It looks awesome and you did a great job. I think Fabrice mentioned everything.

2021-11-10 10:26 UTC, WissenIstNacht commented on packages/ui-components/src/components/button/button.tsx
> +  functionality: 'add' | 'open' | 'normal';
Since the buttons were grouped together in the designs, I tried to get them all into one interface. That being said, we absolutely can. And since other buttons depend on this, we probably should.

2021-11-10 10:31 UTC, Fabricevladimir commented on packages/ui-components/src/components/button/button.tsx
> +  functionality: 'add' | 'open' | 'normal';
Yeah I'm guessing this is going to be an iterative process too based on the availability of different types of buttons.

2021-11-10 10:39 UTC, WissenIstNacht commented on packages/ui-components/src/components/button/button.tsx
> +  if (mode === 'primary') {
no, you can't just pass anything. :)

2021-11-10 10:41 UTC, WissenIstNacht commented on packages/ui-components/stories/Button.stories.tsx
> +export const AllProps = Template.bind({});
I've been asking myself the same thing. For the time being I'd say we don't invest time in something that's already there. As you said, the controls already allow to see the props in action. If we want to refine it and add proper docs and stuff we always do that later.

2021-11-10 13:24 UTC, Fabricevladimir commented on packages/ui-components/stories/Button.stories.tsx
> +    console.log('hi');
@sepehr2github Wasn't this supposed to show up in the action tab in storybook?

2021-11-10 14:56 UTC, sepehr2github approved these changes

2021-11-10 16:49 UTC, Fabricevladimir approved these changes

2021-11-10 17:12 UTC, merged