Feature: App 399 - DAO parameter in url
aragon/app-legacy pull request #331
Opened 2022-04-29 11:01 UTC by WissenIstNacht

## Description

This PR introduces dao identifiers in the URL, allowing users to navigate the app for a given DAO address.

Scope of this is to make sure that the app has access to the DAO identifier in the URL and that every component in the app that triggers some navigation includes this DAO parameter.

Note: So far, only hex addresses are covered, DAO names are not part of this PR.

Task: [233](https://aragonassociation.atlassian.net/browse/APP-233?atlOrigin=eyJpIjoiM2M4YTRiMmQ3OWEwNDU1NzlhNmEzMzk4MWIzNzgyNzQiLCJwIjoiaiJ9)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [x] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-05-02 14:12 UTC, Fabricevladimir requested changes
Thanks! Good work. Left a couple comments

2022-05-02 14:12 UTC, Fabricevladimir commented on packages/web-app/src/app.tsx
> +import PrivacyPolicy from 'containers/privacyPolicy';
This one is embeded in the `PrivacyContext.tsx`. I thought it was cleaner this way instead of spamming these menus in  `App.tsx`. What's the reasoning behind bringing it back?

2022-05-02 14:12 UTC, Fabricevladimir commented on packages/web-app/src/app.tsx
> +            <Route path={paths.Dashboard} element={<CommunityPage />} />
Hahaha stubs are overrated and `CommunityPage` was right there. I approve 👍🏾

2022-05-02 14:12 UTC, Fabricevladimir commented on packages/web-app/src/components/navLink/index.tsx
> +    onItemClick?.();
Pretty sweet this conditional calling

2022-05-02 14:12 UTC, Fabricevladimir commented on packages/web-app/src/components/wrappers/sectionWrappers.tsx
> +      <Link to={generatePath(AllTokens, {network, dao})}>
NGL, I'm not a massive fan of generatePath. I might have preferred nesting which would leave you free to navigate without having to do this every time

2022-05-02 14:12 UTC, Fabricevladimir commented on packages/web-app/src/components/navLink/index.tsx
> +        onClick={() => handleOnClick(data.path)}
This doesn't navigate properly. Probably need to add generate path here as well...

2022-05-02 14:30 UTC, WissenIstNacht commented on packages/web-app/src/app.tsx
> +import PrivacyPolicy from 'containers/privacyPolicy';
Merge error. Already updated 👍🏼

2022-05-02 14:35 UTC, WissenIstNacht commented on packages/web-app/src/components/wrappers/sectionWrappers.tsx
> +      <Link to={generatePath(AllTokens, {network, dao})}>
A refactor of the routing is planned for this sprint (or the next, depending how time goes) where I'll go for nested pages. We're kind of working against the library with the way we've set up things right now, so this is badly needed. But I think the path generation will still be needed in some places. Even with nested pages.

2022-05-02 16:01 UTC, RakeshUP approved these changes

2022-05-03 11:27 UTC, sepehr2github approved these changes
Thank Vali. Seems good to me! just need a conflict fixing

2022-05-03 13:53 UTC, Fabricevladimir approved these changes
Good work, looking good! Thanks

2022-05-04 10:50 UTC, merged