Feature: Add DAO card to explorer
aragon/app-legacy pull request #343
Opened 2022-05-06 12:33 UTC by josemarinas

## Description

Add DAO card to the explorer page

Task: [APP-295](https://aragonassociation.atlassian.net/browse/APP-295)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2022-05-10 10:43 UTC, Fabricevladimir requested changes
Good work! Left a couple of comments and suggestions

2022-05-10 10:43 UTC, Fabricevladimir commented on packages/web-app/src/components/daoCard/index.tsx
> +  logo: string;
Can you make logo optional just in case the DAO has no logo?

2022-05-10 10:43 UTC, Fabricevladimir commented on packages/web-app/src/components/daoCard/index.tsx
> +const getDaoType = (daoType?: DaoType) => {
Were you able to take a look at what the query returns for a DAO "type"?

2022-05-10 10:43 UTC, Fabricevladimir commented on packages/web-app/src/components/daoCard/index.tsx
> +  useEffect(() => {
Nothing to change here, but would be nice if this logic could be extracted to the parent component and leave this one as a mere presentation component. But I guess this is going to depend on what the query returns. Thoughts? 🤔

2022-05-10 10:43 UTC, Fabricevladimir commented on packages/web-app/src/components/daoCard/index.tsx
> +          <Avatar mode="circle" size="large" src={props.logo} />
There is a AvatarDao, but it's in need of a refactor. I have done so in my upcoming PR (CardProposal). It also has a fallback for when no logo is present. I think I understand why that `logo` is not optional. Once, the refactor has been merged, I propose we switch this over to using the AvatarDao instead.

2022-05-10 10:43 UTC, Fabricevladimir commented on packages/web-app/src/containers/daoExplorer/daoExplorer.tsx
> +    setDaos([...placeholderDaos]);
I'm assuming we'll actually filter once we're fetching from the subgraph, right?

2022-05-10 10:43 UTC, Fabricevladimir commented on packages/web-app/src/components/daoCard/index.tsx
> +  font-medium text-ui-600 text-sm desktop:text-base flex line-clamp-2 text-left
On Mobile, line clamp should be 3

2022-05-10 10:43 UTC, Fabricevladimir commented on packages/web-app/src/containers/daoExplorer/daoExplorer.tsx
> +          <ButtonGroup
Button group should hug contents and not be full width on mobile.

2022-05-10 10:43 UTC, Fabricevladimir commented on packages/web-app/src/pages/explore.tsx
> +const DaoWrapper = styled.div.attrs({
Can you take a look at the spacing on mobile as well?

2022-05-10 11:05 UTC, josemarinas commented on packages/web-app/src/components/daoCard/index.tsx
> +const getDaoType = (daoType?: DaoType) => {
No, this just me guessing stuff, I tried to see the metadata on subgraph, but it returns a hash and I could not find it on IPFS, so these are the two types of DAO and this should be updated once subgraph returns the metadata

2022-05-10 11:09 UTC, josemarinas commented on packages/web-app/src/components/daoCard/index.tsx
> +  useEffect(() => {
Yes, I assumed it will return the chainID. I believe the computation of the chainName is fine there, yes it introduces a bit of logic into the component but if you move it to the parent component you will have to watch the list of DAOs and iterate over all the list each time the user clicks see more

2022-05-10 11:10 UTC, josemarinas commented on packages/web-app/src/components/daoCard/index.tsx
> +          <Avatar mode="circle" size="large" src={props.logo} />
Sure, if you want we can merge your PR first, and then I'll rebase my code and add the `AvatarDao` component

2022-05-10 11:12 UTC, josemarinas commented on packages/web-app/src/containers/daoExplorer/daoExplorer.tsx
> +    setDaos([...placeholderDaos]);
Yes, for now is just to have the state and show different things depending on which filter you have selected, for example the `my-daos` filter does not show the `Show more` button

2022-05-10 11:13 UTC, josemarinas commented on packages/web-app/src/components/daoCard/index.tsx
> +  font-medium text-ui-600 text-sm desktop:text-base flex line-clamp-2 text-left
Noted, thank you :)

2022-05-10 11:14 UTC, josemarinas commented on packages/web-app/src/containers/daoExplorer/daoExplorer.tsx
> +          <ButtonGroup
Yes, I tried to fix that, but I couldn't find a way for it not growing, I spent a couple of hours and I decided to address it later

2022-05-10 11:15 UTC, josemarinas commented on packages/web-app/src/pages/explore.tsx
> +const DaoWrapper = styled.div.attrs({
Sure :)

2022-05-10 11:15 UTC, josemarinas commented on packages/web-app/src/components/daoCard/index.tsx
> +  logo: string;
Yes, I should make the name mandatory and the logo optional, you are right

2022-05-10 12:04 UTC, Fabricevladimir commented on packages/web-app/src/components/daoCard/index.tsx
> +const getDaoType = (daoType?: DaoType) => {
Fair enough.

2022-05-10 12:04 UTC, Fabricevladimir commented on packages/web-app/src/components/daoCard/index.tsx
> +  useEffect(() => {
Good point.

2022-05-11 08:11 UTC, WissenIstNacht commented on packages/web-app/src/components/daoCard/index.tsx
> +  switch (daoType) {
What happens on `undefined`?

2022-05-11 08:22 UTC, WissenIstNacht requested changes
Thanks, looks good :)

2022-05-11 08:22 UTC, WissenIstNacht commented on packages/web-app/src/components/daoCard/index.tsx
> +      return t('explore.explorer.tokenBased');
Another thing that bugs me here:

Usually, the `t` function is obtained through the `useTranslation` hook. But in this function you use and *imported* `t` function. Does that do the same thing? If you're not 100% certain I would suggest going the safe way and add

````
  const {t} = useTranslation();
````

right at the start of the function.

2022-05-11 08:22 UTC, WissenIstNacht commented on packages/web-app/src/components/daoCard/index.tsx
> +  switch (daoType) {
What happens on `undefined`?

2022-05-11 10:07 UTC, josemarinas commented on packages/web-app/src/components/daoCard/index.tsx
> +      return t('explore.explorer.tokenBased');
Yes, but this is an external function to the render function and hooks can only be used inside the render function. I can include this function inside the render function `DaoCard` and then I can use the `useTranslation` but since this is something computed externally to the render function, for me, it makes sense to have it outside the render.

2022-05-11 10:07 UTC, josemarinas commented on packages/web-app/src/components/daoCard/index.tsx
> +  switch (daoType) {
The only optional value should be the logo because is not enforced in the dao creation, the other ones should be always present, so no default case needed

2022-05-11 12:25 UTC, Fabricevladimir commented on packages/web-app/src/components/daoCard/index.tsx
> +      return t('explore.explorer.tokenBased');
Do you know if this pulls the configs from our instance of i18n that we are exporting from the `i18n.config.ts` in the root of the project? Unless you're absolutely certain, I would feel a bit more confident if we used the `t` function from the export ( `import i18n from '../../i18n.config.ts'`) like so `i18n.t('translationKey')` 😅

2022-05-11 12:30 UTC, Fabricevladimir approved these changes

2022-05-11 12:30 UTC, Fabricevladimir commented on packages/web-app/src/containers/carousel/index.tsx
> +  const {methods, isConnected} = useWallet();
Good catch!

2022-05-11 12:36 UTC, josemarinas commented on packages/web-app/src/components/daoCard/index.tsx
> +      return t('explore.explorer.tokenBased');
I'm not sure, so I'll import it like that, @WissenIstNacht are you ok with this?

2022-05-12 08:33 UTC, WissenIstNacht approved these changes

2022-05-12 09:07 UTC, merged