Feature: Fetch existing token on erc20 Voting DAO creation
aragon/app-legacy pull request #352
Opened 2022-05-12 12:42 UTC by Fabricevladimir

## Description

- Adds the ability to fetch existing token from all supported networks when creating an ERC20 voting DAO
- Fixes uncontrolled component warnings

Task: [APP-380](https://aragonassociation.atlassian.net/browse/APP-380)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.

- [ ] I have tested my code on the test network.

2022-05-12 14:07 UTC, WissenIstNacht requested changes
Thanks a lot. Few details to fix :)

2022-05-12 14:07 UTC, WissenIstNacht commented on packages/web-app/src/context/providers.tsx
> +const getCustomInfuraProvider = (givenChainId?: number) => {
Please you `SupportedNetworkId` type, instead of just numbers. (Also adapt the Props at the top).

2022-05-12 14:07 UTC, WissenIstNacht commented on packages/web-app/src/context/providers.tsx
>    );
Could you update the documentation for this context? (couldn't select the comment itself so I wrote it here)

2022-05-12 14:07 UTC, WissenIstNacht commented on packages/web-app/src/containers/setupCommunity/addExistingToken.tsx
> +            {console.log(tokenName)}
Necessary?

2022-05-12 14:19 UTC, Fabricevladimir commented on packages/web-app/src/containers/setupCommunity/addExistingToken.tsx
> +            {console.log(tokenName)}
Definitely. No doubt about it.

2022-05-12 14:48 UTC, Fabricevladimir commented on packages/web-app/src/context/providers.tsx
>    );
Context isn't being updated with the new changes so the documentation is still correct.

2022-05-12 15:06 UTC, WissenIstNacht approved these changes

2022-05-13 07:19 UTC, josemarinas approved these changes
Good work, thanks :smile:

2022-05-13 07:21 UTC, sepehr2github approved these changes

2022-05-13 09:32 UTC, merged