Feature: APP-21 Wrong Network modal
aragon/app-legacy pull request #356
Opened 2022-05-17 07:07 UTC by sepehr2github

## Description

- UseSwitchNetwork hook added
- Wrong network modal added

Task: [APP-21](https://aragonassociation.atlassian.net/browse/APP-21)

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-05-17 11:04 UTC, josemarinas commented on packages/web-app/src/context/network.tsx
> +                  nativeCurrency: CHAIN_METADATA[networkState].nativeCurrency,
I've been testing this, and once you change the network, I believe the signer does not update properly because the wallet and icon in the top left corner does appear in blank, and you can't make the transaction until you log out and log in again. This seems like a complicated bug, we can try to fix it right now or make a new issue for this

2022-05-17 11:05 UTC, josemarinas commented on packages/web-app/src/hooks/useSwitchNetwork.tsx
> +              method: 'wallet_addEthereumChain',
Why is this code duplicated on the context and on hooks?

2022-05-17 11:06 UTC, josemarinas reviewed
Thank you so much, I left a couple of comments

2022-05-17 14:44 UTC, sepehr2github commented on packages/web-app/src/hooks/useSwitchNetwork.tsx
> +              method: 'wallet_addEthereumChain',
Forgot to remove from context sorry!

2022-05-17 16:09 UTC, WissenIstNacht requested changes
Hey, really cool functionality, thanks :)

Couple of minor comments, but everything works/looks good on my side!

2022-05-17 16:09 UTC, WissenIstNacht commented on packages/web-app/src/context/network.tsx
> +  const switchNetwork = async () => {
Hey Sepehr, could you move this into a separate hook (something like `useWalletNetworkSwitch`)? I might need to modify/move this context a bit in the future. Having this code here could complicate things.

Sorry and thanks :)

2022-05-17 16:09 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useSwitchNetwork.tsx
> +              method: 'wallet_addEthereumChain',
Haha Sepehr, you read my mind :D

Ignore my comment on the context in this case :p

2022-05-17 16:09 UTC, WissenIstNacht commented on packages/web-app/src/containers/networkErrorMenu/index.tsx
> +              network: network,
Small detail here: This will use the more "simple" name, rather than the one we usually use on label. More contretely, it will say "Switch to ethereum", while it would say "Switch to Ethereum Mainnet" if you use the "nicer" name. Not sure what the designs say, but I would go for the second option.

2022-05-17 16:09 UTC, WissenIstNacht commented on packages/web-app/src/containers/networkErrorMenu/index.tsx
> +            {t('alert.wrongNetwork.description')}
The description string here must also be variable (i.e., take the current network label as an argument).

2022-05-18 10:15 UTC, sepehr2github commented on packages/web-app/src/context/network.tsx
> +                  nativeCurrency: CHAIN_METADATA[networkState].nativeCurrency,
Didn't get what you mean! Can you explain a bit?

2022-05-18 12:39 UTC, WissenIstNacht approved these changes

2022-05-18 13:06 UTC, josemarinas approved these changes

2022-05-19 06:34 UTC, merged