Feature: Connect deposit to SDK
aragon/app-legacy pull request #357
Opened 2022-05-17 12:10 UTC by josemarinas

## Description

Connect deposit to SDK, to allow users to make a deposit into the dao account 

Task: [ID]()

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2022-05-23 09:15 UTC, sepehr2github commented on packages/web-app/src/context/deposit.tsx
> +        isOpen={showModal}
Since you added the showModal state here to control the modal view, Please remove isDepositOpen and all It's dependencies from useGlobalModalContext

2022-05-23 09:17 UTC, sepehr2github commented on packages/web-app/src/pages/newDeposit.tsx
> +            <ReviewDeposit />
On review Deposit when the user ignored the reference part, would be nice to provide a better UI instead of a blank card. maybe you need to check with Design people

2022-05-23 09:19 UTC, sepehr2github requested changes
Thanks, Jose, That's the first step for adding deposit flow which is so cool! left a few minor comments!

2022-05-25 08:35 UTC, Fabricevladimir approved these changes
Thanks for this! Once the changes requested by @sepehr2github are addressed, this'll be good to go.

2022-05-25 08:35 UTC, Fabricevladimir commented on packages/web-app/src/context/deposit.tsx
> +    if (!dao) {
It would be very freaky to get to here without a dao 😆 But I'm glad you're checking for that case nonetheless +1

2022-05-25 08:35 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useFinance.tsx
> +    if (daoType === 'wallet-based') {
You know, one option would be to pass in the `daoType` to the `useClient` hook and have it instantiate the client based on that. But I think this check won't be necessary anymore when there's only one client  from the SDK, right?

2022-06-01 10:29 UTC, sepehr2github approved these changes

2022-06-01 10:46 UTC, merged