Feature/icon DAO-446
aragon/app-legacy pull request #36
Opened 2021-11-11 11:17 UTC by sepehr2github

Icons added!

Notes: 
1) We still need to add some defined sizes like (small, medium, etc...).
2) Let me know if there is any problem with Exported Svgs

2021-11-11 14:23 UTC, WissenIstNacht requested changes
Hey there, thanks for the tedious work. I have a few complaints, though 😅 

Basically, I disagree with the nested `components` folder that you have in both the `icons` and `stories` folder.
- For the one in `icons` I don't really see the point. If you ever open the icons folder you probably intend to look at the icons. So IMO there's not much point in hiding them another level further down 😋 
- For the the one in `stories` I see why you did it. However, I would not call this a `components` folder, as it doesn't contain any components, just import/exports. Also, I would not put those files and corresponding folder into `stories` at all.

I think there's a way to solve both issues at once. You could group the items in `icons` into two subfolders: `interface` and `module`. That way, you have (still) have a subfolder in icons. Then you could basically move the `ìnterface-x-list.tsx` files to those subfolders.

Let me know if I missed something :)

2021-11-11 14:23 UTC, WissenIstNacht commented on packages/ui-components/src/components/icons/index.tsx
> +export {IconFavoriteSelected} from './components/icon_favorite_selected';
case typo :) But please change the name of the file to lowercase and _not_ the name of the import to uppercase.

2021-11-12 11:13 UTC, sepehr2github commented on packages/ui-components/src/components/icons/index.tsx
> +export {IconFavoriteSelected} from './components/icon_favorite_selected';
That's wired. I fixed that before on my visual studio but it didn't apply!!!!

2021-11-12 11:14 UTC, Fabricevladimir approved these changes
Looks great, man! Once the changes requested by @WissenIstNacht have been added you can go ahead and merge.

2021-11-12 13:03 UTC, Fabricevladimir approved these changes

2021-11-12 13:48 UTC, WissenIstNacht approved these changes

2021-11-12 13:49 UTC, merged