Feature/app 511 list item address
aragon/app-legacy pull request #369
Opened 2022-05-25 11:26 UTC by WissenIstNacht

## Description

This PR adds the ListItem->Address component to the UI library. 

Task: [511](https://aragonassociation.atlassian.net/browse/APP-511?atlOrigin=eyJpIjoiMjMxNGZkZDJhYmFhNGJjOTkwZWEyZDc1ODE2NGQzZDciLCJwIjoiaiJ9)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [x] I have tested my code on the test network.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.

2022-05-25 11:46 UTC, Fabricevladimir requested changes
Thanks, looking good. Left a single comment

2022-05-25 11:46 UTC, Fabricevladimir commented on packages/ui-components/src/components/listItem/address.tsx
> +const Container = styled.button.attrs(() => {
There is box-shadow and a border (sometimes) on the variant states

2022-05-26 13:27 UTC, RakeshUP approved these changes
Good to go after the minor css changes!

2022-06-06 06:38 UTC, sepehr2github reviewed
Thanks, Vali, Just a tiny thing. The external link button isn't centered. may I ask you to take a look? 

![Screen Shot 2022-06-06 at 11 07 08 AM](https://user-images.githubusercontent.com/46657145/172108751-c10f3c5f-68ab-4c11-8848-bd6bf8c70c88.png)

2022-06-07 11:27 UTC, WissenIstNacht commented
@sepehr2github, just download Firefox and problem solved! 😋

Jokes aside, Chrome seems to need the Container to have `items-center` as well, which I added now. Thanks for catching this! :)

2022-06-07 14:44 UTC, Fabricevladimir approved these changes
Good to go

2022-06-08 11:44 UTC, sepehr2github approved these changes
Thanks, for the change.

2022-06-09 09:20 UTC, merged