Feature/menu buttons dao 442
aragon/app-legacy pull request #37
Opened 2021-11-12 15:34 UTC by WissenIstNacht

This PR:

- Added button with following variations: 
    - No text, just icon
    - Closed menu button (with menu icon)
    - Opened menu button (with cross icon)
    - Small/default sizing
- Fixed some tests
- Modified some svgs to take color and to correct sizing

2021-11-15 09:32 UTC, sepehr2github approved these changes

2021-11-15 09:32 UTC, sepehr2github commented on packages/ui-components/src/components/button/iconButton.tsx
>    return {src: iconSrc, className: 'w-3 h-3'};
Why did you export StyledIcon? So we can use it as the base of the other Icons button?

2021-11-16 09:16 UTC, Fabricevladimir requested changes
Looking good!

2021-11-16 09:16 UTC, Fabricevladimir commented on packages/ui-components/src/components/button/menuButton.tsx
> +        <IconMenu />
Should we also display a close for mobile? Currently we don't actually see this because the bottomsheet covers up the menu, but say a user goes with a 'traditional' mobile that still shows the nav and toggle button, this will only display the open icon.

2021-11-16 09:16 UTC, Fabricevladimir commented on packages/ui-components/src/components/button/menuButton.tsx
> +          <IconClose className="fill-current text-primary-500" />
You can remove the class names I believe because the svgs define fill and should also take the text color of the parent `OpenButton` which I noticed was primary-500 as well

2021-11-16 09:16 UTC, Fabricevladimir commented on packages/ui-components/stories/MenuButton.stories.tsx
> +export const AllProps = Template.bind({});
Can you add a couple stories for the controls, just to be explicit?

2021-11-16 09:16 UTC, Fabricevladimir commented on packages/ui-components/stories/MenuButton.stories.tsx
> +  onClick: () => {
This overrides the default behavior of the action appearing on the action tab on Storybook. Is this intentional?

2021-11-16 09:47 UTC, WissenIstNacht commented on packages/ui-components/src/components/button/menuButton.tsx
> +        <IconMenu />
Had the same thought. AFAIK we don't really have the designs for it yet.

2021-11-16 10:04 UTC, WissenIstNacht commented on packages/ui-components/stories/MenuButton.stories.tsx
> +  onClick: () => {
Sepehr suggested adding something that was more visible/interactive than the logs on the actions tab on a previous PR. I founod the idea good, so I went ahead and did it.

2021-11-16 10:11 UTC, WissenIstNacht commented on packages/ui-components/src/components/button/iconButton.tsx
>    return {src: iconSrc, className: 'w-3 h-3'};
I was probably using it at some point but ultimately decided against it. Must have forgotten to remove the export. Thanks for pointing it out 👍🏼

2021-11-16 12:43 UTC, Fabricevladimir approved these changes

2021-11-16 12:44 UTC, merged