Feature: APP-544
aragon/app-legacy pull request #374
Opened 2022-06-03 09:41 UTC by sepehr2github

## Description

- Implement the Dao header in ui component

Task: [APP-544](https://aragonassociation.atlassian.net/browse/544)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-06-03 15:09 UTC, Fabricevladimir requested changes

2022-06-03 15:09 UTC, Fabricevladimir commented on packages/ui-components/src/components/headers/headerDao.tsx
> +              label={'ReadMore'}
This should be translated. Also, do you know what this link is supposed to do? Does it show a dropdown or link to a different page? Finally, do we have a specific length before the text truncates and we have to show the `Read More`?

2022-06-03 15:09 UTC, Fabricevladimir commented on packages/ui-components/src/components/headers/headerDao.tsx
> +              iconRight={<IconChevronDown />}
This seems to be the wrong icon. The designs show a different arrow.

2022-06-03 15:09 UTC, Fabricevladimir commented on packages/ui-components/src/components/headers/headerDao.tsx
> +    'w-full bg-white rounded-xl p-3 desktop:p-6 border border-ui-100 space-y-3',
The padding for mobile is 16px and 24px for tablet mode

2022-06-03 15:09 UTC, Fabricevladimir commented on packages/ui-components/src/components/headers/headerDao.tsx
> +            size="hero"
On tablet mode the Avatar should be size big and align to the top

2022-06-03 15:09 UTC, Fabricevladimir commented on packages/ui-components/src/components/headers/headerDao.tsx
> +            <Dropdown
Is it possible to specify the width of the dropdown content to be 320px?

2022-06-03 15:09 UTC, Fabricevladimir commented on packages/ui-components/src/components/headers/headerDao.tsx
> +            <ButtonIcon
ButtonIcon should come after the links dropdown.

2022-06-03 15:09 UTC, Fabricevladimir commented on packages/ui-components/src/components/progress/linear.tsx
> +  const val = (value as number) / (max as number);
Thanks for fixing this

2022-06-03 15:09 UTC, Fabricevladimir commented on packages/ui-components/src/components/headers/headerDao.tsx
> +                    window.open(href, '_blank');
It might be best to make the callback optional in the dropdown because ListItemLink navigates on its own. It also contains an `external` boolean property that will open in a new tab.

2022-06-06 07:49 UTC, sepehr2github commented on packages/ui-components/src/components/headers/headerDao.tsx
> +                    window.open(href, '_blank');
Issue fixed! For links, they should be with HTTPS. What do you mean by making it optional?

2022-06-06 10:33 UTC, RakeshUP approved these changes
Looks good. But in general, this header DAO component seems to be tightly tied up with aragon app like having app.aragon.org URL. Also translated texts are a gray area in the ui-components package. A few components with English text have been moved to web-app package

2022-06-06 12:47 UTC, Fabricevladimir approved these changes
Thanks

2022-06-06 12:51 UTC, merged