Feature: App-512 Create address list
aragon/app-legacy pull request #386
Opened 2022-06-09 11:07 UTC by WissenIstNacht

## Description

### Goal

This PR implements the section of a DAO’s Dashboard that shows a list of Dao member’s.

### Note

Since no “live” data is available, list will currently be populated with mock data.

Task: [512](https://aragonassociation.atlassian.net/browse/APP-512?atlOrigin=eyJpIjoiNTQyNjA1ZGVmMzZlNGZhZWE0OTlmMDg5NTNkOGI2NzEiLCJwIjoiaiJ9)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-06-09 11:41 UTC, Fabricevladimir requested changes
Thanks. Left a couple of comments; let me know what you think.

2022-06-09 11:41 UTC, Fabricevladimir commented on packages/web-app/src/pages/dashboard.tsx
> +const HeaderWrapper = styled.div.attrs({
Is this necessary? The header should be the same sized as the two "columns" of content.

2022-06-09 11:41 UTC, Fabricevladimir commented on packages/web-app/src/pages/dashboard.tsx
> +const LeftContent = styled.div.attrs({
Left and right content aren't constant. The widths change based on whether there are empty states present. By wrapping the snapshots with the divs, we won't be able to change the widths when the snapshots are empty because the dashboard itself isn't aware of that.

2022-06-09 11:41 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useDaoMembers.tsx
> +  'beer.eth',
Oh dear!

2022-06-09 11:43 UTC, Fabricevladimir commented
Also, please take a look at the security hotspot that SonarCloud flagged.

2022-06-09 14:03 UTC, WissenIstNacht commented on packages/web-app/src/pages/dashboard.tsx
> +const HeaderWrapper = styled.div.attrs({
Thanks, I must have accidentally removed this when cleaning up. But yes, changing this is necessary as mobile layout was wrong (didn't fill the screen).

2022-06-09 14:05 UTC, WissenIstNacht commented on packages/web-app/src/pages/dashboard.tsx
> +const LeftContent = styled.div.attrs({
Sorry, completely forgot the empty states...

2022-06-09 14:06 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useDaoMembers.tsx
> +  'beer.eth',
Oh beer!* 😋

2022-06-13 10:01 UTC, Fabricevladimir approved these changes
Thanks, Vali. The only thing I noticed is that when membership snapshot is horizontal, designs seem to limit the number of wallets to 6, with each column having 3 wallets each

2022-06-13 10:21 UTC, WissenIstNacht commented
Hey @Fabricevladimir the acceptance criteria say 3 wallet, that's why you don't see 6. I've brought this up in the ticket. In the meantime I'm leaving it as is.

2022-06-14 08:36 UTC, sepehr2github approved these changes
Thank you, Vali. good to go!

2022-06-14 08:38 UTC, merged