fix fluid type config & font weight
aragon/app-legacy pull request #408
Opened 2022-06-26 16:42 UTC by sepehr2github

## Description

- Fix fluid type configuration
- Font weight 300,400,600 added
- Fluid font was added to explore the page

Task: [ID]()

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-06-28 06:19 UTC, WissenIstNacht reviewed
Hey Sepehr, thanks a lot for fixing that stop. Must have taken a while to find the issue with the prefix...

I left a couple of comments. They don't necessarily need changing, I'm just curious why you made those changes.

2022-06-28 06:19 UTC, WissenIstNacht commented on packages/ui-components/tailwind.config.js
> +        prefix: 'ft-',
oh man, what a silly bug...

2022-06-28 06:19 UTC, WissenIstNacht commented on packages/ui-components/tailwind.config.js
> +        '6xl': [7, 1.2],
Are you sure this is needed? The typography only shows up to 5xl. Also you're never actually using this in the code I think.

2022-06-28 06:19 UTC, WissenIstNacht commented on packages/ui-components/src/components/alerts/alertCard.tsx
> +  className: 'text-ui-600 ft-text-sm',
Why only change the helptext but not the title?

2022-06-28 06:19 UTC, WissenIstNacht commented on packages/web-app/index.html
> +      href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;600;700&family=Syne:wght@700&display=swap"
Why re-introduce the other font-weights again? Are they now needed somewhere?

2022-06-28 06:19 UTC, WissenIstNacht commented on packages/ui-components/src/components/alerts/alertBanner.tsx
> +  className: `ft-text-xs py-0.5 px-2 text-center font-bold ${styles[mode]}`,
Hey, I stumbled upon another issue here regarding the font thinkness (I think I caused this, sorry). Don't worry about it for now, let's discuss in the next daily. I think it's worth opening another bug ticket for it.

2022-06-28 13:35 UTC, Fabricevladimir commented on packages/ui-components/src/components/alerts/alertBanner.tsx
> +  className: `ft-text-xs py-0.5 px-2 text-center font-bold ${styles[mode]}`,
Yeah something is up with the thickness

2022-06-28 13:36 UTC, Fabricevladimir approved these changes
Thanks, you can merge after addressing the other comments. Small fix generating lots of work 😄

2022-06-28 19:59 UTC, sepehr2github commented on packages/ui-components/tailwind.config.js
> +        '6xl': [7, 1.2],
Thanks for mentioning this one! After a quick sync with Selim, I decided to remove this one.

2022-06-28 20:00 UTC, sepehr2github commented on packages/ui-components/src/components/alerts/alertCard.tsx
> +  className: 'text-ui-600 ft-text-sm',
added fluid font base to Title

2022-06-28 20:02 UTC, sepehr2github commented on packages/web-app/index.html
> +      href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;600;700&family=Syne:wght@700&display=swap"
Yes, According to our discussion with Selim we decided to add for now and later do the refactor for the other parts of the application!

2022-06-28 20:03 UTC, sepehr2github commented on packages/ui-components/src/components/alerts/alertBanner.tsx
> +  className: `ft-text-xs py-0.5 px-2 text-center font-bold ${styles[mode]}`,
We postponed this topic until the MVP review by UX people!

2022-06-29 08:12 UTC, WissenIstNacht commented on packages/ui-components/src/components/alerts/alertBanner.tsx
> +  className: `ft-text-xs py-0.5 px-2 text-center font-bold ${styles[mode]}`,
I know what the issue is. Like with this PR, it's just potentially a of small changes. So yeah, let's not think about it right now 👍🏼

2022-06-29 08:18 UTC, WissenIstNacht commented on packages/web-app/index.html
> +      href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;600;700&family=Syne:wght@700&display=swap"
What do you mean add now and refactor later...? The design system only specifies two font weights, 500 and 700. If the font weights 300, 400 and 600 are not used right now, please remove them.

2022-06-29 09:01 UTC, WissenIstNacht requested changes

2022-06-29 09:01 UTC, WissenIstNacht commented on packages/web-app/index.html
> +      href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;600;700&family=Syne:wght@700&display=swap"
So I've checked: The only fonts that are needed are 500 and 700. Please remove the others.

2022-06-29 09:19 UTC, sepehr2github commented on packages/web-app/index.html
> +      href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;600;700&family=Syne:wght@700&display=swap"
I misunderstood what Selim told me

2022-06-29 09:23 UTC, WissenIstNacht approved these changes

2022-06-29 09:47 UTC, merged