Feature: Community Page added APP-663
aragon/app-legacy pull request #431
Opened 2022-07-18 19:50 UTC by sepehr2github

## Description

- page header component added
- Community page added with mock data

Task: [APP-663](https://aragonassociation.atlassian.net/browse/APP-663)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2022-07-19 10:13 UTC, carlosgj94 requested changes
Pool ownership not displaying correctly:
<img width="201" alt="Screenshot 2022-07-19 at 12 11 03" src="https://user-images.githubusercontent.com/4912635/179726476-71e81174-be93-48d8-945b-09bc8eebcb6d.png">
Also, ens pfp not being displayed properly:
<img width="315" alt="Screenshot 2022-07-19 at 12 13 04" src="https://user-images.githubusercontent.com/4912635/179726798-c7889c68-c85b-4309-a4f1-620b26361943.png">

2022-07-19 10:15 UTC, carlosgj94 commented
Also, I don't think the order is working for me (token based in this example):
<img width="318" alt="Screenshot 2022-07-19 at 12 14 22" src="https://user-images.githubusercontent.com/4912635/179727139-722e61a0-1f46-469e-a87e-f934e3a277a1.png">

2022-07-19 10:25 UTC, sepehr2github commented
Thanks, for the review! Forgot to mention, fixing the member item card will be tackle on on next pr, but if you want I can add those changes here @carlosgj94

2022-07-19 10:28 UTC, carlosgj94 commented
I would suggest doing it here as the ticket defined.
Shouldn't be too hard of a fix.
We still have two days for the demo, let's do it!

2022-07-19 10:57 UTC, Fabricevladimir requested changes
Thanks man! Left a few comments

2022-07-19 10:57 UTC, Fabricevladimir commented on packages/ui-components/__tests__/illuObject.test.tsx
> +    return screen;
Ha! I skipped that test on both of my PRs meaning to comeback and figure out just what's wrong

2022-07-19 10:57 UTC, Fabricevladimir commented on packages/ui-components/src/components/headers/headerPage.tsx
> +        <ButtonText label={buttonLabel} iconLeft={<IconAdd />} size="large" />
So it looks like this thing can have multiple buttons instead of just one. It's not really communicated in the component itself, but it shows up on the Community->token-based design [here](https://www.figma.com/file/jPFyviKllHXjsOYJPxvpYZ/Community?node-id=840%3A6826). I suggest a quick sync/thread with Selim.

2022-07-19 10:57 UTC, Fabricevladimir commented on packages/web-app/src/pages/community.tsx
> +  const {data: whitelist, isLoading: whiteListLoading} = useDaoWhitelist(dao);
I'm guessing there is currently no way to differentiate and use the appropriate hook? Not a big performance issue for now but something we should definitely look into in the future.

2022-07-19 10:57 UTC, Fabricevladimir commented on packages/web-app/src/pages/community.tsx
> +      <SearchInput placeholder={'Type to search ...'} />
There's an `AlertInline` component detailing the requirements for being a member for the token-based DAOs

2022-07-19 10:57 UTC, Fabricevladimir commented on packages/web-app/src/pages/community.tsx
> +      <HeaderPage
Can you remove the margin on the mobile view? Might have to give it negative margin even 🤔

2022-07-19 10:57 UTC, Fabricevladimir commented on packages/web-app/src/containers/membershipSnapshot/index.tsx
>      data: {daoMembers, token},
Can you double check that the token is coming in? It's neither being displayed nor calculated properly for whatever reason.

2022-07-19 10:57 UTC, Fabricevladimir commented on packages/web-app/src/components/membersList/index.tsx
> +    else window.open(baseUrl + '/enslookup-search?search=' + address, '_blank');
Aha +1

2022-07-21 08:47 UTC, carlosgj94 approved these changes
lgtm!

2022-07-21 09:20 UTC, RakeshUP approved these changes
LGTM. 

The window.open URLs have an extra `/` after the domain like `https://rinkeby.etherscan.io//enslookup-search?search=cool.eth`. Its not causing any problems though

2022-07-21 09:23 UTC, Fabricevladimir approved these changes
Sweet! Thanks

2022-07-21 09:29 UTC, merged