Feature: Token minting action in proposal creation flow
aragon/app-legacy pull request #435
Opened 2022-07-20 12:10 UTC by RakeshUP

## Description

Task: [APP-75](https://aragonassociation.atlassian.net/browse/APP-75)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-07-21 09:49 UTC, carlosgj94 commented
Could you add in the backlog a card for this? -> 
"Percentage and the summary at the bottom of the card are hardcoded. We need the existing data in DAO to calculate the summary"

It should be under the Epic APP-704

2022-07-21 10:21 UTC, WissenIstNacht requested changes
Thanks a lot for that huge pile of work. There's a couple things that (at least for me) don't quite work. Could you have a look at them?

2022-07-21 10:21 UTC, WissenIstNacht commented on packages/web-app/src/containers/actionBuilder/mintTokens/index.tsx
> +              accept="text/csv"
Not sure if this is a FF or a macOS thing (or if it's just me haha), but "text" doesn't allow `.txt` files (they're unselectable in the file explorer dialogue).

2022-07-21 10:21 UTC, WissenIstNacht commented on packages/web-app/src/containers/actionBuilder/mintTokens/index.tsx
> +            append({address: tuple[0], amount: tuple[1]});
For me, somehow, a field gets added, but the inputs are not populated with addresses or amount.

2022-07-21 10:21 UTC, WissenIstNacht commented on packages/web-app/src/containers/actionBuilder/mintTokens/index.tsx
> +      removeActionCallback={() => removeAction(index)}
Reset action?

2022-07-21 10:46 UTC, RakeshUP commented on packages/web-app/src/containers/actionBuilder/mintTokens/index.tsx
> +              accept="text/csv"
Changed it now to allow .csv and .txt

2022-07-21 10:48 UTC, RakeshUP commented on packages/web-app/src/containers/actionBuilder/mintTokens/index.tsx
> +            append({address: tuple[0], amount: tuple[1]});
I had skipped the first line on the file assuming it would be the CSV Header. Now I've changed that. 

The new logic might not be totally correct, but at least that's what our template does(can be downloaded by clicking on the link on the method description).

2022-07-22 09:14 UTC, Fabricevladimir commented on packages/web-app/src/components/accordionMethod/index.tsx
> +                <Popover
We've a proper dropdown now lol

2022-07-22 09:29 UTC, Fabricevladimir reviewed
Nice work! Left a few comments

2022-07-22 09:29 UTC, Fabricevladimir commented on packages/web-app/src/containers/actionBuilder/mintTokens/addressTokenRow.tsx
> +export const AddressAndTokenRow: React.FC<AddressAndTokenRowProps> = ({
I wonder if we couldn't reuse the AddWallet component here. 🤔

2022-07-22 09:29 UTC, Fabricevladimir commented on packages/web-app/src/containers/actionBuilder/mintTokens/index.tsx
> +      reader.onload = () => {
Not exactly sure why, but when I upload a csv with multiple rows, the data gets parsed properly, but the form adds an empty Address/Token row both above and below the csv filled rows.

2022-07-22 09:29 UTC, Fabricevladimir commented on packages/web-app/src/containers/configureActions/index.tsx
> +            <div className="flex flex-col items-center p-6 text-center bg-ui-0 rounded-xl">
Can you add a TODO here or a task on the backlog to replace this with a refactored StateEmpty component? I ran into the same issue with the voting terminal and created a [ticket](https://aragonassociation.atlassian.net/browse/APP-734) to refactor StateEmpty to also include Illu-object as base.

2022-07-22 09:45 UTC, RakeshUP commented on packages/web-app/src/containers/actionBuilder/mintTokens/addressTokenRow.tsx
> +export const AddressAndTokenRow: React.FC<AddressAndTokenRowProps> = ({
The AddWallet component is a table-like structure with a header and footer. We could maybe use the `WalletRow` component, but again the token distribution calculation part will differ. So most of the code was copied over to `AddressTokenRow`

2022-07-22 09:47 UTC, Fabricevladimir commented on packages/web-app/src/containers/actionBuilder/mintTokens/addressTokenRow.tsx
> +export const AddressAndTokenRow: React.FC<AddressAndTokenRowProps> = ({
Makes sense 👍🏾

2022-07-22 09:50 UTC, WissenIstNacht commented on packages/web-app/src/containers/actionBuilder/mintTokens/index.tsx
> +            append({address: tuple[0], amount: tuple[1]});
I totally missed the template tbh. And so my test file didn't actually contain a header. So yeah, that explains a few things.

2022-07-22 09:55 UTC, WissenIstNacht approved these changes
Thanks for the changes. As you and Fabrice already noticed, there's still a couple of issues with the CSV upload logic (in particular the addition of empty fields). I'm going approve this for now and leave it up to you/Fabrice to decide if and when to fix the CSV stuff.

2022-07-22 12:35 UTC, RakeshUP commented on packages/web-app/src/containers/actionBuilder/mintTokens/index.tsx
> +      reader.onload = () => {
I think the csv file had empty lines that might have caused this. I've added a check for the same. 

Also, an empty row is created when the action is added to the page, and this stays empty when you upload a csv. form validation to be done that will take care of empty rows before submission.

2022-07-22 13:33 UTC, Fabricevladimir approved these changes
Thanks for the fixes

2022-07-22 13:35 UTC, Fabricevladimir commented on packages/web-app/src/containers/actionBuilder/mintTokens/index.tsx
> +      reader.onload = () => {
Sweet. I noticed that all addresses can be removed. Can you have a quick sync with Selim to make sure whether there's an empty state for this or if that one address has stay even if empty? In the meantime, up to you whether you want to include any changes he suggests from the result of your conversation in this PR or go ahead and merge and create a new ticket if necessary

2022-07-22 13:52 UTC, merged