Feature: Add authorized wallets action
aragon/app-legacy pull request #443
Opened 2022-07-22 20:29 UTC by Fabricevladimir

## Description

 - adds the add authorized wallets action to the proposal configure actions page
 - validates the individual entries for proper address and uniqueness of address
 - refactored `AccordionMethod` component to take `ListItemProps `instead of hard-coded values because some methods, this one included do not support a duplication option

Note: Full method validation will be handled in upcoming Remove Wallets Action PR

Task: [APP-562](https://aragonassociation.atlassian.net/browse/APP-562)

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2022-07-25 10:43 UTC, WissenIstNacht commented on packages/web-app/src/containers/actionBuilder/addAddresses/index.tsx
> +        handleRowReset(index);
I think you're referencing the wrong index here.

In the application, the following can be observed: 
- Add the add wallet action 
- Add a couple of wallets
- Reset any of the wallet rows. It will always only reset the first row.
(If you add another action it will obviously do the same for the 2nd, 3rd, etc.)

2022-07-25 10:47 UTC, WissenIstNacht requested changes
Hey man, thanks for that feature!

Aside from the resetting isssue mentioned above, there's also an issue with form validation. Namely, with duplicate addresses. Basically, I'm being told that pretty much any address I enter after the first in a given "Add Wallets" action is a duplicate :(

2022-07-25 11:18 UTC, sepehr2github reviewed
Hey, Thanks for the PR. Found a few points
1) The title is passing space as an acceptable title
2) When I entered an address, then added another one as a duplicate address. when I reset the second field the error didn't gone!

2022-07-25 11:56 UTC, Fabricevladimir commented on packages/web-app/src/containers/actionBuilder/addAddresses/index.tsx
> +        handleRowReset(index);
Index is the root of all evil. Thanks for catching that.

2022-07-25 13:03 UTC, Fabricevladimir commented
> 1. The title is passing space as an acceptable title

For the title, I'll take care of it in the PR for remove since that task also includes full screen validation. It should be just trimming the input field I think.

2022-07-25 19:31 UTC, WissenIstNacht approved these changes
Thanks a lot for the changes, seem to be working fine <3

2022-07-26 11:14 UTC, sepehr2github approved these changes
Thanks for the changes, Seems good to me :)

2022-07-26 11:20 UTC, merged