Feature: App-739 Remove Action
aragon/app-legacy pull request #444
Opened 2022-07-25 19:10 UTC by Fabricevladimir

## Description

- adds remove authorized wallets action to the proposal flow
- adds basic screen validation to Configure Actions screen
- fixes ability to continue with all whitespace proposal title & summary

**Note:** Allowing empty fields to go through as valid in order to mirror create dao user experience. Idea is to filter the list before submitting to SDK anyway. 

Also, reviewers, because #443 isn't merged yet and I needed a few components from that task, I had to merge the feature branch into this current one 😢 

Task: [APP-739](https://aragonassociation.atlassian.net/browse/APP-739)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2022-07-29 09:30 UTC, WissenIstNacht requested changes
Thanks man, lots of good stuff.

2022-07-29 09:30 UTC, WissenIstNacht commented on packages/web-app/src/pages/newProposal.tsx
> +  console.log(errors, dirtyFields);
remove?

2022-07-29 09:30 UTC, WissenIstNacht commented on packages/web-app/src/pages/newProposal.tsx
> +              isNextButtonDisabled={!actionsAreValid(errors)}
Thanks for improving this. However, I think it's still not quite correct. You can continue with empty but "undirtied" fields. I.e., when you add a fresh action.

2022-07-29 09:30 UTC, WissenIstNacht commented on packages/web-app/src/containers/manageWalletsModal/index.tsx
> +  const handleSelectAll = () => {
FYI: Assume you have n addresses total. You search `0xa`, reducing it to a subset of size k (<n). If you then apply `select all` you will end up selecting n addresses. I would expect to only select the k addresses returned by the search.

Not sure what the right implementation is. Up to you to change/leave it.

2022-07-29 09:30 UTC, WissenIstNacht commented on packages/web-app/src/containers/manageWalletsModal/index.tsx
> +type SelectableWallets = Record<string, boolean>;
I don't want to change your style, so don't take this too seriously, but: This is really what a set does. In other words, the boolean assignment is kinda redundant, as the presence of the address in a set already singals that. :)

2022-07-29 09:30 UTC, WissenIstNacht commented on packages/web-app/src/containers/manageWalletsModal/index.tsx
>      setSelectedWallets(tempSelectedWallets);
When re-setting state based on previous state the correct approach is to do `setState(callBackThatTransformsPreviousToNextState)`. In this case: `setSelectedWallets((previous) => {const temp = {...previous}; // etc...}`

2022-07-29 09:30 UTC, WissenIstNacht commented on packages/web-app/src/containers/actionBuilder/addAddresses/emptyState.tsx
> +// This needs to be removed when the empty state is implemented
Well, ackchually...

2022-07-29 09:39 UTC, Fabricevladimir commented on packages/web-app/src/pages/newProposal.tsx
> +              isNextButtonDisabled={!actionsAreValid(errors)}
Crap. I removed required validation actually to match the create DAO experience. The only issue is that it's the metadata resources & links not the wallets that don't take empty fields into account 🤦🏾‍♂️

2022-07-29 09:44 UTC, Fabricevladimir commented on packages/web-app/src/containers/manageWalletsModal/index.tsx
> +  const handleSelectAll = () => {
I'm tempted to create a refactor ticket for this. I adapted the modal to my needs, but I didn't exactly do a deep dive into the existing logic. In fact, even lifting the state might be an improvement.

2022-07-29 09:46 UTC, Fabricevladimir commented on packages/web-app/src/containers/manageWalletsModal/index.tsx
> +type SelectableWallets = Record<string, boolean>;
Merely aliased the type, this was already built.

2022-07-29 09:51 UTC, Fabricevladimir commented on packages/web-app/src/containers/manageWalletsModal/index.tsx
>      setSelectedWallets(tempSelectedWallets);
I didn't catch this, thanks

2022-07-29 09:53 UTC, Fabricevladimir commented on packages/web-app/src/containers/actionBuilder/addAddresses/emptyState.tsx
> +// This needs to be removed when the empty state is implemented
Yes, but it only supports IllustrationHuman as the main illustration. I opened a ticket for a refactor/extension for it.

2022-07-29 16:31 UTC, WissenIstNacht approved these changes
Yup, thanks for the changes 👍🏼

2022-08-01 05:07 UTC, RakeshUP approved these changes

2022-08-01 05:07 UTC, RakeshUP commented on packages/web-app/src/containers/manageWalletsModal/index.tsx
> +  // @RakeshUp considering the initialSelection state, is it
we can remove resetOnClose if the parent component is going to handle transitory state

2022-08-01 12:14 UTC, merged