Feat/ New Token Minting Proposal page and fixes
aragon/app-legacy pull request #450
Opened 2022-08-02 10:13 UTC by RakeshUP

## Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2022-08-03 12:36 UTC, Fabricevladimir requested changes
Thanks! Good work. I do have one more ask though. 😅 Can you connect the `Mint tokens` button on the membership snapshot of the Dashboard to this flow as well if it's not too much of a hassle?

2022-08-03 12:36 UTC, Fabricevladimir commented on packages/web-app/src/app.tsx
> +const NewMintTokenProposalPage = lazy(() => import('pages/newMintToken'));
Quite a mouthful that! 😄

2022-08-03 12:36 UTC, Fabricevladimir commented on packages/web-app/src/app.tsx
> +                path="community/new-mint-token"
Minor and opinion-based, but I think I might have gone with "community/mint-tokens" instead despite that breaking the previously established pattern of "new-[pattern]" if only because it might be more human readable. Feel free to ignore if you disagree.

2022-08-03 12:36 UTC, Fabricevladimir commented on packages/web-app/src/pages/newMintToken.tsx
> +          navLabel={t('newProposal.title')}
Minor string error. This should be "Add Member" instead of "New Proposal" per the designs

2022-08-03 12:36 UTC, Fabricevladimir commented on packages/web-app/src/containers/navbar/index.tsx
> +    processLabel: i18n.t('newProposal.title'),
This should be "Add Member" apparently as well.

2022-08-03 13:30 UTC, WissenIstNacht commented on packages/web-app/src/pages/newMintToken.tsx
> +        <AddActionMenu actions={actions} />
This is not needed here right?

2022-08-03 13:41 UTC, WissenIstNacht requested changes
Thanks, just one thing from my side.

2022-08-03 13:41 UTC, WissenIstNacht commented on packages/web-app/src/pages/newMintToken.tsx
> +        <AddActionMenu actions={actions} />
This is not needed here right?

2022-08-03 18:13 UTC, WissenIstNacht approved these changes

2022-08-04 10:00 UTC, Fabricevladimir approved these changes
Good to go!

2022-08-04 10:17 UTC, merged