Fix: APP-760 Review Proposal - Voting details
aragon/app-legacy pull request #451
Opened 2022-08-02 16:02 UTC by Fabricevladimir

## Description
- wires up proposal details to voting terminal on Proposal Review screen

Task: [APP-760](https://aragonassociation.atlassian.net/browse/APP-760)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2022-08-03 15:43 UTC, WissenIstNacht requested changes
Thanks man. Unfortunately the browser gods are not on your side today...

2022-08-03 15:43 UTC, WissenIstNacht commented on packages/web-app/src/containers/votingTerminal/index.tsx
> +  console.log('isTokenBased', isTokenBased);
?

2022-08-03 15:43 UTC, WissenIstNacht commented on packages/web-app/src/containers/reviewProposal/index.tsx
> +        KNOWN_FORMATS.proposals
When I reach the review page I get: `Uncaught RangeError: Invalid time value`. Chrome is fine, it only happens on Firefox.

2022-08-04 06:45 UTC, sepehr2github commented on packages/web-app/src/utils/date.ts
> +  proposals: 'yyyy/MM/dd hh:mm a',
I would suggest to follow a same date pattern for proposal setting date input and the date we show on review proposal page

2022-08-04 06:47 UTC, sepehr2github approved these changes
Thanks Fabrice, Once you addressed Vali's Comments. You're good to go!

2022-08-04 08:59 UTC, Fabricevladimir commented on packages/web-app/src/utils/date.ts
> +  proposals: 'yyyy/MM/dd hh:mm a',
I know what you mean. Designs, designs

2022-08-04 09:57 UTC, Fabricevladimir commented on packages/web-app/src/containers/reviewProposal/index.tsx
> +        KNOWN_FORMATS.proposals
Actually, this is quite easy to resolve: don't use Firefox 😆 Jk. Thanks for catching that.

2022-08-06 10:20 UTC, WissenIstNacht approved these changes
Not sure what it is you did, but it worked! 🚀

2022-08-08 10:04 UTC, merged