App 710 minting summary
aragon/app-legacy pull request #452
Opened 2022-08-03 10:24 UTC by WissenIstNacht

## Description

On the token minting action of proposal, adds the necessary logic to display:
- count of additional tokens after the mint
- count of additional token holders after the mint
- count of new total token supply after the mint

It does NOT include the count of new total token after the mint, as the necessary currently does not exist on testnets.

Task: [710](https://aragonassociation.atlassian.net/browse/APP-710)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2022-08-04 06:54 UTC, sepehr2github commented on packages/web-app/src/containers/actionBuilder/mintTokens/index.tsx
> +import {useDaoToken} from 'hooks/useDAoToken';
Small Spelling
```suggestion
import {useDaoToken} from 'hooks/useDaoToken';
```

2022-08-04 07:02 UTC, sepehr2github commented on packages/web-app/src/containers/actionBuilder/mintTokens/index.tsx
> +        newTokensCount += parseInt(m.amount);
amount is BigInt, You need to calculate decimals first then add the new amount to corresponding number!

2022-08-04 07:06 UTC, sepehr2github commented on packages/web-app/src/containers/actionBuilder/mintTokens/index.tsx
> +          setNewTokenHolders(prev => {
When I entered my wallet address, It added +1 to new holders. but then when removed the address the calculation didn't change!

2022-08-04 07:09 UTC, sepehr2github commented on packages/web-app/src/containers/actionBuilder/mintTokens/index.tsx
> +                {totalTokens.toString()} {daoToken.symbol}
![Screen Shot 2022-08-04 at 11 37 50 AM](https://user-images.githubusercontent.com/46657145/182785467-28e1d535-af55-4e05-ad6d-fd28111d99bc.png)

When you go to the next page and then come back the total Token will be reset!

2022-08-04 07:10 UTC, sepehr2github requested changes
Thanks, Vali. Seems good, left a few comments.

Question: the token minting form validations weren't part of the ticket, right? If yes, do we have any tickets regarding the corresponding topic?

2022-08-08 06:35 UTC, RakeshUP approved these changes

2022-08-08 07:51 UTC, sepehr2github approved these changes
Thanks for the addressing comments, Just 1 small point to remind for later. Once the user changes the token amount, the address should be required! We can fix this later once we want to add the validations.
![Screen Shot 2022-08-08 at 12 14 42 PM](https://user-images.githubusercontent.com/46657145/183367442-3b2a4f02-145e-4a85-8787-760ea9416d44.png)

2022-08-08 08:50 UTC, merged