Feature: APP-799 Add withdraw executer widget
aragon/app-legacy pull request #454
Opened 2022-08-03 14:01 UTC by sepehr2github

## Description

- Executor widget added to review proposal for withdraw action

Task: [APP-799](https://aragonassociation.atlassian.net/browse/APP-799)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-08-04 06:12 UTC, RakeshUP approved these changes
The new execution widget looks very good! But the app crashes when using the New Withdraw flow on the Finance page. Could you look into that?

2022-08-04 07:43 UTC, sepehr2github commented
> The new execution widget looks very good! But the app crashes when using the New Withdraw flow on the Finance page. Could you look into that?

Thanks, for mentioning it, Issue addressed!

2022-08-04 10:14 UTC, WissenIstNacht requested changes
Thanks a lot, the widget indeed looks sweet! I left a quick refactor request, then it should be good to go!

2022-08-04 10:14 UTC, WissenIstNacht commented on packages/web-app/src/components/reviewExecution/index.tsx
> +  const RenderActions = useCallback(
A function that returns components? That's just another component! :)

I think I can understand why you did this (easier not having to pass down variables as props maybe). But I would really define `RenderActions` as a normal component outside of `ReviewExecution`. This also takes care of detecting changes (currently, you're missing `action` in the dependency array of use callback). Also, if you're worried about performance of rerenders, don't be. Practically none of the things on this page will ever trigger a re-render.

2022-08-04 10:14 UTC, WissenIstNacht commented on packages/web-app/src/components/reviewExecution/index.tsx
> +  const {actions} = getValues();
Remember when we discussed that this could become like a single execution widget that could be used both for review pages as well as proposal details pages? From a technical perspective this could be tricky. Because from the proposal details page we won't have access to the actions context, right?

No need worry about this right now. Just something we might to ask ourselves at some point.

2022-08-04 10:24 UTC, Fabricevladimir requested changes
Good work! I do echo @WissenIstNacht's sentiments in terms of making the execution widget take in the actions and whatever else it needs as props. That said, we can leave this as is and refactor it when we implement the widget on the proposal details page. 

One other thing I encountered was when creating a withdraw through the main create proposal flow, selecting a token from the list doesn't close the modal for whatever reason.

2022-08-04 11:42 UTC, sepehr2github commented on packages/web-app/src/components/reviewExecution/index.tsx
> +  const {actions} = getValues();
Agreed, as Fabrice said my plan was to tackle this once we want to implement the widget on proposal details page

2022-08-08 14:53 UTC, WissenIstNacht approved these changes
Yup, checks out. Thanks a lot!

2022-08-08 17:07 UTC, Fabricevladimir approved these changes
Good to go once you've resolved the conflicts!

2022-08-08 17:07 UTC, Fabricevladimir commented on packages/web-app/src/components/reviewExecution/actionsFilter.tsx
> +        <>
Any particular reason for the fragment tags?

2022-08-08 20:01 UTC, merged