Feature: APP-800 Add/Remove execution widget
aragon/app-legacy pull request #455
Opened 2022-08-04 10:00 UTC by sepehr2github

## Description

- Add/Remove execution widget added to the proposal page

Task: [APP-800](https://aragonassociation.atlassian.net/browse/APP-800)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-08-05 04:42 UTC, RakeshUP approved these changes

2022-08-09 10:00 UTC, WissenIstNacht requested changes
Hey, there seem to be issues with some versions of some files in this PR. Also, the diff shows things that should already be in develop...? Could you please update it such that it matches the current dev branch?

2022-08-09 10:00 UTC, WissenIstNacht commented on packages/web-app/src/components/executionWidget/withdrawCard.tsx
> +import React from 'react';
This is just code that was moved, right? It was under `reviewExecution/actions/withdrawCard.tsx` before?

If so, please use the `git move` command to rename/replace files.

2022-08-09 10:00 UTC, WissenIstNacht commented on packages/web-app/src/components/executionWidget/index.tsx
> +  const RenderActions = useCallback(
This seems to be the old file. Please make sure you don't introduce errors when moving/renaming things (again, using git helps here).

2022-08-09 15:46 UTC, WissenIstNacht approved these changes
Aaah, much better, thanks for updating the branch :D

Would be nice if you could swap out the keys on the mappings. Otherwise, approved!

2022-08-09 15:46 UTC, WissenIstNacht commented on packages/web-app/src/components/executionWidget/actions/addAddressCard.tsx
> +  const filteredMemberWallets = action.inputs.memberWallets.filter(
This is to make sure that "empty addresses" are not counted?

2022-08-09 15:46 UTC, WissenIstNacht commented on packages/web-app/src/components/executionWidget/actions/addAddressCard.tsx
> +          <ListItemAddress label={address} src={address} key={index} />
The `address` would be better as a key.

2022-08-09 15:46 UTC, WissenIstNacht commented on packages/web-app/src/containers/actionBuilder/addAddresses/accordionSummary.tsx
> +  type?: AccordionMethodType['type'];
Technically I think you now export a type that does just that :p

2022-08-09 15:46 UTC, WissenIstNacht commented on packages/web-app/src/components/executionWidget/actions/removeAddressCard.tsx
> +        {action.inputs.memberWallets.map(({address}, index: number) => (
same

2022-08-10 06:26 UTC, sepehr2github commented on packages/web-app/src/components/executionWidget/actions/addAddressCard.tsx
> +  const filteredMemberWallets = action.inputs.memberWallets.filter(
Yup!

2022-08-10 06:26 UTC, sepehr2github commented on packages/web-app/src/components/executionWidget/actions/addAddressCard.tsx
> +          <ListItemAddress label={address} src={address} key={index} />
Ah true Thanks

2022-08-10 06:50 UTC, merged