Feat: Review DAO checkbox validation
aragon/app-legacy pull request #457
Opened 2022-08-08 11:08 UTC by RakeshUP

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task: [ID]()

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2022-08-09 10:22 UTC, Fabricevladimir requested changes
Good work! Quite a few moving parts there. Left a couple of comments.

2022-08-09 10:22 UTC, Fabricevladimir commented on packages/ui-components/src/components/checkbox/checkboxListItem.tsx
> +  errorBorder?: boolean;
I think this bad boy can just be `error` since it indicates when there's an error. Might even be feasible to have `error` as a fourth state. Anyway we can leave any refactors if necessary for later.

2022-08-09 10:22 UTC, Fabricevladimir commented on packages/web-app/src/containers/goLive/index.tsx
>      !Object.values(reviewCheck).every(v => v === true);
Can you modify this so that the button is disabled if at least one of the values is not true? So that you can uncomment line 100?

2022-08-09 14:19 UTC, WissenIstNacht commented on packages/ui-components/src/components/checkbox/checkboxListItem.tsx
> +  errorBorder?: boolean;
I think `state` was not the right word here. The `state` should really be `type` or `kind`. But yeah, otherwise agreed. But yeah, let's not open that can of worms now ^^'

2022-08-09 14:19 UTC, WissenIstNacht commented on packages/web-app/src/components/descriptionList/index.tsx
> +  checkedState?: CheckboxListItemProps['state'];
Yeah, this is why this prop field really shouldn't be called state, hehe.

The `active` property is indeed a state, the others really aren't...

2022-08-09 14:35 UTC, WissenIstNacht requested changes
If it's not too much work, could you separate the `type` of the checkboxes from their `state`?

2022-08-09 14:35 UTC, WissenIstNacht commented on packages/web-app/src/components/descriptionList/index.tsx
>                onClick={onChecked}
`onChecked?.()`. You're call, though (pun intended :D)

2022-08-09 14:35 UTC, WissenIstNacht commented on packages/web-app/src/components/descriptionList/index.tsx
> +  checkedState?: CheckboxListItemProps['state'];
Yeah, this is why this prop field really shouldn't be called `state`, hehe.

The `active` property is indeed a `state`, the others really aren't...

2022-08-09 14:35 UTC, WissenIstNacht commented on packages/web-app/src/components/descriptionList/index.tsx
>                label="These values are correct"
i10n

2022-08-10 10:44 UTC, RakeshUP commented on packages/web-app/src/containers/goLive/index.tsx
>      !Object.values(reviewCheck).every(v => v === true);
When a button is disabled, the onClick is not called; validations are impossible. We have to come up with new variants or introduce a new prop to capture the 'primary-disabled', etc., kinds of buttons

2022-08-10 13:08 UTC, Fabricevladimir commented on packages/web-app/src/containers/goLive/index.tsx
>      !Object.values(reviewCheck).every(v => v === true);
A quick workaround in the meantime could be to wrap the button in a div which will have the disabled click handler. When the button is disabled, the click event will be actually on the parent div.  Something like the following, unless of course it's quicker to change the button styling:

```jsx
<div onClick={showInvalidFields}>
    <button onClick={goToNextPage}/>
</div>
```

2022-08-10 15:32 UTC, WissenIstNacht approved these changes
Thanks for addressing the comments, approving the PR.

Just as a sidenote (no need for action on this): Maybe I expressed my self poorly. What I meant for the interface of the checkboxes in the component library is that we have a property called `state` that holds `'active' | 'error' | 'warning' | ...`, _as well as_ a property called `type` that holds `'single' | 'multi' | ...`.

2022-08-11 10:38 UTC, RakeshUP commented on packages/web-app/src/containers/goLive/index.tsx
>      !Object.values(reviewCheck).every(v => v === true);
Implemented your solution. Thanks @Fabricevladimir

2022-08-11 11:17 UTC, Fabricevladimir approved these changes

2022-08-11 11:23 UTC, merged