Fix: New SDK integration & enabled deposit and dao creation flow
aragon/app-legacy pull request #468
Opened 2022-08-18 08:51 UTC by sepehr2github

## Description

Task: [APP-681](https://aragonassociation.atlassian.net/browse/APP-681)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-08-22 12:26 UTC, Fabricevladimir reviewed
Thanks, man! Left a couple of comments

2022-08-22 12:26 UTC, Fabricevladimir commented on packages/web-app/src/context/createDao.tsx
> +import {IPluginListItem} from '@aragon/sdk-client/dist/internal/interfaces/common';
We need to get this exported properly from the SDK

2022-08-22 12:26 UTC, Fabricevladimir commented on packages/web-app/src/context/createDao.tsx
> +  const createDaoIterator = useMemo(() => {
Why go with an memoized iterator instead of calling the method in the `createDao` function underneath?

2022-08-22 12:26 UTC, Fabricevladimir commented on packages/web-app/src/context/createDao.tsx
> +    return client?.methods.create(getDaoSettings());
In `handlePublishDao`, we called `getDaoSettings` and set the result to the `daoCreationData` state object. Shouldn't `daoCreationData` be used here and in `estimateCreationFees` instead of calling `getDaoSettings` again?

2022-08-22 12:26 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useCachedDao.tsx
> + * @method createWhitelist By passing instance plugin address will create an ERC20Client
Update comment to to WhitelistClient instead of ERC20Client. Copy pasta, I presume?

2022-08-22 12:26 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useCachedDao.tsx
>  export const useDao = (): IUseDaoResponse => {
Might need to rename this so it's more intuitive & matches the filename like we have per convention. I guess this is a client factory, yes?

2022-08-22 14:20 UTC, WissenIstNacht requested changes
Nice! Eventhough this might break a thing or two, I'm kinda excited to introduce this. :) 

I've requested a couple of minro chages. I've also left a couple of questions. Please get back to me on them.

2022-08-22 14:20 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useClient.tsx
> +          : [import.meta.env.VITE_IPFS_ALCHEMY_API as string],
The alchemy import makes sense. Do you remember why Jose added `web3Providers`? Or what exactly it holds? And why we're only using it conditionally?

2022-08-22 14:20 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useCachedDao.tsx
> + * This hook can use to build ERC20 or whitelist clients
```suggestion
 * This hook can be used to build ERC20 or whitelist clients
```

2022-08-22 14:20 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useCachedDao.tsx
>  export const useDao = (): IUseDaoResponse => {
+1 on this. I would go even further an ask if this even still the right approach to this (I'm sure this might have made sense at some point, but I feel like a lot has changed).

What is the idea of this code? Is it here for convenience? I.e., to make it for the devs that rely on this global Client context to get the exact (sub-) client that they need? 

Also, more general thoughts:
1) why return a function instead of directly returning the `ClientXYZ` instance directly? (UPDATE I think I find out why. But I think it's the wrong way to go. `pluginAddress` should be a prop. Then we would not need to return functions).
2) Why not create two hooks, one for each client? Actually maybe this is not a good idea, because then we'd have to extend this manually for each new type of client. But still, I think returning both every time might not be necessary.

2022-08-22 14:20 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useCachedDao.tsx
> +      return new Error('ERC20 SDK client is not initialized correctly');
I think the error is no longer correct now. Since we're only creating the erc20 client now :p

PS: same for whitelist further down

2022-08-22 14:20 UTC, WissenIstNacht commented on packages/web-app/src/context/deposit.tsx
> +    return client?.estimation.deposit(depositParams as IDepositParams);
Do we not need the code around this any more?

2022-08-22 14:45 UTC, WissenIstNacht commented
Also my `yarn.lock` is different then yours. Did you install `dot-env` at some point? If so, make sure to clean your lock file (or let me know and I can push the necessary changes).

2022-08-23 10:11 UTC, sepehr2github commented on packages/web-app/src/context/deposit.tsx
> +    return client?.estimation.deposit(depositParams as IDepositParams);
Yes, We need but the token allowance estimation wasn't available on SDK, on that time

2022-08-25 13:21 UTC, sepehr2github commented on packages/web-app/src/hooks/useClient.tsx
> +          : [import.meta.env.VITE_IPFS_ALCHEMY_API as string],
Sorry my bad, Fixed the env configuration

2022-08-25 13:23 UTC, sepehr2github commented on packages/web-app/src/hooks/useCachedDao.tsx
>  export const useDao = (): IUseDaoResponse => {
The method refactored Also as an answer, Yes It's for convenience also It's for getting the exact sub-client

2022-08-25 16:07 UTC, WissenIstNacht approved these changes
Thanks a lot for the changes Sepehr.

I left two additional minor comments. Would  be nice if you could take care of them. The PR is already approved, because I won't be available tomorrow. Just merge it once you addressed the two comments.

2022-08-25 16:07 UTC, WissenIstNacht commented on packages/web-app/src/hooks/usePluginClient.tsx
> +  type: ClientTypes,
Don't be afraid Sepehr... use the power! :D

No but seriously, we're using Typescript for a reason. Please use actual type instead of Enums, as Enums can not be statically checked. Thanks :)

2022-08-25 16:07 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useClient.tsx
> +      const alchemyApiKey = import.meta.env
Small comment here: The `.env` file should only contain what can not be written in code. This can basically be two thing:
1) Something that you don't know while you write code (for example, the sha of the commit that will trigger a build of this code. You just can not know this while you write code).
2) Something that you can not share in your source code (i.e., passwords, api keys, etc.)

From this two points we can deduce that this is not the case for the URL:
 1) We already know the URL
 2) There is nothing private about the URL.

2022-08-25 17:46 UTC, sepehr2github commented on packages/web-app/src/hooks/useClient.tsx
> +      const alchemyApiKey = import.meta.env
I agree with this idea but Carlos told me to put all URLs and variables on env, but let me do a double sync will update

2022-08-25 20:29 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useClient.tsx
> +      const alchemyApiKey = import.meta.env
Then I apologies for giving you contradictory feedback! 🙏🏼

2022-08-25 20:32 UTC, sepehr2github commented on packages/web-app/src/hooks/useClient.tsx
> +      const alchemyApiKey = import.meta.env
No, thats ok. He's reason was that   Just Imagine a server goes down, you would need to make change, put up a PR, get two approvals, pass CI/CD, then wait for deployment and finally check. That's at least 30 mins you are down, or with something broken. That doesn't make sense, when you could just change it in a variable, but for now we will only add api keys to env files then add urls later

2022-08-26 11:11 UTC, Fabricevladimir approved these changes
Thanks Sepehr

2022-08-27 08:07 UTC, merged