Feature: Dao Card
aragon/app-legacy pull request #47
Opened 2021-11-22 14:19 UTC by WissenIstNacht

This PR 

- implements,
- adds a storybook entry,
- tests
- and documents

the `DaoCard` component.

2021-11-22 14:56 UTC, sepehr2github commented on packages/ui-components/src/utils/addresses.tsx
> +  else return address;
I selected "label" instead of address because sometimes It can be an ENS! But Ens is a kind of address. I guess :)))

2021-11-22 15:11 UTC, sepehr2github requested changes
Great Work. Thanks
Can you add a wide attribute for the Dao card?

2021-11-22 15:38 UTC, WissenIstNacht commented on packages/ui-components/src/utils/addresses.tsx
> +  else return address;
Ok! So then if you do `shortenAddress("blaaaaaaaa.blaaaaaaa.aragon.ens")` you would get `'blaa...ens`?

2021-11-22 17:49 UTC, Fabricevladimir approved these changes
Looks good to me!

2021-11-23 07:20 UTC, RakeshUP approved these changes

2021-11-23 07:47 UTC, sepehr2github approved these changes

2021-11-23 07:49 UTC, sepehr2github commented on packages/ui-components/src/utils/addresses.tsx
> +  else return address;
hmm... No, I think it should be 'blaaaaa....'

2021-11-23 09:41 UTC, merged