F/app 819
aragon/app-legacy pull request #480
Opened 2022-08-31 09:51 UTC by sepehr2github

## Description

- pre-filled the setting information using SDK

Task: [APP-819](https://aragonassociation.atlassian.net/browse/APP-819)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-09-05 10:25 UTC, Fabricevladimir approved these changes
Good work thanks. Remember to add the task for community related part 👍🏾

2022-09-05 12:44 UTC, RakeshUP commented on packages/web-app/src/pages/settings.tsx
> +            <Dd>{network}</Dd>
I guess we should display the `network` we get from SDK. Won't the one from `useNetwork` give the user wallet's network?

2022-09-05 12:44 UTC, RakeshUP approved these changes

2022-09-05 13:37 UTC, WissenIstNacht commented on packages/web-app/src/utils/date.ts
> +  const days = seconds / 86400 < 1 ? 0 : seconds / 86400;
you could simply do `seconds < 86400` :)

2022-09-05 13:57 UTC, WissenIstNacht commented on packages/web-app/src/utils/date.ts
> +export function getDHMFromSeconds(seconds: number): Offset {
Hey, cool effort 👍🏻 

However, the function isn't quite right, I think. I found a couple of issues:
- The function value on the returned object have decimals.`getDHMFromSeconds(100000)` returns 
```{
  "days": 1.1574074074074074,
  "hours": 3.7777777777777777,
  "minutes": 1666.6666666666667
}
```
I don't think this makes sense, given that you return the next smaller unit.
- Something seems to be wrong with the minutes. Check `getDHMFromSeconds(3670)`

2022-09-05 14:00 UTC, WissenIstNacht commented on packages/web-app/src/pages/settings.tsx
> +            <Dd>{network}</Dd>
Rakesh, I think I commented this on your PR too a couple of days ago. `useNetwork` returns the application's network, _NOT the wallet's network_.

2022-09-05 14:01 UTC, WissenIstNacht commented on packages/web-app/src/pages/settings.tsx
> +            <Dd>{Math.round(daoSettings.minTurnout * 100)}% (150 TKN)</Dd>
Shouldn't `150 TKN` also be computed?

2022-09-05 14:02 UTC, WissenIstNacht commented on packages/web-app/src/pages/settings.tsx
> +              {days} Days {hours} Hours {minutes} Minutes
translation?

2022-09-05 14:08 UTC, WissenIstNacht commented on packages/web-app/src/pages/editSettings.tsx
> +  const {data: daoId, loading: paramAreLoading} = useDaoParam();
ahm this was already available on line 40...?

2022-09-05 14:32 UTC, WissenIstNacht requested changes
Hey thanks a lot. I left a couple of comments that should be addressed. As always, let me know if you think I misjudged something! :)

2022-09-06 09:58 UTC, sepehr2github commented on packages/web-app/src/pages/settings.tsx
> +            <Dd>{Math.round(daoSettings.minTurnout * 100)}% (150 TKN)</Dd>
I will crate a ticket to tackle all these, community setting. because It was depended on Rakash PR, Once He merged his PR I can use his method to fetch data

2022-09-06 14:18 UTC, WissenIstNacht approved these changes
Thanks a lot  for the changes 👍🏼

2022-09-06 14:18 UTC, WissenIstNacht commented on packages/web-app/src/utils/date.ts
> +  const minutes = remandedMinutes < 60 ? 0 : remandedMinutes / 60;
```suggestion
  const remainingMinutes = (seconds % 86400) % 3600;
  const minutes = remainingMinutes < 60 ? 0 : remainingMinutes / 60;
```

2022-09-06 15:34 UTC, merged