Feature: App-965 Proposal Actions - Execution Widget
aragon/app-legacy pull request #490
Opened 2022-09-14 09:53 UTC by sepehr2github

## Description

- Execution widget added to the proposal details page

Task: [APP-965](https://aragonassociation.atlassian.net/browse/APP-965)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-09-14 10:52 UTC, Fabricevladimir requested changes
Thanks Sepehr. Left a few comments. Unfortunately, the token & information doesn't show up for me when I open a proposal. 😢

2022-09-14 10:52 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useDaoProposal.tsx
>          if (proposal) setData(proposal);
I'm guessing you're not merging these two because adding the encoded data is temporary?

2022-09-14 10:52 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useDecodeWithdrawToAction.tsx
> + * Get dao metadata
Please update the comment. Also, could you move and rename the file since this isn't a hook but a utility method?

2022-09-14 10:52 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useDecodeWithdrawToAction.tsx
> +  const decoded = await client?.decoding.withdrawAction(data);
Optional chaining shouldn't be necessary for `client.decoding...` since on line 24 you're returning if there is no client.  Same thing for line 37. 

Also, `withdrawAction` isn't an asynchronous method so you don't need the await.

2022-09-14 10:52 UTC, Fabricevladimir commented on packages/web-app/src/components/executionWidget/index.tsx
> +  actions?: Array<Action | undefined>;
What's the reasoning in allowing an array of undefined especially considering actions are optional already?

2022-09-14 10:52 UTC, Fabricevladimir commented on packages/web-app/src/components/executionWidget/index.tsx
> +              if (action)
See above comment. If there are no actions, this shouldn't run at all thereby eliminating the if(action) check.

2022-09-14 10:52 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useDaoProposal.tsx
> +    network,
Why are `apolloClient`, `globalClient` and `network` dependencies for this?

2022-09-14 10:52 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useDecodeWithdrawToAction.tsx
> +  client: Client | undefined,
I'm not sure it makes sense to have the data be undefined if we're going to complain about it immediately afterwards. I understand client being undefined is so we don't have to do something like below correct?
```
decodeWithdrawToAction(data, client!)
// or
if(client) decodeWithdrawToAction(data, client)
```

2022-09-14 10:52 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useDecodeWithdrawToAction.tsx
> +  const response = await fetchTokenData(
Considering there might not be many actions this is fine for now, but we could get a performance boost if we batch fetchTokenData calls into a single `Promise.all` if there are multiple withdraws. It would also be good separation of concerns as well.

2022-09-14 10:52 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useDecodeWithdrawToAction.tsx
> +    tokenBalance: 0, // unnecessary
We should cleanup the withdraw action at some point.

2022-09-14 10:52 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useDaoProposal.tsx
> +    const getClient = async () => {
Please update method name.

2022-09-14 10:52 UTC, Fabricevladimir commented on packages/web-app/src/pages/proposal.tsx
> +    useState<(ActionWithdraw | undefined)[]>();
Why make this an array of undefined as opposed to a list of ActionWithdraws?

2022-09-14 10:52 UTC, Fabricevladimir commented on packages/web-app/src/pages/proposal.tsx
> +        return decodeWithdrawToAction(
Shouldn't there be a check to see whether the action is `withdraw_assets`?

2022-09-14 10:52 UTC, Fabricevladimir commented on packages/web-app/src/pages/proposal.tsx
> +      Promise.all(actionPromises || []).then(value => {
This is a bit weird. I would suggest perhaps checking if there are actions in the first place, up top before you get the `actionPromises`.

2022-09-14 10:52 UTC, Fabricevladimir commented on packages/web-app/src/pages/proposal.tsx
>            {/* TODO: Fill out voting terminal props*/}
This one is on me hehehe. Can you remove that comment please

2022-09-14 17:33 UTC, sepehr2github commented on packages/web-app/src/hooks/useDaoProposal.tsx
>          if (proposal) setData(proposal);
Yup, We need to remove it in near future

2022-09-14 17:42 UTC, sepehr2github commented on packages/web-app/src/components/executionWidget/index.tsx
> +  actions?: Array<Action | undefined>;
because the promise all promise function has value:(ActionWithdraw | undefined)[] type which means arrays of undefined

2022-09-14 17:43 UTC, sepehr2github commented on packages/web-app/src/hooks/useDaoProposal.tsx
> +    network,
Forgot to remove, I had no warning on VS which is wired!

2022-09-14 17:43 UTC, sepehr2github commented on packages/web-app/src/hooks/useDecodeWithdrawToAction.tsx
> +    tokenBalance: 0, // unnecessary
Yes, For sure will add necessory todos

2022-09-14 18:17 UTC, sepehr2github commented on packages/web-app/src/components/executionWidget/index.tsx
> +              if (action)
I know but if you remove the if you'll see that Vs start complaining :/

2022-09-14 18:18 UTC, sepehr2github commented on packages/web-app/src/pages/proposal.tsx
> +    useState<(ActionWithdraw | undefined)[]>();
As I told you before, It's because of the value type on promise.all

2022-09-14 18:25 UTC, sepehr2github commented on packages/web-app/src/hooks/useDecodeWithdrawToAction.tsx
> +  client: Client | undefined,
Please remember that this function will use generally, and if we use this later somewhere and for any reason, the data source couldn't work, the application shouldn't crash!

2022-09-14 18:30 UTC, sepehr2github commented on packages/web-app/src/hooks/useDecodeWithdrawToAction.tsx
> +  const response = await fetchTokenData(
Let's wait till we add more actions so We will refactor this, because we need to filter the withdraw actions first

2022-09-15 10:42 UTC, Fabricevladimir commented on packages/web-app/src/components/executionWidget/index.tsx
> +  actions?: Array<Action | undefined>;
I can kind of see why this is returning the promise is returning undefined. I would suggest filtering the array before passing it in. But the greater question in here then becomes what exactly do we do with those actions that couldn't be decoded for whatever reason? That's something we need to think about.

2022-09-15 10:42 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useDaoProposal.tsx
> +    network,
I think linter will catch when it's missing dependencies only.

2022-09-15 10:45 UTC, WissenIstNacht requested changes
Hey thanks Sepehr :)

Left some suggestion.

2022-09-15 10:45 UTC, WissenIstNacht commented on packages/web-app/src/pages/proposal.tsx
> +    getProposalAction();
If you're using `then` callbacks you don't need to wrap everything in an async function :)
```suggestion
      if (proposal) {
        const actionPromises = proposal.actions.map(action =>
          findDecoder(action)
        );
        Promise.all(actionPromises).then(value => {
          setDecodedActions(value);
        });
      }
```

2022-09-15 10:45 UTC, WissenIstNacht commented on packages/web-app/src/pages/proposal.tsx
> +  const findDecoder = useCallback(
Memoizing things and then using it in effects can lead to tricky bugs. Since you're only using `findDecoder` in the `useEffect`right below it, could you simply move the function into the `useEffect`?

2022-09-15 10:45 UTC, WissenIstNacht commented on packages/web-app/src/pages/proposal.tsx
> +    [apolloClient, client, network]
If you're return a promise in the other case it's gonna make things easier if you return a Promise here too. You can do this by wrapping the returned object with the `reolve` function

```suggestion
          return Promise.resolve({} as ActionWithdraw);
```

2022-09-15 10:45 UTC, WissenIstNacht commented on packages/web-app/src/pages/proposal.tsx
> +    useState<(ActionWithdraw | void)[]>();
`void` is not the right type here, as it represents the return type of functions that don't return anything. Did you mean `undefined` or `null`? (Note that while you _can_ assign `undefined` to `void` they are _NOT THE SAME_. Therefore, `void` is not a replacement for `undefined`)

2022-09-15 10:45 UTC, WissenIstNacht commented on packages/web-app/src/components/executionWidget/index.tsx
> +            {actions?.map((action, index: number) => {
For me TS says that `actions` is always an array. I.e., never `null` or `undefined`. Which makes sense sinse we're assigning `[]` by default on line 30. So the question mark is not necessary :)

```suggestion
            {actions.map((action, index: number) => {
```

2022-09-15 10:45 UTC, WissenIstNacht commented on packages/web-app/src/components/executionWidget/index.tsx
> +  actions?: Array<Action | void>;
Same comment as in the other file :)

2022-09-15 10:55 UTC, Fabricevladimir reviewed
I can see the action! Left one small comment

2022-09-15 10:55 UTC, Fabricevladimir commented on packages/web-app/src/pages/proposal.tsx
> +  }, [apolloClient, client, findDecoder, network, proposal, proposal?.actions]);
Can you take a look at the dependency array?  I think `findDecoder` and `proposal` are perhaps the only ones necessary. You could go one step further and instead of checking for proposal, you could check for `proposal?.actions` in the if statement. But that might be pure overkill because I can't think of any time where the proposal would change and the actions not change 😄

2022-09-16 11:47 UTC, WissenIstNacht approved these changes
Good to go from my side, thanks!

2022-09-16 12:44 UTC, Fabricevladimir approved these changes

2022-09-18 16:22 UTC, merged