Feature/wallet modal DAO-436
aragon/app-legacy pull request #50
Opened 2021-11-23 09:36 UTC by sepehr2github

- Wallet Modal added
- Wallet Card added
- Fix Bottom sheet fixed height issue
- Dynamic navbar wallet button added

2021-11-23 10:57 UTC, WissenIstNacht commented
Nice one, this really takes us a step closer to a basic app! 🥳

2021-11-23 10:59 UTC, WissenIstNacht requested changes

2021-11-23 10:59 UTC, WissenIstNacht commented on packages/ui-components/stories/WalletCard.stories.tsx
> +  title: 'Components/WalletCardProps',
```suggestion
  title: 'Components/WalletCard',
```

2021-11-23 10:59 UTC, WissenIstNacht commented on packages/ui-components/src/components/walletCard/walletCard.tsx
> +  * Allows the Wallet Card component grow vertically
horizontally? :p

Edit: I guess that on me haha

2021-11-23 10:59 UTC, WissenIstNacht commented on packages/ui-components/src/components/walletCard/walletCard.tsx
> +type ContainerProps = Pick<WalletCardProps, 'wide'>;
Nice. I think I forgot to do that on my last PR about `DaoCard`.

2021-11-23 10:59 UTC, WissenIstNacht commented on packages/ui-components/src/components/walletCard/walletCard.tsx
> +              <Title>{BeautifyLabel(name)}</Title>
Care, passing `sdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf.eth` will not shorten the addres. 

No need to change anything right now. AFAIK the designs don't really specify anything about how to shorten ens names yet.

2021-11-23 10:59 UTC, WissenIstNacht commented on packages/ui-components/src/components/walletCard/walletCard.tsx
> +  * wallet ENS name or wallet eth address
I understand why you did this, but I don't think it's the right approach. In the designs, the wallet address must always be present. I think this should be reflected in the interface. I would make `address` non-optional and `name` optional. Then
- if: `name` is not specified: make the `address` a `Title` 
- Else: leave it as you have it now

2021-11-23 10:59 UTC, WissenIstNacht commented on packages/ui-components/src/components/button/iconButton.tsx
> +    className = 'flex items-center flex-row-reverse space-x-reverse space-x-1.5';
Here you changed to `2.5`, but on line 50 you left to `2`. Is that intentional?

2021-11-23 10:59 UTC, WissenIstNacht commented on packages/web-app/src/containers/walletMenu/index.tsx
> +          title="ens-name.eth"
```suggestion
          name="ens-name.eth"
```

2021-11-23 10:59 UTC, WissenIstNacht commented on packages/web-app/src/containers/walletMenu/index.tsx
> +          <ActionListItem
Still necessary? (seeing as we're only doing Metamask right now?)

2021-11-23 10:59 UTC, WissenIstNacht commented on packages/web-app/src/containers/navbar/index.tsx
> +          label={isConnected() ? account : 'Connect account'}
We can do this later, but technically, the `Connect account` label should also be part of the i10n translation.

2021-11-23 11:48 UTC, sepehr2github commented on packages/ui-components/src/components/walletCard/walletCard.tsx
> +  * Allows the Wallet Card component grow vertically
Yes. I used your comment hahaha. I want to keep too much consistency LOL

2021-11-23 12:21 UTC, Fabricevladimir requested changes
Nice work!

2021-11-23 12:21 UTC, Fabricevladimir commented on packages/ui-components/__tests__/walletCard.test.tsx
> +describe('DaoSelector', () => {
Copy paste error?

2021-11-23 12:21 UTC, Fabricevladimir commented on packages/ui-components/src/components/button/walletButton.tsx
> +  ${isSelected ? 'text-primary-500 bg-primary-50' : 'text-ui-600 bg-ui-0'}`,
Can we get an `active` state for this as well for when the button is clicked?

2021-11-23 12:21 UTC, Fabricevladimir commented on packages/web-app/src/containers/navbar/index.tsx
> +import {useMenuContext} from '../../context/menu';
Can you switch this from a "relative" import?

2021-11-23 12:21 UTC, Fabricevladimir commented on packages/web-app/src/pages/home.tsx
>        <BottomSheet onOpen={onOpen} isOpen={isOpen} onClose={onClose} />
I don't foresee a case where we would need multiple instances of the `BottomSheet` can this be moved to a central location like in `app` perhaps?

2021-11-23 12:21 UTC, sepehr2github commented on packages/ui-components/src/components/button/iconButton.tsx
> +    className = 'flex items-center flex-row-reverse space-x-reverse space-x-1.5';
Yes, It's intentional. there is a difference in space between the right & left icon sides.

2021-11-23 13:02 UTC, WissenIstNacht commented on packages/ui-components/src/components/walletCard/walletCard.tsx
> +  * Allows the Wallet Card component grow vertically
👌🏼 😄 

Could you change mine to "horizontally", too? :)

2021-11-23 15:13 UTC, Fabricevladimir commented on packages/ui-components/src/components/button/walletButton.tsx
> +      ${active ? 'text-primary-500 bg-primary-50' : 'text-ui-600 bg-ui-0'}`,
I might have been unclear a bit with this. What I meant was active in terms of state like `hover` and `disable`

2021-11-24 09:31 UTC, Fabricevladimir approved these changes

2021-11-24 09:41 UTC, WissenIstNacht approved these changes

2021-11-24 12:31 UTC, Fabricevladimir commented
Closed for commit signing issues

2021-11-24 12:31 UTC, closed without merging