Feature: Token gating modals
aragon/app-legacy pull request #507
Opened 2022-09-28 20:23 UTC by sepehr2github

## Description

- token gating modal added
- wallet gating modal added

Note: The logic will be addressed on next PR!

Task: [APP-1039](https://aragonassociation.atlassian.net/browse/APP-1039)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-09-29 11:24 UTC, RakeshUP approved these changes

2022-10-03 11:06 UTC, Fabricevladimir reviewed
Thanks Sepehr! Good work. Left a couple of comments.

2022-10-03 11:06 UTC, Fabricevladimir commented on packages/web-app/src/app.tsx
> +const ProtectedRoute: React.FC = () => {
Can you move this to its own file?

2022-10-03 11:06 UTC, Fabricevladimir commented on packages/web-app/src/app.tsx
> +  if (filteredMembers.length === 0 && daoDetails)
I think it's worth asking for login, but right now we're checking for membership regardless. For example, if user  wallet isn't connected, right now, it assumes you're not a member since the query will return no filtered members. This is deceptive because the user doesn't really know why he's getting booted out of the flow even though he has the proper tokens. What we should do instead, I suggest, is direct user to login first and then check for membership.

2022-10-03 11:06 UTC, Fabricevladimir commented on packages/web-app/src/containers/gatingMenu/tokenGating.tsx
> +  const {data: dao} = useDaoParam();
We need to find a way to stop hitting `useDaoParam` on so many components. 🙈

2022-10-03 11:06 UTC, Fabricevladimir commented on packages/web-app/src/containers/gatingMenu/tokenGating.tsx
> +              tokenName: !daoTokenLoading ? daoToken?.name : '',
Unfortunately, this doesn't show a token name for me 😞

2022-10-03 11:06 UTC, Fabricevladimir commented on packages/web-app/src/pages/newProposal.tsx
> +          <WalletGating />
I think these two should be in the `ProtectedRoute` component instead so that everyone can have access to the singular instance, especially since they are needed in multiple flows.

2022-10-03 11:06 UTC, Fabricevladimir commented on packages/web-app/src/app.tsx
> +                />
Can you move the other protected proposal routes as well: `EditSettings`,  `ProposeNewSettings`, `MintTokensProposal`, `ManageMembersProposal` and probably `NewWithdraw` as well? Either that or leave a comment indicating that since it will get a tad bit annoying if we have to be gated while developing 😆

2022-10-03 11:06 UTC, Fabricevladimir commented on packages/web-app/src/app.tsx
> +  return <Outlet />;
What are your thoughts on using the `Outlet` as opposed to returning a child component? Just curious 🙈

2022-10-04 08:42 UTC, sepehr2github commented on packages/web-app/src/app.tsx
> +  return <Outlet />;
For performance not sure but I feel using the react-router approach would be much better,Also I decided this way to keep consistency.

2022-10-04 09:40 UTC, WissenIstNacht commented on packages/web-app/src/app.tsx
> +  return <Outlet />;
Just FYI here: passing `children` simply doesn't work.When I was working on this file a couple of months ago, I remember having the exact same question. So I tried it out and it didn't work. Things might have changed in the meantime. But even if they did, I don't think it's worth rewriting the file. :p

2022-10-04 09:55 UTC, WissenIstNacht commented on packages/web-app/src/containers/gatingMenu/tokenGating.tsx
> +  const {data: dao} = useDaoParam();
Sorry to spam your PR Sepehr, but these are interesting comments :p

I mean you can't actually avoid this parameter, as it's necessary for all sorts of things. But there's something that's bugging me too, here. Namely that the hook actually queries in each component it's called from. I think the best way to solve this would be to create a context around all routes that are DAO-related. In the provider, perform the "dao exists check" and then simply expose the `daoParam` to consumers.

A similar structure might also be useful for things like `client`s and `daoDetails`, btw. Maybe they could even be merged into one?

2022-10-05 09:15 UTC, sepehr2github commented on packages/web-app/src/containers/gatingMenu/tokenGating.tsx
> +  const {data: dao} = useDaoParam();
Agreed! @WissenIstNacht How about creating a bug task to tackle this

2022-10-05 11:44 UTC, WissenIstNacht commented on packages/web-app/src/containers/gatingMenu/tokenGating.tsx
> +  const {data: dao} = useDaoParam();
@sepehr2github Why bug? Is something broken? 😅 

I don't think this is an important thing to tackle. The code works as is expected and performs well (so far). As long as this is true I wouldn't make this a priority. But maybe we can add this to the list of todos and tackle it as a simple improvement task at some point?

2022-10-07 09:53 UTC, WissenIstNacht requested changes
Hey Sepehr, nice job! Lots of cool things in here.

I'm jumping in on Fabrice's behalf since he's not here. I've found a few tricky things that need some more work. I've left some comments in the code where I could. But there's a few things I didn't know where to comment, so I'm writing them here:

- Visiting the url `.../governance/new-proposal` directly in a fresh app crashes the application for me.
- The gating doesn't check whether a user is logged-in. I.e., if I log out and click on proposal creation I'm not stopped.
- The withdrawal flow is not gated.

2022-10-07 09:53 UTC, WissenIstNacht commented on packages/web-app/src/containers/gatingMenu/tokenGating.tsx
> +      onClose={() => close('requiredToken')}
If you click somewhere outside the modal it simply closes. And then you're on the creation flow and you can simply continue. In other words, you should make sure that you can not close the modal except by pressing the "Ok, understood" button.

(Sorry if this is no the right spot in the code for this comment :p)

2022-10-07 09:53 UTC, WissenIstNacht commented on packages/web-app/src/containers/gatingMenu/tokenGating.tsx
> +            navigate(-1);
What happens if you visit the the page on a fresh tab? Should we send people to the DAO dashboard?

2022-10-07 09:53 UTC, WissenIstNacht commented on packages/web-app/src/containers/gatingMenu/tokenGating.tsx
> +  console.log('view', daoToken);
:D

2022-10-07 09:53 UTC, WissenIstNacht commented on packages/web-app/src/components/protectedRoute/index.tsx
> +      daoDetails?.plugins[0].id === 'erc20voting.dao.eth'
Optional chaining (i.e., the question mark after `daoDetails`) is not needed when you check that `daoDetails` exists in the if statement :)

2022-10-07 09:53 UTC, WissenIstNacht commented on packages/web-app/src/containers/gatingMenu/walletGating.tsx
> +import React from 'react';
(same comments as for token gating)

2022-10-09 21:34 UTC, sepehr2github commented on packages/web-app/src/containers/gatingMenu/tokenGating.tsx
> +            navigate(-1);
Thanks, For catching this great point, after a quick sync with Marco we decided to return the user to Governance page all the time

2022-10-10 09:34 UTC, Fabricevladimir approved these changes
Thank you Sepehr, approving 😺
As for the wrong network, if we are to check for it as well, I trust Vali will take care of the review for it, or you can re-request my review again!

2022-10-12 09:22 UTC, WissenIstNacht approved these changes
Sorry this took so long, Sepehr. Thanks for all the changes. I left some minor comments. If you want to take a look at them, great. Otherwise the PR is good to go!

2022-10-12 09:22 UTC, WissenIstNacht commented on packages/web-app/src/containers/gatingMenu/index.tsx
> +            !daoTokenLoading && !detailsAreLoading ? daoToken?.name : '',
Small detail here: I think if `daoToken` is `undefined` the text here will be a string with the value "undefined".

2022-10-12 09:22 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useDaoParam.tsx
> -    // undefined mainnet clients cause problem here. This bypasses the dao param
Scary change. Was something pressing you to do it that you had to do it in this PR?

2022-10-12 09:22 UTC, WissenIstNacht commented on packages/web-app/src/components/protectedRoute/index.tsx
> +    open('gating');
Technically this is a side-effect (the function changes something outside its scope) and should technically be in a useEffect :)

2022-10-19 08:17 UTC, sepehr2github commented on packages/web-app/src/hooks/useDaoParam.tsx
> -    // undefined mainnet clients cause problem here. This bypasses the dao param
Yes, I made this change because each time you directly open proposal pages It takes time to initial the client but this condition will move user to not found page by mistake

2022-10-19 08:30 UTC, merged