Feature/Badge component DAO-466
aragon/app-legacy pull request #51
Opened 2021-11-23 11:15 UTC by RakeshUP

- Badge component added
- New color palettes added in tailwind config

2021-11-23 11:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aragon/zaragoza?pullRequest=51) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aragon/zaragoza?pullRequest=51) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aragon/zaragoza?pullRequest=51) it.</sub>

2021-11-23 11:41 UTC, WissenIstNacht requested changes
Thanks for your first PR, looking good! :)

2021-11-23 11:41 UTC, WissenIstNacht commented on packages/ui-components/src/components/badge/badge.tsx
> +}) <any>``;
```suggestion
}) <StyledBadgeProps>``;
```

2021-11-23 11:41 UTC, WissenIstNacht commented on packages/ui-components/src/components/badge/badge.tsx
> +  colorScheme?: 'default' | 'green' | 'red';
Personally, I would have named the types after the function rather than the color (i.e., "success", "critical", etc.). Imo, this would more nicely reflect the underlying color scheme defined by the design system.
I realize it can be awkward to call the badge with the `critical` props in some situation. But overall I think consistency is more important. 

Let me know if you dis-/agree :)

2021-11-23 12:29 UTC, Fabricevladimir requested changes, later dismissed
Good work, good work!

2021-11-23 12:29 UTC, Fabricevladimir commented on packages/ui-components/src/components/badge/badge.tsx
> +import React from 'react';
Would you mind adding a does it render test for the component?

2021-11-23 12:56 UTC, sepehr2github commented on packages/ui-components/src/components/badge/index.tsx
> +export * from './badge';
Based on prettier in all ts/tsx files, It's better to have an empty line at the end of the files.
Because there is no tsx here It's better to use .ts file instead of tsx

2021-11-23 12:57 UTC, sepehr2github reviewed
Well Done! Thanks

2021-11-24 10:58 UTC, RakeshUP commented on packages/ui-components/src/components/badge/badge.tsx
> +  colorScheme?: 'default' | 'green' | 'red';
I am having the same thought too. And in this particular sense of the badge representing the token price change, it also makes sense to name "green" as "positive" and "red" as "negative". I was not able to decide on the convention, so left it up as the color name itself

2021-11-24 12:25 UTC, WissenIstNacht approved these changes

2021-11-24 14:02 UTC, Fabricevladimir approved these changes

2021-11-24 14:11 UTC, merged