404 page done
aragon/app-legacy pull request #514
Opened 2022-10-07 11:21 UTC by RakeshUP

## Description

Visit any 404 url like [https://staging-app.aragon.org/#/not-found](https://staging-app.aragon.org/#/not-found) to check out the new 404 page

Task: [APP-234](https://aragonassociation.atlassian.net/browse/APP-234)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-10-10 07:51 UTC, sepehr2github reviewed
Hey, Rakash. Thanks for the implementation. The responsive needs a bit of adjustment on SVG part, also the sizes on the desktop seem different than designs, could you take a double look, please? Thanks

<img width="593" alt="Screen Shot 2022-10-10 at 11 16 34 AM" src="https://user-images.githubusercontent.com/46657145/194820011-19058859-009c-4568-bf67-728d1c603d87.png">

2022-10-10 10:10 UTC, Fabricevladimir requested changes
Thanks! Looking good overall, left a couple of comments

2022-10-10 10:10 UTC, Fabricevladimir commented on packages/web-app/src/pages/notFound.tsx
> +              className="col-span-2 h-4"
Can you add cursor-pointer to this one since it's a link?

2022-10-10 10:10 UTC, Fabricevladimir commented on packages/web-app/src/pages/notFound.tsx
>  const NotFound: React.FC = () => {
On mobile, the SVG size is causing a horizontal overflow
![image](https://user-images.githubusercontent.com/16927999/194843188-56bc161d-6139-4f66-86fc-bc1fe0e0daf8.png)

2022-10-11 04:43 UTC, RakeshUP commented
@sepehr2github fixed the image size & margin to a much closer match to the design. See if this looks okay for you

2022-10-11 10:21 UTC, Fabricevladimir approved these changes
Thanks for the changes; looking good👍🏾 
One last thing, can you add a little more margin/padding on the bottom?

2022-10-11 10:22 UTC, Fabricevladimir commented
I lied. Quick question, do you know if the header should be sticky?

2022-10-12 07:17 UTC, sepehr2github approved these changes
Thanks for the changes but before merging, could you check the menu on mobile view, according to designs, the bottom navbar should be available on the 404 mobile version which is not implemented

2022-10-12 10:38 UTC, RakeshUP commented
I spoke to Marco and the following changes have been made:
- @Fabricevladimir,  the header is now sticky with the gradient and blur of desktop navbar
- @sepehr2github, the mobile bottomsheet has been removed from the designs. so no changes there

2022-10-12 10:38 UTC, merged