Feature: App-1045
aragon/app-legacy pull request #515
Opened 2022-10-10 07:53 UTC by sepehr2github

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task: [ID]()

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2022-10-19 10:19 UTC, Fabricevladimir commented
> Notes:
> 
> 1. The token minting summery on proposal creation not working well, will address this issue on another PR

@sepehr2github I believe this issue is happening because the DAO token _isn't_ actually available on Goerli. The token is only on Rinkeby

2022-10-19 14:29 UTC, Fabricevladimir requested changes
Good things, good things. Leaving a few comments. 

Also, I thought I had submitted the review previously 🙈

2022-10-19 14:29 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useDaoProposal.tsx
> +              amount: BigInt(10),
This needs to be multiplied by 10^daoToken decimal

2022-10-19 14:29 UTC, Fabricevladimir commented on packages/web-app/src/pages/proposal.tsx
> +      const decodedMintToken = decodeMintTokensToAction(
When decoding, the token amount we get back needs to be divided by 10^daotoken decimals as well.

2022-10-19 14:29 UTC, Fabricevladimir commented on packages/web-app/src/utils/library.ts
> +      mintTokensToWallets: decoded,
Each one of the amounts in the wallet need to be formatted using the doatoken decimals

2022-10-19 14:29 UTC, Fabricevladimir commented on packages/web-app/src/utils/library.ts
> +      newTokens: BigInt(newTokens),
Same thing here.

2022-10-19 14:29 UTC, Fabricevladimir commented on packages/web-app/src/utils/library.ts
> +    return accumulator + Number(value.amount);
To prevent precision lost, you might need to add those as Bignumbers or Bigs. Not sure how much of a concern that is though to be honest lol

2022-10-19 14:29 UTC, Fabricevladimir commented on packages/web-app/src/utils/types.ts
> +    newTokens: number | bigint;
Why not pass it in only as a `number` and cast the inputs instead?

2022-10-19 14:56 UTC, WissenIstNacht reviewed
Thanks Sepehr. 

Fabrice left a lot of good comments already. Really curious about the comment in the `proposal.tsx` file.

2022-10-19 14:56 UTC, WissenIstNacht commented on packages/web-app/src/pages/proposal.tsx
> +
I'm not sure I understand the changes you made to this `useEffect`. Let's see: If one of the proposal's actions is a minting action, you push that to a separate array and store the index. Any other action gets immediately mapped to the decoded version. And then at the end you splice in that separate array into the array of decoded actions. Right?

But why? Why not simply decode the mint actions immediately, the same way you decode any other action? Why take it out first and add it back later?

2022-10-19 14:56 UTC, WissenIstNacht commented on packages/web-app/src/components/executionWidget/actions/mintTokenCard.tsx
> +                {Big(tokenSupply).toNumber() + Number(newTokens)}{' '}
tokenSupply is already of type `Big`

2022-10-20 09:07 UTC, sepehr2github commented on packages/web-app/src/pages/proposal.tsx
> +
Hey, the decoder method on SDK will return one address per action for token minting, And It's not working for our solution because we considered all the minting addresses as one action, not multiple actions, So In this way, I decoded all the actions for an iterator, then bind them into the one action

2022-10-21 10:53 UTC, Fabricevladimir approved these changes

2022-10-25 13:15 UTC, WissenIstNacht reviewed
Hey there, thanks for the changes.

I'm still a bit uncertain about the code in `proposal.tsx`. The other issue you can just add a TODO and resolve. :)

2022-10-25 13:15 UTC, WissenIstNacht commented on packages/web-app/src/utils/library.ts
> +        newHoldersCount: decoded.length,
That's _technically_ not correct. The minting could go to addresses who already hold that token.

Since this is a bigger task and it's not gonna bother anyone for the next couple of months, please simply add a TODO so that we don't forget or think it's a bug in the future.

2022-10-25 13:15 UTC, WissenIstNacht commented on packages/web-app/src/pages/proposal.tsx
> +
Oh, I see! Thanks a lot for the explanation. Two things:

1. That explanation might be worth putting in a comment.
2. So you're bundling the mints to individual addresses that you get from the SDK, you decode them, you bundle them and then splice them back into the array with all the other actions, right? However, in splice, you only add the bundled action back in. Where do you actually delete the individual mint action you get from the SDK? In other words, shouldn't the delete count in splice be a number other than 0?

2022-10-31 10:02 UTC, WissenIstNacht approved these changes

2022-10-31 10:42 UTC, merged