Feature: APP-1081 - Proposal Creation Nav: Withdraw
aragon/app-legacy pull request #518
Opened 2022-10-11 15:38 UTC by Fabricevladimir

## Description
- Caches newly published proposal
- Redirects to `ProposalDetails` page once proposal is successfully published
- Uses cached proposal for `ProposalDetails` page if SDK data for proposal not yet available
- Uses cached proposals in DAO proposal lists (`Governance`, `Dashboard`) if SDK data for cached proposal not yet available
- Persists cached proposals if functional cookies are set
- Updates `useDaoToken` hook to use SDK (had to be done for caching)

NOTE: This lays the foundation for the other singular proposal flows, hence the size

Task: [APP-1081](https://aragonassociation.atlassian.net/browse/APP-1081)

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2022-10-13 10:39 UTC, RakeshUP approved these changes

2022-10-18 10:01 UTC, WissenIstNacht requested changes
Thanks a lot, looks like there were a couple of tricky things to solve.

What's the state on the proposals hook? `useProposal` says it should take over when `useDaoProposals` is deprecated, yet both seem quite alive?

2022-10-18 10:01 UTC, WissenIstNacht commented on packages/web-app/src/utils/library.ts
> +export const customJSONReplacer = (_: string, value: unknown) => {
Why have a function with 2 args if one of them is not used? :p

Couldn't you just remove it and only keep the `value` argument?

2022-10-18 10:01 UTC, WissenIstNacht commented on packages/web-app/src/utils/library.ts
> +    // not an object? do nothing
Does something throw an Error here? If so, please report it. Swallowed errors will eventually haunt you or someone else.

2022-10-18 10:01 UTC, WissenIstNacht commented on packages/web-app/src/utils/library.ts
> +    if ('flag' in value && value.flag === FLAG_TYPED_ARRAY) {
I think you could leave out the first check. If flag's not in there, `value.flag` would simply evaluate to `undefined` and the comparison would return `false`.

2022-10-18 10:01 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useDaoActions.tsx
> +  const whitelist = daoDetails?.plugins[0].id === 'addresslistvoting.dao.eth';
Just a head-up, you'll have conflicts here.

2022-10-18 10:41 UTC, Fabricevladimir commented on packages/web-app/src/utils/library.ts
> +export const customJSONReplacer = (_: string, value: unknown) => {
This is a calback function that is going to be passed a key  `_` (which is unnecessary for what I'm checking for currently) and a value, which of course I actually need. So if I were to "remove" the first argument and keep only `value`, it would actually be the `key` and not the actual value that I need

2022-10-18 11:11 UTC, Fabricevladimir commented on packages/web-app/src/utils/library.ts
> +    if ('flag' in value && value.flag === FLAG_TYPED_ARRAY) {
True. That would also allow me to remove the try catch block

2022-10-18 11:49 UTC, WissenIstNacht approved these changes
Cheers!

2022-10-18 11:54 UTC, merged