Feature: APP-1086 copyright Updates
aragon/app-legacy pull request #519
Opened 2022-10-12 10:16 UTC by sepehr2github

## Description

- copyright review applied

Task: [APP-1086](https://aragonassociation.atlassian.net/browse/APP-1086)

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-10-12 10:47 UTC, RakeshUP approved these changes

2022-10-13 15:41 UTC, WissenIstNacht requested changes
Ok I'm gonna go ahead and commit this first part. (If something crashes now I'm gonna go on a loooong vacation haha)

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +    "statics": {
statistics

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "subtitle2": "find inspiration for your project, all from one place."
Can you merge this into one subtitle? Now that it's one sentence it looks weird on smaller devices when the paragraph is centered and the bottom line is larger than the top line.

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +    "analyticsHelpText": "Collects information on how you use the App",
I know this is not on you, but there should be a period at the end of this sentence...

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
>        "description": "Start simple and learn as a team. You and your community can always decide how to evolve your DAO as you go.",
Maybe this was still in debate when you were working on it, but currently it say:

Start simple and learn as you go. You can always evolve your DAO in the future.

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "shortTitle": "Select blockchain",
Duplicate

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "description": "The chain you choose is where your tokens and assets are stored. If you already have a token, choose the chain your token is minted on. *This cannot be changed later. * For help
Bro the asterisks are meant to indicate that the text should be bold :p

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "shortTitle": "Describe your DAO",
duplicate

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "metadataOverviewGuide": "read our guide"
missing period

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "nameSubtitle": "Best if under 128 characters",
Latest comment says: `Recommended 128 characters`

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
>      "daoName": "DAO Name",
On the creation flow, this has been changed to `DAO name`.

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "logoSubtitle": "JPG, PNG, GIF, or SVG of no more than 3MB. We recommend 1024x1024px",
Again, they probably forgot. But this should have  period

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "communityOverviewGuide": "read this guide",
period

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +    "membership": "Who can participate in governance?",
Could you move this one down to step 3 of dao creation? It's not really a label and it's only used there.

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +    "mintToken": "Mint your token",
There are still places in the App where this is supposed to be "Mint tokens" and not "Mint your token". (See Add members flow on ERC20 daos.)

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/containers/setupCommunity/createNewToken.tsx
> +          .
This time there's too many periods :D

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "distributeTokensHelpertext": "Add the wallets of your core team and DAO treasury here. If you don't plan on doing an initial distribution, just put your wallet and all tokens will go there. If
Period

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "shortTitle": "Select governance type",
Duplicate

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "shortTitle": "Set voting parameters",
This should replace the current title of step 4 (not only in the overview of the creation process).

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
>        "description": "These are the rules that set how voting works in your DAO. How many people have to participate? What percent counts as winning? How long may a proposal be open for voting? Learn
This one has been updated, too.

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "minimumParticipationSubtitle": "This is the percentage of voters who need to cast a vote for a vote to be valid. For example, if you set quorum at 10% and only 9% of tokens in the network are
Unnecessary space before the word "Note". Also, Asterisks are indicators for boldness

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "button": "Deploy your DAO",
duplicate

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +    "publishDao": "Deploy your DAO",
Duplicate

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +    "publishDaoSubtitle": "The fees below are the cost of using the Ethereum network.",
They haven't taken into account that this may be something else than Ethereum. I would replace "Ethereum network" with "selected blockchain".

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +    "publishDaoButtonLabel": "Approve Transaction",
Sweet, here they capitalize the second word... Dude this is killing me haha

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "description": "The chain you choose is where your tokens and assets are stored. If you already have a token, choose the chain your token is minted on. *This cannot be changed later. * For help
Bro the asterisks are meant to be bold :p

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
>      "daoName": "DAO Name",
This is used on creation flow, where it has been changed to `DAO name`

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "title": "Initiate a token transfer",
I don't know where else to put it so I'm just gonna leave it here. The Copies for the empty state for proposals has been updated, too.

2022-10-13 15:41 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "description": "Ready to distribute tokens or pay members? Initiate a token transfer here. For ideas on how to distribute your community's token, read our guide on token distribution ",
period

2022-10-13 16:09 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
>        "titlePlaceholder": "Type meaningful title",
Apparently this should just say "Title"

2022-10-13 16:10 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "summaryPlaceholder": "Describe your proposal in 2-3 sentences. This will appear in in the proposal overview... ",
No ellipsis at the end.

2022-10-13 16:12 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "proposalPlaceholder": "Write the body of the proposal here... "
No ellipsis.

2022-10-13 16:15 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
>        "description": "For a withdraw, a vote is necessary so that the majority can determine whether your proposal is legitimate. For this, you need this configuration.",
This was updated, too.

2022-10-13 16:29 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "heading": "Set Automations",
second word is lower-case.

2022-10-13 16:30 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "votePasses": "Vote passes",
I think you forgot to actually incorporate that :)

2022-10-13 16:31 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "yesOptionSubtitle": "If the vote passes, the following actions will execute automatically. If the vote fails, nothing will happen",
period

2022-10-13 16:36 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +    "item2Subtitle": "Create a proposal to withdraw assets to a wallet."
My app still shows "Whitdtaw Assests". There's a couple of version of this label in this file, some of which still have the wrong spelling. Could you remove them and use this one instead?

2022-10-13 21:12 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
>      "configureDeposit": "Configure Deposit",
Those have been update by now, too.

2022-10-13 21:39 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
>      "editDaoSettings": "Edit DAO Settings",
"settings"

2022-10-13 21:42 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
>      "newSettings": "New Settings",
Apparently "New settings" but "Edit Settings" is ok?! I need to go get some sleep...

2022-10-13 21:45 UTC, WissenIstNacht commented on packages/web-app/src/containers/transactionModals/publishModal.tsx
> +      buttonLabelSuccess || t('TransactionModal.dismiss'),
Do we have a dismiss left somewhere?

2022-10-14 08:21 UTC, sepehr2github commented on packages/web-app/src/locales/en/common.json
> +      "description": "The chain you choose is where your tokens and assets are stored. If you already have a token, choose the chain your token is minted on. *This cannot be changed later. * For help
Ah really, good to know Thanks

2022-10-14 09:33 UTC, sepehr2github commented on packages/web-app/src/locales/en/common.json
>        "titlePlaceholder": "Type meaningful title",
How do you mean?

2022-10-14 09:38 UTC, sepehr2github commented on packages/web-app/src/containers/transactionModals/publishModal.tsx
> +      buttonLabelSuccess || t('TransactionModal.dismiss'),
It was only one on deposit but updated due to the new comments

2022-10-14 09:46 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
>        "titlePlaceholder": "Type meaningful title",
https://miro.com/app/board/uXjVPTD5xRg=/?openComment=3458764535196551195

2022-10-14 12:01 UTC, sepehr2github commented on packages/web-app/src/locales/en/common.json
>        "titlePlaceholder": "Type meaningful title",
Done!

2022-10-14 13:04 UTC, sepehr2github commented on packages/web-app/src/locales/en/common.json
> +    "mintToken": "Mint your token",
Checked, seems fine by my side!

2022-10-14 13:54 UTC, WissenIstNacht approved these changes
There's still a few things that aren't perfect. But since we're gonna have to modify anyway as soon as we hear back from gtm team, we're gonna go ahead and ship it! 💪🏼

2022-10-14 13:56 UTC, merged