F/app 917
aragon/app-legacy pull request #531
Opened 2022-10-25 04:44 UTC by sepehr2github

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task: [ID]()

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2022-10-26 13:54 UTC, Fabricevladimir approved these changes
Looks good to me

2022-10-31 11:29 UTC, WissenIstNacht commented
Thanks for the PR.

For some reason I can not make the validation error pop up when creating a DAO. Could you give me a DAO name that would result in a clash and therefore shows the error?

2022-11-03 11:27 UTC, sepehr2github commented
> Thanks for the PR.
> 
> For some reason I can not make the validation error pop up when creating a DAO. Could you give me a DAO name that would result in a clash and therefore shows the error?

Hey, There is no way to test this logic because the backend hasn't implemented the ens logic and It's entirely dummy data, I've just put the logic, could tested even by myself

2022-11-03 15:17 UTC, WissenIstNacht requested changes

2022-11-03 15:17 UTC, WissenIstNacht commented on packages/web-app/src/utils/validators.ts
> +}
Yes, it is probably part of the problem as well that the SDK doesn't have that logic implemented. However, I think this code has issues as well.

See, this function is **always** going to return `true`. So even if the SDK's `resolveName` ever did return something useful, your validator function would never make use of it.

It's a bit much to explain in a comment. Let me know if you want to talk about it.

2022-11-04 09:49 UTC, WissenIstNacht commented on packages/web-app/src/utils/validators.ts
> +    if (ensAddress) return i18n.t('errors.ensDuplication');
Now you're never returning `true` :D

As far as I remember the true is necessary for when there is no error (or rather, when the input is actually valid). So I think adding `else return true` under this line would make it good to go.

2022-11-04 09:50 UTC, WissenIstNacht approved these changes
Thanks a lot for the changes.

One small modification left, but I'm approving this already :)

2022-11-04 10:32 UTC, sepehr2github commented on packages/web-app/src/utils/validators.ts
> +    if (ensAddress) return i18n.t('errors.ensDuplication');
I was about to add it ;D, thanks will fix it

2022-11-04 11:47 UTC, merged