Fix: APP-1102
aragon/app-legacy pull request #539
Opened 2022-10-31 07:52 UTC by sepehr2github

## Description

- add failed execution to the proposal details page

Task: [APP-1102](https://aragonassociation.atlassian.net/browse/APP-1102)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-11-03 10:54 UTC, Fabricevladimir requested changes
Looking good Sepher! Left a couple comments here and there, mostly about cleaning up before or after merge.

2022-11-03 10:54 UTC, Fabricevladimir commented on packages/web-app/src/context/proposalTransaction.tsx
> +        setExecutionFailed(false);
Can you set the transaction hash for both failure and success? That way it gets passed to the `ExecutionWidget` as well

2022-11-03 10:54 UTC, Fabricevladimir commented on packages/web-app/src/context/proposalTransaction.tsx
> +  const [executionFailed, setExecutionFailed] = useState(true);
Don't forget to default this to `false` before you merge unless you're going to clear this up after qa

2022-11-03 10:54 UTC, Fabricevladimir commented on packages/web-app/src/components/executionWidget/index.tsx
>      case 'defeated' as 'executable':
Please remove this `case 'defeated' as 'executable'` and uncomment the block preceding for the `defeated` case.

2022-11-03 10:54 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useDaoProposal.tsx
> +export enum ProposalStatus {
I assume this is for demonstration purposes, but please remember to cleanup before merge. Also, SDK exposes a `ProposalStatus` already

2022-11-03 10:54 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useDaoProposal.tsx
> +            status: ProposalStatus.SUCCEEDED,
Same here, don't forget to cleanup before merge

2022-11-03 10:54 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useDaoProposal.tsx
> +          setData({
[Not a code thing] I'm not sure why this broke up into multiple lines, do we have different formatter issues creeping in again? 😬

2022-11-03 10:54 UTC, Fabricevladimir commented on packages/web-app/src/utils/proposals.ts
> +              endDate,
This should be the **execution date** and not `endDate`. Because the SDK proposal will _not_ have the execution date of  a failed transaction, this should then be `new Date()` (ie now) or alternatively a date stored on the context handling the action execution (this would be more accurate technically especially if the failure is to be cached, which we haven't actually talked about but I'm not sure it's worth the hassle right now).

2022-11-04 08:46 UTC, sepehr2github commented on packages/web-app/src/hooks/useDaoProposal.tsx
> +          setData({
No, It might be a vs small issue

2022-11-04 13:12 UTC, Fabricevladimir approved these changes
Sweet 🍬

2022-11-09 10:05 UTC, WissenIstNacht approved these changes
I assume my comment isn't relevant, otherwise you or Fabrice would have noticed. Therefore, I'm approving this. If you think my comment is relevant let me know and maybe drop a todo. :)

2022-11-09 10:05 UTC, WissenIstNacht commented on packages/web-app/src/components/executionWidget/index.tsx
> +            onClick={handleTxViewButtonClick}
Does this case make sense? Is there a TX when the execution fails?

2022-11-09 10:40 UTC, sepehr2github commented on packages/web-app/src/components/executionWidget/index.tsx
> +            onClick={handleTxViewButtonClick}
AFAIK we get tx hash for failed executions, but good point will check with jose and create another ticket if needed on our todo list

2022-11-09 10:40 UTC, merged