Feature: APP-1120 Notification Feedback
aragon/app-legacy pull request #552
Opened 2022-11-11 10:15 UTC by sepehr2github

## Description

- AlertChip to ui-components Added
- Created Alert Context for managing the Alert
- enabling alertChip for web-app

Task: [APP-1120](https://aragonassociation.atlassian.net/browse/APP-1120)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-11-11 11:31 UTC, RakeshUP approved these changes

2022-11-14 10:26 UTC, Fabricevladimir requested changes
Herculean effort, my friend! Left a few comments ❤️

2022-11-14 10:26 UTC, Fabricevladimir commented on packages/ui-components/src/components/alerts/alertChip.tsx
> +  showIcon?: boolean;
@WissenIstNacht, this might be something worth mentioning to Selim in terms of interfaces for these sort of components that conditionally show an icon. Instead of two separate properties (the icon & a flag), we could consider merging the two to simplify the interfaces to something along the lines of "if icon is given, show it; if not, don't show it". That would get rid of the boolean flag.

2022-11-14 10:26 UTC, Fabricevladimir commented on packages/ui-components/src/components/alerts/alertChip.tsx
> +  @-webkit-keyframes fadein {
I think there are TW options for this btw [not a request for change]

2022-11-14 10:26 UTC, Fabricevladimir commented on packages/ui-components/src/components/alerts/alertChip.tsx
> +            width: 10,
The height and width both seem to be 12px on the designs

2022-11-14 10:26 UTC, Fabricevladimir commented on packages/ui-components/src/components/alerts/alertChip.tsx
> +    'flex items-center bg-ui-800 rounded-full px-3 py-2 space-x-1 cursor-default',
I think the background is `bg-ui-900`

2022-11-14 10:26 UTC, Fabricevladimir commented on packages/web-app/src/context/alert.tsx
> +  isOpen: boolean;
I might name this "isShown" instead, but toma-to, to-mato 😄

2022-11-14 10:26 UTC, Fabricevladimir commented on packages/web-app/src/context/alert.tsx
> +      <AlertChip {...{isOpen, label}} showIcon />
I wonder if we ever have a case where we don't actually want to show the icon 🤔

2022-11-14 10:26 UTC, Fabricevladimir commented on packages/web-app/src/components/whitelistWallets/row.tsx
>  export const Row = ({index, ...props}: WhitelistWalletsRowProps) => {
The parent component `WhitelistWallets` is missing the alerts, so when you go through DAO creation with a whitelist DAO, adding, removing, resetting, etc... doesn't show the alert 😞

2022-11-14 10:26 UTC, Fabricevladimir commented on packages/web-app/src/containers/actionBuilder/removeAddresses/index.tsx
> +                    // TODO: This needs to be added later
❤️

2022-11-14 18:47 UTC, sepehr2github commented on packages/ui-components/src/components/alerts/alertChip.tsx
> +  @-webkit-keyframes fadein {
Checked the TW, could find sth

2022-11-15 10:14 UTC, Fabricevladimir approved these changes

2022-11-15 12:46 UTC, merged