vault and simple voting implementations
aragon/app-legacy pull request #56
Opened 2021-11-24 15:16 UTC by novaknole

2021-11-24 15:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aragon/zaragoza?pullRequest=56) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aragon/zaragoza?pullRequest=56) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aragon/zaragoza?pullRequest=56) it.</sub>

2021-11-24 15:39 UTC, nivida requested changes
First of all a big thank you for finishing the Vault and SimpleVoting. I've added a few comments and will have a second look at 1-2 methods of the SimpleVoting contract tomorrow morning.

2021-11-24 15:39 UTC, nivida commented on lerna.json
> +{
EOF.. sorry haha ;-)

2021-11-24 15:39 UTC, nivida commented on package.json
> +	"name": "@aragon/zaragoza-monorepo",
@aragon/zaragoza and later on probably @aragon/aragon.

2021-11-24 15:39 UTC, nivida commented on package.json
> +		"lerna": "^3.22.1"
Is lerna required if we have yarn workspaces?

2021-11-24 15:39 UTC, nivida commented on package.json
> +	"scripts": {},
empty `scripts`

2021-11-24 15:39 UTC, nivida commented on packages/contracts/contracts/lib/governance-primitives/GovernancePrimitive.sol
> +        // the reason behind this - https://matrix.to/#/!poXqlbVpQfXKWGseLY:gitter.im/$6IhWbfjcTqmLoqAVMopWFuIhlQwsoaIRxmsXhhmsaSs?via=gitter.im&via=matrix.org&via=ekpyron.org
lol.. love this language..

2021-11-24 15:39 UTC, nivida commented on packages/contracts/contracts/lib/governance-primitives/GovernancePrimitive.sol
> +    function initialize(DAO _dao) public initializer {
why public?

2021-11-24 15:39 UTC, nivida commented on packages/contracts/contracts/lib/governance-primitives/GovernancePrimitive.sol
> +    function start(Processes.Process calldata process, Proposal calldata proposal) public returns (uint256 executionId) {
Just as a reminder to me and also you.. we have to check the state in eg. execute and other methods.. but quite simple to add this require.

2021-11-24 15:39 UTC, nivida commented on packages/contracts/contracts/src/processes/Processes.sol
> +                        if (bytes4(action.data[:4]) == allowedAction.methods[y]) { // METHOD FOUND STOP SEARCHING
Thanks to 0.8.6 🥳

2021-11-24 15:39 UTC, nivida commented on packages/contracts/package.json
> +  "name": "@aragon/zaragoza-contracts",
Let us discuss about having a package called core for the core contracts and two for the concrete implementation of the governance primitives and permission validators..

2021-11-24 15:39 UTC, nivida commented on packages/contracts/contracts/src/governance-primitives/voting/SimpleVoting.sol
> +        uint256 voteId;
I will think about this again also if we have discussed about.. hmm idk.. there has to be a cleaner way..

2021-11-24 15:39 UTC, nivida commented on packages/contracts/contracts/src/governance-primitives/voting/SimpleVoting.sol
> +        uint256 startDate;
why uint256 for the timestamp and snapshotBlock?

2021-11-24 15:39 UTC, nivida commented on packages/contracts/contracts/src/governance-primitives/voting/SimpleVoting.sol
>          dao = _dao;
I think we can now remove line 72

2021-11-24 15:39 UTC, nivida commented on packages/contracts/contracts/src/governance-primitives/voting/SimpleVoting.sol
> +        vote_.startDate = block.timestamp; // TODO:
todo?

2021-11-24 15:39 UTC, nivida commented on packages/contracts/contracts/src/governance-primitives/voting/SimpleVoting.sol
> +        emit StartVote(voteId, msg.sender, description);
will we probably not store the description on-chain and just reference a hash?

2021-11-24 15:39 UTC, nivida commented on packages/contracts/contracts/src/governance-primitives/voting/SimpleVoting.sol
> +    function _vote(uint256 _voteId, bytes calldata data) internal override {
I think we can merge those two _vote methods.

2021-11-24 15:39 UTC, nivida commented on packages/contracts/contracts/src/governance-primitives/voting/SimpleVoting.sol
> +    * @param data abi encoded data that includes necessary parameters to vote.
voteId missing in natspec.. also we can add more information.. have a look at the other contracts.. the thing is if we define the nat-spec's well can we generate better code references etc.

2021-11-24 15:39 UTC, nivida commented on packages/contracts/contracts/src/governance-primitives/voting/SimpleVoting.sol
> +    function _vote(uint256 _voteId, bool _supports, address _voter, bool _executesIfDecided) internal {
Params etc missing in natspec

2021-11-24 15:39 UTC, nivida commented on packages/contracts/contracts/src/governance-primitives/voting/SimpleVoting.sol
> +        executionExist(_voteId)
Is this required to have it as modifier? Probably better to have it as internal method cause modifiers will get duplicated..

2021-11-24 15:39 UTC, nivida commented on packages/contracts/contracts/src/governance-primitives/voting/SimpleVoting.sol
> +        executionExist(_voteId)
We also can have this check directly in _getExecution and revert if it isn't existing..

2021-11-24 15:39 UTC, nivida commented on packages/contracts/contracts/src/governance-primitives/voting/SimpleVoting.sol
> +    */
missing natspec

2021-11-24 15:39 UTC, nivida commented on packages/contracts/contracts/src/governance-primitives/voting/SimpleVoting.sol
> +        return block.timestamp < vote_.startDate + voteTime && _isVoteExecuted(vote_.voteId); // TODO:
Todo?

2021-11-24 15:39 UTC, nivida commented on packages/contracts/contracts/src/governance-primitives/voting/SimpleVoting.sol
> +    function _isVoteExecuted(uint256 _voteId) internal view returns(bool) {
Let us add this state check to the abstract GovernancePrimitive and are there any reasons to have it here as well?

2021-11-24 15:40 UTC, nivida commented on packages/contracts/contracts/lib/governance-primitives/GovernancePrimitive.sol
> +    string private constant ERROR_NO_EXECUTION = "ERROR_NO_EXECUTION";
This is not used right?

2021-11-26 12:48 UTC, novaknole commented on packages/contracts/contracts/lib/governance-primitives/GovernancePrimitive.sol
> +    function initialize(DAO _dao) public initializer {
@nivida when it's external, you can't call it from child contract at all. So moved it to public. This shouldn't bring any problems as the contracts don't call it internally in other places. so we should be good.

2021-11-26 12:49 UTC, novaknole commented on packages/contracts/contracts/src/governance-primitives/voting/SimpleVoting.sol
> +        uint256 voteId;
can we merge first and think about this later ?

2021-11-26 12:49 UTC, novaknole commented on packages/contracts/contracts/src/governance-primitives/voting/SimpleVoting.sol
> +        uint256 startDate;
Initially, `block.timestamp` and startDate return `uint256`. In the couple of days, I plan on having `uint64`.

2021-11-26 12:51 UTC, novaknole commented on packages/contracts/contracts/src/governance-primitives/voting/SimpleVoting.sol
> +        vote_.startDate = block.timestamp; // TODO:
The `todo` means I have to transform it to uint64 later on.

2021-12-02 11:36 UTC, closed without merging