Feature: APP-1293
aragon/app-legacy pull request #563
Opened 2022-11-17 06:43 UTC by sepehr2github

## Description

- Verification modal has been added

Task: [ID]()

Note: The etherscan API Verification needs an account from DevOps team, once account is got ready, The verification method will be replaced by new API

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-11-17 10:24 UTC, Fabricevladimir requested changes
Thanks Sepehr; left a few comments

2022-11-17 10:24 UTC, Fabricevladimir commented on packages/web-app/src/locales/en/common.json
> +      "modalTitle": "Smart Contract Composer",
This should be "Connect Smart Contract"

2022-11-17 10:24 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +          disabled={addressField === ''}
Because when the form first loads, `addressField` is undefined, the condition returns false, enabling the button by default instead of disabling it. I think this can be fixed by either checking explicitly if the `addressField` is undefined or by adding the types and default values to the `useForm` declaration on the `demoSCC` page. I lean slightly towards the types if only because there's a lot that will need to be connected and I can see the types benefitting us when we wire up the modals to the form. Choice is yours 👍🏾 

Also, it might be a good idea to check if `addressField` is not an empty space character, because that will trigger the button state to default and not disabled.

2022-11-17 10:24 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +                value={value}
It would seem per the designs, that the contract address is shortened in the field so that the user can see both the starting and ending characters

2022-11-17 10:24 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +            required: t('errors.required.tokenAddress') as string,
Not sure if this is within the scope, but do we need custom validation for the address? For example, if the user inputs "abc", this should probably show an error and still keep the button disabled.

2022-11-17 10:24 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +                  handleClipboardActions(value, onChange, alert)
This alert seems to be the _browser_ alert and not the `AlertChip` component

2022-11-17 10:24 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +                adornmentText={value ? t('labels.copy') : t('labels.paste')}
The adornment should be `Clear` instead of  `Copy`

2022-11-17 10:24 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +              <ValueInput
While the contract is validating and when it's successfully validated, the input should be disabled.

2022-11-17 10:24 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +      <ModalHeader
While the contract is validating and has been successfully validated, the back button should be removed/hidden.

2022-11-17 10:24 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +          iconLeft={icons[transactionState]}
When the transaction is successful, the icon should be `iconRight` instead of `iconLeft`

2022-11-17 10:24 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +    [TransactionState.ERROR]: t('scc.addressValidation.tryAgain'),
Two things concerning the error state:
1. Once the user has hit the error state, I expect that clearing the input to reset the state to `WAITING`, which should reset the button label back to the `WAITING` label. That said, can you check with Selim to make sure I'm not just spouting crap? 🤣
2. We don't necessarily have the designs for this, but I think it would make sense to keep the error state consistent with the ABI verification branch error state, meaning, setting the button label to "Retry" and showing the error, "Contract could not be verified" , on the `AlertInline` below the button. Thoughts? 🤔

2022-11-17 10:24 UTC, Fabricevladimir commented on packages/web-app/src/locales/en/common.json
> +      "actionLabelLoading": "Validate Smart Contract ...",
Small typo, text on the designs has it as "Validating Smart Contract ...". Of course, user testing might have us scrambling to change it 😄

2022-11-17 10:24 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +            await validateContract(addressField, provider, setContractValid);
Curious, why not pass in the result of `validateContract` to `setContractValid` instead like so:
```javascript
setContractValid(await validateContract(addressField, provider));
```

No change necessary, just curious.

2022-11-18 14:56 UTC, jamesej commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +                value={value}
I imagine the full address should be shown if there's enough width in the component, the shortening is a fallback to ensure the user can see the start and end of the address.

2022-11-18 15:01 UTC, jamesej commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +          disabled={addressField === ''}
Another thing that would be nice to include is to create a `FieldValues` type and use it as a generic parameter to `useFormContext` and `useWatch` so that `addressField` gets a non-`any` type.

2022-11-19 11:21 UTC, jamesej commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +            await validateContract(addressField, provider, setContractValid);
I think you should trim whitespace off `addressField` before checking it as it's very easy to cut and paste extra whitespace around something.

2022-11-22 08:28 UTC, sepehr2github commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +    [TransactionState.ERROR]: t('scc.addressValidation.tryAgain'),
This is sth that we could fix on integration phase, when we want to integrate the whole flow, what do you think?

2022-11-22 09:53 UTC, sepehr2github commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +          disabled={addressField === ''}
> Another thing that would be nice to include is to create a `FieldValues` type and use it as a generic parameter to `useFormContext` and `useWatch` so that `addressField` gets a non-`any` type.

This is sth that I wanted to do but thought might be good wait for the integration phase, we can add these types later

2022-11-22 15:45 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +    [TransactionState.ERROR]: t('scc.addressValidation.tryAgain'),
I'm not sure that they have much to do with the integration. The integration is just supposed to link the different parts together

2022-11-22 15:58 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +    console.log('check', value);
I see you

2022-11-22 15:58 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
>    [TransactionState.WAITING]: undefined,
This is a general comment and it might be a preference thing, but there is no actual transaction on this flow. It sort of throws you off because the namings are transaction related if that makes sense

2022-11-22 15:58 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +          disabled={addressField === ''}
The issue with waiting for later is that the person who does the integration doesn't necessarily know all the form fields you've used and what the nuances in terms of typing

2022-11-22 16:14 UTC, Fabricevladimir requested changes

2022-11-22 16:14 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +    () => isTransactionSuccessful || !isAddress(addressField),
When the contract has been successfully validated, the button shouldn't be disabled.

2022-11-22 16:14 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +                adornmentText={value ? t('labels.clear') : t('labels.paste')}
Once the contract itself has been validated with your `addressValidator`, 'clear' should should transition to 'copy', which once we've reenabled the adornment, will allow the user to, well, copy the address

2022-11-22 16:14 UTC, Fabricevladimir commented on packages/web-app/src/utils/validators.ts
> +    else return;
Unnecessary to return I think

2022-11-22 16:14 UTC, Fabricevladimir commented on packages/web-app/src/utils/validators.ts
> +    return;
Same here

2022-11-23 10:00 UTC, sepehr2github commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +    [TransactionState.ERROR]: t('scc.addressValidation.tryAgain'),
Yes, I meant the second point you mentioned, whoever did the ABI thing should add contract ABI verification and these minor changes

2022-11-23 16:39 UTC, Fabricevladimir approved these changes

2022-11-24 10:49 UTC, jamesej approved these changes

2022-11-24 10:49 UTC, jamesej commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +
Just a comment maybe for future reference, and this is not about your code but code that was already written, in my view in Typescript it's nicer not to use enum types like TransactionState.WAITING here but to define
`type TransactionState = "waiting" | "loading" | "success" | "error";`
This code would be more concise and readable had that been done. Enum types are good where the name of the thing is different to the value of the thing.

2022-11-24 11:02 UTC, sepehr2github commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
> +
Great, Point. Thanks. Will keep in mind

2022-11-24 11:02 UTC, merged