dao creation bug fix
aragon/app-legacy pull request #564
Opened 2022-11-21 11:57 UTC by RakeshUP

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task: [ID]()

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2022-11-21 16:30 UTC, jamesej requested changes

2022-11-21 16:30 UTC, jamesej commented on packages/web-app/src/context/createDao.tsx
>      });
I'm guessing you may want line 81 to be `: "0"` so that you always get a string type in `total_usd_cost`.

2022-11-21 16:30 UTC, jamesej commented on packages/web-app/src/context/createDao.tsx
> +      ],
Also I wonder if line 204 should be plugins: plugins.push({ id:..., data:... }). The reason being if you set plugins to this constant value, the plugins pushed onto the plugins list at lines 175 and 186 are erased. If you meant to erase them, I think you should remove that code as it now has no effect.

2022-11-24 12:44 UTC, RakeshUP commented on packages/web-app/src/context/createDao.tsx
> +      ],
the PR was still WIP when you reviewed it. should have added WIP to the title 🥺.

2022-11-24 13:45 UTC, sepehr2github commented on packages/web-app/src/context/createDao.tsx
> +        plugins.push({
Could you explain this method, Shouldn't it be on the SDK not here?

2022-11-24 13:45 UTC, sepehr2github commented on packages/web-app/src/context/createDao.tsx
> +function encodeRatio(ratio: number, digits: number): number {
Also What is this method doing?

2022-11-24 13:47 UTC, sepehr2github requested changes
Hey, Rakash. Thanks for the PR but when we created a Dao, It has gone successfully through the blockchain but It didn't exist on the subgraph, for some reason subgraph couldn't list new daos :/

2022-11-24 14:27 UTC, RakeshUP commented on packages/web-app/src/context/createDao.tsx
> +        plugins.push({
yes Sepehr, I've mentioned this in the PR description. Most of the logic will be removed once the encoders are ready on SDK. for now contract addresses and ABI is hardcoded on UI

2022-11-24 14:27 UTC, RakeshUP commented on packages/web-app/src/context/createDao.tsx
> +function encodeRatio(ratio: number, digits: number): number {
also something i copied from SDK, converts to 16 decimal Number I guess. this will also be removed

2022-11-24 16:14 UTC, jamesej approved these changes

2022-11-25 11:20 UTC, sepehr2github approved these changes
Hey, still have challenge to build the erc20 dao but because others could create dao will approve the pr and we can tackle my issue on another pr if needed

2022-11-25 12:42 UTC, merged