Feature: Navigation after DAO creation APP-1040
aragon/app-legacy pull request #572
Opened 2022-11-25 10:03 UTC by RakeshUP

## Description

Navigation to the dashboard to a new empty state upon DAO Creation. This empty state constitutes that the transaction went through, but the subgraph has not yet picked up the data.

Task: [APP-1040](https://aragonassociation.atlassian.net/browse/APP-1040)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-11-25 16:46 UTC, jamesej approved these changes
All looks good, thanks Rakesh

2022-11-26 16:25 UTC, WissenIstNacht requested changes
Hey thanks a lot for the PR. Unfortunately there's a couple of issues related to the handling of the network.

2022-11-26 16:25 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useDaoDetails.tsx
> +  const {network} = useWallet();
`useNetwork()`. At this point, the network must agree with the URL. This is not necessarily the case for the one from the wallet.

2022-11-26 16:25 UTC, WissenIstNacht commented on packages/web-app/src/pages/dashboard.tsx
> +      pollForDaoData = window.setInterval(async () => {
Side-effects should in a `useEffect` (I mean, you even already have one to to deactivate the interval 😅 )

2022-11-26 16:25 UTC, WissenIstNacht commented on packages/web-app/src/context/apolloClient.tsx
> +type PendingDaoCreation = {
Small favour: Could you comment what the keys are? I suppose the outer is the DAO id? What's the inner, then?

2022-11-26 16:25 UTC, WissenIstNacht commented on packages/web-app/src/context/createDao.tsx
> +  const {isOnWrongNetwork, provider, network} = useWallet();
I just wrote a huge comment about this and my IDE crashed. Comment gone. Sorry, you'll have to be ok with a TLDR 😅

This should go via `useNetwork`. It should NOT go through the wallet's network. (Reason: Wallet network mayb be set independetly of what is selected on the UI.).

If you're ok with that I can push a quick commit with the necessary changes.

2022-11-30 14:44 UTC, RakeshUP commented on packages/web-app/src/context/apolloClient.tsx
> +type PendingDaoCreation = {
The outer is network name and the inner one is dao id

2022-11-30 17:42 UTC, WissenIstNacht approved these changes
Hey Rakesh, thanks a lot for the changes and clarifications.

I've made two little adjustments, hope you don't mind 🤗

2022-12-01 12:49 UTC, merged