Feature: Wallet input
aragon/app-legacy pull request #574
Opened 2022-11-27 20:57 UTC by sepehr2github

## Description

- Wallet input added to UI components
- pumped SDK version

Task: [APP-1323](https://aragonassociation.atlassian.net/browse/APP-1323)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-11-28 09:26 UTC, Fabricevladimir requested changes
Thanks, Sepehr! I left a couple of comments

2022-11-28 09:26 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/walletInput.tsx
> +  disabledFilled?: boolean;
Because we don't have a situation where the adornment is ever actually disabled, I think this is more a situation and less of a state, meaning, perhaps this property is unnecessary. I find it might  make more sense to keep the interface smaller by using the `disabled` property that comes out of the box instead to conditionally render the adornment if there is a value in the disabled input. As it stands, passing `disabled` overrides `disabledFilled`

2022-11-28 09:26 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/walletInput.tsx
> +  :focus-within {
TW has a focus within, can you use that one instead?

Also, when I focus-within the input still has an outline: 
![image](https://user-images.githubusercontent.com/16927999/204240617-1d79f6d9-30bf-4489-a148-3c816037ba0d.png)

2022-11-28 09:26 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractAddressValidation.tsx
>              //TODO: This value input needs to replace with wallet input
I think you can remove this now. Also, do you know if we have a task to update the other places on the webapp that requires the `WalletInput`?

2022-11-29 09:59 UTC, sepehr2github commented on packages/ui-components/src/components/input/walletInput.tsx
> +  disabledFilled?: boolean;
I couldn't get what you want from me. could you explain a bit more?

2022-11-30 17:22 UTC, jamesej approved these changes
LGMT if Fabrice's comment at walletInput.tsx:16 is resolved.

2022-12-01 12:11 UTC, Fabricevladimir requested changes

2022-12-01 12:11 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/walletInput.tsx
> +  :focus-within {
I'm still getting this when I run Storybook

2022-12-05 13:14 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/walletInput.tsx
> +  :focus-within {
Resolved with #583

2022-12-05 13:14 UTC, Fabricevladimir approved these changes

2022-12-06 07:19 UTC, merged