APP-1301 - Removed Click rings
aragon/app-legacy pull request #583
Opened 2022-12-02 07:34 UTC by sepehr2github

## Description

- focus rings have been removed

Task: [APP-1301](https://aragonassociation.atlassian.net/browse/APP-1301)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-12-05 11:35 UTC, Fabricevladimir commented
Hey @sepehr2github, when I run Storybook, the outlines are removed on click, but focusing with the keyboard is generating a black outline instead of the `primary-500` ring. :/

2022-12-05 12:28 UTC, sepehr2github commented
> Hey @sepehr2github, when I run Storybook, the outlines are removed on click, but focusing with the keyboard is generating a black outline instead of the `primary-500` ring. :/

2022-12-05 12:29 UTC, sepehr2github commented
> Hey @sepehr2github, when I run Storybook, the outlines are removed on click, but focusing with the keyboard is generating a black outline instead of the `primary-500` ring. :/

which input??? I could find sth similar?

2022-12-05 12:42 UTC, sepehr2github commented
Just a head up: Input rings got approval from marco

2022-12-05 13:11 UTC, Fabricevladimir approved these changes

2022-12-05 17:04 UTC, WissenIstNacht requested changes
Hey @sepehr2github, thanks a lot for the work. Very nearly looks like what we want 🎉 

Unfortunately, there's still a little issue. If you zoom in onto a button, for example, you'll see two things: 
a) the ring do not quite have the right color (particularly noticeable in firefox)
b) there is a few pixels of white space around the blue rings (both firefox and chrome)

![image](https://user-images.githubusercontent.com/32465601/205696357-3531fc52-1a8e-4492-a21f-af06d675bb74.png)

It turns out that this is because of this part of the TW config: 
https://github.com/aragon/apps/blob/2cb7b122f5e1906961e6c56d7701c434e1aa5aa2/packages/ui-components/tailwind.config.js#L169-L171

If you remove these lines, the issue shown in the picture goes away and the rings are shown with proper width and color.

2022-12-06 08:03 UTC, WissenIstNacht requested changes
Hey Sepehr, thanks for the changes. Seems to work 🤞🏼

While I was browsing the app I noticed a clickable component (that is not part of the UI component library) that hasn't been updated: https://github.com/aragon/apps/blob/5f5d237e46e4ec666c675e620dd23cbd5a886ef5/packages/web-app/src/components/navLink/index.tsx#L84-L94

Sorry I didn't catch that earlier 🙏🏼

2022-12-06 08:03 UTC, WissenIstNacht commented on packages/ui-components/src/components/input/dateInput.tsx
> +  outline: 0;
Minor detail: Can we use `focus-visible:outline-none`?

2022-12-07 21:03 UTC, sepehr2github commented on packages/ui-components/src/components/input/dateInput.tsx
> +  outline: 0;
Tested this solution, It's not working for some reason!

2022-12-08 08:48 UTC, WissenIstNacht approved these changes
Let's gooo 👍🏼

2022-12-08 09:59 UTC, merged