Fix: DAO Cards on explore & Empty DAO name on header upon navigation after creation
aragon/app-legacy pull request #588
Opened 2022-12-07 11:27 UTC by RakeshUP

## Description

- DAO cards on explore page linked to the goerli dashboards. The network hardcoding needs to be removed 
- Upon navigation after DAO creation, the DAO name is empty on the navbar. Reading that from the cache during this waiting for subgraph data state

Task: [APP-1347](https://aragonassociation.atlassian.net/browse/APP-1347), [APP-1356](https://aragonassociation.atlassian.net/browse/APP-1356)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-12-07 15:10 UTC, jamesej requested changes
The DAO card links seem to work however the DAO details page shows the name of the DAO as Aragon DAO when its configured name is Yet Another DAO (app.aragon.org/#/daos/goerli/0xad21222ec1019ecbe3e53b72450ab567f8403c28). Just after the DAO was created, as it was navigating to the details page, it did show the title correctly very briefly but then it changed to Aragon DAO. Also if you click the down arrow by the Aragon DAO name by the icon at the top left on the details page, this will show a dialogue where the correct name is shown as a subheading.
This may not be in scope for this ticket, but please fix if it is.

2022-12-07 20:34 UTC, Fabricevladimir approved these changes
Looks good to me.

2022-12-09 09:45 UTC, RakeshUP commented
Hey @jamesej, I am not able to reproduce the issue you are mentioning. The DAO selector dropdown menu takes some time to fetch, after which it shows the correct name for me. There is no place in the web-app where "Aragon DAO" name is hard coded, so I am not able to find out where the issue you mention is coming from.

Please let me know if you face the issue even now. A screen recording would be very helpful

2022-12-09 16:59 UTC, jamesej approved these changes
OK got the latest version of the branch and checked again, now looks good.

2022-12-09 17:01 UTC, merged