feature/Token Card Component DAO-465
aragon/app-legacy pull request #59
Opened 2021-11-25 16:26 UTC by RakeshUP

Token card component implemented

2021-11-26 09:45 UTC, Fabricevladimir requested changes
Nice work!

2021-11-26 09:45 UTC, Fabricevladimir commented on packages/ui-components/__tests__/token.test.tsx
> +    return screen.getByTestId('daoCard');
This test isn't passing. I suspect it might be because of the test id being `daoCard` rather than `tokenCard`.
While it's not part of this task, if you could take a look at the Badge test as well, it would be very appreciated!

2021-11-26 13:53 UTC, WissenIstNacht commented on packages/ui-components/__tests__/token.test.tsx
> +    return screen.getByTestId('daoCard');
There's a fix for the badge test that on one of my PRs 👍🏼

2021-11-26 15:24 UTC, WissenIstNacht requested changes
Hey the current card looks good great.

"Small" issue though (pun intended 😉): You might have missed the mobile version of it. It's not very different, but for example it it hides the grey label and shrinks avatar and typography.

2021-11-29 12:25 UTC, RakeshUP commented
@WissenIstNacht Added the mobile version of the component. I missed checking the design system. Thanks for fixing the test case!

2021-11-29 13:38 UTC, WissenIstNacht commented
All good 👌🏼

I like the `ToggleMobileVisibility` component. Will factor it out next time I need something like this :)

2021-11-29 13:38 UTC, WissenIstNacht approved these changes

2021-11-30 09:40 UTC, Fabricevladimir approved these changes
I had missed the mobile as well 😅 . Nice work

2021-11-30 10:16 UTC, merged