Fix: Minimum duration in setup voting step of New Proposal flow
aragon/app-legacy pull request #599
Opened 2022-12-13 10:57 UTC by RakeshUP

## Description

There are some UI artifacts that are left as such for now, as there's going to be a redesign in this step.

Task: [APP-1381](https://aragonassociation.atlassian.net/browse/APP-1381)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2022-12-13 16:26 UTC, WissenIstNacht requested changes
Thanks!

2022-12-13 16:26 UTC, WissenIstNacht commented on packages/web-app/src/containers/setupVotingForm/index.tsx
> +                {days && days >= 1 && (
This displays `0` (literally the character 0 in the UI) when the check doesn't pass. Changing to `days && days >= 1 ? /*component*/ : null` does the trick.

2022-12-13 16:26 UTC, WissenIstNacht commented on packages/web-app/src/containers/setupVotingForm/index.tsx
> +                  defaultValue={days}
You'll have to go round up on `default value` and `min` in the input intself. Because if it's not exactly a day you'll be short on the duration. I guess just doing days+1 should do the trick. If people want more granular control they can use the date+time control. But up to you.

2022-12-14 12:55 UTC, sepehr2github approved these changes
Thanks Rakash, Once you addressed Vale PRs, It's good to go

2022-12-14 14:55 UTC, RakeshUP commented on packages/web-app/src/containers/setupVotingForm/index.tsx
> +                {days && days >= 1 && (
Thanks that's a good catch!

2022-12-14 14:59 UTC, RakeshUP commented on packages/web-app/src/containers/setupVotingForm/index.tsx
> +                  defaultValue={days}
Changing to days+1 for now. I guess this step is going to be redesigned pretty soon and Majority Voting plugin is incorporated into the designs. We can come back at that time to make this component more robust

2022-12-14 15:17 UTC, WissenIstNacht approved these changes

2022-12-14 15:18 UTC, merged