Feature/overview section wrapper dao 467
aragon/app-legacy pull request #61
Opened 2021-11-26 12:17 UTC by WissenIstNacht

This PR

- implements the token section wrapper
- implements the transfer section wrapper
- embeds both on the current finance page as an example

2021-11-26 14:24 UTC, RakeshUP approved these changes
Works well!

I see a few files were linted in this PR, we should do a whole project lint when the PR queue is nearly empty, so as to minimize merge conflicts. Till then we'll try to cope with lint errors!

2021-11-26 15:00 UTC, WissenIstNacht commented
Very good point, thanks for bringing it up (I always forget).

We initially agreed on formatting and linting configs. But somehow it seems like not everyone follows them (or at least not automatically). Let's sync in a meeting on this to find out where we're at.

2021-11-28 20:56 UTC, sepehr2github commented on packages/ui-components/src/components/icons/interface/index.ts
> +export {IconLinkExternal} from './icon_link_external';
Can you remove this one IconLinkExternal` has already been exported in line 22

2021-11-28 21:09 UTC, sepehr2github requested changes
Great as always! Thank you. :)

2021-11-29 08:41 UTC, WissenIstNacht commented on packages/ui-components/src/components/icons/interface/index.ts
> +export {IconLinkExternal} from './icon_link_external';
On my screen the one on line 22 is no longer there 😅 

Explanation: I started with this PR before any `ExternalLinkIcon` was exported. After Fabrice was done with his PR I rebased this one. Since he had also exported that icon on his branch there are now two exports. So I deleted one of them. But I can change which one I delete if you want ;)

2021-11-29 08:51 UTC, sepehr2github commented on packages/ui-components/src/components/icons/interface/index.ts
> +export {IconLinkExternal} from './icon_link_external';
No, It's ok hahaha. I just want to make sure It works fine. Thank you :))))

2021-11-29 08:51 UTC, sepehr2github approved these changes

2021-11-29 11:52 UTC, merged