Feature: APP-1573 & APP-1559 - Explorer
aragon/app-legacy pull request #629
Opened 2023-01-14 12:57 UTC by Fabricevladimir

## Description
This PR does the following on the Explorer page
- hides the statistics block
- removes the temporary demo DAOs block
- fixes Build Faster CTA copy 
- allows user to see retrieve more than top 4 DAOs

Task: [APP-1559](https://aragonassociation.atlassian.net/browse/APP-1559) & [APP-1573](https://aragonassociation.atlassian.net/browse/APP-1573)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2023-01-15 11:21 UTC, RakeshUP approved these changes

2023-01-16 11:59 UTC, sepehr2github approved these changes
Seems good to me

2023-01-16 12:02 UTC, WissenIstNacht requested changes
Hey there, thanks for cleaning up :)

I'm not sure why this happens, but loading the explorer page lands me on the newest DAO filter and shows me 4 DAOs, repeatedly (About 6 times or something. So 24 DAOs in total).

2023-01-16 15:05 UTC, WissenIstNacht approved these changes

2023-01-16 15:09 UTC, merged