Chore: Show Warning for Minimum Duration
aragon/app-legacy pull request #636
Opened 2023-01-17 11:36 UTC by RakeshUP

Task: [APP-1436](https://aragonassociation.atlassian.net/browse/APP-1436)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2023-01-18 17:09 UTC, Fabricevladimir commented
Hey @RakeshUP, can you rebase on top of develop, please. It's not playing well at all with my local setup 😢

2023-01-18 17:46 UTC, Fabricevladimir reviewed
Thanks 🙂, left a couple of minor comments

2023-01-18 17:46 UTC, Fabricevladimir commented on packages/web-app/src/containers/configureCommunity/index.tsx
> +                  disabled={durationDays === '365'}
Would be nice to have this in a constant like `MAX_DURATION_DAYS`

2023-01-18 17:46 UTC, Fabricevladimir commented on packages/web-app/src/containers/configureCommunity/index.tsx
> +        setValue('durationHours', '1');
Same thing for this so we don't have to hunt it all over the place if a change is needed.

2023-01-19 09:36 UTC, Fabricevladimir requested changes

2023-01-19 09:36 UTC, Fabricevladimir commented on packages/web-app/src/containers/configureCommunity/index.tsx
> +          <AlertInline
Most of this works for me, although I think it is a bit awkward. That said, I encountered an issue when you remove the value from the DAYS field (which shows an appropriate error) and then add 24+ hours to the HOURS field. The behavior is that the DAYS field get updated with the appropriate hours, but the error is not cleared.

<img width="587" alt="image" src="https://user-images.githubusercontent.com/16927999/213407334-4124a83a-ef93-434e-aa2e-969e315fbe48.png">

2023-01-19 09:48 UTC, RakeshUP commented on packages/web-app/src/containers/configureCommunity/index.tsx
> +          <AlertInline
Made some changes, please check and let me know

2023-01-19 10:27 UTC, Fabricevladimir commented on packages/web-app/src/containers/configureCommunity/index.tsx
> +          <AlertInline
Looks good 👍🏾

2023-01-19 10:28 UTC, Fabricevladimir approved these changes

2023-01-19 12:00 UTC, WissenIstNacht approved these changes
Looks good, thanks!

2023-01-19 12:51 UTC, merged