Feature: App-1437
aragon/app-legacy pull request #652
Opened 2023-01-25 08:57 UTC by sepehr2github

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task: [ID]()

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2023-01-25 09:50 UTC, RakeshUP approved these changes

2023-01-25 13:22 UTC, WissenIstNacht commented on packages/web-app/src/containers/goLive/community.tsx
> +                    : 'Anyone'}
i18n :p

2023-01-25 13:37 UTC, WissenIstNacht requested changes
Thanks a lot! :)

2023-01-25 13:37 UTC, WissenIstNacht commented on packages/web-app/src/containers/goLive/community.tsx
> +                    : 'Anyone'}
i18n :p

2023-01-25 13:37 UTC, WissenIstNacht commented on packages/web-app/src/containers/goLive/governance.tsx
> +            <Dt>{t('labels.minimumParticipation')}</Dt>
This slightly changed (additional GTE sign). Reference: https://github.com/aragon/apps/blob/7fd13ae7bab8a02e8cd04b6f51a413ced6b00e68/packages/web-app/src/pages/settings.tsx#L224

2023-01-25 13:37 UTC, WissenIstNacht commented on packages/web-app/src/pages/createDAO.tsx
> +          tokenTotalSupply === 0
Hey, are those the fixes for what we talked about in the call this morning? If so, it's not quite what I expected/understood.

2023-01-26 06:46 UTC, sepehr2github commented on packages/web-app/src/pages/createDAO.tsx
> +          tokenTotalSupply === 0
if we always set a default value for eligibilityTokenAmount we don't need to force user touch the value all the time! That's why those conditions removed!

2023-01-26 10:38 UTC, WissenIstNacht approved these changes
Sorry about the comment on the mininum support threshold not working. Something must have been wrong with my localhost. I tested it again and it works just like we discussed 👌🏼

2023-01-26 10:46 UTC, merged