Feature: Add multisig to create dao community field
aragon/app-legacy pull request #662
Opened 2023-01-30 17:01 UTC by josemarinas

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task: [APP-1703](https://aragonassociation.atlassian.net/browse/APP-1703)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2023-01-31 10:25 UTC, Fabricevladimir commented on packages/web-app/src/components/multisigWallets/row.tsx
> +                  data-testid="trigger"
This is missing the bgWhite property

2023-01-31 11:25 UTC, Fabricevladimir reviewed
Thanks, left a couple of comments

2023-01-31 11:25 UTC, Fabricevladimir commented on packages/web-app/src/components/multisigWallets/index.tsx
> +          </TableTitleContainer>
There's a divider missing under the header row

2023-01-31 11:25 UTC, Fabricevladimir commented on packages/web-app/src/components/multisigWallets/row.tsx
> +                    <ListItemAction title={t('labels.copy')} bgWhite />
Copy pasta, maybe? Label should be remove/delete

2023-01-31 11:25 UTC, Fabricevladimir commented on packages/web-app/src/components/multisigWallets/row.tsx
> +                adornmentText={value ? t('labels.copy') : t('labels.paste')}
If there is a value in the input, the adornment button should be clear instead of copy

2023-01-31 11:25 UTC, Fabricevladimir commented on packages/web-app/src/components/multisigWallets/row.tsx
> +          {isMobile && <Title>Address</Title>}
Translation string if you've time

2023-01-31 11:25 UTC, Fabricevladimir commented on packages/web-app/src/containers/setupCommunity/index.tsx
>      resetField('whitelistWallets');
This can be removed too. Not part of your changes though

2023-01-31 11:25 UTC, Fabricevladimir commented on packages/web-app/src/containers/setupCommunity/index.tsx
> +
Why not hijack this and use membership instead of eligibility only? Just curious

2023-01-31 11:59 UTC, WissenIstNacht requested changes
Thanks a lot Jose.

2023-01-31 11:59 UTC, WissenIstNacht commented on packages/ui-components/src/components/checkbox/checkboxListItem.tsx
> +  className: `py-1.5 px-2 flex-1 rounded-xl border-2 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 ${
Are you sure this is not disrupting existing items that may be wrapped in a flex display? I know it's unlikely, just want to make sure.

2023-01-31 11:59 UTC, WissenIstNacht commented on packages/web-app/src/locales/en/common.json
> +      "summary": "Summary"
Already exists as a label :)

2023-01-31 11:59 UTC, WissenIstNacht commented on packages/web-app/src/components/multisigWallets/row.tsx
> +        <RowContainer>
If it's not necessary to have the `RowContainer` and `Title` inside the `Controller`, could you move them out?

2023-01-31 11:59 UTC, WissenIstNacht commented on packages/web-app/src/components/multisigEligibility/index.tsx
> +      defaultValue={'multisig'}
Same here. If you can, move it would be nice if you could move things out of the controller that are not necessary inside it.

2023-01-31 15:07 UTC, josemarinas commented on packages/ui-components/src/components/checkbox/checkboxListItem.tsx
> +  className: `py-1.5 px-2 flex-1 rounded-xl border-2 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 ${
It was the only way I managed to do it, believe me I tried without editing the ui components, but I couldn't make work any solution with the current tools, the only one I found was selecting the child with tailwind, but its only available on version 3 (we use version 2) and upgrading tailwind broke a lot of stuff. I checked the ones in dao creation and didn't break anything I didnt do a deep dive into all the instances and check with the design if this breaks anything because its a looooot of time, buy since it's only a `flex-1` should be no problem, it could cause a problem if in some place we have this and dont want it to grow for some reason

2023-01-31 15:15 UTC, josemarinas commented on packages/web-app/src/components/multisigWallets/row.tsx
> +        <RowContainer>
Sure :)

2023-01-31 15:15 UTC, josemarinas commented on packages/web-app/src/components/multisigWallets/row.tsx
> +          {isMobile && <Title>Address</Title>}
Forgot about it, my bad

2023-01-31 16:09 UTC, josemarinas commented on packages/web-app/src/containers/setupCommunity/index.tsx
> +
Not sure I'm following, the idea behind this is that if for some reason you change from multisig to token the default option is still marked

2023-01-31 16:20 UTC, josemarinas commented on packages/web-app/src/components/multisigWallets/index.tsx
> +          </TableTitleContainer>
Solved

2023-01-31 22:19 UTC, WissenIstNacht commented on packages/ui-components/src/components/checkbox/checkboxListItem.tsx
> +  className: `py-1.5 px-2 flex-1 rounded-xl border-2 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 ${
Haha, in that case I'd rather risk breaking a Checkbox input somwhere rather than upgrading to TW3 :D

Thanks for the answer. Should be good for now 👍🏼

2023-01-31 22:23 UTC, WissenIstNacht approved these changes

2023-02-01 01:09 UTC, Fabricevladimir approved these changes
Good to go after these two tiny comments 👍🏾

2023-02-01 01:09 UTC, Fabricevladimir commented on packages/web-app/src/components/multisigEligibility/index.tsx
> +                </Title>
Can you use the Label component for this? The styling is slightly off with the newly created `Title` component here.

2023-02-01 01:09 UTC, Fabricevladimir commented on packages/web-app/src/components/multisigWallets/index.tsx
> +  className: 'ft-text-base desktop:font-bold font-semibold text-ui-800',
Real quick, in the Tailwind config file, can you add the corresponding `semibold` key under the `fontWeight` property?

2023-02-01 01:25 UTC, Fabricevladimir commented on packages/web-app/src/components/multisigWallets/index.tsx
> +              />
Not on you, but something is up with this button mode. It's `ghost` in the designs, but button `ghost` doesn't have the gray background. I'm confused!

2023-02-01 09:03 UTC, josemarinas commented on packages/web-app/src/components/multisigWallets/index.tsx
> +              />
Yes a bit weird I forgot to add a bgWhite to make the button gray so I added it

2023-02-01 11:35 UTC, merged