Feature: APP-1540 - Multisig - Proposal Duration Warnings
aragon/app-legacy pull request #663
Opened 2023-01-30 21:09 UTC by Fabricevladimir

## Description

- Adds warnings for minimum duration 

Task: [APP-1540](https://aragonassociation.atlassian.net/browse/APP-1540)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2023-02-01 12:54 UTC, jamesej requested changes
Hi if you choose Specific Date & Time for Start Time, the time field doesn't update properly when you try to edit it. I'd guess the loop between the update event and the rerendering has issues.

2023-02-02 11:45 UTC, WissenIstNacht requested changes
Thanks a lot Fabrice! Lots of good things in here. I've left some comments on structure. 

Additionally: 
a) I'm not sure where the issue comes from, but your enddates do not consider the start offset. E.g., if the current time is 10AM, the start time will be 10:10 AM but the end date will be 11am instead of 11:10AM. This is visible in the last proposal review when you just step through the flow normally.
b) I think landing on the vote setup screen has reset the times pretty much every time I did it. I don't think that should be the case.

2023-02-02 11:45 UTC, WissenIstNacht commented on packages/web-app/src/containers/dateTimeSelector/index.tsx
> +  const {days, hours, minutes} = {...defaultOffsets, ...defaultDateOffset};
Since these are a type `Offset` and the only place your using them is as arguments of type `Offset`, you might get by without destructuring the object. But no biggie :)

2023-02-02 11:45 UTC, WissenIstNacht commented on packages/web-app/src/containers/dateTimeSelector/useDateTimeSelector.ts
> +// NOTE: Keeping this in the dateTimeSelector folder despite
I really wouldn't. The only thing that's really going to change if you put this here is that other people will put other hooks wherever. It very much doubt that it will prevent people from forgetting this hook when using the `DateTimeSelector` as a) they will just copy existing code in the first place and b) mess it up anyway, because people just mess up lol.

Also, the file really should have a tsx ending.

2023-02-02 11:45 UTC, WissenIstNacht commented on packages/web-app/src/containers/setupVotingForm/tokenVoting.tsx
> +                  <DateTimeSelector
Are you intentionally nesting this inside the `Controller` with `name="durationSwitch`? I mean, the `Duration` and `DateTimeSelector` come with their own `Controllers` already. I'm not sure if or what the implications are of nesting controllers, but it seems wrong somehow.

Edit: Same question for `Duration`, obviously.

2023-02-02 11:45 UTC, WissenIstNacht commented on packages/web-app/src/containers/dateTimeSelector/useDateTimeSelector.ts
> +export const useDateTimeSelectorValidation = (
I'm struggling a bit with this one. It seems to me like all this code could just be inside the `DateTimeSelector`, no? (Obviously you'd have to pass some getters/setters between parent and child). It seems so tightly linked to the `DateTimeSelector` component that I don't really see the benefit of extracting it into a hook. I mean, you said it yourself, the component and this hook are inseparable.

2023-02-02 13:06 UTC, Fabricevladimir commented on packages/web-app/src/containers/dateTimeSelector/index.tsx
> +  const {days, hours, minutes} = {...defaultOffsets, ...defaultDateOffset};
Saves me keystrokes to destructure them 😄

2023-02-02 13:11 UTC, Fabricevladimir commented on packages/web-app/src/containers/dateTimeSelector/useDateTimeSelector.ts
> +export const useDateTimeSelectorValidation = (
Got feedback on this as well from James. I can get away with the validator in `DateTimeSelector`, but the other methods, not so much, especially since most are targeting the togglers. I'll take those out and essentially copy them over in both TokenVoting & Multisig forms

2023-02-02 13:21 UTC, Fabricevladimir commented on packages/web-app/src/containers/setupVotingForm/tokenVoting.tsx
> +                  <DateTimeSelector
This shouldn't have any effect. Saves from having to watch both toggle values.

2023-02-02 17:16 UTC, jamesej approved these changes
OK All good now thanks. Issue with timezones jumping to GMT+0 on dateTimeSelector being corrected to now from time in past now is in another ticket.

2023-02-02 21:40 UTC, WissenIstNacht approved these changes
LGTM!

2023-02-02 22:39 UTC, merged