Feat: APP-1694 Minimum Proposal Threshold settings.
aragon/app-legacy pull request #664
Opened 2023-01-30 22:18 UTC by WissenIstNacht

## Description

Allow to change the minimum proposal threshold parameter as part of the normal settings flow for MV DAOs.

Task: [1694](https://aragonassociation.atlassian.net/browse/APP-1694)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

2023-01-31 12:43 UTC, Fabricevladimir approved these changes
Looks good 👍🏾

2023-01-31 12:43 UTC, Fabricevladimir commented on packages/web-app/src/pages/editSettings.tsx
> +              <AccordionItem
It's slightly confusing having this as a community change when it appears under governance settings in the actions & action cards, but I'm guessing that's a design thing.

2023-01-31 14:18 UTC, WissenIstNacht commented on packages/web-app/src/pages/editSettings.tsx
> +              <AccordionItem
Horrible. But got it confirmed by Selim. The idea being that it needs to align with the DAO creation and the settings views.

2023-01-31 17:56 UTC, jamesej requested changes
I came across a minor display issue in that the New Settings display has a decimal '10.0' and the Old Settings display has none
<img width="325" alt="ProposeSettingsOldSettingsProposalThreshold" src="https://user-images.githubusercontent.com/458150/215843606-86e51269-f4f3-4900-853d-a7ee6b1177bd.png">
<img width="343" alt="ProposeSettingsNewSettingsProposalThreshold" src="https://user-images.githubusercontent.com/458150/215843639-c54d4acf-f7ab-40c1-8d96-e53345ead34b.png">
 '10'. It might be that the actual new value has a decimal rounding issue and is very slightly larger than 10.

2023-02-01 17:10 UTC, jamesej approved these changes
Thanks Vali all good now

2023-02-01 17:26 UTC, merged