App 1684
aragon/app-legacy pull request #665
Opened 2023-01-31 10:04 UTC by sepehr2github

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task: [ID]()

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2023-02-01 11:58 UTC, RakeshUP approved these changes
The PR is still in draft!

2023-02-03 14:51 UTC, WissenIstNacht requested changes
Hey there, thanks for the PR. Unfortunately, that the doesn't quite fix the error 😅

2023-02-03 14:51 UTC, WissenIstNacht commented on packages/web-app/src/pages/proposal.tsx
> +    else if (canVote && !earlyExecution) {
This is not gonna work :( 
  
Because if your DAO has EE enabled. this will always evaluate to false, thereby ignoring `canVote`.

2023-02-05 20:44 UTC, sepehr2github commented on packages/web-app/src/pages/proposal.tsx
> +    else if (canVote && !earlyExecution) {
> This is not gonna work :(
> 
> Because if your DAO has EE enabled. this will always evaluate to false, thereby ignoring `canVote`.
> 
> // Edit: Note that simply removing the negation will not make it work either. Because than you'd only be able to vote in a DAO with EE.

Thanks for the review, Conditions changed to fix the issue

2023-02-07 10:29 UTC, WissenIstNacht approved these changes
Hey Sepehr, thanks for the changes. The button seems to work.

2023-02-07 10:47 UTC, merged