Feature/fetch today token data - DAO-506
aragon/app-legacy pull request #67
Opened 2021-12-01 14:03 UTC by Fabricevladimir

Added the following hooks:
- `useIsMounted` - to determine whether component is mounted before setting the state to avoid memory leak warning
- `useInterval` - run useEffect callback at specified interval 
- `usePollTokens` - combination of previous hooks that fetches the **current** USD value for given token list

2021-12-02 08:46 UTC, sepehr2github commented on packages/web-app/src/pages/finance.tsx
> +const TOKENS = [
I Think It's better to put all contacts inside a file on the contacts folder

2021-12-02 09:15 UTC, sepehr2github commented on packages/ui-components/src/components/tokenCard/token.tsx
>  export type TokenCardProps = {
On line 8 there is a type warning --> Type 'string | null' is not assignable to type 'string' for tokenSymbolURL

2021-12-02 09:15 UTC, sepehr2github reviewed
Well Done! It's a big move on our roadmap. Thank you

2021-12-02 11:15 UTC, WissenIstNacht commented on packages/web-app/src/pages/finance.tsx
> +                  tokenSymbolURL={token.imgUrl}
As Sepehr mentioned over in `ui-components` this field may not take a null value. I agree with that approach. It keeps presentational components as dumb as possible, thereby separating responsibility.
This means the data must be checked (and any default values assigned) before passing it to the component. 

On a different, but related note. I missed this when reviewing @RakeshUP's PR. On the `TokenCard` component: Even with non-null props and default values there's still a chance that something  goes wrong when fetching the token icon. Could you add a default symbol/icon/thing to the code base's assets and call it `onError` on the img component?

2021-12-02 11:28 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useInterval.tsx
> + * @param callback Function to run after each interval. Defaults to 60000ms
300000?

2021-12-02 11:46 UTC, WissenIstNacht commented on packages/web-app/src/hooks/usePollTokens.tsx
> +        const price = await fetchTokenUsdPrice(address);
Is there a technical reason for not using `Promise.all()` here instead of awaiting prices in sequence?

2021-12-02 12:07 UTC, WissenIstNacht requested changes
Nice, works well!

Left a couple of minor remarks. Also, let me know if I misunderstood something about the sequential use od async/await, as this may have a sizeable impact on performance.

2021-12-02 12:07 UTC, WissenIstNacht commented on packages/web-app/src/pages/finance.tsx
> +            })}
I know the designs aren't there yet, but could you add a simple component that says "No token information available" if `prices` is null?

2021-12-02 12:38 UTC, Fabricevladimir commented on packages/ui-components/src/components/tokenCard/token.tsx
>  export type TokenCardProps = {
@WissenIstNacht I want to address part of your comment here as well.
The issue with this is that there are tokens have null for their icons because newly created ones don't have an icon. That said, there is a placeholder for these tokens in the designs, and I would prefer having the component itself render the placeholder as opposed to passing the placeholder icon (I think it's just a rounded element?) for the following reasons:

1. We can check if the icon is a broken icon (img onError) and display the placeholder only if the placeholder exists in the TokenCard itself.
2. Dev experience: anyone using the token card will have to create a placeholder icon if their token has no icon when it could have worked out of the box. 
2. (Semantics really lol) Passing the placeholder icon into the token card is passing 'falsy' data because that icon is not the token's icon in actual fact. 

I don't think that checking if a source is given makes the component less dumb because it doesn't need to hold state to do that.

2021-12-02 14:28 UTC, Fabricevladimir commented on packages/web-app/src/pages/finance.tsx
> +const TOKENS = [
I'm keeping `TOKENS` on this page to show that the token data will not be imported from a different module but either passed as props or queried inside  the Finance page itself

2021-12-02 14:39 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useInterval.tsx
> + * @param callback Function to run after each interval. Defaults to 60000ms
No, 60000 lol

2021-12-02 18:24 UTC, Fabricevladimir commented on packages/web-app/src/pages/finance.tsx
> +            })}
Wait, you at least have the DAO token no? So there should never be a case where there are no tokens to display...

2021-12-03 10:05 UTC, WissenIstNacht commented on packages/web-app/src/pages/finance.tsx
> +            })}
Ok, but isn't the presence of this token also dependent on fetching data (e.g. a subgraph call)? What happens if that fails?

2021-12-03 10:11 UTC, Fabricevladimir commented on packages/web-app/src/pages/finance.tsx
> +            })}
This is a design/UX issue I think. The user should be aware that there was an error fetching their token and not that they have **no** tokens because one says there is an abnormal state and the other, oops your tokens are all gone. I can add a placeholder for it, but I think a better approach is necessary.

2021-12-03 11:05 UTC, WissenIstNacht commented on packages/web-app/src/pages/finance.tsx
> +            })}
Fair enough, hadn't thought about that. :)

2021-12-03 11:15 UTC, WissenIstNacht approved these changes
Thanks for all the changes. Looks good to me!

2021-12-03 18:46 UTC, sepehr2github approved these changes

2021-12-03 19:19 UTC, merged