Feature: APP-1542 - Multisig DAO - Proposal Gating
aragon/app-legacy pull request #678
Opened 2023-02-04 22:55 UTC by Fabricevladimir

## Description

- Gates proposal creation based on membership and DAO settings 

Task: [APP-1542](https://aragonassociation.atlassian.net/browse/APP-1542)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2023-02-06 15:12 UTC, jamesej requested changes
Isn't working correctly as it stands, see my comment in files.

2023-02-06 15:12 UTC, jamesej commented on packages/web-app/src/components/protectedRoute/index.tsx
>      else close('gating');
The test here isn't right, it shouldn't be checking if filteredMembers.length is zero but rather if the current user is in that list. I wrote some code that seems to fix it:

```
  const gateMultisigProposal = useCallback(() => {
    if ((daoSettings as MultisigVotingSettings).onlyListed === false) {
      close('gating');
    } else if (
      !filteredMembers.some(mem => mem.address === address) &&
      !membersAreLoading
    ) {
      open('gating');
    } else {
      close('gating');
    }
  }, [membersAreLoading, close, daoSettings, open, address, filteredMembers]);
```

2023-02-06 15:42 UTC, Fabricevladimir commented on packages/web-app/src/components/protectedRoute/index.tsx
>      else close('gating');
Wait, but doesn't `filteredMembers` returning 0 signify that the user isn't in the list of members anyway?🤔

2023-02-07 09:43 UTC, jamesej commented on packages/web-app/src/components/protectedRoute/index.tsx
>      else close('gating');
Lol OK I didn't check what useDaoMembers actually did, and see that it is filtering by address. I checked again - there is an issue in that you get gated out in a DAO where anyone can make proposals, because in the current code the condition at line 77 doesn't return from the function and reopens the gating at line 80. So actually it's the `else if` you need.

2023-02-07 09:46 UTC, jamesej commented on packages/web-app/src/components/protectedRoute/index.tsx
>      else close('gating');
Perfect example for the doubters of why loads of if/thens in your code is a bad idea! :wink:

2023-02-08 11:58 UTC, WissenIstNacht approved these changes
Works for me, thanks.

2023-02-08 11:58 UTC, WissenIstNacht commented on packages/web-app/src/components/protectedRoute/index.tsx
> +      {!isGatingOpen && <Outlet />}
A part of me really like this, a part really doesn't haha. No need to change though

2023-02-08 11:59 UTC, RakeshUP approved these changes

2023-02-08 14:28 UTC, Fabricevladimir commented on packages/web-app/src/components/protectedRoute/index.tsx
> +      {!isGatingOpen && <Outlet />}
Hahaha! It annoyed me a bit because the scroll bar would suddenly pop up when the proposal creation page actually loaded in the background so I was like, you know what go away!

2023-02-08 14:35 UTC, jamesej approved these changes
All good thanks

2023-02-08 14:36 UTC, merged