Chore: Fix spacing issues in Explore page and List-Item-Header
aragon/app-legacy pull request #680
Opened 2023-02-06 11:18 UTC by RakeshUP

Task: [APP-1504](https://aragonassociation.atlassian.net/browse/APP-1504), [APP-1506](https://aragonassociation.atlassian.net/browse/APP-1506)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

[APP-1504]: https://aragonassociation.atlassian.net/browse/APP-1504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-1506]: https://aragonassociation.atlassian.net/browse/APP-1506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-02-07 11:13 UTC, sepehr2github approved these changes
Thanks

2023-02-09 09:39 UTC, WissenIstNacht requested changes

2023-02-09 09:39 UTC, WissenIstNacht commented on packages/web-app/src/containers/carousel/index.tsx
> +  className: 'relative -mt-13 mb-5 -mx-2 tablet:-mx-3 desktop:mx-0',
This doesn't quite correspond to the designs :(

With this, the carousel is completely below the colored section, while it should be half on top of the colored section and half on top of the white one.

2023-02-09 10:26 UTC, RakeshUP commented on packages/web-app/src/containers/carousel/index.tsx
> +  className: 'relative -mt-13 mb-5 -mx-2 tablet:-mx-3 desktop:mx-0',
Thanks for catching that. I think my hot reload didn't work properly when I made that change. And my placebo made me believe that the card had actually moved by 16px! :)

2023-02-09 16:41 UTC, WissenIstNacht requested changes
I'm really sorry for the situation with the button ticket, Rakesh.

Nevertheless, the current changes can't be merged in. I would suggest taking those changes out and just proceed with the other two tickets.

And thanks for addressing the comments 👍🏼

2023-02-09 16:41 UTC, WissenIstNacht commented on packages/ui-components/src/components/button/buttonBase.tsx
> +  small: {minWidth: '64px'},
This is not really feasible :/

This makes some buttons in the app too wide. E.g., icons and pagination.

2023-02-10 08:34 UTC, WissenIstNacht approved these changes

2023-02-10 10:17 UTC, merged