Fix: calendar date input double icon
aragon/app-legacy pull request #704
Opened 2023-02-13 09:06 UTC by baxri

## Description

When the Date Input field is displaying (e.g. on proposal creation when selecting ‘Specific Date + Time’), there is a double display of the calendar icon (Firefox issue only!).

[https://aragonassociation.atlassian.net/browse/APP-1750](https://aragonassociation.atlassian.net/browse/APP-1750)

2023-02-13 14:03 UTC, jamesej requested changes

2023-02-13 14:03 UTC, jamesej commented on packages/ui-components/src/components/input/dateInput.tsx
>    let className = `${baseClasses}`;
Input container needs to have the class for 'position:relative' added because the Overlay which has position:absolute won't use the input container as the base for it's positioning otherwise. Maybe you had this set up as a manual style and forgot to add it. Also the horizontal positioning of Overlay is wrong - maybe another manual style that didn't get added?

2023-02-14 05:35 UTC, WissenIstNacht requested changes
Hey there, thanks for the PR, cool stuff.

There is a small issue with the changes, though. As it stands, the date input now has two icons (a chevron down and the calendar icon) when using chrome on mobile.

If you can make that go away and keep the rest of changes, then that's fine with me. Otherwise, I would suggest just getting rid of the custom icon on Firefox. I.e., just delete the `{isFF && ...` section in the component.

2023-02-14 08:20 UTC, WissenIstNacht commented
Update: Hey, @baxri,  I didn't see @jamesej had reviewed the PR before me. Sorry, didn't want to step on anyone's toes :D

2023-02-14 12:17 UTC, baxri commented
> 

May be it it better to remove custom Icon for now, since there might be some other headaches, it works in a different in all browsers. What do you think? just to lease default icon and behavior for this date input?

2023-02-14 12:35 UTC, WissenIstNacht approved these changes
Hey @baxri, yes this is what I meant. Thanks a lot 😊 👍🏼

2023-02-16 10:44 UTC, WissenIstNacht approved these changes

2023-02-16 11:53 UTC, jamesej approved these changes
All good thanks

2023-02-16 12:07 UTC, merged