Chore: Proposals improvements
aragon/app-legacy pull request #708
Opened 2023-02-14 08:53 UTC by baxri

## Description

New proposals are added on the bottom of the ‘Proposal Cards list’ at the Governance Page (e.g. see image 1 below), instead of on top of the list. and general improvements.

https://aragonassociation.atlassian.net/browse/APP-1748

2023-02-14 11:25 UTC, sepehr2github commented on packages/web-app/src/pages/governance.tsx
> +  // Othervise it means there is a show more was clocked
clicked? spelling issue

2023-02-14 11:54 UTC, sepehr2github requested changes
Cool, Thanks George, But I found some points such as:
The loading button should be hidden when navigating through the proposal type filter, also filter doesn't work properly

2023-02-14 13:34 UTC, baxri commented
> Cool, Thanks George, But I found some points such as: The loading button should be hidden when navigating through the proposal type filter, also filter doesn't work properly

@sepehr2github  good catch, this is problem in current version also of the app. I will fix it.

2023-02-15 06:57 UTC, sepehr2github approved these changes
Thanks, Goerge. Much better now. LGTM 👍

2023-02-15 10:25 UTC, merged