transfer sections added
aragon/app-legacy pull request #72
Opened 2021-12-05 19:47 UTC by sepehr2github

- Just all transfer sections added

2021-12-06 16:22 UTC, WissenIstNacht commented on packages/web-app/src/pages/transfers.tsx
> +        <TransferSectionWrapper title={'November'}>
I think this should be computed dynamically.

Also, this must be translatable to different language.

2021-12-06 16:26 UTC, WissenIstNacht commented on packages/web-app/src/pages/transfers.tsx
> +        <TransferSectionWrapper title={'2021'}>
Same here

2021-12-06 17:01 UTC, WissenIstNacht requested changes
Thanks mate. I think it should be possible to set the sections titles dynamically.

2021-12-06 17:01 UTC, WissenIstNacht commented on packages/web-app/src/pages/transfers.tsx
> +        <TransferSectionWrapper title={'November'}>
I think this should be computed dynamically.

Also, this must be translatable to different language.

2021-12-06 17:01 UTC, WissenIstNacht commented on packages/web-app/src/pages/transfers.tsx
> +        <TransferSectionWrapper title={'2021'}>
Same here

2021-12-07 10:23 UTC, Fabricevladimir commented on packages/web-app/src/pages/transfers.tsx
> +import {TransferSectionWrapper} from 'components/sectionWrapper';
If we are using these guys outside of the finance overview page, we could combine them into one SectionWrapper or ListGroup component that shows IconButton and SeeAllButton conditionally. That said, this probably shouldn't be done right now.

2021-12-07 10:27 UTC, Fabricevladimir reviewed
Looks good. We'll be able to flesh out the page easily now.

2021-12-07 10:27 UTC, Fabricevladimir commented on packages/web-app/src/pages/transfers.tsx
> +        <TransferSectionWrapper title={'November'}>
Agreed. There was a thread about a formatting and date library. Lets see if we can agree on one quickly so we can use it there.

2021-12-07 10:27 UTC, Fabricevladimir commented on packages/web-app/src/pages/transfers.tsx
> +const ColoredDiv = styled.div.attrs({className: 'h-6 w-full bg-blue-100'})``;
`blue-100` isn't part of the design system, is it?

2021-12-07 10:36 UTC, WissenIstNacht commented on packages/web-app/src/pages/transfers.tsx
> +const ColoredDiv = styled.div.attrs({className: 'h-6 w-full bg-blue-100'})``;
I think he copy pasted from my PR a while back, sorry for that. 😅

That being, said their just placeholders 👍🏼

2021-12-07 11:26 UTC, sepehr2github commented on packages/web-app/src/pages/transfers.tsx
> +const ColoredDiv = styled.div.attrs({className: 'h-6 w-full bg-blue-100'})``;
@Fabricevladimir, I copied from @WissenIstNacht as a placeholder. All the ColoredDiv will remove soon

2021-12-07 14:39 UTC, Fabricevladimir commented on packages/web-app/src/pages/transfers.tsx
> +const ColoredDiv = styled.div.attrs({className: 'h-6 w-full bg-blue-100'})``;
Pffft! I didn't even realize that it was for the placeholder. This one is on me

2021-12-07 14:53 UTC, sepehr2github commented on packages/web-app/src/pages/transfers.tsx
> +        <TransferSectionWrapper title={'November'}>
I had the same idea but due to lack of transfers data. It's not clear to me what do you expect?
@Fabricevladimir 
@WissenIstNacht

2021-12-07 14:54 UTC, sepehr2github commented on packages/web-app/src/pages/transfers.tsx
> +import {TransferSectionWrapper} from 'components/sectionWrapper';
Good idea. We will definitely do that

2021-12-07 15:08 UTC, WissenIstNacht commented on packages/web-app/src/pages/transfers.tsx
> +        <TransferSectionWrapper title={'November'}>
What would you do if you had data? :)

Essentially, there's two things that need to be done here: 

1. Determine what is the last week, month, year (and/or maybe older). Note, this has nothing to do with transfer data being available.
2. Categorize data according to the answers above.

The first step could be done with a simple `utils` type of function that returns the date that delimit the categories (`getDateCategories: () => dates[]`). The second could be done with a hook that takes transfer data and splits them up into these categories (`useCategorizedTransfers: (TransferData[]) => TransferData[][]`). For this step, I think we'll have to assume that there will be some type like `TransderData` that will contains some form of date.

2021-12-10 09:41 UTC, closed without merging

2021-12-10 10:23 UTC, WissenIstNacht commented
Hey @sepehr2github why did you close this PR? 😅

2021-12-13 07:31 UTC, sepehr2github commented
> Hey @sepehr2github why did you close this PR? 😅

Because I want to open another PR. :)))

2021-12-13 09:20 UTC, WissenIstNacht commented
But you can have several open PRs ...? :)

Are you going to continue working on this later or your not going to be working on this anymore?