Fix: Alpha Launch chain Fix
aragon/app-legacy pull request #740
Opened 2023-02-24 10:00 UTC by sepehr2github

## Description

- Fix search input clear action
- Fix dev Related copy issues
- Remove other chains except for goerli & mainnet from dao creation
- Add Network hook to useClient

Task: [APP-1857](https://aragonassociation.atlassian.net/browse/APP-1857) - [APP-1860](https://aragonassociation.atlassian.net/browse/APP-1860) - [APP-1813](https://aragonassociation.atlassian.net/browse/APP-1813)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

[APP-1857]: https://aragonassociation.atlassian.net/browse/APP-1857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-1860]: https://aragonassociation.atlassian.net/browse/APP-1860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-1813]: https://aragonassociation.atlassian.net/browse/APP-1813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-02-25 08:46 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useClient.tsx
> +
What does the wallet's `chainId` do here? The wallet is never responsible for telling the app which network it's in. As the todo said, all this needed was to add the line `const {network} = useNetwork();` and then delete the line `const network = 'goerli';`.

//Little detail: Since SDK is going with `mainnet` instead of `ethereum` you'll have to do `network === 'ethereum' ? 'mainnet' : network` when assigning the network in the `contextParams` object.

2023-02-25 14:52 UTC, sepehr2github commented on packages/web-app/src/hooks/useClient.tsx
> +
Hey, So there are two pages that don't have a network in their path, explore page and dao creation, for dao creation it doesn't matter because It will check the user selection but for explore page which newest daos are there we had to select a chain so we decided to show the active daos according to wallet chain

2023-02-25 14:52 UTC, sepehr2github commented on packages/web-app/src/hooks/useClient.tsx
> +      network: activeNetwork === 'ethereum' ? 'mainnet' : 'goerli',
@WissenIstNacht It's already there ?!

2023-02-26 07:09 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useClient.tsx
> +
Well, that's still wrong and you'll have problems sooner or later if you query the `chainId` from the wallet inside this hook. If you want to have a special behavior for the explorer page, than you should do that in the explorer page and not here.

The network context gives you a callback called `setNetwork`, which lets you set the network for the app.  So if you want a specific network on the explorer page (for example, the user's current wallet network), you take the logic that you have here and use it in the explorer page to set the network.

As a side comment: When exactly would `activeNetwork` be the user's wallet network? `network` will always either be `goerli` or `ethereum`, so it will always exit after the first if statement...?

2023-02-26 07:10 UTC, WissenIstNacht commented on packages/web-app/src/hooks/useClient.tsx
> +      network: activeNetwork === 'ethereum' ? 'mainnet' : 'goerli',
Yes, this you would have to keep. But you will have to replace `goerli` at the end with `network` sooner or later.

2023-02-26 13:32 UTC, sepehr2github commented on packages/web-app/src/hooks/useClient.tsx
> +      network: activeNetwork === 'ethereum' ? 'mainnet' : 'goerli',
yes but for now, let's go with this condition, will update later on, because it useNetwork type the mainnet input doesn't exist

2023-02-27 06:22 UTC, sepehr2github commented on packages/web-app/src/hooks/useClient.tsx
> +
I found out the use network has a default value, So in this case It doesn't need setNetwork in explore page also in the future It will keep the last network variable, Which would be fine for now, Also in the use network state the default value should be Ethereum but I used goerli for now because the mainnet contract data is not there

2023-02-27 18:20 UTC, jamesej requested changes
Looks good except for this one minor thing about defaulting to the tab that shows the default network in DAO creation

2023-02-27 18:20 UTC, jamesej commented on packages/web-app/src/containers/selectChainForm/index.tsx
This I think should be `useState<NetworkType>('main');` because mainnet is the default selection and you can't see your default selection if this defaults to 'test' as now.

2023-02-28 08:13 UTC, jamesej approved these changes
All good! many thanks

2023-02-28 08:24 UTC, merged