WIP: Updated wallet connect
aragon/app-legacy pull request #787
Opened 2023-03-09 13:39 UTC by baxri

https://aragonassociation.atlassian.net/jira/software/c/projects/APP/boards/40/backlog?view=detail&selectedIssue=APP-2004&issueLimit=100&assignee=63e28d68724a5c79c7bb2abf

2023-03-09 16:57 UTC, jamesej commented on packages/web-app/src/hooks/useWallet.tsx
> +  };
Nothing wrong with this, just a tip: you can use Promise.resolve(value) to make an already resolved promise with the value passed in. So you could write
```
disconnect: () => {
  disconnect();
  return Promise.resolve(true);
}
```

2023-03-10 09:32 UTC, sepehr2github commented on packages/web-app/src/utils/constants/api.ts
> +export const walletConnectProjectID = 'a405a1eafd0773a279ad607c01a546ae';
This need to be handled in env file

2023-03-10 09:47 UTC, sepehr2github commented on packages/web-app/src/index.tsx
> +  walletConnectProvider({projectId: walletConnectProjectID}),
As provider we need to have aragon RPC node to increase stablity, please add aragon RPC here as backup solution

2023-03-10 10:00 UTC, sepehr2github commented on packages/web-app/src/components/fullScreenStepper/fullScreenStepper.tsx
> +              //@ts-ignore
Typescript is the only thing that protects us from many issues that might be existed especially in this project which has almost 0 test coverage, So please when you see a typescript issue please check the source and then disable it if there aren't any options, regardless this is redundant and should be removed, you just had to build the UI Component to update type interfaces :))

2023-03-10 10:01 UTC, sepehr2github commented on packages/web-app/src/pages/dashboard.tsx
> +          // @ts-ignore
Same as the pervious one should be removed, you just need to build the UI Components

2023-03-10 10:03 UTC, sepehr2github commented on packages/web-app/src/components/fullScreenStepper/fullScreenStepper.tsx
> +/* eslint-disable @typescript-eslint/ban-ts-comment */
Also this one is not needed

2023-03-10 10:07 UTC, sepehr2github commented on packages/web-app/src/hooks/useWallet.tsx
> +      await new Promise(resolve => resolve(true));
Could you explain a bit regarding this method?

2023-03-10 10:08 UTC, sepehr2github requested changes
Thanks, @baxri, This PR could solve many issues that we've experienced for wallet connection.

2023-03-10 10:10 UTC, sepehr2github commented on packages/web-app/src/pages/dashboard.tsx
> +/* eslint-disable @typescript-eslint/ban-ts-comment */
Same

2023-03-13 13:13 UTC, sepehr2github commented on packages/web-app/src/index.tsx
> +      ethereumClient={ethereumClient}
```suggestion
      ethereumClient={ethereumClient}
      themeMode="light"
```

Please add theme here to enable the light theme for web3 modal

2023-03-13 13:13 UTC, sepehr2github approved these changes
Thanks, one more change needed and then good to go

2023-03-13 15:54 UTC, merged