Feature/Transfers page DAO-478
aragon/app-legacy pull request #79
Opened 2021-12-09 09:35 UTC by RakeshUP

2021-12-09 12:11 UTC, WissenIstNacht requested changes
Thanks a lot! :)

Aside from the comments, don't forget to take care of the linting issues.

2021-12-09 12:11 UTC, WissenIstNacht commented on packages/web-app/src/pages/transfers.tsx
> +const transfers = [
Could you add a type to this? (there should be a types file in `utils` for global-ish types)

2021-12-09 12:11 UTC, WissenIstNacht commented on packages/web-app/src/components/transferList/index.tsx
> +        // key should be changed later
Do you think it's worth adding a hashing library that computes `uid`s for keys?

2021-12-09 12:11 UTC, WissenIstNacht commented on packages/web-app/src/pages/transfers.tsx
> +      <div className="space-y-1.5">
Button group here? (I think you can ommit the Button labeled "External COntracts") for now.

2021-12-09 15:10 UTC, WissenIstNacht commented on packages/web-app/src/pages/transfers.tsx
> +      <div className="space-y-1.5">
Ignore the above comment, I forgot that there is a separate ticket for this. Sorry!

2021-12-10 10:49 UTC, Fabricevladimir commented on packages/web-app/src/components/transferList/index.tsx
> +        // key should be changed later
Each transfer will have an id coming from the subraph, we should be able to use that.

2021-12-10 10:51 UTC, Fabricevladimir approved these changes
Good work! This should be ready to merge once the changes requested by @WissenIstNacht are made. Also, do you mind copying over the `warning` colors from the ui-components package so that the withdraw can show with proper colors? In the future, we should probably delete the web-app tailwind config and reference the one from the ui-components if possible since there doesn't seem to be any difference between the two.

2021-12-10 12:21 UTC, RakeshUP commented on packages/web-app/src/components/transferList/index.tsx
> +        // key should be changed later
Yeah as Fabrice said, there would be an id present which should be used as the key

Most of the hashing libraries use the current time for calculating hash, so it would re-render the list item every time the parent renders. It would behave the same way as not passing the key prop only.

Using index causes bugs though!

2021-12-10 12:23 UTC, RakeshUP commented on packages/web-app/src/pages/transfers.tsx
> +const transfers = [
Types should come from the subgraph by using codegen. I saw a type definition for types in the utils file, which should probably be removed once we fetch types from the subgraph

2021-12-10 16:17 UTC, WissenIstNacht commented on packages/web-app/src/pages/transfers.tsx
> +const transfers = [
This is partly true:

- It is true for data that actually comes from subgraph. This will only be a subset of data we use, though (think token information).
- The development of subgraph is not done (and should not be done) in isolation. Sarkawt would be very happy to have some insight into what data we need. Types would be a great way to start.
- Nothing stops you from changing any types you declare now later :D

But it's OK for now. :)

2021-12-10 16:29 UTC, WissenIstNacht commented on packages/web-app/src/components/transferList/index.tsx
> +        // key should be changed later
> Yeah as Fabrice said, there would be an id present which should be used as the key

Right 👍🏼

> Most of the hashing libraries use the current time for calculating hash [...]

Well... yes... that would not be the smartest thing to do 😄. I was thinking along the lines of an object hash or something 👍🏼

2021-12-10 16:39 UTC, WissenIstNacht commented
Hey, thanks for getting back to me on the comments! :)

Please address the linting issues and we should be good to go 👍🏼 
(One is related to the above type issue. If you really can't bring yourself to quickly  copy it from your IDE then at least add an eslint ignore statement :D)

2021-12-13 13:13 UTC, RakeshUP commented
Fixed the linting issues and added the type.

2021-12-14 09:57 UTC, WissenIstNacht approved these changes
Sorry, forgot to approve.

2021-12-14 10:16 UTC, WissenIstNacht commented
Hey, there were some merge conflicts with my PR, so I resolved them. Also took care of the linting issue 👍🏼

I'll let you merge in case you want to have a look at the changes 🙂

2021-12-14 12:09 UTC, merged