Fix: Dao Name truncate
aragon/app-legacy pull request #790
Opened 2023-03-15 10:45 UTC by sepehr2github

## Description

- Fix DAO Name text overlap

Task: []()

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2023-03-15 14:36 UTC, Fabricevladimir requested changes

2023-03-15 14:36 UTC, Fabricevladimir commented on packages/web-app/src/components/daoSelector/index.tsx
> +  max-width: 150px;
Shouldn't this be closer to 88px & just width instead since the maximum size of the card is 196px?

Also, on desktop, the card should get space-x-2

2023-03-17 05:44 UTC, RakeshUP approved these changes

2023-03-17 10:23 UTC, Fabricevladimir approved these changes

2023-03-17 10:23 UTC, merged