Fix: APP-2080 APP-2030
aragon/app-legacy pull request #804
Opened 2023-04-03 02:00 UTC by sepehr2github

## Description

-
Task: [ID]()

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2023-04-03 09:29 UTC, RakeshUP approved these changes

2023-04-03 09:38 UTC, Fabricevladimir requested changes
Thanks Sepehr! Left a couple comments

2023-04-03 09:38 UTC, Fabricevladimir commented on packages/web-app/src/components/addWallets/index.tsx
> +      append({address, amount: '1'});
If you set this to one by default, you should also update the `tokenTotalSupply` here or through default valaues when creating the form as well. Right now, the value for `tokenTotalSupply` is set to 0 by default and only gets updated once the user has changed one of the `addWallet` rows, triggering the validation. 

The minimum tokens required field as well doesn't get 1 and stays 0

2023-04-03 09:38 UTC, Fabricevladimir commented on packages/web-app/src/containers/navbar/exploreNav.tsx
> +  const path = t('logo.linkURL');
Seems like you're missing keys? The linter is complaining, and the links aren't showing the proper text.

2023-04-03 11:38 UTC, sepehr2github commented on packages/web-app/src/containers/navbar/exploreNav.tsx
> +  const path = t('logo.linkURL');
It's not on my side, AS I mentioned in Pr description we need to merge another Crowdin Pr to apply the changes

2023-04-03 14:02 UTC, Fabricevladimir commented on packages/web-app/src/containers/navbar/exploreNav.tsx
> +  const path = t('logo.linkURL');
Then I would suggest converting this to a draft until the Crowdin PR is merged.

2023-04-04 05:13 UTC, sepehr2github commented on packages/web-app/src/containers/navbar/exploreNav.tsx
> +  const path = t('logo.linkURL');
Yeah, I synced with james for tackling this

2023-04-04 08:38 UTC, Fabricevladimir requested changes

2023-04-04 08:38 UTC, Fabricevladimir commented on packages/web-app/src/components/addWallets/index.tsx
>      resetField('tokenTotalSupply');
Because tokenTotalSupply is given a default of 1 wwhen creating the form, when it resets, it resets to 1. This will be an incorrect value if there are more than one wallets in the form and the user resets distribution. Each wallet present will get 1 token, and totalTokenSupply will equal 1.

Also, removing all the wallets in the list leads to a case where the totalTokenSupply no longer gets calculated and gets stuck at 1.

2023-04-04 10:39 UTC, Fabricevladimir approved these changes
Sweet! Thanks for the fix. You can merge once the crowdin stuff comes in and the linter passes

2023-04-04 15:23 UTC, merged