Feat/ens routing
aragon/app-legacy pull request #805
Opened 2023-04-04 08:08 UTC by baxri

2023-04-04 09:56 UTC, Fabricevladimir requested changes
Whew! Massive and tricky one

2023-04-04 09:56 UTC, Fabricevladimir commented on packages/web-app/src/containers/daoExplorer/daoExplorer.tsx
> +                }
Why is the DAO name being changed here? This doesn't have anything to do with ens AFAIK.

2023-04-04 09:56 UTC, Fabricevladimir commented on packages/web-app/src/containers/daoExplorer/daoExplorer.tsx
> +                      dao: dao.ensDomain.includes('dao.eth')
On chains where ens doesn't exist, the SDK will return the domain as `null.dao.eth`. Using this current logic, all Mumbai & Polygon DAOs will fail to navigate properly. 

@sepehr2github created a function `toDisplayEns`in the libraries utils that returns the proper ens or an empty string if the ens subdomain does not exist. Something like the following might be what you're looking for:
```javascript
dao: toDisplayEns(dao.ensDomain) || dao.address
```

2023-04-04 09:56 UTC, Fabricevladimir commented on packages/web-app/src/containers/daoExplorer/daoExplorer.tsx
> +  console.log('displayedDaos', displayedDaos);
Please remove

2023-04-04 09:56 UTC, Fabricevladimir commented on packages/web-app/src/pages/dashboard.tsx
>      data: daoId,
Might be best to rename this to `daoAddressOrEns` for more clarity.

2023-04-04 09:56 UTC, Fabricevladimir commented on packages/web-app/src/pages/dashboard.tsx
> +          dao={dao.address}
If you follow this through, you'll find that this `dao.address` is being used to navigate to the various pages from the dashboard. Because the ens isn't getting passed down, you go from ens on daoDashboard -> address in governance/finance/communities. 

If the user starts out with the ens name, it must stay consistent throughout the whole application.

2023-04-04 09:56 UTC, Fabricevladimir commented on packages/web-app/src/pages/editSettings.tsx
> +        daoId={daoDetails?.address as string}
Same as previous comment. There is no reason why this should be solely dao address and not also the ens if it exists.

2023-04-04 09:56 UTC, Fabricevladimir commented on packages/web-app/src/pages/finance.tsx
> +  // load dao details
Is this necessary or something to be done afterwards?

2023-04-04 09:56 UTC, Fabricevladimir commented on packages/web-app/src/pages/newDeposit.tsx
> +      formMethods.setValue('to', daoDetails?.address as string);
Actually I think we really want the ens here (if available) as well so the resulting deposit shows a human friendly name and not just an address

2023-04-04 09:56 UTC, Fabricevladimir commented on packages/web-app/package.json
> +    "@aragon/sdk-client": "^1.2.0",
Please rebase. We're already on 1.3.0 hehe

2023-04-04 09:56 UTC, Fabricevladimir commented on packages/web-app/src/containers/configureWithdraw/index.tsx
> +      setValue(`actions.${actionIndex}.from`, daoDetails?.address);
Same as Deposit, the ens is more human friendly so it's best to show it if it is available.

2023-04-04 09:56 UTC, Fabricevladimir commented on packages/web-app/src/containers/compareSettings/index.tsx
> +        daoId={daoDetails?.address as string}
Anywhere this id is eventually used for navigation, we want the ens if it is available because we don't want to show inconsistent data in the browsser nav bar.

2023-04-06 09:19 UTC, Fabricevladimir requested changes
Thanks. Unfortunately I wasn't able to review this because the app crashes immediately when I run it

2023-04-06 09:19 UTC, Fabricevladimir commented on packages/web-app/src/containers/daoExplorer/daoExplorer.tsx
> -  const {isConnected} = useWallet();
I'm guessing this is a rebase went wrong. These changes are the ones we want from develop

2023-04-11 13:27 UTC, Fabricevladimir requested changes

2023-04-11 13:27 UTC, Fabricevladimir commented on packages/web-app/src/containers/compareSettings/index.tsx
> +            daoId={daoDetails?.address as string}
This daoId is being used to navigate. If the URL contains the ens address but we always pass the address down, whenever we navigate from the component, it will remove the ens from the URL

2023-04-11 13:27 UTC, Fabricevladimir commented on packages/web-app/src/containers/compareSettings/index.tsx
> +            daoId={daoDetails?.address as string}
Same thing here. In fact I'd suggest renaming the prop to `daoAddressOrEns` to properly reflect that this can be either

2023-04-11 13:27 UTC, Fabricevladimir commented on packages/web-app/src/containers/configureWithdraw/index.tsx
> +    if (from === '' && daoDetails?.address) {
I have a sinking feeling that I requested this to also include the ens. If so I appologize because you were right, it only needs the DAO address.

2023-04-17 19:36 UTC, sepehr2github approved these changes
thanks, Fabrice, I checked all the changes precisely and Seems good to go!

2023-04-18 09:41 UTC, Fabricevladimir approved these changes

2023-04-18 10:08 UTC, merged