APP-2120 - New Deposit Flow
aragon/app-legacy pull request #818
Opened 2023-04-20 09:28 UTC by sepehr2github

## Description

- New Deposit flow added
- empty state added to finance page

Task: [ID]()

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2023-04-24 13:50 UTC, Fabricevladimir requested changes
Thanks, Sepehr. Modal makes things much less complicated! Left a few comments and questions.

2023-04-24 13:50 UTC, Fabricevladimir commented on packages/ui-components/src/components/illustrations/object/illuObject.tsx
> +  IlluObjectProps & HTMLAttributes<HTMLElement>
Why allow other props to be passed into it? Aren't we aiming for these to be rather unchangeable by the consumer?

2023-04-24 13:50 UTC, Fabricevladimir commented on packages/web-app/src/containers/pageEmptyState/index.tsx
> +  subtitle: TemplateStringsArray;
Why an array and not merely a string?

2023-04-24 13:50 UTC, Fabricevladimir commented on packages/web-app/src/containers/pageEmptyState/index.tsx
> +            iconLeft={<IconAdd />}
Do all of the empty states actually have the `IconAdd`? As far as I can tell, none of them do?

2023-04-24 13:50 UTC, Fabricevladimir commented on packages/web-app/src/containers/pageEmptyState/index.tsx
> +const PageEmptyState = ({
I don't see the real difference between this and the `StateEmpty` custom component we already have. If the sizing is the issue, can't we just wrap the container around `StateEmpty`?

Also, can you remove the unholy amount of space at the bottom of the empty state page on mobile especially?

2023-04-24 13:50 UTC, Fabricevladimir commented on packages/web-app/src/containers/transactionModals/DepositModal.tsx
> +import {generatePath, useParams} from 'react-router-dom';
Lint, lint :)

2023-04-24 13:50 UTC, Fabricevladimir commented on packages/web-app/src/containers/transferMenu/index.tsx
> +          title={t('TransferModal.newTransfer') as string}
Shouldn't this be "Deposit assets" and also include a subtitle? Also, casting it as a string is unnecessary.

2023-04-24 13:50 UTC, Fabricevladimir commented on packages/web-app/src/containers/transactionModals/DepositModal.tsx
> +                location.reload();
This is actually a good example of where you would actually want to invalidate a query that is fetching information instead of reloading the entirety of the page and losing cached data.

2023-04-24 13:50 UTC, Fabricevladimir commented on packages/web-app/src/containers/transactionModals/DepositModal.tsx
> +      <span className="px-1 text-ui-400">or</span>
I see you translation string, hehe. Also, this should be semibold

2023-04-24 13:50 UTC, Fabricevladimir commented on packages/web-app/src/containers/treasurySnapshot/index.tsx
>        <StateEmpty
This is lacking the wallet next to the illustration head. Is this an illuhuman issue?

2023-04-24 13:50 UTC, Fabricevladimir commented on packages/web-app/src/context/globalModals.tsx
> +  | 'deposit';
I'm hating this context lol

2023-04-24 13:50 UTC, Fabricevladimir commented on packages/web-app/src/locales/en/common.json
> +      "description": "Begin by making your first treasury deposit.\u2028 Learn more about managing a DAO treasury {{link}}.",
What's up with the unicode value? It's rendering gibberish on chrome btw.

Update: Seems like this is supposed to be a line separator? It ain't workin

2023-04-24 13:50 UTC, Fabricevladimir commented on packages/web-app/src/pages/governance.tsx
> +          'governance.emptyState.subtitle' as unknown as TemplateStringsArray
Shouldn't this just be a string?

2023-04-24 13:50 UTC, Fabricevladimir commented on packages/web-app/src/public/noTransfers.svg
> +<svg width="400" height="226" viewBox="0 0 400 226" fill="none" xmlns="http://www.w3.org/2000/svg">
Hold up, so this includes the wallet next to the person's head, where is this being used in the application?

2023-04-24 13:51 UTC, Fabricevladimir commented
Also, you're linking the wrong ticket. It should be APP-2120 I believe

2023-04-25 17:49 UTC, sepehr2github commented on packages/web-app/src/pages/governance.tsx
> +          'governance.emptyState.subtitle' as unknown as TemplateStringsArray
because the type of key input in htmlIn function is TParam0 which is a TemplateStringsArray

2023-04-25 17:50 UTC, sepehr2github commented on packages/web-app/src/locales/en/common.json
> +      "description": "Begin by making your first treasury deposit.\u2028 Learn more about managing a DAO treasury {{link}}.",
It should be solved in crowdin dashboard! Maybe James can help tp fix this issue

2023-04-25 17:51 UTC, sepehr2github commented on packages/web-app/src/context/globalModals.tsx
> +  | 'deposit';
hahaha, It's not my favorite as well

2023-04-25 17:52 UTC, sepehr2github commented on packages/web-app/src/containers/transferMenu/index.tsx
> +          title={t('TransferModal.newTransfer') as string}
That was according to new crowdin key updates, there were no subtitle anymore

2023-04-25 17:57 UTC, sepehr2github commented on packages/web-app/src/containers/pageEmptyState/index.tsx
> +  subtitle: TemplateStringsArray;
Same as the other one, It's for htmlIn method

2023-04-25 17:58 UTC, sepehr2github commented on packages/ui-components/src/components/illustrations/object/illuObject.tsx
> +  IlluObjectProps & HTMLAttributes<HTMLElement>
because I had to pass className and It should act like normal component, regardless all these concerns will be addresses with the new version of ODS

2023-04-26 07:25 UTC, sepehr2github commented on packages/web-app/src/containers/transactionModals/DepositModal.tsx
> +                location.reload();
Yeah, we can fix this later by react query refactor!

2023-04-26 09:22 UTC, sepehr2github commented on packages/web-app/src/containers/pageEmptyState/index.tsx
> +const PageEmptyState = ({
yeah but this should be tackled in a separate ticket because we used StateEmpty in several places also the font size & weight and card are diffrent

2023-04-26 09:30 UTC, sepehr2github commented on packages/web-app/src/containers/transferMenu/index.tsx
> +          title={t('TransferModal.newTransfer') as string}
Also checked with james again, He's aware of them

2023-04-26 11:18 UTC, Fabricevladimir reviewed
Thanks for the changes, left my final comments

2023-04-26 11:18 UTC, Fabricevladimir commented on packages/web-app/src/pages/governance.tsx
> +          'governance.emptyState.subtitle' as unknown as TemplateStringsArray
Since the htmlIn function returns a string, why not call it and pass it in here and make the subtitle prop a string? It's the same thing being done for the StateEmpty component.

2023-04-26 11:18 UTC, Fabricevladimir commented on packages/web-app/src/containers/transactionModals/DepositModal.tsx
> +      <span className="px-1 font-semibold text-ui-400">or</span>
Don't forget translation string for or. Also, would you be so kind to lowercase the filename please

2023-04-26 11:18 UTC, Fabricevladimir commented on packages/ui-components/src/components/illustrations/object/illuObject.tsx
> +  IlluObjectProps & HTMLAttributes<HTMLElement>
Another option would have to wrap it in a span or something, but yeah we'll clear up the properties when we get to that in the ODS

2023-04-26 11:18 UTC, Fabricevladimir commented on packages/web-app/src/containers/transferMenu/index.tsx
> +          title={t('TransferModal.newTransfer')}
This is just showing new transfer instead of deposit. Is this intended? The designs seem to be different.

2023-04-26 11:18 UTC, Fabricevladimir commented on packages/web-app/src/containers/treasurySnapshot/index.tsx
> +        type="both"
Aha sweet

2023-04-26 11:18 UTC, Fabricevladimir commented on packages/web-app/src/locales/en/common.json
> +      "description": "Begin by making your first treasury deposit.\u2028 Learn more about managing a DAO treasury {{link}}.",
Yeah reach out to him so we can get a new translation file because it's visible to the user

2023-04-26 11:18 UTC, Fabricevladimir commented on packages/web-app/src/pages/finance.tsx
> +              {isMobile && (
Keep the desktop one because we want the breadcrumb to show up on tablet mode as well

2023-04-26 13:03 UTC, sepehr2github commented on packages/web-app/src/containers/transferMenu/index.tsx
> +          title={t('TransferModal.newTransfer')}
Fixed due to daily discussion

2023-04-27 09:14 UTC, Fabricevladimir approved these changes

2023-04-27 09:16 UTC, merged