Feature/transfer modal DAO-445
aragon/app-legacy pull request #82
Opened 2021-12-10 07:39 UTC by sepehr2github

- Modal added to ui components
- Radix Dialog package added
- Transfer modal added
- add background selection and hide border option to many & actionItemList
- change menu context to wallet context 
- transferModal context added (we can use this context for other transfer modal pages)

2021-12-10 10:32 UTC, Fabricevladimir requested changes
Nice work setting things up!

2021-12-10 10:32 UTC, Fabricevladimir commented on packages/ui-components/package.json
> +    "@radix-ui/react-dialog": "^0.1.1",
Is there a reason why the package is installed as both dev and regular dependency?

2021-12-10 10:32 UTC, Fabricevladimir commented on packages/ui-components/src/components/modal/modal.tsx
> +  onClose: () => void;
Can this property be optional?

2021-12-10 10:32 UTC, Fabricevladimir commented on packages/ui-components/stories/modal.stories.tsx
> +const popoverContent: ReactNode = (
Copy paste? Should be `ModalContent`?

2021-12-10 10:32 UTC, Fabricevladimir commented on packages/web-app/src/pages/finance.tsx
> +        title={t('finance.allTransfers')}
The title is on the wrong page. It should be on the `AllTransfers` page not Finance

2021-12-10 10:32 UTC, Fabricevladimir commented on packages/web-app/src/containers/transferMenu/index.tsx
> +    <Modal
The position for the modal is different from that in the designs. In the designs, it's at the top of the page. Not a major concern for now probably. Just something to keep in mind.

2021-12-10 10:32 UTC, Fabricevladimir commented on packages/web-app/src/locales/en/common.json
> +    "addTransfers":"Add Transfer"
Should be "New Transfer" for the button.

2021-12-10 12:37 UTC, Fabricevladimir approved these changes

2021-12-13 09:44 UTC, RakeshUP approved these changes
The space between the list items in the modal is 24px vs 12px in the design
Modal close on pressing escape key doesn't seem to be working. Do you know why?

2021-12-13 11:08 UTC, WissenIstNacht reviewed
Hey there, thanks a lot for all the work!

There's nothing objectively wrong with your PR, but there's a lot of things I find a bit strange. In particular, I feel like there's a lot of things in your PR that should have been discussed with Selim to avoid misunderstandings and problems later on.

2021-12-13 11:08 UTC, WissenIstNacht commented on packages/ui-components/src/components/modal/modal.tsx
> +  background?: string;
Hey, did you discuss this with Selim? It doesn't seem to me like we'll have a lot of different background colors on Modals.

Side note: I'm not a fan of letting the user pass Tailwind color names here. If anything, I think it would be better to give the user some colors they can chose from. Then, we translate that to tailwind classes inside the Modal component. Also, this would be something worth documenting in the comment above. ;)

2021-12-13 11:08 UTC, WissenIstNacht commented on packages/ui-components/src/components/modal/modal.tsx
> +        <ModalContent
Small detail: I would call this `ModalContainer`, as the children are the content. (See your comment on line 21)

2021-12-13 11:08 UTC, WissenIstNacht commented on packages/ui-components/src/components/actionListItem/actionListItem.tsx
> +  bordered,
Defaulting to true would avoid the need to change all existing items that have a border. On the other hand I realize we'll have a lot of borderless action items. Might be worth asking Selim on the topic?

2021-12-13 11:08 UTC, WissenIstNacht commented on packages/web-app/src/pages/finance.tsx
> +        subtitleColor="primary-500"
Again, I wouldn't pass tailwind colors into here.

2021-12-13 11:08 UTC, WissenIstNacht commented on packages/web-app/src/pages/finance.tsx
> +        title={'$469,657.98'}
This should be dynamic. (I know, real data is not available. But there is some mock data. You could set up a hook that computes the necessary information given that mock data.)

2021-12-13 11:08 UTC, WissenIstNacht commented on packages/web-app/src/context/walletMenu.tsx
> +  const value = useMemo(
I don't think this is necessary. None of the computations here are expensive.

2021-12-13 11:08 UTC, WissenIstNacht commented on packages/web-app/src/context/transfersModal.tsx
> +const TransferModalsProvider: React.FC<Props> = ({children}) => {
Why do we need two such contexts? Wouldn't one be enough? You can't have both opened at the same time anyway, right?

2021-12-13 11:08 UTC, WissenIstNacht commented on packages/web-app/src/components/sectionWrapper/index.tsx
> +export const PageWrapper = ({
Could you move this to a separate file? (Page != Section :D)

2021-12-13 13:07 UTC, WissenIstNacht commented
Also a LOT of tests are currently not passing. Could you try to fix them?

2021-12-13 14:04 UTC, sepehr2github commented on packages/web-app/src/context/transfersModal.tsx
> +const TransferModalsProvider: React.FC<Props> = ({children}) => {
Context structure is one of the challenges that we need to discuss. I consider each context based on its usage. We Will use TransfetModal context for its related states also the same for the wallet modal. (In other words It's a placeholder for more states)

2021-12-13 14:06 UTC, sepehr2github commented on packages/web-app/src/context/walletMenu.tsx
> +  const value = useMemo(
For now yes, but in the future, We will add more wallet states. (When we want to implement the full wallet flow)

2021-12-14 10:36 UTC, merged