SCC - Action Input Form
aragon/app-legacy pull request #821
Opened 2023-04-21 10:55 UTC by RakeshUP

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task: [ID]()

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2023-04-21 11:00 UTC, jamesej reviewed
That looks really great, it's pretty concise. One thing though, you'll need to cover all the possible primitive types like `fixed` etc [https://docs.soliditylang.org/en/v0.8.19/abi-spec.html#types](https://docs.soliditylang.org/en/v0.8.19/abi-spec.html#types)

2023-04-27 09:15 UTC, sepehr2github commented on packages/web-app/src/containers/smartContractComposer/index.tsx
> +      // @ts-ignore
Why did you ignore ts?

2023-04-27 09:21 UTC, sepehr2github requested changes
The modal will remove the empty state when I close it 
<img width="1064" alt="Screenshot 2023-04-27 at 12 39 53 PM" src="https://user-images.githubusercontent.com/46657145/234818690-6bfcd8e7-528e-4e8c-98c4-e51eb1fb3415.png">

Also if I jump back then Jump next the modal pops up

2023-04-27 09:21 UTC, sepehr2github commented on packages/web-app/src/containers/smartContractComposer/components/inputForm.tsx
> +          <div className="mb-1.5 text-base font-bold capitalize text-ui-800">
Lint!

2023-04-27 09:22 UTC, sepehr2github commented on packages/web-app/src/containers/smartContractComposer/components/inputForm.tsx
> +            <div className="mb-1.5 text-base font-bold capitalize text-ui-800">
Please fix all lint errors

2023-04-27 09:22 UTC, RakeshUP commented on packages/web-app/src/containers/smartContractComposer/index.tsx
> +      // @ts-ignore
There's a [cyclic type dependency here](https://github.com/aragon/app/blob/13b77d9eaca4e1b5724e5e91ab673f71865f9789/packages/web-app/src/utils/types.ts#L386), and TS won't stop complaining about it. I've used ts-ignore on multiple places, I'll try to remove that and fix the ts issue

2023-04-28 09:58 UTC, RakeshUP commented
@sepehr2github, I've fixed the lint warnings and the issues with empty state and the SCC modal. 

I'll fix the @ts-ignore thing in my upcoming PR

2023-05-04 08:29 UTC, sepehr2github requested changes
Thanks for the changes, One small issue still left, when I add a new contract and click to add another one, the modal input is disabled

2023-05-04 11:43 UTC, sepehr2github approved these changes
Thanks, will fix the issue in upcoming prs

2023-05-04 13:31 UTC, merged