New deposit page skeleton
aragon/app-legacy pull request #84
Opened 2021-12-10 12:27 UTC by RakeshUP

This is just the bare-bones version of the new deposit page. Still needs some changes, which could be done with the subsequent PR's :)

2021-12-13 10:11 UTC, Fabricevladimir reviewed
Looks good!

2021-12-13 10:11 UTC, Fabricevladimir commented on packages/web-app/src/pages/newDeposit.tsx
> +      <NavigationBar>
Huh. There is indeed a navbar on this page, but it's not the usual and neither was that specified in the designs as a variant... If it will be used in multiple pages, might be worth turning into its own component. That is something for the future maybe.

2021-12-13 10:11 UTC, Fabricevladimir commented on packages/web-app/src/pages/newDeposit.tsx
> +          <FormItem
If it won't take much time, can you move this to the ui-component? It corresponds to the Label in the Components designs on figma. Or alternatively, create a Jira task for it.

2021-12-13 10:11 UTC, Fabricevladimir commented on packages/web-app/src/app.tsx
>              <Route path={paths.NotFound} element={<NotFoundPage />} />
Are you intentionally not adding the Nav to the NotFound? User is sort of stuck right now simply because there is no way to navigate out. Of course you can still change the path on the browser...

2021-12-13 13:22 UTC, WissenIstNacht commented on packages/web-app/src/pages/newDeposit.tsx
> +      <NavigationBar>
Yup, might be worth a quick exchange between us and Selim to know where this is headed.

2021-12-13 13:52 UTC, WissenIstNacht requested changes
Thanks a lot, design is looking great so far!

Left a minor comment on the step card.

2021-12-13 13:52 UTC, WissenIstNacht commented on packages/web-app/src/pages/newDeposit.tsx
> +          <CenteredFlex>
This will certainly be useful in the future too. Could you put into a component of its own? (No need to go wild yet. Just make it take a few props that allow to display it as is now)

2021-12-14 09:34 UTC, sepehr2github commented on packages/web-app/src/pages/newDeposit.tsx
> +            <SearchInput />
Please use TextInput with IconDown on the right side. It's possible to pass adornment

2021-12-14 09:35 UTC, sepehr2github commented on packages/web-app/src/pages/newDeposit.tsx
> +const ProgressBar = styled.progress.attrs({
It's not needed right now but we should add ProgressBar to Component UI as single component

2021-12-14 09:36 UTC, sepehr2github submitted a review, later dismissed
Thank you Rakesh. Looks nice! Also please remove conflicts.

2021-12-14 12:11 UTC, RakeshUP commented
Putting this PR on hold till a few components(Label, Wizard, Progress Bar, etc) are done. If someone else wants to work on New Deposit page immediately, we can merge this and refactor later

2021-12-21 16:36 UTC, WissenIstNacht commented on packages/web-app/src/pages/newDeposit.tsx
> +            <InsetButtonText>New Transfer</InsetButtonText>
translation

2021-12-21 16:47 UTC, WissenIstNacht commented on packages/web-app/src/pages/newDeposit.tsx
> +            <ButtonWallet label="patito.dao.eth" src={null} />
button should be set disabled.

2021-12-21 16:51 UTC, WissenIstNacht approved these changes
Awesome, thanks! 💪🏻 🙂

I left two minor comments. I'll let you deal with them and merge afterwards.

2021-12-21 17:35 UTC, Fabricevladimir commented on packages/web-app/src/pages/newDeposit.tsx
> +      <NavigationBar>
Considering the navbar is just another evolution of the current one, I suggest leaving this one out and ignore the designs for now until the navbar is refactored.

2021-12-21 17:36 UTC, Fabricevladimir approved these changes
Good to merge, once the requested changes have been made.

2021-12-22 09:01 UTC, merged