APP-2132 - Add Warning for Minting tokens to DAO treasury
aragon/app-legacy pull request #840
Opened 2023-05-10 10:42 UTC by sepehr2github

## Description

- warning modal added
- update address validation for mint token action

Task: [APP-2132](https://aragonassociation.atlassian.net/browse/APP-2132)

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2023-05-12 10:14 UTC, Fabricevladimir requested changes
Thanks Sepehr. Looks good. Left a couple minor coments

2023-05-12 10:14 UTC, Fabricevladimir commented on packages/web-app/src/containers/mintTokensToTreasuryMenu/index.tsx
> +                required: t('errors.required.walletAddress') as string,
Can you remove the casting please?

2023-05-12 10:14 UTC, Fabricevladimir commented on packages/web-app/src/containers/mintTokensToTreasuryMenu/index.tsx
> +                      handleClipboardActions(value, onChange, alert)
I think you're using the wrong alert here. This is the browser one, but should be the chip alert.

2023-05-12 10:14 UTC, Fabricevladimir commented on packages/web-app/src/containers/actionBuilder/mintTokens/index.tsx
> +  const openMintoTreasuryModal = (index: number) => {
Misspelling?

2023-05-12 10:14 UTC, Fabricevladimir commented on packages/web-app/src/locales/en/common.json
> +      "step1CtaLabel": "OK, I have understood the risk",
This is rather counterintuitive and confusing. When I say I understand the risk, I expect it to mean that I understand the risk let me do what I want to do anyway.

2023-05-12 10:14 UTC, Fabricevladimir commented on packages/web-app/src/containers/mintTokensToTreasuryMenu/index.tsx
> +export type ProcessType = typeof processes[number];
What is the use of these two?

2023-05-12 10:24 UTC, jamesej requested changes
Also there is an issue where the modal extends off the right hand side in tablet view (but not mobile for some reason). You need to make the browser window maybe 1000px wide but 1600 high or something like that to see this one.

2023-05-12 10:24 UTC, jamesej commented on packages/web-app/src/containers/actionBuilder/mintTokens/addressTokenRow.tsx
> +      if ((address === daoAddress || address === ensName) && !isModalOpened) {
Comparison needs to be case-insensitive

2023-05-13 19:54 UTC, sepehr2github commented on packages/web-app/src/locales/en/common.json
> +      "step1CtaLabel": "OK, I have understood the risk",
We need to check this with selim

2023-05-15 11:04 UTC, Fabricevladimir approved these changes
Thanks Sepehr, looks good. This can be merged once you've addressed Jame's comment about the tablet mode

2023-05-15 11:04 UTC, Fabricevladimir commented on packages/web-app/src/containers/actionBuilder/mintTokens/index.tsx
> +  const isModalOpened = useMemo(
The calculation is one check and the dependency the same, at this point, memoizing might actually be harmful!

2023-05-15 15:18 UTC, jamesej commented on packages/web-app/src/containers/actionBuilder/mintTokens/index.tsx
> +  const isModalOpened = useMemo(
Fixed this one

2023-05-15 15:19 UTC, jamesej approved these changes
All good now

2023-05-15 15:28 UTC, merged