Feat: Etherscan NatSpec comments and SCC Issues
aragon/app-legacy pull request #846
Opened 2023-05-17 07:58 UTC by RakeshUP

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task: [ID]()

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2023-05-19 09:51 UTC, Fabricevladimir requested changes
Thanks, Rakesh; doing a bang-up job, good stuff, good stuff. Left a few comments; let me know what you think.

2023-05-19 09:51 UTC, Fabricevladimir commented on packages/ui-components/src/components/listItem/action.tsx
> +  truncateText?: boolean;
I'm not sure I can think of a time when we *don't* want to truncate the overflowing text in this component. That said, we'll revisit in corresponding ODS ticket.

2023-05-19 09:51 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/components/actionListGroup.tsx
> +          mode={selectedAction === a ? 'selected' : 'default'}
The fact we have to manaully update the bgWhite probably means component itself has styling issues!

2023-05-19 09:51 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/components/inputForm.tsx
>          Sorry, no public Write functions were found for this contract.
Hello translation strings!

2023-05-19 09:51 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/desktopModal/index.tsx
> +                } Actions to compose`}
Translation string hehe

2023-05-19 09:51 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/mobileModal/index.tsx
> +                } Actions to compose`}
You guessed it--translation strings!

2023-05-19 09:51 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/contractListModal/index.tsx
> +      onBackButtonClicked={props.onBackButtonClicked}
When we're deep into the flow like actually filling out the action input, clicking on back does not have the intended result as it returns us to a state where the modal is empty.

2023-05-19 09:51 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/mobileModal/index.tsx
> +const MobileModal: React.FC<Props> = props => {
I'm not sure if this is within the scope of this task but the modal header on mobile behaves quite a bit differently than on desktop. Right now we always have the search, but when we're filling out an action, the header no longer contains the close IconButton, and the search input is replaced with the Contract name.

2023-05-19 09:51 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/components/inputForm.tsx
>        <ActionDescription>{selectedAction.notice}</ActionDescription>
Here, we're missing the contract name next to the action name on desktop, and after the description on mobile.

2023-05-19 10:26 UTC, RakeshUP commented on packages/ui-components/src/components/listItem/action.tsx
> +  truncateText?: boolean;
I added this specifically so that the subtitle is completely displayed on the AddActionMenu, which was raised as an issue by Pieter

2023-05-19 10:27 UTC, RakeshUP commented on packages/web-app/src/containers/smartContractComposer/components/actionListGroup.tsx
> +          mode={selectedAction === a ? 'selected' : 'default'}
Yes, this was frustrating. But I left it out as this will be fixed by ODS

2023-05-19 10:29 UTC, RakeshUP commented on packages/web-app/src/containers/smartContractComposer/components/inputForm.tsx
>          Sorry, no public Write functions were found for this contract.
This specific use case is not covered by the existing i18n strings. This is when an added contract only has view/read functions and no write functions. Need a new key for this. 

That said, all i18n related issues are being fixed in another ticket APP-2199

2023-05-22 10:53 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/desktopModal/index.tsx
> +                } Actions to compose`}
Resolving all translation string comments since they're being taken cared of in the other ticket

2023-05-22 14:32 UTC, RakeshUP commented on packages/web-app/src/containers/smartContractComposer/contractListModal/index.tsx
> +      onBackButtonClicked={props.onBackButtonClicked}
Fixed

2023-05-22 14:32 UTC, RakeshUP commented on packages/web-app/src/containers/smartContractComposer/mobileModal/index.tsx
> +const MobileModal: React.FC<Props> = props => {
This needs change to the BottomSheet, let me fix this in a separate PR.

2023-05-22 15:04 UTC, Fabricevladimir approved these changes
Left a couple of small comments. Thanks!

2023-05-22 15:04 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/components/inputForm.tsx
> +        <div className="p-3 mt-5 space-y-2 bg-white desktop:bg-ui-50 rounded-xl border-ui-100 shadow-100">
You forgot to add the 'border' class name

2023-05-22 15:04 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/mobileModal/index.tsx
> +        onClose={props.onClose}
When I click on a contract name from the list, clicking on back close the modal instead of going to the previous view (list of contracts).

2023-05-23 03:24 UTC, merged