Feature: APP-2199 Contact Composer - Design QA Issues
aragon/app-legacy pull request #856
Opened 2023-05-24 17:05 UTC by jamesej

## Description

This fixes the issues raised in this ticket with the exception of the second number 1 which is I think covered in another ticket. Also it leaves parameter names as they are, as making them more readable could cause more confusion than it would save.

Task: [APP-2199](https://aragonassociation.atlassian.net/browse/APP-2199)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2023-05-24 22:06 UTC, Fabricevladimir requested changes
Thank, James! The core functionalities are working as expected, left a few comments about styling

2023-05-24 22:06 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useDaoActions.tsx
> +    title: i18n.t('TransferModal.item2Title'),
Are you sure this will pick up a change in locale and not stay with whatever locale/language it was initially loaded with?

2023-05-24 22:06 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/mobileModal/index.tsx
> +                href={t('scc.listContracts.learnLinkURL')}
As far as I can tell this link doesn't actually go anywhere. There doesn't seem to be an actual link to go to

2023-05-24 22:06 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/mobileModal/index.tsx
> +              <ListHeaderContract
When smart contracts are removed, I noticed that we show an empty modal instead of the emptyState modal. Is this intentional?

2023-05-24 22:06 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/emptyStateModal/emptyState.tsx
>            description={t('scc.emptyState.description')}
There is supposed to be a link in here as well. Are we missing crowdin keys?

2023-05-24 22:06 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/desktopModal/index.tsx
> +  // @ts-ignore
Curious, why are we ignoring ts here?

2023-05-24 22:06 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/components/listHeaderContract.tsx
> +  const liaProps = {
Who is lia? ;) hehehe

2023-05-24 22:06 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/components/listHeaderContract.tsx
> +              href={`https://etherscan.io/address/${sc.address}#code`}
I think we need to add this link on the CHAIN_METADATA object (or build it from the existing `explorer` property) and use the connected network to determine which one to use. Currently, this will point to the Mainnet address only

2023-05-24 22:06 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/components/listHeaderContract.tsx
> +            <Link
Wny have you gone with the `Link` component instead of the `ListItemAction`?

2023-05-24 22:06 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/components/listHeaderContract.tsx
> +        </button>
This should be `ButtonIcon` secondary I think.

2023-05-24 22:06 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/components/listItemContract.tsx
> +export const ListItemContract: React.FC<Props> = ({
This seems to be used only once, and never with `dropdownItems`. Was this supposed to be used as the `listHeaderContract`?

2023-05-24 22:06 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/components/inputForm.tsx
>  const InputForm: React.FC<InputFormProps> = ({
My dear friend, rebase... sorry.

2023-05-24 22:06 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/components/listHeaderContract.tsx
> +    <ListItemAction {...{...liaProps, ...rest}} iconLeft={liaProps.title} />
Honestly, given enough time, we probably should make this `ListHeaderContract` a web-app specific local component instead of bending over backwards to funnel everything into the `ListItemAction`

2023-05-24 22:06 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/mobileModal/index.tsx
> +  const {getValues} = useFormContext<SccFormData>();
We already have a useFormContext hook imported. Are you intentionally using this for the typing?

2023-05-24 22:06 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/mobileModal/index.tsx
> +  const [search, setSearch] = useState('');
Random thought. I noticed that on the initial modal (not empty state) where we list the contracts that searching doesn't actually do anything. If that's the case, I think we probably need some sort of design adjustment to remove the search input from the modal header unless a contract is selected.

2023-05-24 22:06 UTC, Fabricevladimir commented on packages/web-app/src/containers/smartContractComposer/desktopModal/index.tsx
> +              <Link
There is a styling issue with this where it's pushing the Connet button to the center of the column

2023-05-25 07:22 UTC, jamesej commented on packages/web-app/src/hooks/useDaoActions.tsx
> +    title: i18n.t('TransferModal.item2Title'),
Good point, have reverted to how it was before as actually it turns out I didn't need to change this.

2023-05-25 07:23 UTC, jamesej commented on packages/web-app/src/containers/smartContractComposer/mobileModal/index.tsx
> +                href={t('scc.listContracts.learnLinkURL')}
Yeah just not in CrowdIn keys yet

2023-05-25 07:28 UTC, jamesej commented on packages/web-app/src/containers/smartContractComposer/desktopModal/index.tsx
> +  // @ts-ignore
If you delete the comments you'll see some incomprehensible type error which seems to cause no actual problems

2023-05-25 07:31 UTC, jamesej commented on packages/web-app/src/containers/smartContractComposer/components/listHeaderContract.tsx
> +    <ListItemAction {...{...liaProps, ...rest}} iconLeft={liaProps.title} />
Yeah maybe but.. no time!

2023-05-25 07:49 UTC, jamesej commented on packages/web-app/src/containers/smartContractComposer/components/inputForm.tsx
>  const InputForm: React.FC<InputFormProps> = ({
Seems I dodged this particular bullet!

2023-05-25 07:49 UTC, jamesej commented on packages/web-app/src/containers/smartContractComposer/emptyStateModal/emptyState.tsx
>            description={t('scc.emptyState.description')}
Yeah there are no keys for a link here

2023-05-25 07:51 UTC, jamesej commented on packages/web-app/src/containers/smartContractComposer/mobileModal/index.tsx
> +  const {getValues} = useFormContext<SccFormData>();
Ah silly me, fixed

2023-05-25 09:34 UTC, jamesej commented on packages/web-app/src/containers/smartContractComposer/desktopModal/index.tsx
> +              <Link
Fixed, thanks

2023-05-25 09:34 UTC, jamesej commented on packages/web-app/src/containers/smartContractComposer/mobileModal/index.tsx
> +  const [search, setSearch] = useState('');
Going to leave this for now I think

2023-05-25 09:35 UTC, jamesej commented on packages/web-app/src/containers/smartContractComposer/mobileModal/index.tsx
> +              <ListHeaderContract
OK added this thanks

2023-05-25 10:12 UTC, Fabricevladimir approved these changes
Fingers crossed!

2023-05-25 10:14 UTC, merged