Feature/typeahead search dao 475
aragon/app-legacy pull request #86
Opened 2021-12-10 15:16 UTC by WissenIstNacht

This PR:

- Exposes the `value` and `onChange` attributes of `<input />` (and propagates it up throughout the parent react components). Thereby allowing for to be used as a controlled component.
- Introduces a series of hooks (`useDaoTokens`, `useTokenInformation`) that should be used as a blue print for fetching token-related later on.
- It introduces the `HookData<T>` that should be used as output type of asynchronous data-fetching hooks.
- It refactors the existing `usePollTokens` hook to conform to the above
- It introduces `sort` and `filter` methods for token information. 
- It refactors the existing search Input on `finance/tokens` page into a type-ahead search that allows to filter through tokens.

2021-12-13 11:01 UTC, Fabricevladimir requested changes
Great work! Ready for whatever data coming in

2021-12-13 11:01 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/textInput.tsx
> +      <StyledInput {...props} disabled={disabled} {...props} />
Spreading props twice.

2021-12-13 11:01 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/textInput.tsx
>  export type TextInputProps = {
This component doesn't seem to be using the base input type which means we lose all kinds of native input attributes. Can you modify the props to extend  `InputHTMLAttributes<HTMLInputElement>`? That way other than our additional props, everything is set automatically? Even the `onChange` event can be omitted from the props then.

2021-12-13 11:01 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/textInput.tsx
> +  onChange: (event: BaseSyntheticEvent) => void;
I think this might be the following might be the proper type: `React.ChangeEventHandler<HTMLInputElement>`. I don't think it should matter much since `BaseSyntheticEvent` is (?) the parent of all the other events, but just in case so we don't lose some specific attributes...

2021-12-13 11:01 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useDaoTokens.tsx
> +    if (daoAddress) 42;
I see you 42 lol

2021-12-13 11:01 UTC, Fabricevladimir commented on packages/web-app/src/utils/tokens.ts
> +    if (a[criteria] < b[criteria]) {
Good call since we might have to sort them based on different criteria

2021-12-13 11:01 UTC, Fabricevladimir commented on packages/web-app/src/utils/tokens.ts
> +      lowercaseSymbol.indexOf(lowercaseTerm) >= 0 ||
This man is a fan of IE 😄

2021-12-13 11:21 UTC, WissenIstNacht commented on packages/web-app/src/utils/tokens.ts
> +      lowercaseSymbol.indexOf(lowercaseTerm) >= 0 ||
Wait, what? Internet explorer...? 😅

2021-12-13 11:21 UTC, WissenIstNacht commented on packages/ui-components/src/components/input/textInput.tsx
>  export type TextInputProps = {
Legacy... Will take a moment to add the proper types!

2021-12-13 12:34 UTC, sepehr2github approved these changes
Thank you, Vali. Nice PR!

2021-12-13 12:34 UTC, sepehr2github commented on packages/web-app/src/utils/tokens.ts
> +export function sortTokens<K extends keyof BaseTokenInfo>(
I like How you play with Typing stuff:)))). Well Done!

2021-12-13 12:36 UTC, sepehr2github commented on packages/web-app/src/utils/tokens.ts
> +export function sortTokens<K extends keyof BaseTokenInfo>(
Also Please Take care of Fabrice Comments

2021-12-13 14:22 UTC, Fabricevladimir commented on packages/web-app/src/utils/tokens.ts
> +      lowercaseSymbol.indexOf(lowercaseTerm) >= 0 ||
Oh that was about preferring `indexOf` over `includes`. `includes` is ES6 so odds are IE does not support it!

2021-12-13 17:47 UTC, WissenIstNacht commented on packages/web-app/src/utils/tokens.ts
> +      lowercaseSymbol.indexOf(lowercaseTerm) >= 0 ||
Ehrm, yes, exactly, that was my intention! haha

2021-12-13 18:09 UTC, Fabricevladimir approved these changes
Ready to merge!

2021-12-13 18:09 UTC, Fabricevladimir commented on packages/ui-components/src/components/input/textInput.tsx
> +})<React.InputHTMLAttributes<HTMLInputElement>>``;
Isn't `StyledInput` all by itself enough? Assuming that styled-components has their return type correctly I mean...

2021-12-14 09:28 UTC, WissenIstNacht commented on packages/ui-components/src/components/input/textInput.tsx
> +})<React.InputHTMLAttributes<HTMLInputElement>>``;
Without the <type>, you mean? Possibly :)

2021-12-14 09:55 UTC, merged