feat: DRAFT APP-2194 existing tokens wrapping/unwrapping
aragon/app-legacy pull request #871
Opened 2023-06-09 15:42 UTC by babarella

## DRAFT
- Blocked by SDK. Unable to retrieve wrapped token address and details. (need unwrapped and wrapped token details)
- Translations are hard-coded (no crowdine keys yet)
- The wrap-unwrap modal visible by default (for development purposes).
- Other minor things needed from Selim to agree on.

CC: @jamesej @sepehr2github

## Description

**This is DRAFT PR for wrapping-unwrapping existing tokens functionality.**

[APP-2194](https://aragonassociation.atlassian.net/browse/APP-2194)
[APP-2231](https://aragonassociation.atlassian.net/browse/APP-2231)
[APP-2232](https://aragonassociation.atlassian.net/browse/APP-2232)

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2023-06-27 11:29 UTC, sepehr2github requested changes
Hey, thanks but I found a new issue, 
When I click on create dao the wrapping modal comes up with a loading! could you check that, Thanks

2023-06-29 18:01 UTC, sepehr2github requested changes
<img width="372" alt="Screenshot 2023-06-29 at 9 27 56 PM" src="https://github.com/aragon/app/assets/46657145/7afa615b-d674-42f0-a8c6-fd93c2af5809">

<img width="409" alt="Screenshot 2023-06-29 at 9 29 22 PM" src="https://github.com/aragon/app/assets/46657145/47d4f4c4-5776-4d07-b1f7-95a33595cedf">

The description should have some variables in it, ANT should be replaced with dao token symbols, 

Also, I couldn't wrap the token, When enter a number the button stay disabled, Also  the mint token buttons should be hided as well if a underlying token exists
<img width="1188" alt="Screenshot 2023-06-29 at 9 30 25 PM" src="https://github.com/aragon/app/assets/46657145/a9b5f734-433c-4e99-b8fa-dcd0f49ad5c8">

2023-06-29 18:26 UTC, babarella commented
> <img alt="Screenshot 2023-06-29 at 9 27 56 PM" width="372" src="https://user-images.githubusercontent.com/46657145/249858583-7afa615b-d674-42f0-a8c6-fd93c2af5809.png"> <img alt="Screenshot 2023-06-29 at 9 29 22 PM" width="409" src="https://user-images.githubusercontent.com/46657145/249858747-47d4f4c4-5776-4d07-b1f7-95a33595cedf.png">
> The description should have some variables in it, ANT should be replaced with dao token symbols,
> 
> Also, I couldn't wrap the token, When enter a number the button stay disabled, Also the mint token buttons should be hided as well if a underlying token exists <img alt="Screenshot 2023-06-29 at 9 30 25 PM" width="1188" src="https://user-images.githubusercontent.com/46657145/249858823-a9b5f734-433c-4e99-b8fa-dcd0f49ad5c8.png">

![image](https://github.com/aragon/app/assets/114730054/32fd26a8-64eb-438e-b593-ddaa5d5c5b8c)

Hey, Sepehr, I'm not sure what the issues on your side are but I am not able to reproduce them.
The token symbol is passed, just when daoToken is not loaded, then the placeholder is ANT for informational purposes.

2023-06-29 18:49 UTC, Fabricevladimir approved these changes

2023-06-29 18:49 UTC, Fabricevladimir commented on packages/web-app/src/context/govTokensWrapping.tsx
> +      amount: BigInt(Number(amount)),
If amount is a string why not go directly to BigInt since the custructor supports passing in a string?

2023-06-29 19:18 UTC, sepehr2github approved these changes
Thanks

2023-06-29 19:27 UTC, merged