Fix: APP-2233 - get members for token existing from covalent API
aragon/app-legacy pull request #881
Opened 2023-06-19 09:26 UTC by sepehr2github

## Description

- use getTokenHoldersPaged and getTotalHolders to fetch total holders and members list

Task: [APP-2233](https://aragonassociation.atlassian.net/browse/APP-2233)

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2023-06-19 11:13 UTC, Fabricevladimir requested changes
Thanks, Sepehr. Left a few comments

2023-06-19 11:13 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useDaoMembers.tsx
> +            network,
When the network is Goerli, this is going to throw because Covalent does not support Goerli. Isn't the idea to fallback to the subgraph then? 

Also, when this throws, the entire existing tokens governance compatibility hangs. Idealy, we should either show subgraph data or no total holders and still allow the token to be used in the flow

2023-06-19 11:13 UTC, Fabricevladimir commented on packages/web-app/src/components/verificationCard/index.tsx
> +  if (!tokenType || !tokenTotalHolders)
If the query for fetching tokenTotalHolders throws an error (for example the contract doesn't exist or the we're on Goerli), `tokenTotalHolders` will be `undefined` and cause this spinner to show forever.

2023-06-20 08:06 UTC, sepehr2github commented on packages/web-app/src/hooks/useDaoMembers.tsx
> +            network,
Selim is supposed to prepare a empty screen for us, I can redirect to subgraph till then

2023-06-21 08:02 UTC, Fabricevladimir approved these changes

2023-06-21 11:12 UTC, merged