Feat: APP-2230 tweaking dao creation flow to account for wrapped tokens
aragon/app-legacy pull request #885
Opened 2023-06-21 22:07 UTC by babarella

## Description

Tweaking dao creation flow to account for wrapped tokens

Task: [APP-2230](https://aragonassociation.atlassian.net/browse/APP-2230) [APP-2226)](https://aragonassociation.atlassian.net/browse/APP-2226)

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2023-06-25 19:47 UTC, sepehr2github commented on packages/web-app/src/containers/configureCommunity/minParticipation.tsx
> +  const isGovTokenRequiresWrapping =
The min participation flow should be applied only for ERC20 and not ERC20 governance

2023-06-25 19:49 UTC, sepehr2github commented on packages/web-app/src/containers/setupCommunity/addExistingToken.tsx
> +          <SelectEligibility />
We have an eligibility token component in verification card as well, please merge those duplicated components

2023-06-25 19:56 UTC, sepehr2github requested changes
<img width="836" alt="Screenshot 2023-06-25 at 11 22 50 PM" src="https://github.com/aragon/app/assets/46657145/f7c0c4ca-e537-455b-b517-59bfac82452e">

Thanks, Nikita, I think after the merge the flow of ERC20 and governance ERC20 is broken, For example, minimum participation doesn't look proper for compatible token

2023-06-27 00:22 UTC, babarella commented
> <img alt="Screenshot 2023-06-25 at 11 22 50 PM" width="836" src="https://user-images.githubusercontent.com/46657145/248583974-f7c0c4ca-e537-455b-b517-59bfac82452e.png">
> Thanks, Nikita, I think after the merge the flow of ERC20 and governance ERC20 is broken, For example, minimum participation doesn't look proper for compatible token

Resolved, thank you for your findings.

2023-06-28 09:50 UTC, sepehr2github approved these changes
Thanks

2023-06-28 13:38 UTC, merged