Feat: DAO Wallet Connect Main Flow
aragon/app-legacy pull request #908
Opened 2023-07-05 06:46 UTC by RakeshUP

## Description

Pending flows: 
- To check mobile UI
- Action builder accordion for WC actions
- cleanup useWalletConnectInterceptor hook

Task: [APP-2263](https://aragonassociation.atlassian.net/browse/APP-2263), [APP-2265](https://aragonassociation.atlassian.net/browse/APP-2265), [APP-2266](https://aragonassociation.atlassian.net/browse/APP-2266)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [ ] I have tested my code on the test network.

2023-07-05 11:52 UTC, Fabricevladimir requested changes
Fantastic work, Rakesh! Lots of good stuff here! Left a few minor comments

2023-07-05 11:52 UTC, Fabricevladimir commented on packages/web-app/src/containers/walletConnect/dAppValidationModal/index.tsx
> +  const [uri] = useWatch({name: [WC_CODE_INPUT_NAME], control});
Not an issue here, but I think if we go with "uri", it's also worth updating the symbolic constant name to reflect that as well.

2023-07-05 11:52 UTC, Fabricevladimir commented on packages/web-app/src/containers/walletConnect/dAppValidationModal/index.tsx
> +          onClick={handleConnectDApp}
Hey, this one is on me, but can you change the icon from IconSpinner to the actual xs `Spinner` component we have that spins when the connection status is LOADING?

Also, can you disable the input while the status is loading and successful?

2023-07-05 11:52 UTC, Fabricevladimir commented on packages/web-app/src/containers/actionBuilder/index.tsx
> +      //TODO: Create a separate action-builder accordion for Wallet Connect Actions to handle the non-decodable flow and AlertCards
Thanks for the TODO!

2023-07-05 11:52 UTC, Fabricevladimir commented on packages/web-app/src/containers/walletConnect/index.tsx
> +  if (
I'm guessing it's taking to long to determine which modal to show? Would having the list of connected dApps in the same modal as the empty state help?

2023-07-05 11:52 UTC, Fabricevladimir commented on packages/web-app/src/containers/walletConnect/dAppValidationModal/index.tsx
> +              label={t('wc.validation.codeInput.statusSuccess')}
This translation string needs the dApp name as a variable

2023-07-05 11:52 UTC, Fabricevladimir commented on packages/web-app/src/containers/walletConnect/dAppValidationModal/index.tsx
> +  const handleConnectDApp = useCallback(async () => {
For whatever reason, the first time I click on the button after successfully connecting to the dApp, the App crashes.

Also, when I have at least 1 dApp connected and then connect an additional one, the newly connected dApp is not shown on the `connectedAppsModal` and the `actionListenerModal` is shown with the previous dApp.

2023-07-05 11:52 UTC, Fabricevladimir commented on packages/web-app/src/containers/walletConnect/connectedAppsModal/index.tsx
> +              label={'Connect new dApp'}
Don't forget the translation string for this

2023-07-05 11:52 UTC, Fabricevladimir commented on packages/web-app/src/containers/walletConnect/connectedAppsModal/index.tsx
> +            />
There is also a "Learn more" external link under the cta button

2023-07-05 11:52 UTC, Fabricevladimir commented on packages/web-app/src/containers/walletConnect/actionListenerModal/index.tsx
> +            <IconSpinner className="mr-2 w-1.75 desktop:w-2.5 h-1.75 desktop:h-2.5 animate-spin" />
There is a spinner component already, also the color of the spinner should be one of the primary colors (500 maybe?)

2023-07-05 11:52 UTC, Fabricevladimir commented on packages/web-app/src/containers/walletConnect/actionListenerModal/index.tsx
> +            onClick={() => wcDisconnect(selectedSession.topic)}
When I disconnect the dApp, the `actionListenerModal` is still shown for that dApp. Additionally, the dApp still shows on the `connectedAppsModal` until the WC flow is exited and re-opened. Is this intentional?

2023-07-05 11:52 UTC, Fabricevladimir commented on packages/web-app/src/containers/walletConnect/connectedAppsModal/index.tsx
> +import Header from 'containers/smartContractComposer/desktopModal/header';
If we are reusing this here, it might make sense to move it from the smartContractComposer folder into the main components one.

2023-07-06 09:15 UTC, RakeshUP commented on packages/web-app/src/containers/walletConnect/connectedAppsModal/index.tsx
> +            />
I don't see it in the designs 🤔

2023-07-06 09:17 UTC, RakeshUP commented on packages/web-app/src/containers/walletConnect/connectedAppsModal/index.tsx
> +import Header from 'containers/smartContractComposer/desktopModal/header';
Actually, I was thinking we should maybe use a separate one for WC because the Header in SCC has some SCC specific code. Please see if we want to use a new one when you work on the action builder.

2023-07-07 05:24 UTC, RakeshUP commented on packages/web-app/src/containers/walletConnect/dAppValidationModal/index.tsx
> +  const handleConnectDApp = useCallback(async () => {
Fixed the crashing issue. I'm still not sure if we are using WC correctly, the disconnect flow still is buggy. Will fix those issues once we complete the whole UI flow

2023-07-07 05:26 UTC, RakeshUP commented on packages/web-app/src/containers/walletConnect/actionListenerModal/index.tsx
> +            onClick={() => wcDisconnect(selectedSession.topic)}
No this is a bug and I'm not able to find out why it's not working. The `session_delete` event is supposed to fired by WC, which can be used to update our UI and remove the app from the `connectedAppsModal`. Will fix it once the whole Proposal flow is complete

2023-07-09 10:20 UTC, Fabricevladimir commented on packages/web-app/src/containers/walletConnect/connectedAppsModal/index.tsx
> +import Header from 'containers/smartContractComposer/desktopModal/header';
Actually, we can refactor it I think by moving out a handler and passing in the string it should display.

2023-07-09 10:20 UTC, Fabricevladimir commented on packages/web-app/src/containers/walletConnect/connectedAppsModal/index.tsx
> +            />
Take a look at this node [here](https://www.figma.com/file/rMMNyElDv5S0y3Niu1k8TJ/Governance?type=design&node-id=9019-15442&mode=design&t=QPTKxuUjkM4X54B8-0)

2023-07-09 10:24 UTC, Fabricevladimir reviewed
Once that external link comes in, I think this will be good to merge! Thanks

2023-07-09 10:24 UTC, Fabricevladimir commented on packages/web-app/src/containers/walletConnect/dAppValidationModal/index.tsx
> +  const handleConnectDApp = useCallback(async () => {
Sounds good.

2023-07-09 10:24 UTC, Fabricevladimir commented on packages/web-app/src/hooks/useWalletConnectInterceptor.ts
> +      // if (!currentWcRecord) {
Can you delete these commented out code if they're not going to be used again?

2023-07-10 07:29 UTC, RakeshUP commented on packages/web-app/src/containers/walletConnect/index.tsx
> +  if (
If I am correct, wallet connect is returning the active sessions pretty quickly, but loading the dApp icons is taking more time than that. that's why the connectedAppsModal looks like it takes pretty long to load.

2023-07-10 07:30 UTC, RakeshUP commented on packages/web-app/src/hooks/useWalletConnectInterceptor.ts
> +      // if (!currentWcRecord) {
I'm thinking of refactoring this file and the walletConnectInterceptor file inside the `services` directory. I'm not sure if WC websockets are causing the bugs mentioned above or our code.. After the flow is ready, I was thinking I'll debug the hook and make necessary changes

2023-07-10 09:22 UTC, Fabricevladimir approved these changes
Let's go!

2023-07-10 10:53 UTC, merged