fix: APP-2253 removed scroll from modals and bottom sheet components
aragon/app-legacy pull request #917
Opened 2023-07-11 21:08 UTC by babarella

## Description

When popup modals are displayed, background page is still scrollable.

Task: [APP-2253](https://aragonassociation.atlassian.net/browse/APP-2253)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the ``CHANGELOG.md`` file in the root folder.
- [x] I have tested my code on the test network.

2023-07-12 07:34 UTC, RakeshUP commented on packages/ui-components/src/components/backdrop/backdrop.tsx
> +  }, []);
I think this useEffect block is interfering with the one below. I was able to prevent scrolling only when I commented out this block of code. Could you check if that's right?

2023-07-12 07:35 UTC, RakeshUP requested changes
I'm not able to test this one. It could be due to the useEffect block that I've mentioned in the comment. Seems like two useEffects's are racing to set `overflow` on the html tag

2023-07-12 10:37 UTC, Fabricevladimir commented
@babarella, Can you take a look at Radix UI? We're using their headless Dialog component, which _should_ by default render the content underneath inert/unscrollable

2023-07-12 18:58 UTC, babarella commented
> @babarella, Can you take a look at Radix UI? We're using their headless Dialog component, which _should_ by default render the content underneath inert/unscrollable

Applied radix overlay for modals, thanks for suggestion.

2023-07-13 08:56 UTC, RakeshUP approved these changes
Thanks!

2023-07-13 11:35 UTC, merged