Feature/Label component DAO-530
aragon/app-legacy pull request #93
Opened 2021-12-14 12:53 UTC by RakeshUP

2021-12-14 18:35 UTC, Fabricevladimir reviewed
Good work!

2021-12-14 18:35 UTC, Fabricevladimir commented on packages/ui-components/src/components/label/label.tsx
> +      {helpText && <HelpText>{helpText}</HelpText>}
If `helpText` is being shown only when it's not null or undefined, should it not be optional as well?

2021-12-14 18:35 UTC, Fabricevladimir commented on packages/ui-components/src/components/label/label.tsx
> +        {isOptional && <Badge label='Optional' />}
For the sake of translations, the `label` property of the `Badge` should also be received as a prop. Very tedious to work with. Perhaps we can have something like the following for these things: `<Badge label={badgeLabel || 'Optional'} />`.  
But then again, that pollutes all the code. Any ideas for this kind of stuff in general? It's almost like someone not using internationalization is being punished...

2021-12-15 11:01 UTC, RakeshUP commented on packages/ui-components/src/components/label/label.tsx
> +        {isOptional && <Badge label='Optional' />}
I've made changes as you've suggested. I too don't have any idea right now :)

2021-12-15 14:25 UTC, WissenIstNacht requested changes, later dismissed
Looking good, thanks! 👌🏻

2021-12-15 14:25 UTC, WissenIstNacht commented on packages/ui-components/src/components/label/label.tsx
> +  isOptional?: boolean;
Very minor detail here:

To stay consistent with the designs (and the vocabulary in it), I would treat the badge the same way you did `helptext`. I.e., just have one optional field called `badge` of type `string`. If empty, no badge is shown, otherwise, the badge is displayed with the text passed in `badge`.

2021-12-16 09:55 UTC, Fabricevladimir commented on packages/ui-components/src/components/label/label.tsx
> +  isOptional?: boolean;
Agreed. In fact, the whole badge might have been meant to be passed in. Like what if you need a success badge next to your label?

2021-12-16 09:58 UTC, Fabricevladimir approved these changes
Ready to merged once the requested changes are made!

2021-12-16 10:08 UTC, sepehr2github approved these changes
Thank you Rakash. Nice Pr!

2021-12-16 10:08 UTC, sepehr2github commented on packages/ui-components/src/components/label/label.tsx
> +        {isOptional && <Badge label={badgeLabel || 'Optional'} />}
Can you make the 'Optional' lowercase?

2021-12-16 10:11 UTC, WissenIstNacht commented on packages/ui-components/src/components/label/label.tsx
> +  isOptional?: boolean;
This crossed my mind too. I decided against it since I would expect him to design the interface (on figma) differently. Currently, there's only a boolean variable for `badge`.

But now that I think about it again, I might be wrong. This might be worth clarifying with Selim. @RakeshUP Could you please ask him how he envisioned it and try to align both his design and your implementation?

2021-12-17 11:43 UTC, RakeshUP commented on packages/ui-components/src/components/label/label.tsx
> +        {isOptional && <Badge label={badgeLabel || 'Optional'} />}
It's capital Optional in the design

2021-12-17 11:50 UTC, RakeshUP commented on packages/ui-components/src/components/label/label.tsx
> +  isOptional?: boolean;
According to the design, the badge was a boolean. 
The other text prop lets us pass i18n text label for the badge. We don't have i18n in ui-component package.

2021-12-17 11:52 UTC, RakeshUP commented
Things are a little ambiguous around the badge used in this component. I'm still going ahead and merging it, lets change it later when we have more clarity

2021-12-17 11:52 UTC, merged