F/app 2297
aragon/app-legacy pull request #941
Opened 2023-07-26 10:29 UTC by sepehr2github

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task: [APP-0000](https://aragonassociation.atlassian.net/browse/APP-0000)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have tested my code on the test network.

2023-07-28 13:21 UTC, Fabricevladimir requested changes
Nice work, but unfortunately this dies at the propose setting step

2023-07-28 13:21 UTC, Fabricevladimir commented on src/containers/compareSettings/index.tsx
> +    toDisplayEns(daoDetails?.ensDomain) === ''
This is fine, but why not use the or operator?

2023-08-02 07:55 UTC, sepehr2github commented on src/containers/compareSettings/index.tsx
> +    toDisplayEns(daoDetails?.ensDomain) === ''
because toDisplayEns doesn't return null or undefined

2023-08-07 10:03 UTC, Fabricevladimir reviewed
Thanks, Sepher. Nice job dealing with these nasty little issues! 
One final thing, considering going directly to settings/new-proposal only shows the page with no data, can you add a check to make sure that when the user goes directly to that page they get redirected to the Edit Settings page if possible? If not, the next best thing would be redirected to the Settings page. What do you think?

2023-08-07 10:03 UTC, Fabricevladimir commented on src/containers/compareSettings/compareMetadata.tsx
> +            URL_PATTERN.test(daoLogo) || daoLogo?.startsWith?.('blob') ? (
Would be nice to add this starts with test into the regex itself.

2023-08-07 10:03 UTC, Fabricevladimir commented on src/containers/defineMetadata/index.tsx
> +              if (URL_PATTERN.test(value) || value?.startsWith?.('blob')) {
See comment on `compareMetadata.tsx`

2023-08-07 10:03 UTC, Fabricevladimir commented on src/hooks/useDaoDetails.tsx
> +    if (avatar && typeof avatar !== 'string') {
The check for whether the avatar exits seems to be duplicated for no reason

2023-08-07 10:03 UTC, Fabricevladimir commented on src/hooks/useDaoDetails.tsx
> +      daoDetails!.metadata.avatar = URL.createObjectURL(avatar);
The non-null assertion is unnecessary because the condition assumes that avatar, a nested property of `daoDetails`, exists.

2023-08-07 10:03 UTC, Fabricevladimir commented on src/hooks/useDaoDetails.tsx
> +        daoDetails!.metadata.avatar = URL.createObjectURL(imageBlob);
Same thing here

2023-08-07 10:03 UTC, Fabricevladimir commented on src/hooks/useDaoDetails.tsx
> +      daoDetails!.metadata.avatar = avatar;
And here as well.

2023-08-07 10:03 UTC, Fabricevladimir commented on src/containers/editSettings/multisig.tsx
> +    if (!daoDetails?.metadata.name || !daoName || daoName === '') return false;
Something like this might be a bit more concise.
```suggestion
    if (!daoDetails?.metadata.name || !daoName?.trim()) return false;
```

2023-08-07 10:03 UTC, Fabricevladimir commented on src/containers/editSettings/multisig.tsx
> +    setValue('areSettingsChanged', isMetadataChanged || isGovernanceChanged);
Aha so previously only governance changes were being tracked! Good catch

2023-08-07 11:11 UTC, sepehr2github commented on src/containers/defineMetadata/index.tsx
> +              if (URL_PATTERN.test(value) || value?.startsWith?.('blob')) {
The URL_PATTERN Regex is using for links list as well so I think keeping it link this will be better

2023-08-07 11:11 UTC, sepehr2github commented on src/containers/compareSettings/compareMetadata.tsx
> +            URL_PATTERN.test(daoLogo) || daoLogo?.startsWith?.('blob') ? (
The URL_PATTERN Regex is using for links list as well so I think keeping it link this will be better

2023-08-07 12:42 UTC, Fabricevladimir approved these changes

2023-08-07 12:42 UTC, Fabricevladimir commented on src/pages/proposeSettings.tsx
> +          navigate(generatePath(Settings, {network, dao: daoDetails?.address}));
Sorry, this is on me, can you switch that from settings to edit settings page instead?

2023-08-07 13:35 UTC, merged