WIP: Feat: Offchain DAO creation
aragon/app-legacy pull request #957
Opened 2023-08-03 06:57 UTC by selankon

## Description

This PR is developed on the vocdoni `offChain` plugin context.  

The branch implement changes on the DAO creation form to add the option to create `offChain` proposals with a executive committee. 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have tested my code on the test network.

2023-08-03 06:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aragon/app?pullRequest=957) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aragon/app?pullRequest=957) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aragon/app?pullRequest=957) it.</sub>

2023-09-22 12:01 UTC, elboletaire requested changes
Some of the `useMemo` and `useCallbacks` used are not necessary. Ensure you try any changes to these methods, since I can only speak for the code I've seen... I tried to check all the affected methods to ensure I'm not saying it wrong, but I could be wrong in some of them... so double-check it please.

2023-09-22 12:01 UTC, elboletaire commented on package.json
> +    "@vocdoni/sdk": "^0.1.1",
Both need upgrade:
- react providers should be at least 0.1.9
- sdk should be at least 0.3.1

2023-09-22 12:01 UTC, elboletaire commented on src/components/addCommitteeMembers/index.tsx
> +  };
In a case like this, it's usually better to use an affect for the second action (in this case listening for changes in the addresses field). Doing so, you may not need the timeout anymore.

Still, is not a terrible solution to have a timeout this way

2023-09-22 12:01 UTC, elboletaire commented on src/components/addCommitteeMembers/index.tsx
> +  };
Kinda confusing to see the timeout below set to zero when this one is set to 50 though.

2023-09-22 12:01 UTC, elboletaire commented on src/components/executionExpirationtime/index.tsx
> +  );
Considering how are you using these methods (`handleDaysChanged`, `handleHoursChanged` and `handleMinutesChanged`), I don't think you need to use `useCallback` at all. These could probably be defined as regular methods, since you're not using state values in the methods (you're using state methods, but not state values). `useCallback` is used mostly when you need to access state values in the function that could change, but I don't see this being the case.

2023-09-22 12:01 UTC, elboletaire commented on src/components/filteredAddressList/index.tsx
> +  );
In this case it totally makes sense to use a `useCallback` because you're using a state value (`searchValue`) in your function. No need to do anything here, just adding a comment for extending my explanation above.

2023-09-22 12:01 UTC, elboletaire commented on src/containers/goLive/committee.tsx
> +import CommitteeAddressesModal from '../committeeAddressesModal';
[minor] weird import sorting

2023-09-22 12:01 UTC, elboletaire commented on src/context/createDao.tsx
> +
[minor] Most, if not all, of these imports should be above the already existing ones. Again, weird import sorting.

Note there's no need to alphabetically sort them, but at least they should be properly grouped (first external imports, then `../`, finally `./`).

2023-09-22 12:01 UTC, elboletaire commented on src/context/createDao.tsx
> +  );
I'm pretty sure this callback does not need to be a callback either.

2023-09-22 12:01 UTC, elboletaire commented on src/context/createDao.tsx
> +        } else {
Avoid using `else` when possible. In this case you could `break` the execution at the end of the if, and skip the usage of the `else` (and all its related indentation).

Not a required change, since it won't affect in code's efficiency, but would help following coders to read it better.

2023-09-22 12:01 UTC, elboletaire commented on src/components/addCommitteeMembers/row.tsx
> +        return validationResult;
For consistency, use brackets here (`{}`) or move the return to the same line, so it's a one-liner.

2023-09-22 12:01 UTC, elboletaire commented on src/pages/createDAO.tsx
> +  }, [eligibilityType, errors.eligibilityTokenAmount, membership]);
No need to use `useMemo` here.

2023-09-22 13:55 UTC, selankon commented on package.json
> +    "@vocdoni/sdk": "^0.1.1",
As the packages are not yet on npmjs i didn't push the update awaiting the last version before merge to develop. But thanks to remember it!

2023-10-16 09:50 UTC, selankon commented on src/components/addCommitteeMembers/index.tsx
> +  };
This code cames from https://github.com/aragon/app/blob/develop/src/components/addWallets/index.tsx#L73-L85 and when rebased from actual develop head, the second timeout will have also timeout. I add it here 2ea8af38

2023-10-16 09:54 UTC, selankon commented on src/components/executionExpirationtime/index.tsx
> +  );
This code cames from https://github.com/aragon/app/blob/develop/src/containers/configureCommunity/index.tsx#L54-L127 , implemented as `useCallback` so I will let as is

2023-10-16 09:57 UTC, selankon commented on src/containers/goLive/committee.tsx
> +import CommitteeAddressesModal from '../committeeAddressesModal';
mmm the import sorting is done by prettier rules and are automatically executed when document is saved. So i cannot change it, the rules are defined by the configuration files of the repository.

2023-10-16 10:01 UTC, selankon commented on src/context/createDao.tsx
> +
Same as above, I am not sure I can change this manually

2023-10-16 10:16 UTC, selankon commented on src/context/createDao.tsx
> +  );
This is a callback because this code is inspired from a similar function from the Aragon app code: https://github.com/aragon/app/blob/develop/src/context/createDao.tsx#L152-L155 .

2023-10-16 11:18 UTC, selankon commented on src/components/addCommitteeMembers/row.tsx
> +        return validationResult;
fix 26c7ced8

2023-10-16 11:18 UTC, selankon commented on src/context/createDao.tsx
> +        } else {
Fix 26c7ced8

2023-10-16 13:46 UTC, elboletaire commented on src/containers/goLive/committee.tsx
> +import CommitteeAddressesModal from '../committeeAddressesModal';
I'd said prettier does sort as I said (we're using it in ui-components and ui-scaffold following such rules). Are you sure you have the sort on save actually enabled? If so, kinda weird rules IMHO 😅

2023-10-30 11:52 UTC, selankon commented
Closed in favour to https://github.com/aragon/app/pull/1074

2023-10-30 11:52 UTC, closed without merging