Feature/New components - wizard & linear progress DAO-531
aragon/app-legacy pull request #96
Opened 2021-12-15 10:51 UTC by RakeshUP

2021-12-15 17:25 UTC, WissenIstNacht requested changes
Thanks for exporting the components :)

2021-12-15 17:25 UTC, WissenIstNacht commented on packages/ui-components/src/components/progress/linearProgress.tsx
> +  ::-webkit-progress-bar {
Soooooo apparently this is not yet officially supported for firefox :joy:

If you have a fix, go for it. Otherwise don't worry. Just drop a "FIXME" or"TODO" and we'll find a way to deal with it later. 👍🏻

2021-12-15 17:25 UTC, WissenIstNacht commented on packages/ui-components/tailwind.config.js
> +      lg: '976px',
_technically_ `desktop` is supposed to be `lg` haha.

The designs were lagging behind here when we settled on names and value, hence why it's wrong. Sorry for that. Could you change `976px` to `1280px`? No need to change the rest rn. We'll try to have a dedicated task for this at some point.

2021-12-15 17:25 UTC, WissenIstNacht commented on packages/ui-components/src/components/wizard/wizard.tsx
> +        <p className="text-ui-400">Step {currentStep} of {totalSteps}</p>
Parts of this is going to be untranslated 😕

I'm honestly not sure how to deal with this... It seems stupid to pass in "Step" and "of" as a label. In particular since I'm not sure it even works in every language. Even with the locales and i10n I'm not sure this is simple easy to achieve. Maybe we should sync with Selim on that and ask him to stick with an "x/y" format for now...

No need for action, that's ok for now. But could you add a TODO here, too?

2021-12-15 17:25 UTC, WissenIstNacht commented on packages/ui-components/src/components/wizard/wizard.tsx
> +  description?: string;
Don't think this is ever optional 🤔

2021-12-16 10:44 UTC, Fabricevladimir requested changes
Good work!

2021-12-16 10:44 UTC, Fabricevladimir commented on packages/ui-components/src/components/progress/linearProgress.tsx
> +  ::-webkit-progress-bar {
For the moment it might be best to bite the bullet and just have it as a nested div with the size of the inner one being the percentage. Like this the style is stuck to these specific colors too... But I really like the progress element...

2021-12-16 10:44 UTC, Fabricevladimir commented on packages/ui-components/src/components/wizard/wizard.tsx
> +        <p className="text-ui-400">Step {currentStep} of {totalSteps}</p>
Either that or just have the user pass in the whole string (not a fan of). But if we are passing in `currentStep` as well as `totalSteps`, the percentage should be calculated by the component itself. ` <LinearProgress max={totalSteps} value={currentStep} />`

2021-12-16 12:56 UTC, sepehr2github commented on packages/ui-components/src/components/progress/linearProgress.tsx
> +  ::-webkit-progress-bar {
I think it's possible to make it compatible with firefox by adding a -moz- prefix? I'm not sure

2021-12-16 13:00 UTC, sepehr2github reviewed
As always you did a great job! Thank you.

2021-12-17 11:57 UTC, RakeshUP commented on packages/ui-components/tailwind.config.js
> +      lg: '976px',
Changed lg to 1280px. I found out this figma grid component just now, we'll change the viewports like in this file later
https://www.figma.com/file/ZHEzSel0rN5aFIpXjn3341/Aragon-Design-Tokens?node-id=213%3A5

2021-12-17 15:43 UTC, RakeshUP commented on packages/ui-components/src/components/progress/linearProgress.tsx
> +  ::-webkit-progress-bar {
Fixed that. It was possible when using -moz prefix

2021-12-17 15:44 UTC, RakeshUP commented on packages/ui-components/src/components/wizard/wizard.tsx
> +        <p className="text-ui-400">Step {currentStep} of {totalSteps}</p>
removed progressValue prop. The component now calculates the progress using the current and total steps

2021-12-17 15:46 UTC, RakeshUP commented on packages/ui-components/src/components/wizard/wizard.tsx
> +        <p className="text-ui-400">Step {currentStep} of {totalSteps}</p>
@WissenIstNacht Good catch. I've added a TODO. Maybe we could switch to x/y format. I'll inform Selim and see what he comes up with

2021-12-17 17:03 UTC, WissenIstNacht approved these changes

2021-12-20 09:20 UTC, Fabricevladimir approved these changes

2021-12-20 09:35 UTC, merged