Feature/token selection modal DAO-509
aragon/app-legacy pull request #97
Opened 2021-12-16 11:20 UTC by sepehr2github

- Token Modal added
- WalletAugmentedContext updated / provider added
- erc20Token api added
- FetchBalance service added
- formatUnits function added for hexadecimal
- Network token config added
- getTokenInfo & isTokenERC20 function added utils/token

Note: because there is no direct way to fetch a list of wallet tokens from ethers.js I had to check the balance for each token one by one

2021-12-17 12:34 UTC, WissenIstNacht requested changes
Hey, thanks for that huge piece of work! Lots of new and tricky things in there!

However, there's quite a few things I don't understand why you did them the way you did. Also, dividing your work into smaller, indenpendent tasks would really have helped here.

If there's anything unclear in my comments, anything you don't understand or you think I didn't understand, please let me know.

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/utils/tokens.ts
> +export async function isTokenERC20(
This method is unused.

Also, I'm confused what you wanted to do with it? When would you use it? I mean if you create a contract from an erc20 abi although the address is not an erc20 contract, you will get an error anyway?

Maybe I'm missing something, let me know! :)

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/utils/tokens.ts
> +    decimals = await contract.decimals();
Please put these calls into an array and pass it to `Promise.all()`. Then await the promise.

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/utils/tokens.ts
> +  } catch (err) {}
Please don't swallow errors.

If another dev uses this and something goes wrong in this method, it's going to be absolutely impossible to find the problem. At the _very least_ `console.error` the error or don't catch it at all. Ideally, extend `Error` properly and throw it. In _any case_ please document that the function can go wrong and what happens when it does.

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/utils/network.ts
> +export const networks: networksType = {
None of these are `networks` 😅

See my comments in `type.ts` for more detail.

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/utils/types.ts
> +export type networksType = {
1) Types are capitalized
2) The information in this type does not describe a network
3) I don't think this is necessary. You can put this directly into environmentConfig. By this I mean: You can directly put these tokens into the `curatedTokens` `Record` in `EnvironmentConfig`.

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/utils/types.ts
> +  networkName: string;
`networkName` is not necessary, as it can always be accessed form `useWallet` (there is information in there for every chain).

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/utils/types.ts
> +export type ChainId = 1 | 4;
```suggestion
export type SupportedChainId = 1 | 4;
```

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/services/amount.ts
> +/**
space (it's free! :D)

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/context/augmentedWallet.tsx
> +  isConnected: boolean;
`useWallet` already provides `isConnected` and `account`, no need to retype them here.

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/context/augmentedWallet.tsx
> +  const [provider, updateProvider] =
please stick to the typical react style and call this `setProvider`, so everyone knows this function belongs to `useState`.

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/context/transfersModal.tsx
> +   * TODO: ==============================================
Yes, so I guess this is an open discussion at this point. I personally would manage all the modals in one context, since they are all related to one another (in the sense that you can never two modals open at the same time). In other words, I agree with the changes you made here. I would even go on step further and expand this for every type of modal we have. 

But this is totally ok for now 👍🏻

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/ui-components/src/components/input/SearchInput.tsx
>  export type SearchInputProps = Omit<TextInputProps, 'adornment' | 'side'>;
`side` and `adornment` both no longer exist on the parent type.

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/ui-components/src/components/input/textInput.tsx
> +  rightAdornmentOnClick?: () => void;
This is a tricky one. I understand why you did this, but I'm not sure it was a good idea. The reason I'm saying this is because the interface of this component is now completely different from the designs. For example, the `SearchInput` with the cross on the right hand side is just the active state of the component. It's not a text input with two adornments.

In other words, we will have to work this completely in the future. I don't want to throw your hard work away now, so we'll keep it as is now. But in the future, I would please ask you not to change components if they are different than on the design (If any one gives you trouble for this send them ot me. I'll explain to them why it's not your fault). In general, just work with what you have (even if it's not completely right), and then do a complete refactor later. If what you have is really unsuable (i.e., completely different from the designs), then please create a separate ticket and make the changes before you need them.

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/services/amount.ts
> +export const FetchBalance = async (
function name should be lower case.

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/services/amount.ts
> + * @returns a promise that will return a balance amount
fetchBalance should return a single numer value that is the balance of the `walletAddress` in the `contractAddress`.

Other information should be separated.

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/utils/tokens.ts
> +export async function getTokenInfo(
Why is this method necessary? Can't we get this method through the APIs we use?

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/containers/tokenMenu/tokenBox.tsx
> +  return balance && balance !== '0.0' ? (
I think ethers provides an isZero check, no?

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/containers/tokenMenu/tokenBox.tsx
> +export default function TokenBox({
According to the design, this should be a `ListItemToken`. It should be part of the ui library and not in the web-app.

Do not change this as part of this PR, but make create a separate subtask ticket. Ideally, this should have been done before this PR.

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/containers/tokenMenu/index.tsx
> +  const {control, watch, resetField} = useForm({
This looks like a VERY complicated way of doing something that can be done in 2 lines of code :D.

Is this really necessary for a simple typeahead search?

2021-12-17 12:34 UTC, WissenIstNacht commented on packages/web-app/src/containers/tokenMenu/index.tsx
> +          {Object.entries(networks[chainId || 4].curatedTokens)
I'm not sure about the data / types in this component. I've mentioned this somewhere else already, but hy fetch this data explicitly? Don't we fetch this information already? (and by "already" I mean, as soon as we are connected to our APIs. For now you would have to mock like we did for other tokens.)

2021-12-20 10:45 UTC, sepehr2github commented on packages/web-app/src/containers/tokenMenu/tokenBox.tsx
> +  return balance && balance !== '0.0' ? (
yes but It works with a BigNumber  format

2021-12-20 14:16 UTC, sepehr2github commented on packages/web-app/src/containers/tokenMenu/index.tsx
> +          {Object.entries(networks[chainId || 4].curatedTokens)
You were right and I changed the name of the list. but let's keep it in that way because once the spike task is done we can do a refactor if needed! let me know if you have further ideas. Thank you!

2021-12-21 10:18 UTC, Fabricevladimir reviewed
Massive task! Nice work

2021-12-21 10:18 UTC, Fabricevladimir commented on packages/web-app/src/containers/tokenMenu/index.tsx
> +  const {control, watch} = useForm();
There is no real need to have this as a separate form. Leave it in for now, but add a todo so that when we wire the form together we remember to integrate it into the main form.

2021-12-21 10:18 UTC, Fabricevladimir commented on packages/web-app/src/containers/tokenMenu/index.tsx
> +      const searchValue = watch('searchToken');
Careful with using the `watch` function because it causes an entire rerender. Maybe use the `useWatch` hook instead or remove the search logic from the form and have a piece of state for it.

2021-12-21 10:18 UTC, Fabricevladimir commented on packages/web-app/src/containers/tokenMenu/index.tsx
> +        <TokenTitle>{t('TokenModal.yourToken')}</TokenTitle>
Small typo, should be `yourTokens`

2021-12-21 10:18 UTC, Fabricevladimir commented on packages/web-app/src/containers/tokenMenu/index.tsx
> +            tokenLogo={
Are we taking care of tokens without a logo? If not drop a todo. Once the avatars have been finalized we'll have one that automatically does this for us.

2021-12-21 10:18 UTC, Fabricevladimir commented on packages/web-app/src/containers/tokenMenu/index.tsx
> +        <Controller
I don't think the search term should be stored in the form considering we never actually use it outside of this menu. If a token custom token is being added, we can use `setvalue('tokenName', searchTerm)` to store the token name in the form data when the add custom token button is clicked.

2021-12-21 10:18 UTC, Fabricevladimir commented on packages/web-app/src/containers/tokenMenu/index.tsx
> +  className: 'w-full justify-center',
When we make an iteration through the ui-components, I'll update the styling for the button to center the contents by default. Thanks!

2021-12-21 10:18 UTC, Fabricevladimir commented on packages/web-app/src/services/amount.ts
> +import {Contract, providers as EthersProviders} from 'ethers';
Curious, why have this as a service as apposed to a function in the token utils file?

2021-12-21 10:18 UTC, Fabricevladimir commented on packages/web-app/src/utils/library.ts
> +// Library utils / Ethers for now
What is the purpose of this separate utils file? Like what do we put in it?

2021-12-21 10:18 UTC, Fabricevladimir commented on packages/web-app/src/utils/tokens.ts
> +export async function getTokenDecimals(
For the custom tokens, we don't have a token name... It would be nice if this could return the name and symbol as well. I realized this just now 😓

2021-12-23 08:08 UTC, sepehr2github commented on packages/web-app/src/containers/tokenMenu/index.tsx
> +      const searchValue = watch('searchToken');
In this component because with each input onchange event list should update using useWatch doesn't make so much difference

2021-12-23 08:09 UTC, sepehr2github commented on packages/web-app/src/containers/tokenMenu/index.tsx
> +  className: 'w-full justify-center',
Thank you!

2021-12-23 08:19 UTC, sepehr2github commented on packages/web-app/src/services/amount.ts
> +import {Contract, providers as EthersProviders} from 'ethers';
I thought because It's fetching data it can categorize as a service but you're right! utils/token definitely is a better place.

2021-12-23 08:33 UTC, sepehr2github commented on packages/web-app/src/utils/library.ts
> +// Library utils / Ethers for now
Some ethers numeric utils functions like formatUnits, parseUnits, toBigNum, etc...
reference: https://github.com/aragon/govern/blob/develop/packages/govern-console/src/utils/lib.tsx

2021-12-23 08:37 UTC, sepehr2github commented on packages/web-app/src/containers/tokenMenu/index.tsx
> +        <Controller
Yes, maybe🤔. when the token selection logic was complete (Deposit flow) we can do a double-check and change it if needed

2021-12-23 10:09 UTC, Fabricevladimir approved these changes
Looks good!

2021-12-23 10:09 UTC, Fabricevladimir commented on packages/web-app/src/containers/tokenMenu/tokenBox.tsx
>  import {Avatar} from '@aragon/ui-components';
Aye my friend, I am sorry to say that this will be refactored later because it's an official ui-component now (listItemToken)! Not now of course

2021-12-23 11:15 UTC, WissenIstNacht approved these changes
Many thanks for going through all the comments!

PS: I have a two comments regarding the search. Things to keep in mind for later. 
- As I mentioned earlier: I agree with Fabrice that this could be simplified to just reading the value from the input. I don't think the extra form is necessary. It should be enough to read the value from the input can be used it directly as a search term. 
- More importantly, there's another related issue here. Due to the way the token data is structured, you can only search for the token address or token symbol, which is not ideal. In other words, "typing Ara" would not find "ANT". This should be corrected at some point. For inspiration, you cna check how this is done on the "All token" page.

2021-12-23 11:43 UTC, sepehr2github commented on packages/web-app/src/containers/tokenMenu/tokenBox.tsx
>  import {Avatar} from '@aragon/ui-components';
Yes my friend. I know the tokenListItem is my Pr

2021-12-23 14:22 UTC, merged