scc input field validations
aragon/app-legacy pull request #986
Opened 2023-08-16 10:46 UTC by RakeshUP

Task: [APP-2403](https://aragonassociation.atlassian.net/browse/APP-2403)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [x] I have tested my code on the test network.

2023-09-05 10:41 UTC, Fabricevladimir requested changes
Thanks, Rakesh. Left a couple of comments. 

Also, ran into an issue where the data of a previous unadded action isn't being cleared when a new action is selected. Not sure exactly where it's coming from.

2023-09-05 10:41 UTC, Fabricevladimir commented on src/utils/validators.ts
> +export async function actionsAreValid(
This function is awkward because everything is negated!

2023-09-05 10:41 UTC, Fabricevladimir commented on src/containers/smartContractComposer/components/inputForm.tsx
> +          render={({field: {name, value, onBlur, onChange}}) => (
Can you copy this controller with the address validation for the previous case? Since we know how to validate addresses and not really encodedData, we should make use of that. As it is right now, addresses don't show an error when they're invalid, only the whole action shows a required error.

2023-09-05 10:41 UTC, Fabricevladimir commented on src/components/fullScreenStepper/step.tsx
> +  return <>{props.children}</>;
Why the change here? lol

2023-09-05 10:41 UTC, Fabricevladimir commented on src/containers/actionBuilder/scc/index.tsx
> +                  label={t('newProposal.configureActions.alertCritical')}
This is going to need a different string because if an address field is invalid for example, this error is incorrect.

2023-09-05 10:41 UTC, Fabricevladimir commented on src/containers/actionBuilder/scc/index.tsx
> +  validateSCCAction(actionData, network).then(res => setIsValid(res));
Shouldn't this be inside a useEffect? If not, it will run on every render.

2023-09-05 10:41 UTC, Fabricevladimir commented on src/containers/smartContractComposer/components/inputForm.tsx
> +              mode={
Why not use the library provided validation here as well?

2023-09-05 10:41 UTC, Fabricevladimir commented on src/containers/proposalStepper/index.tsx
I'm assuming you want this running on every render? Why not put it in a useEffect?

2023-09-08 10:23 UTC, RakeshUP commented on src/containers/actionBuilder/scc/index.tsx
> +  validateSCCAction(actionData, network).then(res => setIsValid(res));
react-hook-form mutates arrays and objects. So useEffect won't run when `actionData` array fields change. 

We either do the validations on the render (or) use something like [use-deep-compare-effect](https://github.com/kentcdodds/use-deep-compare-effect). I think in this component the most re-renders would be due to change in `actionData` and thus the validations would run most of the time. So I chose to put it on the render

2023-09-08 10:23 UTC, RakeshUP commented on src/containers/proposalStepper/index.tsx
Same as https://github.com/aragon/app/pull/986#discussion_r1319674067

2023-09-08 10:25 UTC, RakeshUP commented on src/containers/smartContractComposer/components/inputForm.tsx
> +              mode={
I'm not aware of any validations for BigNumbers. Could you let me know if you know any?

The only rationale behind this check here is to make sure it's non-empty

2023-09-08 11:28 UTC, RakeshUP commented
@Fabricevladimir I'll get the new string after Evan/Selim return from the offsite next week.  

Regarding the inputs not being reset, it can happen when the function and input names are the same for multiple functions(due to function overloading). I'll check if this is the case and add some index/unique property to the form keys

2023-09-13 11:42 UTC, Fabricevladimir commented on src/containers/smartContractComposer/components/inputForm.tsx
> +              mode={
No, what I meant was having the validation done in the controller and displaying the error under the field itself, it's the same thing about the previous address comment.

Using this Goerli contract `0xF7CdB7bD236615f90246b9607D553CcB6E554c5D`, if you try to withdraw Ether, add the action, and then remove the last character of the receiver address, the input gets the error state, but an incorrect message is being shown for the entirety of the action.

<img width="611" alt="image" src="https://github.com/aragon/app/assets/16927999/48205acf-197f-4c57-8a55-bf558855f0ea">

2023-09-13 11:45 UTC, Fabricevladimir commented
> Regarding the inputs not being reset, it can happen when the function and input names are the same for multiple functions(due to function overloading). I'll check if this is the case and add some index/unique property to the form keys

Using the same contract, after filling out the `withdrawEther` action, instead of adding the action, switch to any of the withdraw actions and you'll see that the amount and the receiver from the `withdrawEther` function is being filled in. I think this might just be a case of not clearing the current potential action when we select another function.

2023-09-15 10:41 UTC, Fabricevladimir approved these changes

2023-09-15 10:41 UTC, Fabricevladimir commented on src/components/executionWidget/actions/sccExecutionWidget.tsx
> +  console.log('SCCExecutionCard', action);
You forgot to remove this one!

2023-09-19 10:21 UTC, jamesej commented on src/components/executionWidget/actions/sccExecutionWidget.tsx
> +  console.log('SCCExecutionCard', action);
I fixed this to get this one merged

2023-09-19 10:22 UTC, merged