Feat: Implement primary delegation flow
aragon/app-legacy pull request #991
Opened 2023-08-17 07:44 UTC by RuggeroCino

## Description

- Implement primary delegation flow from the governance page

Task: [APP-2376](https://aragonassociation.atlassian.net/browse/APP-2376)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran all tests with success and extended them if necessary.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have tested my code on the test network.

2023-08-18 13:18 UTC, Fabricevladimir requested changes, later dismissed
Thanks @RuggeroCino, lots of good things. Left a few comments. Additionally, noticed a weird issue when we try to reclaim voting power after having delegated it to another wallet:

https://github.com/aragon/app/assets/16927999/c3f39cc5-4d91-48c3-bd30-16425e97d0cf

2023-08-18 13:18 UTC, Fabricevladimir commented on src/containers/delegateVotingMenu/delegateVotingForm.tsx
> +  const alertLabel = isReclaimMode
Give me a space! lol

2023-08-18 13:18 UTC, Fabricevladimir commented on src/containers/delegateVotingMenu/delegateVotingForm.tsx
> +}))<{classname?: string}>``;
If you cast className as a string, then you can make use of the usual `className` react attribute on the styled component without any issues.

```suggestion
const FormGroup = styled.div.attrs({
  className: 'flex flex-col gap-1.5' as string,
})``;
```

2023-08-18 13:18 UTC, Fabricevladimir commented on src/containers/delegateVotingMenu/delegateVotingMenu.tsx
> +
Sepehr is working on a PR that should make this unnecessary all over the place I think.

2023-08-18 13:18 UTC, Fabricevladimir commented on src/context/globalModals.tsx
> +  const [isDelegateVotingOpen, setIsDelegateVotingOpen] =
I was really hoping this context would die off or at the very least we get an option to pass a callback onClose. Sometimes you really need that flexibility, especially with the login flow. When you try to do an action, the login menu will pop up, once you've logged in, you have to retry the action. Leads to an unnecessary click. Anyway food for thought.

2023-08-18 13:18 UTC, Fabricevladimir commented on src/hooks/useDaoToken.tsx
> +    async function getDaoMetadata(address: string) {
Not sure when this copy pasta happened, but can you update the name since this isn't getting DAO metadata?

2023-08-18 13:18 UTC, Fabricevladimir commented on src/locales/en/common.json
> +}
-_-

2023-08-18 13:18 UTC, Fabricevladimir commented on src/containers/delegateVotingMenu/delegateVotingSuccess.tsx
> +          />
Both of these buttons should be of size large

2023-08-18 13:18 UTC, Fabricevladimir commented on src/containers/delegateVotingMenu/delegateVotingForm.tsx
> +          onClick={handleCancel}
Can you add `size="large"` to these buttons as well?

2023-08-18 13:24 UTC, RuggeroCino commented on src/containers/delegateVotingMenu/delegateVotingForm.tsx
> +  const alertLabel = isReclaimMode
Ahaah will add some spaces 🙈

2023-08-18 13:28 UTC, Fabricevladimir commented on src/containers/delegateVotingMenu/delegateVotingForm.tsx
> +    delegate.address !== currentDelegate;
Not sure if the issue is here, but when the connected wallet ens is what shows up as the delegate, the form allows me to run a transaction to reclaim my delegation even though I hold the voting power. 

Also happens if I paste my wallet address into the form while "Delegate to somebody" is selected.

2023-08-18 13:30 UTC, RuggeroCino commented on src/containers/delegateVotingMenu/delegateVotingForm.tsx
> +}))<{classname?: string}>``;
Oh nice suggestion!

2023-08-18 13:30 UTC, RuggeroCino commented on src/locales/en/common.json
> +}
Auto formatting 😅

2023-08-18 13:54 UTC, RuggeroCino commented on src/context/globalModals.tsx
> +  const [isDelegateVotingOpen, setIsDelegateVotingOpen] =
We can for sure improve this dialog handling and pass custom properties to dialogs, it makes sense to open a tech debt for that 👍🏻

2023-08-18 15:00 UTC, cgero-eth commented on src/containers/delegateVotingMenu/delegateVotingMenu.tsx
> +
Mmm.. I'm not sure if we can reuse the logic of the protected routes here, or at least we'll need to update Sepehr's PR to be able to customise the `handleCloseLogin` callback because on the protected routes we currently do a `navigate(-1)` while here we have a different logic :/
I'd suggest to tackle this together with the ticket to refactor the dialog handling

2023-08-21 07:21 UTC, RuggeroCino commented on src/containers/delegateVotingMenu/delegateVotingForm.tsx
> +    delegate.address !== currentDelegate;
I suppose that it wasn't working as expected because I wasn't checking for "normalised" addresses, I updated the check

2023-08-21 07:22 UTC, cgero-eth commented
> Thanks @RuggeroCino, lots of good things. Left a few comments. Additionally, noticed a weird issue when we try to reclaim voting power after having delegated it to another wallet:
> 
>  Aragon.App.-.Google.Chrome.2023-08-18.09-13-05.mp4

I updated the component to use `react-hook-form` and correctly validate the delegate address, after that I could not replicate the issue you mentioned. Let me know if this is working properly for you now

2023-08-22 16:46 UTC, jamesej requested changes
Great work apart from the one comment I had.

2023-08-22 16:46 UTC, jamesej commented on src/services/aragon-sdk/aragon-sdk-service.ts
> +export const aragonSdkService = new AragonSdkService();
Ooh I don't love this. Seems like you're adding a wrapper around what's already a wrapper just to test for whether the client is null. Can't you get rid of this class? Seems like an unnecessary indirection.

2023-08-23 07:37 UTC, RuggeroCino commented on src/services/aragon-sdk/aragon-sdk-service.ts
> +export const aragonSdkService = new AragonSdkService();
Hey @jamesej, thanks for checking the code! Sure, I usually use these `-service` classes to collect the functions and utilities (when needed) to interact with a third party service. Given that currently this class doesn't have utilities or some specific logic that can be shared across the service, I can just remove them and move these functions on the `useDelegateTokens` and `useDelegatee` hooks

2023-08-23 09:57 UTC, jamesej approved these changes
Thanks Ruggero!

2023-08-23 10:01 UTC, merged

2023-08-23 10:04 UTC, jamesej approved these changes
Thanks Ruggero!